### ISSUE TITLE
Add support for without watermark HD videos

### ISSUE THREAD

**Issue by NettieJM** [drawrowfly/tiktok-scraper#101]
I have noticed that the videos available in HD are downloaded in Normal.

**Comment by drawrowfly** [comment]
vide size will be x10 times larger. will add this feature to the next update

**Comment by vnnegt** [comment]
> I have noticed that the videos available in HD are downloaded in Normal.

is there an indication on the screen when a video is HD?

**Comment by NettieJM** [comment]
> 
> 
> > I have noticed that the videos available in HD are downloaded in Normal.
> 
> is there an indication on the screen when a video is HD?

It's like this.
![sNrRA7ddrj](https://user-images.githubusercontent.com/28821962/80266911-72c8aa00-86d9-11ea-9a5e-64cdefbcb60a.png)

**Comment by drawrowfly** [comment]
Use --hd flag to download hd video BUT this option only will work with the --noWaterMark flag

https://github.com/drawrowfly/tiktok-scraper/blob/master/examples/CLI/Examples.md
