### ISSUE TITLE
Error: Cannot find module '../build'

### ISSUE THREAD

**Issue by kilpsz** [drawrowfly/tiktok-scraper#103]
**Describe the bug**
Getting error when trying to start tiktok-scraper in cmd.

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
Steps to reproduce the behavior: Start cmd, type tiktok-scraper ; get errors
- Used OS - Win 10
- NodeJs Version - v14.0.0
- Scraper Version - Latest? 
- CLI or Module - cmd
- Used method 
- Used options

**Screenshots**
![ihiHW0D](https://user-images.githubusercontent.com/54575302/80198081-4143d600-8628-11ea-8e4f-0449f75534a7.png)

**Comment by drawrowfly** [comment]
To avoid extra questions and etc from mine side you need to fill all the fields?

**Scraper Version - Latest?** version of the scraper?
**tiktok-scraper --version**

**Comment by kilpsz** [comment]
I can't do that since I get the error when doing anything tiktok-scraper related

**Comment by drawrowfly** [comment]
**tiktok-scraper --version** is not related to the scraping process

**Comment by kilpsz** [comment]
Oh, i still get the same error though. 

[https://i.imgur.com/eocngOQ.png](url)

**Comment by drawrowfly** [comment]
did you tried to reinstall it completely ? If yes then post here content of a file 
C:\Users\keith\tiktok-scraper\package.json

**Comment by kilpsz** [comment]
I tried but i don't know if i did it properly so imma paste the json file just in case.


{
    "name": "tiktok-scraper",
    "version": "1.1.9",
    "description": "TikTok Scraper & Downloader. Scrape information from User, Trending and HashTag pages and download video posts",
    "main": "./build/index.js",
    "types": "./build/index.d.ts",
    "bin": {
        "tiktok-scraper": "bin/cli.js"
    },
    "files": [
        "build"
    ],
    "dependencies": {
        "archiver": "^3.1.1",
        "async": "^3.1.0",
        "bluebird": "^3.7.1",
        "jsdom": "^16.0.1",
        "json2csv": "4.5.1",
        "ora": "^4.0.2",
        "progress": "^2.0.3",
        "request": "^2.88.0",
        "request-promise": "^4.2.4",
        "socks-proxy-agent": "^5.0.0",
        "yargs": "^14.2.0"
    },
    "devDependencies": {
        "@types/archiver": "^3.1.0",
        "@types/bluebird": "^3.5.30",
        "@types/jest": "^25.1.4",
        "@types/json2csv": "^4.5.1",
        "@types/ora": "^3.2.0",
        "@types/progress": "^2.0.3",
        "@types/request": "^2.48.4",
        "@types/request-promise": "^4.1.45",
        "@typescript-eslint/eslint-plugin": "^2.24.0",
        "@typescript-eslint/parser": "^2.24.0",
        "eslint": "^6.8.0",
        "eslint-config-airbnb-base": "^14.0.0",
        "eslint-config-prettier": "^6.10.0",
        "eslint-plugin-import": "^2.20.1",
        "eslint-plugin-prettier": "^3.1.2",
        "jest": "^25.1.0",
        "jest-canvas-mock": "^2.2.0",
        "prettier": "^1.19.1",
        "ts-jest": "^25.2.1",
        "ts-node": "^8.8.1",
        "typescript": "^3.8.3"
    },
    "scripts": {
        "build": "rimraf build && tsc",
        "docker:build": "tsc",
        "format": "prettier --config ./.prettierrc.js --write './src/**/*.ts'",
        "lint": "eslint ./src/**/*.ts",
        "test": "eslint ./src/**/*.ts && jest --coverage --verbose"
    },
    "jest": {
        "verbose": true,
        "transform": {
            "^.+\\.tsx?$": "ts-jest"
        },
        "setupFiles": [
            "jest-canvas-mock"
        ],
        "testRegex": "(/__tests__/.*|(\\.|/)(test|spec))\\.(jsx?|tsx?)$",
        "moduleFileExtensions": [
            "ts",
            "tsx",
            "js",
            "jsx",
            "json",
            "node"
        ]
    },
    "repository": {
        "type": "git",
        "url": "git+https://github.com/drawrowfly/tiktok-scraper.git"
    },
    "keywords": [
        "TikTok",
        "Scraper"
    ],
    "author": "Andrew Nord <andrew.nord.flow@gmail.com>",
    "license": "MIT",
    "bugs": {
        "url": "https://github.com/drawrowfly/tiktok-scraper/issues"
    },
    "homepage": "https://github.com/drawrowfly/tiktok-scraper#readme"
}

**Comment by drawrowfly** [comment]
My guess is that when you install the package there are not enough permissions to write folders

Post here screenshot of the folder content C:\Users\keith\tiktok-scraper\

**Comment by kilpsz** [comment]
https://i.imgur.com/6vVsfdH.png

**Comment by kilpsz** [comment]
Oh i got it now, now sure what i did wrong in the beginning since i did so many things,but to fix i had to delete all the stuff from npm folder and then install it again.

**Comment by ProgrammingLife** [comment]
I have the same issue after installing it globally from local folder.
