### ISSUE TITLE
Popular videos by hashtag

### ISSUE THREAD

**Issue by socialmediaguy** [drawrowfly/tiktok-scraper#106]
With the hashtag feature will it download the most popular videos (with most likes and views?)

Is tthis work I will definitly buy you a coffe or 2! Thanks

**Comment by drawrowfly** [comment]
i'm doing this only because i like to solve problems,  I'm not doing anything for "coffee" and etc. Your donations are only your own choice!!

**Comment by socialmediaguy** [comment]
Hi,
Sorry, I didn't mean to offend you. I don't know how it came across but by
your reaction, it didn't come across well. I was just really grateful for
you your work so it was my way of saying thank you and that I appreciate it.

**Comment by drawrowfly** [comment]
All good )

Anyway this was a duplicate #105 

Feature to filter the result will be added in the future updates
