### ISSUE TITLE
Batch file with tiktok-scraper

### ISSUE THREAD

**Issue by AplhaSlayer1964** [drawrowfly/tiktok-scraper#107]
**Is your feature request related to a problem? Please describe.**
Should I be able to run the command in a batch scrip to automatically have it download? Whenever I run it in batch script it just keep sending the same command and never actually executed the program.

**Describe the solution you'd like**
Am I just being stupid or is it because it's a node.js program it needs to do something more than just a batch script with the command.

**Comment by drawrowfly** [comment]
open issue and fill out bug template
