### ISSUE TITLE
Get user profile

### ISSUE THREAD

**Issue by yberdnikov** [drawrowfly/tiktok-scraper#11]
Thank you for such amazing library.
is there any way to get user profile info ? Like following/followers count ?

**Comment by drawrowfly** [comment]
You mean add additional info about user profile to the output ?

**Comment by yberdnikov** [comment]
@drawrowfly I mean, if there's a way to get users follower/following count ?

**Comment by drawrowfly** [comment]
off-course there is

**Comment by yberdnikov** [comment]
any way to add it to this package ? would be awesome

**Comment by drawrowfly** [comment]
thats what i was asking for before. You suggesting to add user info to the output result?

**Comment by yberdnikov** [comment]
sorry, yes, would be great

**Comment by drawrowfly** [comment]
just pushed an update. But note if you will scrape to many profiles you will receive a Rate Limit error that will block that request for at least 15 minutes
