### ISSUE TITLE
Save history in javascript methods?

### ISSUE THREAD

**Issue by paulwongx** [drawrowfly/tiktok-scraper#110]
Is it possible to save history by setting options in the javascript methods? I tried using the "store" and "historypath" key in options to no avail. Could this be a feature in the future? Thanks for your work on this package.

**Comment by AplhaSlayer1964** [comment]
It looks like the historypath just broke in this latest update. (I don't know about the store command)

**Comment by drawrowfly** [comment]
create new issue and fill out bug template
