### ISSUE TITLE
Modification time based on createTime

### ISSUE THREAD

**Issue by renox92** [drawrowfly/tiktok-scraper#111]
**Is your feature request related to a problem? Please describe.**
Not related to a problem.

**Describe the solution you'd like**
Would be great if downloaded videos had mtime based on createTime. Having an option to append filenames with a time stamp would be nice too.

**Comment by drawrowfly** [comment]
not sure what you mean, can be more specific

**Comment by AplhaSlayer1964** [comment]
I think he wants to know if you can grab the date the video was uploaded and set that as the date created in the files info and the ability to add that date to the file name. 
ie "2020/04/28 - 14165141346165161.mp4"

**Comment by renox92** [comment]
> I think he wants to know if you can grab the date the video was uploaded and set that as the date created in the files info and the ability to add that date to the file name.

Pretty much this. Right now whenever a video is downloaded it has creation date based on when you had downloaded the file. So even if a video was uploaded years ago it would appear as "created/modified today" when downloaded. Since csv/json files contain date of upload I'd like it to to be used as a creaton date of downloaded file. Plus an ability to put it in the filename like "YYMMDD HH-MM-SS - video_id". Although as long as file has a proper timestamp it won't be hard to batch rename to add creation date in whatever format one sees fit.

**Comment by drawrowfly** [comment]
You gotta be more specific
**"Right now whenever a video is downloaded it has creation date based on when you had downloaded the file"**
When you download video files (not file with metadata) you get it as VIDEO_ID.mp4
When you download file with video metadata you get is for example user_CURRENT_TIMESTAMP.json or csv

If you are proposing to download video file(not file with metadata) as for example PUBLISH_DATE_VIDEO_ID.mp4 then just say it!

**Comment by drawrowfly** [comment]
well that can be done, i will add it to a todo list

**Comment by renox92** [comment]
> you get it as VIDEO_ID.mp4

And in file manager (in my case Finder) its modification date displays as "Today at xx:xx" or whenever I downloaded that file, which makes sense. What I'm suggesting is that during download process the program looks at _createdTime_ column in the .csv file for that VIDEO_ID, and makes "modification time of VIDEO_ID.mp4 = createdTime of VIDEO_ID"

**Comment by drawrowfly** [comment]
Got it but i don't see point of this if you have free time then you can make a pull request to add this feature. Also it will require from you to use more then default FS package and i prefer not add more 3rd party libraries

**Comment by mohalistatus** [comment]
can possible caption or hashtags set as filename ?

**Comment by drawrowfly** [comment]
No idea what you mean
