### ISSUE TITLE
want json file only with text

### ISSUE THREAD

**Issue by mohalistatus** [drawrowfly/tiktok-scraper#112]
i want set new feature in json or csv if some one need only text information's

  --filetype, --type, -t  Type of the output file where post information will
                          be saved. 'all' - save information about all posts to
                          the` 'json' and 'csv'
                               [choices: "csv", "json", "all", "text"] <<<<<<<<<<<<<<

in csv file add only CAPTION and Hashtags

ex: saved csv file
"We’re kicking off the #happyathome live stream series today at 5pm PT!"

or if not possible just tell me which file i edit so i can do this.

**Comment by drawrowfly** [comment]
don't see use case for that

**Comment by mohalistatus** [comment]
plz tell me which file i edit for add some changes in output json or csv file

**Comment by drawrowfly** [comment]
brrrr

i think i already emailed you before that look for the **writeFile** method 
https://github.com/drawrowfly/tiktok-scraper/blob/master/src/core/TikTok.ts#L523

**in csv file add only CAPTION and Hashtags** 
Regarding this you probably mean custom output format, i will take a look on what i can do in the future update
