### ISSUE TITLE
Add an event that runs when a new video is posted.

### ISSUE THREAD

**Issue by icourt1** [drawrowfly/tiktok-scraper#113]
**Is your feature request related to a problem? Please describe.**
I don't like having to use a setInterval and spam the api with requests until I get a new video. This makes me save the previous video's id and check if a new one has released.

**Describe the solution you'd like**
I think you should add a newVideo event that runs as soon as a new video is posted.

**Comment by asportnoy** [comment]
bump

**Comment by drawrowfly** [comment]
"I think you should add a newVideo event that runs as soon as a new video is posted."
"I don't like having to use a setInterval and spam the api"

Just to be clear that you do realize that what you are asking for is what you hate to do(spam the api) . The approach is simple setInterval is executing Api Call every N seconds to check if there is a video and there is no other way . I mean this can be done without need of editing the package it self

**Comment by icourt1** [comment]
Just wanted to see if the author had known a better way of doing it using the official tiktok api

**Comment by drawrowfly** [comment]
This is not an official API!
