### ISSUE TITLE
High rate if Indian videos

### ISSUE THREAD

**Issue by LordRampantHump** [drawrowfly/tiktok-scraper#115]
Tick tok serves its data by geographical location, i keep getting a crap tonne of indian videos. Is the api being proxied or is there a way to force geographics?

**Comment by drawrowfly** [comment]
No and no. You can use your own proxy only and thats it nothing is proxied by default

**Comment by drawrowfly** [comment]
You can set US proxy and you should get US related content

**Comment by LordRampantHump** [comment]
> No and no. You can use your own proxy only and thats it nothing is proxied by default

Awesome stuff! Very useful little script, thanks man
