### ISSUE TITLE
Batch download error

### ISSUE THREAD

**Issue by 1keyz1** [drawrowfly/tiktok-scraper#117]
@drawrowfly 
What are I'm doing wrong?

`tiktok-scraper from-file C:\Users\Admin\pros.txt ASYNC_TASKS -n 10`
`tiktok-scraper from-file C:\Users\Admin\pros.txt --number 10`

both don't work

> You need to set number of task that should be executed at the same time

**Comment by drawrowfly** [comment]
Fill out bug template

**Comment by drawrowfly** [comment]
tiktok-scraper from-file C:\Users\Admin\pros.txt ASYNC_TASKS -n 10

ASYNC_TASKS - replace with number
