### ISSUE TITLE
fail retrieving profile posts for 

### ISSUE THREAD

**Issue by rzv** [drawrowfly/tiktok-scraper#118]
**Describe the bug**
Getting posts for https://www.tiktok.com/@sponsoredcontent10010 returns 0 posts

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- mac os x catalina 10.15
- node v11.13.0
- tiktok-scraper --version 1.1.9 
- module
- method: TikTokScraper.user
- options: {number: 30}
- no proxy / vpn / vps etc
- the profile is public https://www.tiktok.com/@sponsoredcontent10010

Thanks

**Comment by drawrowfly** [comment]
Soon same can happen with all profiles, they changed few things few weeks ago, when i will have time i will implement changes

**Comment by rzv** [comment]
Might be that it's an ad account, and the videos in this account don't come through the /share/user/item endpoint

Also, great work on this!

**Comment by drawrowfly** [comment]
Update with new API version will be released next week
