### ISSUE TITLE
403 Error

### ISSUE THREAD

**Issue by clublek** [drawrowfly/tiktok-scraper#121]
Command used: tiktok-scraper user USERNAME -d -s -w -n 0 --filepath "C:\tiktok"

When scraping the profile i get the following error:
403 - "<HTML><HEAD>\n<TITLE>Access Denied</TITLE>\n</HEAD><BODY>\n<H1>Access Denied</H1>\n \nYou don't have permission to access \"http&#58;&#47;&#47;www&#46;tiktok&#46;com&#47;discover\" on this server.<P>\nReference&#32;&#35;18&#46;6690dd58&#46;1588261127&#46;36c4826\n</BODY>\n</HTML>\n"

**Comment by drawrowfly** [comment]
bug template exists to report bugs

99% issue is related to your IP
