### ISSUE TITLE
Syntax Report

### ISSUE THREAD

**Issue by mocodesallday** [drawrowfly/tiktok-scraper#122]
**Describe the bug**
I'm a new programmer, but would love some help. To download, I downloaded Node and also did "sudo npm i -g tiktok-scraper"  in terminal. Then, I put this in my terminal: tiktok-scraper hashtag love

And it outputted this syntax error
    File "/Library/Frameworks/Python.framework/Versions/3.5/bin/tiktok-scraper", line 5, in <module>
    from tiktok_scraper.cli import main
ImportError: No module named 'tiktok_scraper'

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- Used OS: MacOXC
- NodeJs Version (node -v): v12.16.3
- Scraper Version (tiktok-scraper --version): Running ito the error so can't check
- CLI or Module: It's not importing :/
- Used method: hashtag
- Used options
- Do you run the scraper through Proxy, VPN, VPS?
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles!
- Preferably provide URL to the profile,hashtag,video and etc page: https://www.tiktok.com/tag/love

**Screenshots**

**Comment by drawrowfly** [comment]
this is not a bug related to package. You probably have installed some Python version of the scraper. Remove it
