### ISSUE TITLE
`tiktok-scraper user` no output

### ISSUE THREAD

**Issue by blasphemite** [drawrowfly/tiktok-scraper#123]
**Describe the bug**
No output with any use of `tiktok-scraper user `.

Any usage of the `user` argument gives no output, even after clearing history, specifying `--historypath`, etc. 

Other arguments work `video` etc. The `user` argument was working for me until this morning it seems, but suddenly has no output.

Example of command that gives no output:

`tiktok-scraper user willsmith -n 10 -t csv`
`tiktok-scraper user willsmith -n 10 -d --filepath /home/will/videos`

I had variations of both of these commands working yesterday, but today neither work with no other changes to my system. Is there a more verbose log I can share?

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
_- Used OS_
Ubuntu LTS 18.04
_- NodeJs Version (node -v)_
10.20.1
_- Scraper Version (tiktok-scraper --version)_
1.1.10
_- CLI or Module_
bash
_- Used method_
_- Used options_
`user`
_- Do you run the scraper through Proxy, VPN, VPS?_
No
_- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles!_
Yes. Tested on public profiles. Tested with profiles I've never scraped before to be sure they weren't in my history.
_- Preferably provide URL to the profile,hashtag,video and etc page_
Examples provided above

**Screenshots**

**Comment by drawrowfly** [comment]
Probably problem with the IP or #118. Scraper is working fine

**Comment by drawrowfly** [comment]
Did more tests and is working fine. Double check your IP or try to use proxy.

**Comment by blasphemite** [comment]
Could you clarify what you mean "double check your ip?"

The `video` option works fine, but `user` gives no output, if it was network shouldn't I expect neither to work? 

`tiktok-scraper video https://www.tiktok.com/@tiktok/video/6807491984882765062` 
gives `CSV path: /home/myuser/6807491984882765062.csv`

but `tiktok-scraper user tiktok` and `tiktok-scraper user tiktok -n 10`
give no output at all.

**Comment by blasphemite** [comment]
Tested with proxy and works fine. Hmm. 

Thanks for quick reply!
