### ISSUE TITLE
how to set -s custom location

### ISSUE THREAD

**Issue by AplhaSlayer1964** [drawrowfly/tiktok-scraper#125]
How do you set the custom location for the -s command? Is it possible to have two custom locations for use in quickly saving a watermarked copy and a non watermarked copy?

**Comment by drawrowfly** [comment]
https://github.com/drawrowfly/tiktok-scraper/blob/master/examples/CLI/DownloadHistory.md

--historypath

**Comment by AplhaSlayer1964** [comment]
I thought i they were the same I just wasn't sure. Thanks for the quick response!
