### ISSUE TITLE
trend -d -n 100 downloading only 57 videos?

### ISSUE THREAD

**Issue by RubenBenBen** [drawrowfly/tiktok-scraper#126]
**Describe the bug**
I just installed it and tried `tiktok-scraper trend -d -n 100` , but it downloads only 57 videos. I've checked, there's more than 100 videos on tiktok trending page. It downloads all 100 with hashtag command: `tiktok-scraper hashtag 2020 -d -n 100`

**To Reproduce**
just run `tiktok-scraper trend -d -n 100`

- Used OS: macOS catalina
- NodeJs Version: v12.16.3
- Scraper Version: 1.1.10
- CLI or Module: CLI
- Used method: `tiktok-scraper trend -d -n 100`
- Used options: `-d -n 100`
- Do you run the scraper through Proxy, VPN, VPS? : No

**Comment by drawrowfly** [comment]
Well thats how it is with the trending feed, some requests return same videos.

Try to set longer timeout

in the future i will improve it
