### ISSUE TITLE
--Store not working for me

### ISSUE THREAD

**Issue by AgentCW4** [drawrowfly/tiktok-scraper#127]
**Describe the bug**
In my case the --store or -s function is not working

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**

- "tiktok-scraper hashtag dank -d -n 1" is working fine with the terminal downloading the file
- "tiktok-scraper hashtag dank -d -n 1 -s" or
- "tiktok-scraper hashtag dank -d -n 1 --store" is not working (also not with a path after store or s)
all cases have been tried with and without administrator permissions

**Screenshots**
Without -s: 
![image](https://user-images.githubusercontent.com/48552058/80917761-6ab7dc80-8d61-11ea-8a4d-437fba1bbfb2.png)

it says the scraper is starting but nothing is happening:
![image](https://user-images.githubusercontent.com/48552058/80917783-93d86d00-8d61-11ea-9fc7-aa4f4b288db4.png)

thank you for your solutions

**Comment by drawrowfly** [comment]
brrr

Its working completely fine

Double check the purpose of the --store, -s command and type **tiktok-scraper history**

**Comment by drawrowfly** [comment]
i think i need to rewrite documentation with more examples and explanations
