### ISSUE TITLE
Music cover URL

### ISSUE THREAD

**Issue by fanoftiktok** [drawrowfly/tiktok-scraper#128]
I suggest that music information includes music cover URL?

I think it is only one line change

```
musicMeta: {
  musicId: posts[i].itemInfos.musicId,
  musicName: posts[i].musicInfos.musicName,
  musicAuthor: posts[i].musicInfos.authorName,
  musicOriginal: posts[i].musicInfos.original,
  playUrl: posts[i].musicInfos.playUrl[0],
  cover: posts[i].musicInfos.covers[0],
},
```

What you think @drawrowfly?

**Comment by drawrowfly** [comment]
if it still available in the response then why not. Anyway in a couple of days i was planing to push new update with the changes related to the api endpoint and can include it

**Comment by fanoftiktok** [comment]
It is still available, there is also `coverMedium` and `coverLarge` options, but I think that these are not so important because the only change is resolution suffix. Cover have `100px` and others have `720px` or `1080px`.

Nice, what new updates you thought to bring related to TikTok API? I'm interested to hear about them👂

**Comment by drawrowfly** [comment]
nothing actually special for now, just replacing old api endpoints with the new ones

**Comment by drawrowfly** [comment]
Cover was added with the last update
