### ISSUE TITLE
Turn off the ouput table

### ISSUE THREAD

**Issue by ProvocativeCheese** [drawrowfly/tiktok-scraper#129]
Is there a way to turn off the output given in the table after the tiktok-scraper has finished its scraping?

**Comment by drawrowfly** [comment]
Table is only shown when downloading in batches

And i don't see point to turning it off

**Comment by ProvocativeCheese** [comment]
I am downloading in batches :)

Just for visual aesthetics to make the output in my cmd less clogged.  If there was an option, it would be nice to turn it off.

**Comment by drawrowfly** [comment]
Currently it is not necessity in it and requires to add extra commands. Maybe in the future we can add it

But if you would like to solve this task your self and make a pull request then please be my guest :)
