### ISSUE TITLE
use authorName in downloaded file

### ISSUE THREAD

**Issue by meptike** [drawrowfly/tiktok-scraper#13]
Is it possible to use authorName for the downloaded file?

**Comment by sinha2366** [comment]
![Screenshot_212](https://user-images.githubusercontent.com/16883045/75411240-26810980-58e4-11ea-88d5-81bd2ad94e7e.png)

When downloading, the following error occurs:
TypeError: this.stream.clearLine is not a function

**Comment by drawrowfly** [comment]
i will add this to a To Do

**Comment by drawrowfly** [comment]
@meptike you can update package to the latest version already
