### ISSUE TITLE
A function to fetch comments on a post when cookie is provided

### ISSUE THREAD

**Issue by abdatta** [drawrowfly/tiktok-scraper#130]
**Is your feature request related to a problem? Please describe.**
Couldn't find a function for fetching comments on a post.

**Describe the solution you'd like**
Fetching comments from a post requires login, which requires a captcha, so it's difficult to automate. But I'd like to have a function that can be supplied with a cookie (say, we have one from a manual login session), and then it should be able fetch me the comments (as long as the cookie is valid at least).
What do you say? :)

**Comment by drawrowfly** [comment]
You mean this ?
https://www.tiktok.com/api/comment/list/?aweme_id=${video_id}&cursor=${skip}&count=${limit}&aid=1988&app_language=en&device_platform=web_pc&current_region=NL&fromWeb=1&channel_id=3&verifyFp=&_signature

Well i was thinking on adding it to this repo and it will require to add more documentation and how to get **sid_guard** value

Regarding authorization i already solved it but didn't pushed the update due to fact that repo will become a bot and will be used for spam

**Comment by drawrowfly** [comment]
Anyway pull requests are always welcome, if you plan on doing it don't forget to sign the url

**Comment by abdatta** [comment]
Yes, I am already working on a PR, and I am expecting the user will provide the `sid_guard` value from their cookie. Also, it'll be very helpful if you can share how you have solved the authorization. If you don't want to push it to this repo (because of the reason you mentioned), you can share it over email or somewhere else (maybe here?). Will be very grateful for that! :)

**Comment by endemio** [comment]
There is prioblem for me to find how does **_signature** generating. If we have that "howto" - scrapping comments wont be complex task

**Comment by abdatta** [comment]
Signature is not a big deal, this library already supports that. Having the login information (cookie) is the challenge. If that is provided then it's a simple fetch.

**Comment by drawrowfly** [comment]
@abdatta sorry but i can't provide any info related to the auth . 

Regarding cookies you only need 1 value in the cookie header and it is **sid_guard**=blahblah and this value can be found in any request to the TikTok in google chrome inspector if you have authorized to the TikTok

**Comment by abdatta** [comment]
No problem, I have figured out the authorisation as well :) Thanks!

**Comment by drawrowfly** [comment]
No one seems to make any pull request regarding this matter. Issue closed

**Comment by mikepro123** [comment]
> No problem, I have figured out the authorisation as well :) Thanks!

can you solve this issue
