### ISSUE TITLE
Live video downloading capability?

### ISSUE THREAD

**Issue by vnnegt** [drawrowfly/tiktok-scraper#131]
As a developer myself I realize this is a pretty significant feature request and I would be more than happy to buy you a bunch of coffee.

Just wondering if this is something you'd be able to tackle in the future

Not sure if you're familiar with it, but I use `PyInstaLive` with Instagram and something similar would be awesome

**Comment by drawrowfly** [comment]
Did you checked if the live videos are available on the web version?

**Comment by drawrowfly** [comment]
I can't find any web profile with live video on, until i do have example nothing can be done
