### ISSUE TITLE
Missing readline.js

### ISSUE THREAD

**Issue by VeronQ** [drawrowfly/tiktok-scraper#132]
**Describe the bug**

**readline.js** is missing.

Is there any doc about how to use **Proxy, VPN or VPS** for this library?

> Module build failed: Error: ENOENT: no such file or directory, open '/Users/userName/projectName/node_modules/readline/readline.js'

**To Reproduce**
- Used OS (**macOS Catalina 10.15.4**)
- NodeJs Version (**13.12.0**)
- CLI or **Module**
- Used method (**getUserProfileInfo**)
- Used options (**None**)
- Do you run the scraper through Proxy, VPN, VPS? (**None**)
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles! (**Yes**)
- Preferably provide URL to the profile,hashtag,video and etc page (**https://www.tiktok.com/@tiktok**)

Thank you for your work.

**Comment by drawrowfly** [comment]
This is not related to the package. 
Package it self works/installs fine, something is wrong with the node install from your side or the way you use it. Just to be clear it won't work from the front 

Regarding proxy:
    // Set proxy {string[] | string default: ''}
    // http proxy: 127.0.0.1:8080
    // socks proxy: socks5://127.0.0.1:8080
    // You can pass proxies as an array and scraper will randomly select a proxy from the array to execute the requests
    proxy: '',

**Comment by VeronQ** [comment]
What dio you mean by "_Just to be clear it won't work from the front_".
Can't I integrate this library in a web application?

What do you suggest?

**Comment by drawrowfly** [comment]
"Can't I integrate this library in a web application?" where exactly? if back end (nodeJs) then yes

**Comment by VeronQ** [comment]
Is there any demo of using tiktok-scraper with node.js server?

**Comment by drawrowfly** [comment]
...
https://github.com/drawrowfly/tiktok-scraper#module

**Comment by VeronQ** [comment]
Hello,

I've succeeded implementing your library with Node.js.
It works great on local environment.
(https://github.com/VeronQ/live-follower-count)

However, when trying to host on Netlify, one of your project dependencies trigger an error.
Any idea what's happening?

```sh
ModuleNotFoundError: Module not found: Error: Can't resolve 'canvas' in '/opt/build/repo/node_modules/jsdom/lib/jsdom'
10:08:43 PM:     at factory.create (/opt/build/repo/node_modules/webpack/lib/Compilation.js:925:10)
10:08:43 PM:     at factory (/opt/build/repo/node_modules/webpack/lib/NormalModuleFactory.js:401:22)
10:08:43 PM:     at resolver (/opt/build/repo/node_modules/webpack/lib/NormalModuleFactory.js:130:21)
10:08:43 PM:     at asyncLib.parallel (/opt/build/repo/node_modules/webpack/lib/NormalModuleFactory.js:224:22)
10:08:43 PM:     at /opt/build/repo/node_modules/neo-async/async.js:2830:7
10:08:43 PM:     at /opt/build/repo/node_modules/neo-async/async.js:6877:13
10:08:43 PM:     at normalResolver.resolve (/opt/build/repo/node_modules/webpack/lib/NormalModuleFactory.js:214:25)
10:08:43 PM:     at doResolve (/opt/build/repo/node_modules/enhanced-resolve/lib/Resolver.js:213:14)
10:08:43 PM:     at hook.callAsync (/opt/build/repo/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
10:08:43 PM:     at _fn0 (eval at create (/opt/build/repo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
10:08:43 PM:     at resolver.doResolve (/opt/build/repo/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7)
10:08:43 PM:     at hook.callAsync (/opt/build/repo/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
10:08:43 PM:     at _fn0 (eval at create (/opt/build/repo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
10:08:43 PM:     at hook.callAsync (/opt/build/repo/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
10:08:43 PM:     at _fn0 (eval at create (/opt/build/repo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
10:08:43 PM:     at resolver.doResolve (/opt/build/repo/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43)
10:08:43 PM: resolve 'canvas' in '/opt/build/repo/node_modules/jsdom/lib/jsdom'
```
