### ISSUE TITLE
History file updating even when nothing scraped

### ISSUE THREAD

**Issue by rikkiran** [drawrowfly/tiktok-scraper#135]
**Describe the bug**

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- Used OS = Windows 10
- NodeJs Version (node -v) = v10.15.3
- Scraper Version (tiktok-scraper --version) = 1.1.10
- CLI or Module = Module
- Used method = from-file
- Used options = -d --filepath -s --historypath
- Do you run the scraper through Proxy, VPN, VPS?no
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles!
- Preferably provide URL to the profile,hashtag,video and etc page
-------------------------------

I noticed a problem that after a while Tiktok stops allow the program to scrape. I'm assuming it's my IP address because after a while it starts working again. However, even if it fails to download anything, it still updates the history file with the last scrape date, so the next time you run it, it will skip all the videos that it missed and you will have no idea that there was a problem.

Is it possible to only update the history file when it successfully downloads something? The individual user json file stays blank, so that's good, but the history file updates as if everything went ok.

edit:
So I noticed if it's a user you already have a history for, it won't update the history file. But if it's a new user, it will add it to the history file with the current date as the last scrape date. So this only affects new users. I hope that helps.

Thanks for your work, it's a great program!

**Comment by drawrowfly** [comment]
"it will skip all the videos that it missed " cant happening

The point of history file is to store data about downloaded posts and that data is Video Id's and if scraper didn't collected any data if won't add any extra video ID's to the history file

Regarding update the date of the last scraper i will change it in the next update

**Comment by rikkiran** [comment]
Thank you!
