### ISSUE TITLE
Bulk scraping not actually downloading posts

### ISSUE THREAD

**Issue by AplhaSlayer1964** [drawrowfly/tiktok-scraper#136]
**Describe the bug**

I have a list of 105 different accounts and when I run the command it says that scrapping has been completed but it has not downloaded anything for some accounts(manly the last few). Is the scraper just getting rate limited before it reaches the bottom? I have async set to 1 hopping that would help stopping it from getting rate limited so fast. If I use the same command except with user it will download them properly.

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- Used OS: windows 10
- NodeJs Version (node -v): v14.0.0
- Scraper Version (tiktok-scraper --version): 1.1.10
- CLI or Module: CLI
- Used method: from-file
- Used options: from-file (async=1), -d, -s, --filepath, --historypath
- Do you run the scraper through Proxy, VPN, VPS?: VPN(IPA)
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles!: Yes all profiles are public
- Preferably provide URL to the profile,hashtag,video and etc page: It seems to only happen to any new account I added at the bottom of my user.tx file. I have to try running it several times before it will actually download any videos and it still doesn't download some of them. 

**Screenshots**

**Comment by drawrowfly** [comment]
To scrape a lots of profiles you need good amount of proxies

**Comment by AplhaSlayer1964** [comment]
So If I broke it up into say chunks of 30 users and had my vpn reconnect to a different server in between each chunk would that fix the issue?

**Comment by AplhaSlayer1964** [comment]
Also I tried using PIA socks5 proxy but it was just saying scraping complete even though it did nothing. did I have it set up correctly? socks5://user:password@46.166.186.197:1080

**Comment by AplhaSlayer1964** [comment]
Also for the timeout in between requests is that request of each video for a given user or for just each user that is checked?

**Comment by drawrowfly** [comment]
I will release soon new update that supports new api endpoints that are more stable then the old ones 

socks5://user:password@46.166.186.197:1080 yes that is correct
