### ISSUE TITLE
Add pagination option

### ISSUE THREAD

**Issue by LMontull** [drawrowfly/tiktok-scraper#137]
Would be super useful to include a pagination option (i.e: an offset) when calling the methods, so you could split the scraping in multiple function calls. 

Btw, congratulations on the project, great piece of code.

**Comment by drawrowfly** [comment]
Already added this feature from mine side. New update will be released next week :)

**Comment by LMontull** [comment]
Oh that's amazing!! :)

Closing the issue then.
