### ISSUE TITLE
getvideometa doesn't handle usernames with dots

### ISSUE THREAD

**Issue by rens23** [drawrowfly/tiktok-scraper#138]
**Describe the bug**
When scraping a video via the function:
TikTokScraper.getVideoMeta
Usernames with a dot in it won't get scraped and instead get the error:
Bad url format. Correct format: https://www.tiktok.com/@USERNAME/video/ID

**To Reproduce**
Try:
const posts = await TikTokScraper.getVideoMeta("https://www.tiktok.com/@markie.ly/video/6779981033744993542", {  });

**Possible fix**
Change (line 917-919 src/core/TikTok.ts):
if (!/^https:\/\/(www|v[a-z]{1})+\.tiktok\.com\/(\w.+|@(.\w.+)\/video\/(\d+))$/.test(this.input)) {
            throw `Not supported url format`;
        }
to
if (!/^https:\/\/(www|v[a-z]{1})+\.tiktok\.com\/(\w.+|@(.+)\/video\/(\d+))$/.test(this.input)) {
            throw `Not supported url format`;
        }

**Comment by drawrowfly** [comment]
Always fill out bug template completely. I don't see any issues in the latest version!
