### ISSUE TITLE
Output files are not generated when number of post to scraper is way bigger than number of existing posts

### ISSUE THREAD

**Issue by hfcr2020** [drawrowfly/tiktok-scraper#139]
**Describe the bug**
No files are generated when I try to generate JSON and CSV files using a hastag that is not really popular and for which I want to get a lot of information (-n). If I use a -n between 1 and 6 it works.

**To Reproduce**
- Used OS
Windows 10
- NodeJs Version (node -v)
v12.16.2
- Scraper Version (tiktok-scraper --version)
v1.1.10
- CLI or Module
Windows CMD. I execute the following command `tiktok-scraper hashtag duquepresidente -d false -n 1000 -t json`
- Used method
hashtag
- Used options
duquepresidente -d false -n 1000 -t json
- Do you run the scraper through Proxy, VPN, VPS?
No
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles!
N/A
- Preferably provide URL to the profile,hashtag,video and etc page
N/A. I want to get anything that is there.

**Screenshots**
![image](https://user-images.githubusercontent.com/64443049/81927848-a1ed7f80-95e4-11ea-86bc-f87fce004396.png)

**Comment by drawrowfly** [comment]
Yes, there is bug. Will fix it in next update

**Comment by rakemen** [comment]
I am unable to download anything from tiktok now, the process just stops after running the command with no output.

**Comment by drawrowfly** [comment]
Use proxy

**Comment by drawrowfly** [comment]
Fix in the latest update
