### ISSUE TITLE
Error: getaddrinfo ENOTFOUND www.tiktok.com

### ISSUE THREAD

**Issue by raizen138** [drawrowfly/tiktok-scraper#141]
**Describe the bug**
When I try to use the command tiktok-scraper user it gives me this error: "Error: getaddrinfo ENOTFOUND www.tiktok.com". I was trying it a week before and it worked fine so I don't know what is happening if you could help me there. If it is something stupid I'm sorry.

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- Used OS
_Ubuntu 18.04.3 LTS_
- NodeJs Version (node -v)
_v13.3.0_
- Scraper Version (tiktok-scraper --version)
_1.1.3_
- CLI or Module
_Ubuntu cmd using the command line `tiktok-scraper user nba`_
- Used method
- Used options
_user_
- Do you run the scraper through Proxy, VPN, VPS?
_No_
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles!
_Yes, I was trying with nba and it is a public profile_
- Preferably provide URL to the profile,hashtag,video and etc page
_https://www.tiktok.com/@nba_

**Comment by drawrowfly** [comment]
1. Problem with internet
2. Problem with Ip
