### ISSUE TITLE
Occasional Issues Retrieving All Videos for User

### ISSUE THREAD

**Issue by aholmes97** [drawrowfly/tiktok-scraper#142]
**Describe the bug**
No videos are retrieved for the specific user/profile. 
I have used a bash script within a cronjob to periodically scrape certain public profiles. On occasion (and I cannot understand what the pattern is), the scraper will run and retrieve nothing at all. Reinstalling and setting it up on a different system works, however implementing the bash script on that system also reproduces the issue (eventually).

Whilst it will not retrieve anything for the user method, I can still retrieve individual videos using the video method. (Thought I would try as I wondered whether there was anything having issues with my IP making so many requests).

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- Used OS - Raspian 10 and Debian 10 (both buster)
- NodeJs Version (node -v) - 10.19.0 and 12.16.3
- Scraper Version (tiktok-scraper --version) - 1.1.10 (both)
- CLI or Module -  CLI
- Used method - user
- Used options - filepath, store, historypath, download, hd, w, type
E.g. tiktok-scraper user applemusic —filepath /home/pi/tiktok/ --store --historypath /home/pi/tiktok/history/ - -download --hd -w --type csv
- Do you run the scraper through Proxy, VPN, VPS? - No
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles! - Yes. When the issue occurs, I can put a new user in (any user at all) and it still won’t retrieve anything.
- Preferably provide URL to the profile,hashtag,video and etc page - Happens across all e.g. tiktok, applemusic etc.
**Screenshots**

**Comment by codespikex** [comment]
@aholmes97 I debugged the issue and I think yesterday TikTok pushed an update that requires the "verifyFP" parameter along with signature, It's currently working on single video and trending but gives issues on username & keyword. Check this #143 

@drawrowfly Kindly look at this issue

**Comment by drawrowfly** [comment]
Use proxy if you make a lot of requests

**Comment by drawrowfly** [comment]
When you perform a lots of requests from a single IP your IP will be put in a "temporarily black list"

**Comment by aholmes97** [comment]
If it is due to the blacklist, do you know why retrieving an individual video still works? As I would have thought all requests from the IP would be blacklisted? Do you know how long the temporary blacklist is for? Or the details around the blacklist? For example, would I be blacklisted for scraping once an hour?

**Comment by drawrowfly** [comment]
"temporarily black list" figure of speech, in other words Rate Limit

No idea, maybe 30 min
