### ISSUE TITLE
[TIKTOK verifyFP UPDATE] Facing issues while downloading videos from Username & Keyword

### ISSUE THREAD

**Issue by codespikex** [drawrowfly/tiktok-scraper#143]
**Describe the bug**
I was using your web API for downloading videos using keywords and username using CLI but from yesterday It's giving me an empty response. I investigated and I think it's related with "verifyFP", before an empty verifyFP was sending response data but now without verifyFP it's sending an empty response. Can you tell us how to generate verifyFP like we're generating signature?

**To Reproduce**
- Used OS: **Windows 10** 
- NodeJs Version (node -v): **12.x**
- Scraper Version (tiktok-scraper --version): **Latest**
- CLI or Module: **CLI**
- Used method: **Default** 
- Used options: **Username & Keyword giving empty response**
- Do you run the scraper through Proxy, VPN, VPS? **Home IP**
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles! **Public Profile**
- Preferably provide URL to the profile,hashtag,video and etc page

**Screenshots**
https://www.tiktok.com/tag/pkcricketfever?lang=en
https://www.tiktok.com/@ch.zulqarnain25?lang=en

**Comment by drawrowfly** [comment]
verifyFP can be null, value don't have importance 

Use proxy if you make a lot of request

**Comment by drawrowfly** [comment]
Also new update is coming with much faster scraping user feed and less http requests

**Comment by codespikex** [comment]
I also tried proxies, it's the same and for testing I'm only fetching 2 videos but sending an empty response. Kindly can you confirm it's working fine on your end?

**Comment by drawrowfly** [comment]
Working fine from mine side and others people, bad proxy then
