### ISSUE TITLE
download single video with watermark not working?

### ISSUE THREAD

**Issue by RubenBenBen** [drawrowfly/tiktok-scraper#145]
**Describe the bug**
I'm trying to download a single video with watermark. I tried `tiktok-scraper -d -w false video https://www.tiktok.com/@lucagallone/video/6809289785870421254` `tiktok-scraper -d -w true video https://www.tiktok.com/@lucagallone/video/6809289785870421254` , but none of them is with watermark.

**To Reproduce**
just run `tiktok-scraper -d -w true video https://www.tiktok.com/@lucagallone/video/6809289785870421254`

- Used OS: macOS catalina
- NodeJs Version: v12.16.3
- Scraper Version: 1.1.10
- CLI or Module: CLI
- Used method: `tiktok-scraper -d -w false video https://www.tiktok.com/@lucagallone/video/6809289785870421254` `tiktok-scraper -d -w true video https://www.tiktok.com/@lucagallone/video/6809289785870421254` 
- Used options: `-d -w false` `-d -w true`
- Do you run the scraper through Proxy, VPN, VPS? : No

**Comment by drawrowfly** [comment]
https://github.com/drawrowfly/tiktok-scraper/blob/master/examples/CLI/Examples.md example 8

**Comment by RubenBenBen** [comment]
I tried example 8, it still downloads it **without** watermark. I just don't see any example showing a video **with** watermark.
