### ISSUE TITLE
Tiktok scrapper giving any result.

### ISSUE THREAD

**Issue by Techyuvi** [drawrowfly/tiktok-scraper#147]
Hi, i am using tiktok-scraper for scraping and it was working fine till **2020-05-20**. Now as i open tiktok-scraper it not giving any result and also no error. my ip is not blocked as i am able to open tiktok user account on my system but not through tiktok-scraper. Please guide me how can i handle. also check if it is a tiktok-scrapper issue then please fix it.

**Comment by drawrowfly** [comment]
Fill out bug issue template

**Comment by drawrowfly** [comment]
works fine from mine side

**Comment by Techyuvi** [comment]
So, could you please suggest what will be issue? i am running it by  **tiktok-scraper user user_name -d -n 2**. it gives me no result. Thanks

**Comment by drawrowfly** [comment]
95% IP
