### ISSUE TITLE
How to implement to ios and android app?

### ISSUE THREAD

**Issue by Mokin711** [drawrowfly/tiktok-scraper#148]
I am a front end developer and interested in reading data from tikok like those tiktok tracker app in the app store. I mainly use firebase function to run some javascript if I ever need to use some backend feature like push notifications so I don't quiet understand if it is possible to covert the concept here into mobile apps. Can you give me some clues about if this is even possible?

**Comment by drawrowfly** [comment]
Build Rest API and or use for example firebase
