### ISSUE TITLE
can't scrape post user

### ISSUE THREAD

**Issue by areltiyan** [drawrowfly/tiktok-scraper#149]
**Describe the bug**
just tes with example code
and then test run code but collector has length 0 

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- Used OS - Windows 10
- NodeJs Version (node -v) - v12.13.0
- Scraper Version (tiktok-scraper --version) - Latest
- CLI or Module - Module n Cli
- Used method - example code
- Used options - example code
- Do you run the scraper through Proxy, VPN, VPS? - vps
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles! - Yes
- Preferably provide URL to the profile,hashtag,video and etc page - just test blalablalabroo profile

**Screenshots**
![image](https://user-images.githubusercontent.com/54056041/82756228-1a351b80-9e03-11ea-9382-7c580bd8bb2a.png)

![image](https://user-images.githubusercontent.com/54056041/82756236-2a4cfb00-9e03-11ea-9c7e-59e6ac5bf74a.png)

**Comment by drawrowfly** [comment]
Well they probably discontinued older api. I will update the package shortly

**Comment by drawrowfly** [comment]
Actually still working, i will apply small fix. Next big update will be shortly after

**Comment by areltiyan** [comment]
maybe tiktok server side, 
I didn't edit it the code but working again. Thanks for respons @drawrowfly
