### ISSUE TITLE
The old video API has been disabled

### ISSUE THREAD

**Issue by fanoftiktok** [drawrowfly/tiktok-scraper#150]
**Describe the bug**
Videos can no longer be scraped from old API.

**Comment by mightymander** [comment]
do you have another way?

**Comment by drawrowfly** [comment]
It is working completely fine, but yes sooner or later it will be deactivated . Next  update will be released soon, with the new API

**Comment by fanoftiktok** [comment]
@drawrowfly TikTok updated it last night, it is not working anymore. I just tested it.

**Comment by drawrowfly** [comment]
Working fine from mine side. It stopped for around 30 min. Set custom user agent

**Comment by fanoftiktok** [comment]
Get user works fine, but get user videos is broken. I changed user-agent from the default

```js

// This one works well
const user = await TikTokScraper.getUserProfileInfo(username);

// This will timeout
const posts = await TikTokScraper.user(username, { number: 20000 });
```

**Comment by drawrowfly** [comment]
It works completely fine for me and few other people

**"verifyFp, secUid, language, region, appId"** this values are irrelevant and not important to execute request

**Comment by drawrowfly** [comment]
"const posts = await TikTokScraper.user(username, { number: 20000 });"

Thats a big number, always better to use proxy

**Comment by drawrowfly** [comment]
Anyway i will try to push a new update soon, with renewed api endpoints and few other features

**Comment by fanoftiktok** [comment]
Yep, I use proxies. Okay, changing the user-agent fix the problem for now. Thanks for the quick response! I look forward to the new update

**Comment by mightymander** [comment]
how do you download all videos from a list of users?

**Comment by liner601** [comment]
Unfortunately it seems changing the user agent does not work anymore, I hope to see the update to the new api soon!

**Comment by drawrowfly** [comment]
Use proxy . Works fine from mine side

**Comment by liner601** [comment]
> Use proxy . Works fine from mine side

Doesn't seem to work for me, says scraping then eventually times out, no output files.
