### ISSUE TITLE
Missing Metadata

### ISSUE THREAD

**Issue by aholmes97** [drawrowfly/tiktok-scraper#152]
**Describe the bug**
Both through batch processing and user processing (haven't tried individual videos), the metadata is not being downloaded since update to 1.1.11. It still works on 1.1.10.

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**

Used OS -  Debian 10
NodeJs Version (node -v) - 12.16.3
Scraper Version (tiktok-scraper --version) - 1.1.11
CLI or Module - CLI
Used method - user
Used options - filepath, store, historypath, download, hd, w, type
E.g. tiktok-scraper user applemusic —filepath /home/pi/tiktok/ --store --historypath /home/pi/tiktok/history/ - -download --hd -w --type csv
Do you run the scraper through Proxy, VPN, VPS? - Tried both
If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles! - Yes
Preferably provide URL to the profile,hashtag,video and etc page - Happens across all e.g. tiktok, applemusic etc.
**Screenshots**

**Comment by drawrowfly** [comment]
Use -t instead -type
