### ISSUE TITLE
videoUrlNoWaterMark   Function failure

### ISSUE THREAD

**Issue by jackshi007** [drawrowfly/tiktok-scraper#155]
**Describe the bug**
videoUrlNoWaterMark Function failure 

**To Reproduce**
tiktok-scraper video https://www.tiktok.com/@ondymikula/video/675776210967047
7061

videoUrlNoWaterMark   url
https://api2.musical.ly/aweme/v1/playwm/?video_id=v090441a0000bn469kdqa7ljb6oj4jt0

response
{"status_code": 0, "status_msg": "", "extra": {"logid": "20200602075814010189036200000264CA", "now": 1591084694961, "fatal_item_ids": []}, "log_pb": {"impr_id": "20200602075814010189036200000264CA"}, "block_code": 2018}

**Comment by drawrowfly** [comment]
Don't see any issues from my side

Use proxy

Also fill out please next time the bug report properly!
