### ISSUE TITLE
Can't download video without watermark

### ISSUE THREAD

**Issue by riffshop** [drawrowfly/tiktok-scraper#157]
Hello, i'll try to download tiktok without watermark and it still had watermark
my command is : "tiktok-scraper video LINK -d -w true" thanks before 💯

**Comment by drawrowfly** [comment]
tiktok-scraper video https://www.tiktok.com/@tiktok/video/6800111723257941253 -d -w

This command will download video without the watermark. If video is with the watermark then it was already uploaded with it

**Comment by riffshop** [comment]
can i download all video user without watermark and just put -w in my command ?

**Comment by drawrowfly** [comment]
yes you can
