### ISSUE TITLE
Empty data return from scraper

### ISSUE THREAD

**Issue by mukkaramwaheed** [drawrowfly/tiktok-scraper#158]
Yesterday I got data, but now scraper returns nothing. 

Shall I use a proxy for this may be TikTok block my IP?

**Comment by drawrowfly** [comment]
Before reporting issue/bug try all ways and if there is a bug fill out Bug Template

**Comment by drawrowfly** [comment]
Also you just got "rate limited" . Using proxy is a very good idea

**Comment by mukkaramwaheed** [comment]
thanks for your response
