### ISSUE TITLE
Can't scrape the user meta information in bulk without downloading the videos

### ISSUE THREAD

**Issue by venkovachev** [drawrowfly/tiktok-scraper#159]
I'm trying to scrape users' meta form file, `tiktok-scraper from-file usernames.txt 2 -n 50 -t csv ` but when I try to start the scraper it shows an error message `You need to specify file type(-t) where data will be saved AND/OR if posts should be downloaded (-d)`

When I add `-d` to download the videos `tiktok-scraper from-file usernames.txt 2 -n 50 -t csv -d` the scraper starts and both download the videos and scrape the meta info for all of the users and turns it in cvs files

**Comment by drawrowfly** [comment]
Will be fixed in next update
