### ISSUE TITLE
Can't extract Tac value

### ISSUE THREAD

**Issue by iwantooxxoox** [drawrowfly/tiktok-scraper#160]
Error message: "Can't extract Tac value" when use 
```
 TikTokScraper.user('USERNAME', { number: 100 });
```

**Comment by drawrowfly** [comment]
well they've probably changed signature method

**Comment by iwantooxxoox** [comment]
Yes, I think so. Do you have any idea on this? thank you

**Comment by thibaultleouay** [comment]
have a look at this: https://sf16-muse-va.ibytedtos.com/obj/rc-web-sdk-gcs/acrawler.js 
and this 
```
        window.byted_acrawler.init({
            aid: 1988,
            dfp: false,
            boe: false,
            intercept: true,
            enablePathList: ["/api/user/detail", "/api/music/detail", "/api/item/detail", "/api/challenge/detail/", "/share/item/list", "/api/item_list/", "/api/comment/list/", "/api/comment/list/reply/", "/api/discover/user/", "/api/commit/follow/user/", "/api/recommend/user/", "/api/impression/write/", "/share/item/explore/list", "/api/commit/item/digg/", "/node/share/*", "/discover/render/*"],
        });
```

**Comment by drawrowfly** [comment]
They just moved away tac signature

**Comment by thibaultleouay** [comment]
They are using acrawler.js to generate the signature 

it might be similar to what they are doing on douyin see 

https://github.com/elvisyjlin/media-scraper/issues/9

**Comment by drawrowfly** [comment]
Brrrr. old info, since 2019 lots of things changed. Please do not rush to post any fast conclusions

**Comment by ThibaultJanBeyer** [comment]
1. What does "Tac" mean?
2. By "they" you mean Tiktok?
3. And that means the scraper is broken because TikTok changed something?
4. Are you working on this?

:)

**Comment by ThibaultJanBeyer** [comment]
I had a quick look but as I've no clue what `Tac` is I don't think I can help :(
[This code](https://github.com/ThibaultJanBeyer/tiktok-scraper/blob/1a7c338cc493090daa6467f96dd74897fc1778cb/src/helpers/Signature.ts#L17) looks very cryptic to me.
I suppose you're somehow faking an authentification or something?

**Comment by aymather** [comment]
Also experiencing this issue. Only getting it when scraping info on posts though, still able to get a user's profile information... I'm assuming they just operate differently?

**Comment by sharif9876** [comment]
This guy seems to have a solution that works:
https://github.com/carcabot/tiktok-signature

Updated 4 hours ago. Might be worth taking a look at the changes he just made

**Comment by drawrowfly** [comment]
@ThibaultJanBeyer Tac value served as a "secret/key" in signature generating process. Before it was rendered in the web page it self. 
@thibaultleouay is right about the way signature is being generated right now. I have implemented it from mine side, but not luck yet, signature is bad

I also have was able to generate valid tac but it only works with the new endpoints

@sharif9876 is using **puppeteer** and that is way too heavy. This is the "last resort" solution

**Comment by sharif9876** [comment]
@drawrowfly Not sure if this helps you, but if you inspect TikTok's webpage, they call this file:
https://sf16-muse-va.ibytedtos.com/obj/rc-web-sdk-gcs/acrawler.js

If you run that code in your own project, it exposes a new `byted_acrawler.sign()` method that you can pass the URL to. That is what the `tiktok-signature` package is using

**Comment by drawrowfly** [comment]
"I have implemented it from mine side, but not luck yet, signature is bad"

still working on it

**Comment by thibaultleouay** [comment]
I'm trying to inject the new script with jsdom on my side too. 

the other TikTok signature repo seems to also have an issue with the old endpoint too 

https://github.com/carcabot/tiktok-signature/issues/52

**Comment by drawrowfly** [comment]
Patience is very important. Love challenges :)

**Comment by leehanse** [comment]
thanks, wait for resolve this issue

**Comment by charlyBerthet** [comment]
Hi folks!! I am also investigating. Do you guys know what are these red dot characters in [acrawler.js script](https://sf16-muse-va.ibytedtos.com/obj/rc-web-sdk-gcs/acrawler.js) ?

<img width="801" alt="Capture d’écran 2020-06-05 à 10 30 07" src="https://user-images.githubusercontent.com/3427453/83855050-d356f800-a717-11ea-896c-bf52127cd976.png">

**Comment by subokita** [comment]
> Hi folks!! I am also investigating. Do you guys know what are these red dot characters in [acrawler.js script](https://sf16-muse-va.ibytedtos.com/obj/rc-web-sdk-gcs/acrawler.js) ?
> 
> <img alt="Capture d’écran 2020-06-05 à 10 30 07" width="801" src="https://user-images.githubusercontent.com/3427453/83855050-d356f800-a717-11ea-896c-bf52127cd976.png">

Seems to be ASCII code 16  (Data Line Escape)
Probably just extra space the obfuscator add into / shrunk into, shouldn't have any impact on logic of the code.

**Comment by szokeptr** [comment]
I have a solution that allows calling `byted_acrawler.sign()` in Node environment natively, without pupeteer. Let me know if that helps.

**Comment by drawrowfly** [comment]
I did this yesterday through jsdom, but signature is invalid

**Comment by drawrowfly** [comment]
And if someone will have a solution to any problem, do not ask if we need it. 
Test it and post the solution here or submit pull request !

**Comment by szokeptr** [comment]
Sorry, I just started working with TikTok yesterday, I don't know anything about it and I am just working out of experience with Instagram. I didn't know if you already know that solution (but don't like it or whatever) so I though I'd ask before posting. 
So my solution is like this:
I took acrawler.js and executed it in Node.js, which showed me that the script populates the global scope with 3 properties: TAC, oprand and byted_acrawler:
```
szokeptr@Peters-Mac-Pro /tmp
  % node ./acrawler.js                                                                                                                                                                                                                                             !1847
[
  'global',
  'clearInterval',
  'clearTimeout',
  'setInterval',
  'setTimeout',
  'queueMicrotask',
  'clearImmediate',
  'setImmediate',
  'TAC',
  'oprand',
  'byted_acrawler'
]
```

The `byted_acrawler` object has a method `sign` that will error if called in node environment since it relies on some browser-only APIs like `navigator` and `location`. If you provide manually these, the method can be called and a correct signature is made:
```js
… contents of acrawler.js …

// Populate the global scope with missing APIs
location = {
    href: 'https://www.tiktok.com/',
    protocol: 'https:'
};

navigator = {
    userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36'
};

function signUrl(url) {
        return byted_acrawler.sign({ url });
}

```

I tested this with the following endpoints: 
- `https://m.tiktok.com/api/item_list/`
- `https://www.tiktok.com/node/share/user/@username`

**Comment by drawrowfly** [comment]
The signature won't be valid

**Comment by szokeptr** [comment]
The server accepts it with the endpoints I listed above.

**Comment by drawrowfly** [comment]
I've tested with the old api. It actually accepts 1 request out of 3 . Weird. Anyway i will update repo shortly

**Comment by EmilioBarradas** [comment]
@szokeptr Although your solution works for some endpoints, other endpoints require more complex properties (createElement, HTMLCanvasElement, GPUINFO, plugins) in order to generate a signature; you would need to implement those properties into the global scope as well, which is a hassle. It seems like some jsdom implementation is the solution to this, but I have not been able to generate any valid signatures for an endpoint other than the trending page.

**Comment by drawrowfly** [comment]
i will push working version within few hours

**Comment by szokeptr** [comment]
@EmilioBarradas I only need the two mentioned endpoints at this moment, but I will continue investigating since it was a lot of fun 😃

**Comment by areltiyan** [comment]
well working in new version ! wow @drawrowfly

**Comment by drawrowfly** [comment]
@szokeptr the only thing i have learned from the tiktok that there are to many bugs and daily updates, that mess-up with all tests. If you didn't mentioned that your tests are working , i would've abandon this way as it didn't worked for me before!!!

Cheers!

PS

New update was pushed But there is But:
1. it is a bit ugly code for now
2. scraping data from the hashtag feed won't be stable as i wasn't able to find the new endpoint for the hashtag feed as i did with the music feed for example

**Comment by charlyBerthet** [comment]
@szokeptr I am wondering, how did you figure out that global vars `location` and `navigator` were needed?

**Comment by drawrowfly** [comment]
This is similar to previous signature method . They using user agent to bind signature to the browser

**Comment by szokeptr** [comment]
@charlyBerthet since I knew that the sign method worked perfectly in browser but not in Node env, I created recursive mocks of the browser APIs in the global scope using the awesome JS [Proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) and logged all property access attempts.

**Comment by szokeptr** [comment]
@drawrowfly I see that you implemented something similar to what I mentioned. Does that mean that this works for more than those 2 endpoints? (I don’t actively use your module, so I am not sure how everything works)

**Comment by EmilioBarradas** [comment]
@szokeptr Just tested with '/api/user/detail/' and '/api/music/detail/' and it doesn't seem like it does :(

**Comment by drawrowfly** [comment]
@szokeptr 

Basically all Web API endpoints that require the signature

Old API endpoints can be signed but it won't work the way you expect it to , it will randomly return empty response, it means that something is wrong from their side :)

**Comment by EmilioBarradas** [comment]
@drawrowfly What are the new endpoints?

**Comment by ThibaultJanBeyer** [comment]
However, that solution now only works 1 out of 5 times. 4/5 times I get `Result is empty. Try with different input data(username, hashtag and etc)`. Do you have the same?

**Comment by ThibaultJanBeyer** [comment]
> Old API endpoints can be signed but it won't work the way you expect it to , it will randomly return empty response, it means that something is wrong from their side :)

So TikTok has a bug in their code now and you expect it to be resolved soon? :D

**Comment by drawrowfly** [comment]
The only "anti-scraping shit" is captcha

And scraper is working fine expect hashtag feed!

**Comment by drawrowfly** [comment]
And it's not a bug, it's "TikTok" :) . There was lots of times when API behavior was random 

Every few weeks they update UI and that can affect the API

**Comment by drawrowfly** [comment]
@EmilioBarradas just the usual stuff, the ones that are used right now in TikTok Web, you can explore them through inspector

**Comment by tarikhagustia** [comment]
u're awesome bro @drawrowfly ..

**Comment by ThibaultJanBeyer** [comment]
I see thanks fo the clarification, great work! :)

**Comment by youngvo** [comment]
@drawrowfly Thanks for your great tool.
> And scraper is working fine expect hashtag feed!
So did you find any hints to configure the hashtag feed?

**Comment by geco** [comment]
> @drawrowfly Thanks for your great tool.
> 
> > And scraper is working fine expect hashtag feed!
> 
> So did you find any hints to configure the hashtag feed?

Which is the similar invocation method to scrape generic posts? Trending? Thank you in advance

**Comment by youngvo** [comment]
> Which is the more similar invocation method to scrape generic posts? Trending? Thank you in advance
@geco what do you mean? I can't get you on this. Please explain more.
My questions is that at the moment the search for hashtag is not stable. We need to scrape 3 times at least or more to fetch the list of media objects tagged with a specify hashtag.

**Comment by geco** [comment]
I see. There is way using "search for hashtag" (3 times or what we need to have results each), but having new results at every invocation? Now i continue getting always same results.
