### ISSUE TITLE
Can't download video normally

### ISSUE THREAD

**Issue by Live-yan** [drawrowfly/tiktok-scraper#161]
**Describe the bug**

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- Used OS ： **Linux (centos 8.1.1911)**
- NodeJs Version (node -v) ：**v10.21.0**
- Scraper Version (tiktok-scraper --version) ：**tiktok-scraper@1.1.16**
- CLI or Module ：**All about downloads**
- Used method：**All about downloads**
- Used options：**All about downloads**
- Do you run the scraper through Proxy, VPN, VPS?  **no**
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles!
- Preferably provide URL to the profile,hashtag,video and etc page

**Screenshots**

![QQ截图20200605212650](https://user-images.githubusercontent.com/48639236/83882349-8c4b2000-a774-11ea-9a0d-022b7eb49f73.jpg)

**Comment by drawrowfly** [comment]
#160 Some functionality is not working properly

**Comment by Live-yan** [comment]
> #160 Some functionality is not working properly

Could you tell me more about it？
