### ISSUE TITLE
Scraping Following, Followers, Diggs, Videos

### ISSUE THREAD

**Issue by yousufabdel860** [drawrowfly/tiktok-scraper#163]
Was wondering if it was still possible to get these metrics as it was in past versions:

 - number of accounts a channel follows 
 -number of accounts a channel is followed by
 -number of total videos a channel has posted
 -number of total diggs by a channel
 -number of hearts received by a channel

These metrics seem to have been missing ever since a new version was released

**Comment by drawrowfly** [comment]
This info is not provided anymore with the new API endpoints.  But you can use **getUserProfileInfo** to get this info

**Comment by yousufabdel860** [comment]
Is getUserProfileInfo something that can be added to the scraper and supported with info in a csv?

**Comment by drawrowfly** [comment]
It is already existing method in the module. I get it you need it in the CLI probably. If current signature method won't fail soon(can happen) i will add option to execute extra request to obtain this data
