### ISSUE TITLE
Issues with --historypath option

### ISSUE THREAD

**Issue by vnnegt** [drawrowfly/tiktok-scraper#164]
**Describe the bug**

It doesn't appear that the `--historypath` option is working as intended any longer.

**To Reproduce**
1. scrape a profile and store history to a custom path:
`tiktok-scraper user <USER> --number 0 --download --hd --noWaterMark --store --filepath "<FILE PATH>" --historypath "<HISTORY PATH>"`
2. Repeat step number 1. The scraper will scrape the same files again, but this time it will display `Result is empty. Try with different input data(username,hashtag and etc)` at the end

- Used OS
Windows 10

- NodeJs Version (node -v)
13.12.0

- Scraper Version (tiktok-scraper --version)
tiktok-scraper@1.1.18

- CLI or Module

- Used method
`user`

- Used options
`--number`
`--download`
`--hd`
`--noWaterMark`
`--store`
`--filepath`
`--historypath` 

- Do you run the scraper through Proxy, VPN, VPS?
No

- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles!

- Preferably provide URL to the profile,hashtag,video and etc page

**Screenshots**

**Comment by blasphemite** [comment]
Same issue with `--historypath`. The same files are redownloaded, and I get the `Result is empty. Try with different input data(username,hashtag and etc)` error.

- Used OS
Ubuntu 18.04

- NodeJs Version (node -v)
10.20.1

- Scraper Version (tiktok-scraper --version)
1.1.18

- CLI or Module
cli

- Used options
`-d`
`-w`
`-s`
`--historypath`
`-p`
`--filepath`

- Do you run the scraper through Proxy, VPN, VPS?
VPN SOCKS proxy

**Comment by drawrowfly** [comment]
Fixed with the latest update. Confirm and close the issue if all good. Thanks!

**Comment by blasphemite** [comment]
Working for me. Thank you!

**Comment by vnnegt** [comment]
thanks for the quick fix @drawrowfly  !

**Comment by davispuh** [comment]
I think it's broken again. I just cloned latest `master` and if I set `--historypath` it doesn't write there.

**Comment by davispuh** [comment]
Ohh actually it works but for `user`. I was trying `video`
