### ISSUE TITLE
Possibility of adding in more advanced metrics

### ISSUE THREAD

**Issue by yousufabdel860** [drawrowfly/tiktok-scraper#165]
While the current metrics available are fairly useful, I was wondering what was possible in regards to us advancing some of these metrics and providing more in depth insights in current areas.

Authentication is probably necessary
-including the distribution of viewership for each post (Percentage of views that came from FYP,
Following, Personal Profile, etc)
-including the average watch time of each post
-including the location distribution of viewership (Percentage of views that came from a certain country)

**Comment by drawrowfly** [comment]
I think i already replied to this inquiry over the email

This data can be pulled from mobile api only and from personal account that authentication was made from

I will add this to a to do list , but no promises that this will added soon
