### ISSUE TITLE
Thank You!

### ISSUE THREAD

**Issue by bestMate** [drawrowfly/tiktok-scraper#166]
Thank You! Thank You for this great tool and your support

You did a really great job, your tool is being used by a lot of big and small brands. I think we need to provide more support to you. Let me know please what is the best financial way to support you as a developer of this and other your great tools. I've tried through "buy me a coffee" but for some reason it didn't let me to send funds through it!

**Comment by drawrowfly** [comment]
Really glad to hear that :)

If you really want to make donation the best and easiest way is through "buymeacoffe". 

Also i do not force, ask anyone to send me funds and etc. It is only your own decision :)

Thank You 👍
