### ISSUE TITLE
Scrape All Videos Doesn't Function Properly

### ISSUE THREAD

**Issue by huge-breasts** [drawrowfly/tiktok-scraper#168]
When using "tiktok-scraper user USER -d -w 0" alone or along with "-w --hd" doesn't scrape all video on a users page. It does scrape all however if I were to put "tiktok-scraper user USER -d -w 100" and the users page has less than 100 videos. 

Is this a bug or just me? 
If so, do I need to update or wait for a fix?

**Comment by huge-breasts** [comment]
It actually only works sometimes. I have to retry the command multiple times for it to download all videos in bulk.

**Comment by drawrowfly** [comment]
1. Fill out bug template if you have issue
2. try to use -n 0
