### ISSUE TITLE
0 doesn't work when attempting to download all videos from a page

### ISSUE THREAD

**Issue by huge-breasts** [drawrowfly/tiktok-scraper#169]
**Describe the bug**

When trying to download all videos from a page using "tiktok-scraper user USER -d -n 0" either alone or with "-w --hd" fails to download all videos, only downloading some. 

Example: When downloading videos from @test0n using "tiktok-scraper user test0n -d -n 0", only 12 out of the 24 videos on the page download. 

It seems using "0" to download all videos from a page doesn't work anymore at least for me. I've attached screenshots below. 

My apologies for filling out my previous issue improperly. I also mistyped the first form anyway.

**Screenshots**
![example1](https://user-images.githubusercontent.com/66509098/83939394-ddb9d600-a799-11ea-9bae-9b3b38c4ced8.JPG)
![example2](https://user-images.githubusercontent.com/66509098/83939396-df839980-a799-11ea-8edc-72d94705601f.JPG)

**Comment by MrJmpl3** [comment]
I had this problem too. In the console show multiples downloading but in the folder dont save, save only 4 o 5 videos.

**Comment by drawrowfly** [comment]
Will be fixed in next update

**Comment by MrJmpl3** [comment]
> Will be fixed in next update

Thanks, the problem is only in download using the CLI, 

I use manual download with the scrapping in custom scripts and all correct

**Comment by huge-breasts** [comment]
> Will be fixed in next update



> > Will be fixed in next update
> 
> Thanks, the problem is only in download using the CLI,
> 
> I use manual download with the scrapping in custom scripts and all correct

Thanks for the response. I'm glad I wasn't the only one experiencing issues. Looking forward to the fix!

**Comment by xathian** [comment]
Not sure if the update 13 hours ago was supposed to fix this but it did not, still having my download stop after 31 videos on a tiktok account that has over 100 videos.

**Comment by reallyuniquename** [comment]
Use `-n 999` for now.

**Comment by drawrowfly** [comment]
Fix in the latest update

**Comment by rabea98** [comment]
Thank you @drawrowfly  for the hard work!
