### ISSUE TITLE
authorMeta does not giving meta details like, digg, following etc

### ISSUE THREAD

**Issue by muke5hy** [drawrowfly/tiktok-scraper#170]
**Describe the bug**
`authorMeta` in the video response not giving following details. Checked with `getUserProfileInfo` and its working but in video object it's not.

```
following
fans
heart
video
verified
digg
```

**To Reproduce**
- Mac OS
- Node v12.16.2
- Scraper Version 1.1.17
- Module 
- TikTokScraper.user
- number

**Comment by drawrowfly** [comment]
Unfortunately that's the way new API is working 

I will add extra option to the CLI to collect author data , but in module you can use other method that you have mentioned

**Comment by rugualter** [comment]
Hi drawrofly did you already add the option to CLI?

**Comment by luispablo** [comment]
It'd be nice to update the docs (readme) according to this. :-)
