### ISSUE TITLE
Sync npm version with Github release

### ISSUE THREAD

**Issue by MrJmpl3** [drawrowfly/tiktok-scraper#171]
**Describe the bug**
In the tab of Release in Github has v1.1.9 but in NPM page has 1.1.18 version.

Could you sync that? Only make a tag per version

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
Go to Release Page

**Screenshots**

**Comment by drawrowfly** [comment]
ouch

Final version is 1.1.19

Pushed tag

**Comment by MrJmpl3** [comment]
> ouch
> 
> Final version is 1.1.19
> 
> Pushed tag

Bro, Now, package.json is wrong 😅, in package.json have 1.1.18 version

**Comment by drawrowfly** [comment]
This won't affect version that you install locally
