### ISSUE TITLE
After reinstalling windows 10 - Can't extract Tac value

### ISSUE THREAD

**Issue by stiflermt** [drawrowfly/tiktok-scraper#174]
Hi I seem to have hit some unexpected error, I keep getting the following error "Can't extract Tac value"  when calling the script as follows:

tiktok-scraper user testProfile --hd -d -w --filepath "d:\tiktok\"

I had found a post somewhere stating that this may be a IP issue, and have tried from numerous IPs and still get the same result unfortunately

**Comment by drawrowfly** [comment]
You have old version there is no such error at all in the new version
