### ISSUE TITLE
tiktok-scraper hashtag HASHTAG_NAME can't work

### ISSUE THREAD

**Issue by h357650113** [drawrowfly/tiktok-scraper#175]
1. eg: version 1.1.19
> tiktok-scraper hashtag cats -d -n 10

2. error filename in -z
> tiktok-scraper hashtag cats -d -n 10 -z
<img width="522" alt="截屏2020-06-07 下午4 39 43" src="https://user-images.githubusercontent.com/10824697/83964179-af451380-a8dd-11ea-9ffb-a91cd7562d60.png">

**Comment by drawrowfly** [comment]
https://github.com/drawrowfly/tiktok-scraper/issues/160#issuecomment-639741662
