### ISSUE TITLE
Throws a false positive in stderr

### ISSUE THREAD

**Issue by ThibaultJanBeyer** [drawrowfly/tiktok-scraper#177]
by default ora outputs logs to `stderr` which causes implementations using `exec` to throw:

`{ stdout: '', stderr: '- TikTok Scraper Started\n' }`

There is an option that will output the ora stream to `stdout` instead. See https://www.npmjs.com/package/ora/v/3.4.0#stream

I added a PR to fix that: https://github.com/drawrowfly/tiktok-scraper/pull/176

**Comment by drawrowfly** [comment]
Thanks! )
