### ISSUE TITLE
Scraping a hastag doesnt work with example code, but works in CLI

### ISSUE THREAD

**Issue by vvettoretti** [drawrowfly/tiktok-scraper#179]
**Describe the bug**

When scraping a hashtag with the example code, it doesnt work and returns
`{ collector: [] }`
However when using CLI, everything works fine. Used command is
`tiktok-scraper hashtag test -n 100 -t csv `

Used code
```
const TikTokScraper = require("tiktok-scraper");
(async () => {
  try {
    const posts = await TikTokScraper.hashtag("HASHTAG", {
      number: 100,
    });
    console.log(posts);
  } catch (error) {
    console.log(error);
  }
})();
```
Returning
`{ collector: [] }`
CLI works fine though. 
**To Reproduce**
- Windows 10 x64
- NodeJs Version 12.16.1
- Scraper Version 1.1.19
- CLI and Module
- TikTokScraper.hashtag
- Whatever hastag, {number:100}
- Do you run the scraper through Proxy, VPN, VPS? - No

**Comment by drawrowfly** [comment]
https://github.com/drawrowfly/tiktok-scraper/issues/160#issuecomment-639741662
