### ISSUE TITLE
How are new posts handled?

### ISSUE THREAD

**Issue by moodiest** [drawrowfly/tiktok-scraper#18]
Hey there, when downloading posts, how does the program handle new posts for an already downloaded user? Ideally, I'd be able to just run the script again for a user and it would download said user's new posts and their metadata without having to redownload everything. Is this a possibility?

Apologies for opening an issue for this, I couldn't see a way to contact you, drawrowfly.

**Comment by drawrowfly** [comment]
In the current version it is not possible, but i can add this feature to the next update

**Comment by moodiest** [comment]
> In the current version it is not possible, but i can add this feature to the next update

Awesome, I look forward to it. Thank you!

**Comment by drawrowfly** [comment]
@moodiest new update pushed, you can update package to the latest version and it can store the progress to avoid duplicates

**Comment by CCTT9696** [comment]
When i tried to scrape the same user twice, i got two different files with the same username but different number.
The one with inadequate files didn't get any addition.
Im curently on version 1.0.12

**Comment by drawrowfly** [comment]
it is _TIMESTAMP
