### ISSUE TITLE
Wrong fans count with calling TikTokScraper.getUserProfileInfo

### ISSUE THREAD

**Issue by dlyakin** [drawrowfly/tiktok-scraper#181]
**Describe the bug**
When I call 
```
const user = await TikTokScraper.getUserProfileInfo
console.log(user)
```
I see  fans: 162000
But in TikTok application in analytics I see 161991

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- Centos
- NodeJs Version v10.19.0
- Scraper Version 1.1.18
- Module
- TikTokScraper.getUserProfileInfo()
- VPS
- Public profile

**Comment by drawrowfly** [comment]
Data is collected directly from the tiktok

**Comment by dlyakin** [comment]
I see, but may be there is a way to get exact count?
