### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by liner601** [drawrowfly/tiktok-scraper#185]
**Describe the bug**
The scraper runs with no output then times out back to command input.

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- Windows 10
- v12.16.3
- 1.2.0
- Pretty sure its cli since I don't use docker but I don't know what cli means.
- tiktok-scraper user USERNAME
- None, I've tried proxies and it doesn't fix the issue.
- Nope.
- Profiles are public

**Screenshots**
Phase 2
![Screenshot_1602](https://user-images.githubusercontent.com/45104683/84507793-0b3ade00-acca-11ea-99af-955dc5a70d57.png)
Phase 1
![Screenshot_1601](https://user-images.githubusercontent.com/45104683/84507795-0c6c0b00-acca-11ea-889f-3609e0aeb954.png)
.

**Comment by drawrowfly** [comment]
Can't reproduce. Not enough information

**Comment by liner601** [comment]
> Can't reproduce. Not enough information

... Didnt I just give all the steps to reproduce this issue? i gave you my os, command, node js version. What else do you need? I installed it trough npm if thats what you're looking for.
