### ISSUE TITLE
filter video by upload location and date range, also download quality down to 1kb each video

### ISSUE THREAD

**Issue by mreimrei** [drawrowfly/tiktok-scraper#186]
I'm looking for this video I have little memory of that I lost because of accidental refresh. I only know where it is from and possibly the song, but the song has about 50M videos. I need to make my search easier since I don't want to be insane. My ideas are in the title. Are they plausible? Thank you.

**Comment by drawrowfly** [comment]
Here you can create only Issues or Propose new features related to the scraper. 
Please use google for such questions

**Comment by mreimrei** [comment]
Yes, I’m sorry, I did mean it as a proposal of features for the scraper, I hope that is clear. It was after downloading the scraper that I asked. Although, I may have sounded ignorant because I don’t know what’s plausible, since I know nothing about code.

**Comment by mreimrei** [comment]
I intend on downloading the videos with the scraper

**Comment by drawrowfly** [comment]
I'm still not sure what is the feature that you are proposing to add to the scraper?

**Comment by mreimrei** [comment]
> I'm still not sure what is the feature that you are proposing to add to the scraper?

1. download videos based on location of upload, say country-based e.g. I want to download all videos uploaded in Switzerland
2. specify download by a specific date, e.g. I want to download all videos that are uploaded on May 5th, 2020
3. Adjust quality of download down to as low as possible, say 100kb per video or lower
