### ISSUE TITLE
Problem when installation program

### ISSUE THREAD

**Issue by arvinls** [drawrowfly/tiktok-scraper#187]
**Describe the bug**
I can not download the video successfully. 
This is my first time download the github program, so the question may be some stupid. But it is really comfused me.

**To Reproduce**

- Used OS :   Windows  X86-based PC
- NodeJs Version   v12.18.0
- Scraper Version   version 1.2.0

After distrubute the program by using "npm i -g tiktok-scraper". When i running "tiktok-scraper --help" , it shows like this 

Commands:
  **cli.js** user [id]                 Scrape videos from the User Feed. Enter only
                                   the username
  cli.js hashtag [id]              Scrape videos from the Hashtag Feed. Enter
                                   hashtag without the #
  cli.js trend                     Scrape posts from the Trend Feed
  cli.js music [id]                Scrape videos from the Music Feed. Enter only
                                   the music id
  cli.js video [id]                Extract metadata from a single video without
                                   the watermark. To download use -d flag
  cli.js history                   View previous download history
  cli.js from-file [file] [async]  Scrape users, hashtags, music, videos
                                   mentioned in a file. 1 value per 1 lin
Examples:
  cli.js user USERNAME -d -n 100
  cli.js trend -d -n 100
  cli.js hashtag HASHTAG_NAME -d -n 100
  cli.js music MUSIC_ID -d -n 50
  cli.js video https://www.tiktok.com/@tiktok/video/6807491984882765062 -d
  cli.js history
  cli.js history -r user:bob
  cli.js history -r all
  cli.js from-file BATCH_FILE ASYNC_TASKS -d

I don't know why it is not "**tiktok-scraper** user [id]     Scrape videos from username. Enter only username".

When I run ">tiktok-scraper trend -d -n 10", it will running. But the download .mp4 files are only 219kb.

I want to know where is wrong?

**Comment by drawrowfly** [comment]
Any errors? Video files are completed(you can view them)?

**Comment by arvinls** [comment]
> Any errors? Video files are completed(you can view them)?

No, all the file are only 219KB, it can not be open.

**Comment by arvinls** [comment]
> Any errors? Video files are completed(you can view them)?

It is no error printed. When running by using username it just creates a fold, and does nothing. So is it because I did not install something ？ I do not know how to figure out it？

**Comment by anup2050** [comment]
just started with me too.. if i scrape trend or music then it download 3-4 kb files which is corrupt

**Comment by drawrowfly** [comment]
Update to the latest version and it will work

**Comment by arvinls** [comment]
> just started with me too.. if i scrape trend or music then it download 3-4 kb files which is corrupt

how do you solve this problem?
