### ISSUE TITLE
Not able to get video list of user

### ISSUE THREAD

**Issue by aashitshah26** [drawrowfly/tiktok-scraper#188]
Hey i have used the following 2 urls to get data but was not able to get any data:

`https://m.tiktok.com/api/item_list?secUid=null&id=rupashah2203&sourceType=8&count=50&minCursor=0&maxCursor=50&lang=null&verifyFp=null/`

When intercepting the request from web i get the url 

`https://m.tiktok.com/api/item_list/?count=30&id=6626622408684748805&type=1&secUid=MS4wLjABAAAAJH2yLzWCA2iLVIu_qYyVPhFFrPRsIGq503ZjWd_crXF_-HL_a6FmqkmsMMhvBBHg&maxCursor=0&minCursor=0&sourceType=8&appId=1180&region=IN&language=en&verifyFp=verify_kbdaeq33_sZGG81WG_bBDg_4vdj_9AhP_qtZXMEm4BoAI&_signature=Pv7ACgAgEBBM40HNEEGByj7-wRAAGAg`

How to get the verifyFp and signature cause without it the list is returning empty. Please help me

**Comment by drawrowfly** [comment]
verifyFp is not important to execute  the request , as long as you have valid signature key your request will be execuded
