### ISSUE TITLE
Posts with pages "Video currently unavailable"

### ISSUE THREAD

**Issue by remlap** [drawrowfly/tiktok-scraper#189]
Posts with pages "Video currently unavailable" will not scrape but videos are available on the users profile.

`tiktok-scraper --hd -d video https://www.tiktok.com/@mariamenounos/video/6830547359403937030`

`Can't extract metadata from the video: https://www.tiktok.com/@mariamenounos/video/6830547359403937030`

I assume some sort of geoblocking is in play but the video can be viewed when clicking through profile but not directly.

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- Ubuntu 20.04
- NodeJs v10.19.0
- Scraper Version 1.2.0
- CLI
- Used method: video
- Used options: -hd -d
- No Proxy
- URL: https://www.tiktok.com/@mariamenounos/video/6830547359403937030
- Profile: https://www.tiktok.com/@mariamenounos

**Comment by drawrowfly** [comment]
i can't access video https://www.tiktok.com/@mariamenounos/video/6830547359403937030 it means it is not public, probably owner has privacy enabled. Nothing can be done in this case

**Comment by remlap** [comment]
> i can't access video https://www.tiktok.com/@mariamenounos/video/6830547359403937030 it means it is not public, probably owner has privacy enabled. Nothing can be done in this case

You can access the video though https://www.tiktok.com/@mariamenounos it's the first.

**Comment by drawrowfly** [comment]
Video should be available from the direct url https://www.tiktok.com/@mariamenounos/video/6830547359403937030 and it is not

**Comment by drawrowfly** [comment]
Maybe this is some kinda bug related to some update from the tiktok side
