### ISSUE TITLE
music ID not working

### ISSUE THREAD

**Issue by hiamlegend** [drawrowfly/tiktok-scraper#19]
Command does not do anything. Am I correctly inserting the music id?

URL: https://www.tiktok.com/music/The-Box-6768646921029470981?lang=en

Tried
`tiktok-scraper music The-Box-6768646921029470981 -n 50 -d`

`tiktok-scraper music 6768646921029470981 -n 50 -d`

`tiktok-scraper music The-Box -n 50 -d`

none is downloading

**Comment by drawrowfly** [comment]
Your package needs version update

**Comment by rosnaib11** [comment]
Same, to me either no data or stuck at "TikTok Scraper Started" and just loading forever

```
tiktok-scraper music original-sound-66664538..... -n 100 -d

tiktok-scraper music 66664538545.... -n 100 -d
```

**Comment by devbiansor** [comment]
@hiamlegend did you manage to run this command?
