### ISSUE TITLE
Rounded number

### ISSUE THREAD

**Issue by madnai** [drawrowfly/tiktok-scraper#190]
When Im using method getHashtagInfo as a result I get number of 'views'.
Unfortunatelly I don't get a exact number but rounded numer.
For example for hashtag 'funny' I get views: '368200000000',

The same issue happen on getUserProfileInfo.
As a return I get rounded number of fans.

**Comment by dlyakin** [comment]
TikTok api returns this values. Several days ago TikTok has rounded all number values in it API

**Comment by drawrowfly** [comment]
Issue is related to the tiktok itself
