### ISSUE TITLE
Can't extract metadata from the video

### ISSUE THREAD

**Issue by dlyakin** [drawrowfly/tiktok-scraper#191]
**Describe the bug**
Try to get metada for video and get error:
Can't extract metadata from the video: https://www.tiktok.com/@joewaud_pov_/video/6835800055857810694

code:
`const videoMeta = await TikTokScraper.getVideoMeta('https://www.tiktok.com/@joewaud_pov_/video/6835800055857810694');`

**To Reproduce**
- Cent OS
- NodeJs Version 12
- Scraper Version 1.1.18
- CLI or Module : Module
- Used method: getVideoMeta
- Used options: none
- Do you run the scraper through: VPS
- Preferably provide URL to the profile,hashtag,video and etc page : https://www.tiktok.com/@joewaud_pov_/video/6835800055857810694

**Comment by drawrowfly** [comment]
I can't access this url and same thing is happening with the scraper. Scraper can retrieve only publicly visible data

**Comment by drawrowfly** [comment]
Also now i can access this video and scraper was able to retrieve the metadata. Also update to the latest version

**Comment by dlyakin** [comment]
@drawrowfly How do you try to get access this url? 

I click this link in Incognito Chrome mode and get access. Look at the screenshot 
![image](https://user-images.githubusercontent.com/6614211/84602221-76351200-ae8e-11ea-83e7-edfb56c31bbd.png)

**Comment by dlyakin** [comment]
https://www.tiktok.com/@tiktok/video/6836658539403037958 one more video @drawrowfly

**Comment by dlyakin** [comment]
One more https://www.tiktok.com/@dasha_poleva_/video/6834569295997963526
