### ISSUE TITLE
videoUrlNoWaterMark stopped working

### ISSUE THREAD

**Issue by brennanerbz** [drawrowfly/tiktok-scraper#192]
Not sure what happend but URLs are coming back as:
https://api2.musical.ly/aweme/v1/playwm/?video_id=awesome&improve_bitrate=1&ratio=1080p

**Comment by e316** [comment]
This just started happening with me also.

**Comment by brennanerbz** [comment]
It looks like they changed their ID system? The videoUrls used to go to v19.tiktokcdn and are now directed to v16m

**Comment by e316** [comment]
Is it possible to download the non hd version for now.

**Comment by drawrowfly** [comment]
Before video id was extracted from the video file content , after switching to the new API this video id was in the response and now they replaced video id value to the "awesome" :)

I will restore original way of getting uniq video id

Also i've noticed traffic from the https://bytedance.com/(TikTok owner) to this repo. My guess that they are tracking everything that is done here  :)

**Comment by drawrowfly** [comment]
Fixed with the latest update

**Comment by brennanerbz** [comment]
This still isn't working for the node module
