### ISSUE TITLE
webHookUrl function not working

### ISSUE THREAD

**Issue by ohari5336** [drawrowfly/tiktok-scraper#194]
repo working but I download user video then it creates video (.mp4) file but not save the video.
but this is not a big issue according to my requirements.

I want to set webhook URL in this using you command this:

tiktok-scraper --webHookUrl "http://localhost/a.php"

but its show this error:

Not enough non-option arguments: got 0, need at least 1

please see this and share any solution
I am run this code in my windows 10 64bit

node -v
v12.5.0

npm -v
6.9.0

**Comment by drawrowfly** [comment]
No enough data. Please completely fill out bug template

**Comment by drawrowfly** [comment]
Also before you will . Read on how to use the scraper
