### ISSUE TITLE
Download is not working - just generating videos of size 8 bytes

### ISSUE THREAD

**Issue by ShinRai1090** [drawrowfly/tiktok-scraper#195]
**Describe the bug**
Download is not working - just generating videos of size 8 bytes

tried the below command and it was working till a few hours back -
tiktok-scraper user username -d -n <Number>

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- Used OS:
Windows 10
- NodeJs Version (node -v):
12.15.0
- Scraper Version (tiktok-scraper --version):
1.1.19
- CLI or Module:
CLI
- Used method:
user -d -n
- Used options:
-d -n
- Do you run the scraper through Proxy, VPN, VPS?
No
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles!
Yes
- Preferably provide URL to the profile,hashtag,video and etc page
All profiles I tried faced this issue.

**Screenshots**

**Comment by drawrowfly** [comment]
Update scraper to 1.2.1

**Comment by ShinRai1090** [comment]
I was going to come and update to say it worked after I tried the update, but saw your comment 😆 

thanks 👍
