### ISSUE TITLE
user likes

### ISSUE THREAD

**Issue by kaaaan44** [drawrowfly/tiktok-scraper#196]
I see https://github.com/davidteather/TikTok-Api/releases add this user likes future.How we scraper or download videos if userLikes are not hidden.Can this be added?

**Comment by drawrowfly** [comment]
i can add this method but it will only work if user is allowing to view his liked videos section. Most users keep it private

**Comment by drawrowfly** [comment]
Will be added to the todo list, but no promises that it will be done soon
