### ISSUE TITLE
I updated and then water mark is in videos

### ISSUE THREAD

**Issue by ProtoNimra** [drawrowfly/tiktok-scraper#198]
**Describe the bug**
water mark is in videos after I updated to version 1.2.1 when I used batch file

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**

- Scraper Version (tiktok-scraper --version)
1.2.1
- Preferably provide URL to the profile,hashtag,video and etc page

**Screenshots**
If applicable, add screenshots t

![water mark](https://user-images.githubusercontent.com/66974858/84706912-0caf1500-af1b-11ea-94aa-42c8371d164c.png)

o help explain your problem.

**Comment by drawrowfly** [comment]
Try to execute this command: 
`tiktok-scraper user americanredcross -d -n 5 -w`

It will work 100%

Some users do upload videos with the watermark from the beginning

**Comment by drawrowfly** [comment]
Oh batch command sorry 
`tiktok-scraper from-file file 3  -d -w -n 5`

In file i had:
```
americanredcross
tiktok
```

**Comment by ProtoNimra** [comment]
it got  stucked  :(

> Oh batch command sorry
> `tiktok-scraper from-file file 3 -d -w -n 5`
> 
> In file i had:
> 
> ```
> americanredcross
> tiktok
> ```

**Comment by ProtoNimra** [comment]
ohh thank you, working now... this is an amazing tool

> Oh batch command sorry
> `tiktok-scraper from-file file 3 -d -w -n 5`
> 
> In file i had:
> 
> ```
> americanredcross
> tiktok
> ```

**Comment by brennanerbz** [comment]
Does this work with the npm version too? Getting '' for videoUrlNoWaterMark

**Comment by ProtoNimra** [comment]
> Does this work with the npm version too? Getting '' for videoUrlNoWaterMark

Yes, I used npm version...

**Comment by brennanerbz** [comment]
Sorry, that was confusing. It works from the command line, but it doesn't work if you install it as dependency in your project.
