### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by sriramkumar1996** [drawrowfly/tiktok-scraper#199]
The generated _signature is not working to get the required data. 

**To Reproduce**
- OS: Ubuntu 20.04 LTS 
- NodeJs Version: v10.19.0
- Scraper Version (1.2.2)
- CLI or Module(Any)
- Used method(Any)
- Used options(Any)
- Do you run the scraper through Proxy, VPN, VPS? No(Testing), Yes(Production)
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles! Public
- Preferably provide URL to the profile,hashtag,video and etc page
1. tiktok-scraper user bethrivera8 -d -n 10
2. tiktok-scraper hashtag funny -d -n 10

Getting empty files with no data.

**Comment by drawrowfly** [comment]
use proxy
