### ISSUE TITLE
Short url

### ISSUE THREAD

**Issue by jackshi007** [drawrowfly/tiktok-scraper#201]
![image](https://user-images.githubusercontent.com/5241707/84764432-92b27680-af82-11ea-92a4-11ca2adf5b97.png)
 
hi~
can provide short url for tiktok-scraper ?

**Comment by jackshi007** [comment]
tiktok-scraper video https://vt.tiktok.com/DNoWLR
Can't extract metadata from the video: https://vt.tiktok.com/DNoWLR

**Comment by TheSwedishFish13** [comment]
Having the same issue.
Also, the short links redirect to https://m.tiktok.com/v/[video_id] rather than the needed /@user/[video_id]

![image](https://user-images.githubusercontent.com/27036706/84810418-52321780-afd9-11ea-8af0-4a2888a2ff99.png)

**Comment by drawrowfly** [comment]
New version supports other url formats
