### ISSUE TITLE
Download creates 0 bytes files

### ISSUE THREAD

**Issue by Fukitsu** [drawrowfly/tiktok-scraper#203]
**Describe the bug**
Downloading doesn't work, it only creates (or "downloads") a 0 bytes file. 
## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- Used OS
Windows 10
- NodeJs Version (node -v)
12.18.0
- Scraper Version (tiktok-scraper --version)
1.2.2
- CLI or Module
CLI
- Used method
video
user
- Used options
-d -w --hd
-d -w
- Do you run the scraper through Proxy, VPN, VPS?
No
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles!
Yes, it's public
- Preferably provide URL to the profile,hashtag,video and etc page
It happens with any video or profile
**Screenshots**

**Comment by vnnegt** [comment]
i've been experiencing the same issue, although it doesn't appear to be every file scraped, and doesn't happen every time so i thought maybe it was a TikTok issue

**Comment by huge-breasts** [comment]
Same issues here. Attempting to scrape all videos from a page only properly downloads a select few at random. The rest come out as broken 0 byte files.

**Comment by drawrowfly** [comment]
Just pushed an update that is fixing this issue
