### ISSUE TITLE
HD option not downloading the HD version any longer

### ISSUE THREAD

**Issue by vnnegt** [drawrowfly/tiktok-scraper#204]
**Describe the bug**

Looks like the HD option is no longer working after the upgrade to `1.2.4`

## If fields below will be empty then issue will be Ignored and Closed
**To Reproduce**

1. Scrape a profile with the following command + options:
`tiktok-scraper user <USER> --number 0 --download --hd --noWaterMark --store --filepath "<FILE_PATH>" --historypath "<HISTORY_PATH>" `

- Used OS
Win10

- NodeJs Version (node -v)
node/13.12.0

- Scraper Version (tiktok-scraper --version)
1.2.4

- CLI or Module
cli

- Used method
user

- Used options
--number
--download
--hd
--noWaterMark
--store
--filepath
--historypath 

- Do you run the scraper through Proxy, VPN, VPS?
No

- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles!

- Preferably provide URL to the profile,hashtag,video and etc page

**Screenshots**

**Comment by areltiyan** [comment]
i think hd version just like this

https://api-h2.tiktokv.com/aweme/v1/play/?video_id=videoid&improve_bitrate=1 
**_or_**
https://api2-16-h2.musical.ly/aweme/v1/play/?video_id=videoid&improve_bitrate=1

this will downloading HD version/higher rasio automatic

**Comment by drawrowfly** [comment]
--hd is adding improve_bitrate=1

**Comment by drawrowfly** [comment]
And yes it does not downloading higher quality with that value anymore. Well will check it later

**Comment by PerterPon** [comment]
I think with the new domain, `improve_bitrate` did not work anymore, so sad, any other ideas?

**Comment by drawrowfly** [comment]
try latest version. quality will be better

**Comment by kkshl** [comment]
Is the API dead?

**Comment by vnnegt** [comment]
@drawrowfly apologies for the misunderstanding, but are you saying this will be fixed soon, or was this fixed with the latest update?

because i still cannot download HD videos

thanks

**Comment by drawrowfly** [comment]
Nothing was broken from the beginning . I have updated it and quality is better already . Also in the future if there will be another way off course I(or someone else) will update the repo

**Comment by drawrowfly** [comment]
Did you updated to the latest version?

**Comment by vnnegt** [comment]
Yes i have updated.

The reason I ask is because I compared an HD video i downloaded previously, with one i downloaded with the new version, and the new version is definitely lower quality.

The old one has larger dimensions, higher bitrate, bigger size, etc

Maybe it's a TikTok change?

**Comment by drawrowfly** [comment]
As you probably noticed that scraper didn't download videos without the watermark, the url it self changed and with that change changed the params and etc

Anyway there is always i way
