### ISSUE TITLE
Some public tiktok videos are not downloading

### ISSUE THREAD

**Issue by kamronbek29** [drawrowfly/tiktok-scraper#205]
Some public tiktok videos are not downloading. I tried to download videos, some of them are downloaded, but least not. 

For example:
1. https://vm.tiktok.com/JJJ1ANB/
2. https://vm.tiktok.com/J1Ey32m/
3. https://vm.tiktok.com/J1En8q1/
4. https://vm.tiktok.com/J1E9h1q/
5. https://vm.tiktok.com/J1EWdfv/
6. https://vm.tiktok.com/J1sCdxY
7. https://vm.tiktok.com/J1EsbBL/
8. https://vm.tiktok.com/J1EpAm2/
9. https://vm.tiktok.com/J1EPL83/
10. https://vm.tiktok.com/J1EHmsH/
11. https://vm.tiktok.com/J1ECxDQ/
12. https://vm.tiktok.com/J1EgJww/
13. https://vm.tiktok.com/J1EQyBM/
And a lot of other videos. I dont understand why it is happening. Could you, please, check it and fix it, please?

**Comment by kamronbek29** [comment]
> Some public tiktok videos are not downloading. I tried to download videos, some of them are downloaded, but least not.
> 
> For example:
> 
> 1. https://vm.tiktok.com/JJJ1ANB/
> 2. https://vm.tiktok.com/J1Ey32m/
> 3. https://vm.tiktok.com/J1En8q1/
> 4. https://vm.tiktok.com/J1E9h1q/
> 5. https://vm.tiktok.com/J1EWdfv/
> 6. https://vm.tiktok.com/J1sCdxY
> 7. https://vm.tiktok.com/J1EsbBL/
> 8. https://vm.tiktok.com/J1EpAm2/
> 9. https://vm.tiktok.com/J1EPL83/
> 10. https://vm.tiktok.com/J1EHmsH/
> 11. https://vm.tiktok.com/J1ECxDQ/
> 12. https://vm.tiktok.com/J1EgJww/
> 13. https://vm.tiktok.com/J1EQyBM/

**Comment by drawrowfly** [comment]
fill out bug template

**Comment by kamronbek29** [comment]
> fill out bug template

Edited issue, could u check it now?

**Comment by drawrowfly** [comment]
If you are using version of the scraper 1.1.10 the you need to update the tiktok-scraper

**Comment by kamronbek29** [comment]
> If you are using version of the scraper 1.1.10 then you need to update the tiktok-scraper

Could you please tell me, how to update it?

**Comment by AlphaBetaWhisky** [comment]
`git pull origin master` or re-download tiktok-scraper
