### ISSUE TITLE
New link showing empty page

### ISSUE THREAD

**Issue by DeadlyMissile** [drawrowfly/tiktok-scraper#207]
**Describe the bug**
I got the video id. Put it in the new url and nothing loads. Tried the link on reqbin and it shows nothing. No content

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- Tried on my iPhone ( I had a video id stored from previous sessions )
- NodeJs Version (node -v)
- Scraper Version (tiktok-scraper --version)
- CLI or Module
- Used method
- Used options
- Do you run the scraper through Proxy, VPN, VPS?
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles!
- Preferably provide URL to the profile,hashtag,video and etc page

**Screenshots**

**Comment by drawrowfly** [comment]
Please fill out bug template completely with all version options and etc

**Comment by drawrowfly** [comment]
Just to be clear scraper has a lot of options with a lot of different links and etc

**Comment by DeadlyMissile** [comment]
This link to be exact
https://api2-16-h2.musical.ly/aweme/v1/play/?video_id=${id}&vr_type=0&is_play_url=1&source=PackSourceEnum_PUBLISH&media_type=4${
                    this.hdVideo ? `&ratio=540p` : ''

**Comment by drawrowfly** [comment]
TikTok changed the way you can access this url, you won't be able access it from the browser, but you can download it through scraper

**Comment by DeadlyMissile** [comment]
@drawrowfly I see you used 540p. We no longer have 1080p?

**Comment by drawrowfly** [comment]
TikTok is dropping the video quality if you will set 1080. The best result i've got was with the 540p

**Comment by Inzilkin** [comment]
Tiktok gives empty page. How fix it? https://api2-16-h2.musical.ly/aweme/v1/play/?video_id=v09044380000bpsh3nct0rnp7h6dkr40&vr_type=0&is_play_url=1&source=PackSourceEnum_PUBLISH&media_type=4(link)
