### ISSUE TITLE
--version give wrong version

### ISSUE THREAD

**Issue by AlphaBetaWhisky** [drawrowfly/tiktok-scraper#208]
**Describe the bug**
Package.json version is 1.2.4, but tiktok-scrapper --version give 1.1.10, I downloaded the project, ran yarn and yarn build, and still the same problem.

I also have problems with `Can't extract Tac value`, but feel like this problem might be part of it.

- Used OS: Windows 10
- NodeJs Version: v14.4.0
- Scraper Version : 1.1.10, but want 1.2.4.
- CLI
- Used options: --version
- No VPN or Proxy

**Comment by drawrowfly** [comment]
it is not a scraper related bug

**Comment by drawrowfly** [comment]
Remove it completely and install again

**Comment by AlphaBetaWhisky** [comment]
If others have problems updating your version I think `yarn global add tiktok-scraper` fixed it for me.
