### ISSUE TITLE
videoUrlNoWaterMark is not working

### ISSUE THREAD

**Issue by kienvtqhi** [drawrowfly/tiktok-scraper#209]
I ran your example code. The videoUrlNoWaterMark is not working. When i open the url in browser, it show an empty page. It is not a video without watermark. 

https://api2.musical.ly/aweme/v1/playwm/?video_id=v09044b90000bpfdj5q91d8vtcnie6o0

Any solution to open it? Thank you!

**Comment by Silicon-Central** [comment]
You need to update this lib by running "npm upgrade"
After doing so you will realize that this it is still showing a white page and not the video. This is because TikTok is "banning" your browser from seeing the video. You can go around this by downloading the video via curl or viewing the video from VLC (or a similar app).

**Comment by kienvtqhi** [comment]
@Silicon-Central Thanks for your answer. I tried to open the video from VLC and download via curl but they are failed.

**Comment by drawrowfly** [comment]
#207 duplicate . New url without the watermark won't open as usually in browsers (tiktok side) . But you can download them with scraper

**Comment by Jetereting** [comment]
> #207 duplicate . New url without the watermark won't open as usually in browsers (tiktok side) . But you can download them with scraper or by using curl just don't set headers

curl -o https://api2.musical.ly/aweme/v1/playwm/?video_id=v09044b90000bpfdj5q91d8vtcnie6o0

is also not work.

**Comment by drawrowfly** [comment]
curl "https://api2-16-h2.musical.ly/aweme/v1/play/?video_id=ID&vr_type=0&is_play_url=1&source=PackSourceEnum_PUBLISH&media_type=4&improve_bitrate=1&ratio=580p" --output bob.mp4 -H "user-agent:okhttp"

**Comment by MrJmpl3** [comment]
> curl "https://api2-16-h2.musical.ly/aweme/v1/play/?video_id=ID&vr_type=0&is_play_url=1&source=PackSourceEnum_PUBLISH&media_type=4&improve_bitrate=1&ratio=580p" --output bob.mp4 -H "user-agent:okhttp"

A simple question, Why the user-agent is okhttp? I ask that, because I use axios to download.

**Comment by drawrowfly** [comment]
It is even simpler, you can pass there any value except real browser user agent and it will work

**Comment by RotemAkerman** [comment]
Tried the exact command as you wrote:
```curl "https://api2-16-h2.musical.ly/aweme/v1/play/?video_id=ID&vr_type=0&is_play_url=1&source=PackSourceEnum_PUBLISH&media_type=4&improve_bitrate=1&ratio=580p" --output bob.mp4 -H "user-agent:okhttp"```
and it downloaded an empty file 

Also tried my own URL after parsing: `https://api2.musical.ly/aweme/v1/playwm/?video_id=v090440c0000broava1e3ejpfk11urn0` - same results
Tried using another provider that gets the video w/o watermark, it redirects to:
```
http://v19.tiktokcdn.com/95c4cef8287588b761722734d2ebc876/5ef107ef/video/tos/useast2a/tos-useast2a-ve-0068c002/3218ef6f07b54a7aacc5da298b617b44/
```
which does not include the video id at all
