### ISSUE TITLE
Does anyone have a better HD version idea?

### ISSUE THREAD

**Issue by PerterPon** [drawrowfly/tiktok-scraper#212]
video id: v070256f0000br5426evge3nbfelgg20

I download the video by the old way, and the size is almost 200MB, but the old way was blocked by TikTok, now the new way only got 9.6MB, I tried a lot of time to figure out a new way, but I failed,  does anyone have a better way?

**Comment by shivshnkr** [comment]
> video id: v070256f0000br5426evge3nbfelgg20
> 
> I download the video by the old way, and the size is almost 200MB, but the old way was blocked by TikTok, now the new way only got 9.6MB, I tried a lot of time to figure out a new way, but I failed, does anyone have a better way?

+1

**Comment by rofiqsetiawan** [comment]
@PerterPon 

It seems they changed their api from `https://api2.musical.ly/aweme/v1/playwm/?video_id=` to `https://api.tiktokv.com/aweme/v1/playwm/?video_id=`

`improve_bitrate=1` and `ratio=1080p` still works 👍

**Comment by remlap** [comment]
> @PerterPon
> 
> It seems they changed their api from `https://api2.musical.ly/aweme/v1/playwm/?video_id=` to `https://api.tiktokv.com/aweme/v1/playwm/?video_id=`
> 
> `improve_bitrate=1` and `ratio=1080p` still works

How can this be integrated into tiktok-scraper?

Thank you.

**Comment by PerterPon** [comment]
> @PerterPon
> 
> It seems they changed their api from `https://api2.musical.ly/aweme/v1/playwm/?video_id=` to `https://api.tiktokv.com/aweme/v1/playwm/?video_id=`
> 
> `improve_bitrate=1` and `ratio=1080p` still works 👍

emmmm, I tried this way, and the size of the video: `v070256f0000br5426evge3nbfelgg20 ` is still 10MB, and it has a watermark

**Comment by remlap** [comment]
Have you closed this because you have a fix?

Thanks

**Comment by areltiyan** [comment]
> > @PerterPon
> > It seems they changed their api from `https://api2.musical.ly/aweme/v1/playwm/?video_id=` to `https://api.tiktokv.com/aweme/v1/playwm/?video_id=`
> > `improve_bitrate=1` and `ratio=1080p` still works +1
> 
> emmmm, I tried this way, and the size of the video: `v070256f0000br5426evge3nbfelgg20 ` is still 10MB, and it has a watermark

try to add `&watermark=0`

**Comment by remlap** [comment]
> &watermark=0

That wont make it 1080p though.

**Comment by drawrowfly** [comment]
brr

This endpoint is pointing to the originally uploaded video, if there is watermark then it was uploaded with it

**No watermark:** https://api.tiktokv.com/aweme/v1/playwm/?video_id=v09044b20000brls6d9e3ejmgvhtbf3g 
**Watermark:** https://www.tiktok.com/@tiktok/video/6839775130407750917

I will add this endpoint to the scraper
