### ISSUE TITLE
Link without watermask die

### ISSUE THREAD

**Issue by tienbm** [drawrowfly/tiktok-scraper#213]

**Comment by Inzilkin** [comment]
all work, if you downloading with curl and headers is clear. same thing in the python.

**Comment by tienbm** [comment]
I use npm. when use "tiktok-scraper": "1.2.1" result {"error":"Can't extract metadata from the video: https://vm.tiktok.com/JJ2j67k"}

**Comment by drawrowfly** [comment]
works fine from mine side. some people cant correctly update the scraper version 

to check version 
`tiktok-scraper --version`

**Comment by drawrowfly** [comment]
Before posting any message, you need to make sure that you have tried everything,scraper version, ip or proxy related iossues
