### ISSUE TITLE
Make channel history JSON paths relative (OperationalError: ENOENT: no such file or directory)

### ISSUE THREAD

**Issue by Gorrrg** [drawrowfly/tiktok-scraper#214]
**Is your feature request related to a problem? Please describe.**
When moving the history files to another location, the accessing the history fails (ie. when using -r) because the paths to the reference files of the channels are absolute.

**Describe the solution you'd like**
Make them relative. Just use the base name of the file since people will most likely not store them in a different place. At most they may want to store them in a subdirectory to the history path.

**Comment by drawrowfly** [comment]
People actually do store them in random places thats why i have add --historypath option you can use it to point to the file location

**Comment by Gorrrg** [comment]
No that's not what I mean, lol. I do use the **historypath** option myself!

There's json files for each channel.  And their location is stored in _tiktok_history.json_ with an absolute path, like "D:\\Video\\Channels\\tiktok-scraper/1234567890.json"! That's the path I'm talking about. The one in _tiktok_history.json_ under "file_location".

Let's say I store the history in one place "D:\Videos" for a while but decide to store it in another place "D:\Temp", so I move all the files into "D:\Temp". But then the history removal function breaks! Because in the _tiktok_history.json_ the file_locations still point to "D:Videos\1234567890.json" and so on.
