### ISSUE TITLE
download the latest hashtag videos

### ISSUE THREAD

**Issue by darko1x** [drawrowfly/tiktok-scraper#218]
I'm trying to download videos from hashtag using this line: 
tiktok-scraper hashtag ## -n 10 -d -w -s --hd --filepath /Users/path/file
here is my problem: the scraper is downloading the last 10 videos, when I ask it to download the next last 10 videos ( respecting the history of my last download) the scraper returns nothing. 
Is it possible to use the scrapper like this? Am I doing something wrong?

**Comment by drawrowfly** [comment]
This is expected the behavior with -s

If hashtag feed didn't updated yet and you have used -s option before then scraper won't download videos that were already downloaded before 

Also hashtag method it self is unstable yet https://github.com/drawrowfly/tiktok-scraper/issues/160#issuecomment-639741662
