### ISSUE TITLE
What is window.byted_acrawler.sign?

### ISSUE THREAD

**Issue by DeadlyMissile** [drawrowfly/tiktok-scraper#221]
I am trying to use this to scrape data from a video link, like username, like count etc. However this seems to require a signature now. Since I am using this with the Dart language I can’t for the love god find out what is window.byted_acrawler.sign so I can generate a signature. What is it?

**Comment by drawrowfly** [comment]
This method is being created in global scope from this function https://github.com/drawrowfly/tiktok-scraper/blob/master/src/helpers/Signature.ts

Function to create the signature method was taken from the tiktok page. You can run this function only in JS or if you have lots of free time you can decode and rewrite the signature method

**Comment by DeadlyMissile** [comment]
@drawrowfly So you are saying all I have to do is convert this Function((function(t) {.....}) ?

**Comment by drawrowfly** [comment]
yes

**Comment by DeadlyMissile** [comment]
The (t) being the url correct @drawrowfly ? And thank you very much for taking your time to help me!
