### ISSUE TITLE
Inconsistently returning data

### ISSUE THREAD

**Issue by aymather** [drawrowfly/tiktok-scraper#223]
The `.hashtag()` method is returning data inconsistently. This is the code I'm using for the following example.

```
const tiktok = require('tiktok-scraper');

(async () => {
    try {
        const posts = await tiktok.hashtag('justinbieber');
        console.log(posts);
    } catch (error) {
        console.log(error);
    }
})();
```

Which sometimes will give me a full response with lots of posts inside the collector, but most of the time, the collector will be empty.

I have yet to have this problem with the `.user()` method, just the `.hashtag()` method seems to be inconsistent. 

Configuration:
```
NodeJS: v12.16.3
tiktok-scraper: ^1.2.5
```

**Comment by drawrowfly** [comment]
https://github.com/drawrowfly/tiktok-scraper/issues/160#issuecomment-639741662

will be fixed later
