### ISSUE TITLE
getVideoMeta#VIDEO_URL_WITHOUT_THE_WATERMARK can not open it

### ISSUE THREAD

**Issue by liuyonggen** [drawrowfly/tiktok-scraper#224]
service : getVideoMeta.
all url videoUrlNoWaterMark is Invalid，we can not open it。

 "videoUrlNoWaterMark": "https://api2-16-h2.musical.ly/aweme/v1/play/?video_id=v07025570000brjm6n0src5ub2nt47eg&vr_type=0&is_play_url=1&source=PackSourceEnum_PUBLISH&media_type=4",

---------------------
example:
{
  "id": "6838543836608859393",
  "text": "lagi bikin challenge yang lagi hits #voguechallenge 🆘❌ #fyp #foryourpage",
  "createTime": "1592222566",
  "authorMeta": {
    "id": "74325286681",
    "name": "breindaa"
  },
  "musicMeta": {
    "musicId": "6823954622663674630",
    "musicName": "Gimme clout pls",
    "musicAuthor": "i.i.i.i.i.il"
  },
  "imageUrl": "https://p16-tiktok-sg.ibyteimg.com/obj/v0201/2a77d00d32ca4492b7c76e7a99f4373e_1592222568?x-expires=1593054000&x-signature=e%2BRL2SMpxmo2mBoLCL51coPmL24%3D",
  "videoUrl": "https://v16m.tiktokcdn.com/8ad0be426e39a61241de144fbc574fdf/5ef1ca63/video/tos/alisg/tos-alisg-pve-0037/8811ad7591c2441c8020b3d03d0a647a/?a=1180&br=1314&bt=657&cr=0&cs=0&dr=3&ds=3&er=&l=202006230324370101890560343BB55A2A&lr=tiktok&mime_type=video_mp4&qs=0&rc=ajp3NXhmdnFwdTMzOjgzM0ApOmc0aWZoODxpN2Q2M2c0O2diMWtfMm8tM2dfLS0yLzRzczZiXy8uMy0wYC1jNTYtMl46Yw%3D%3D&vl=&vr=",
  "videoUrlNoWaterMark": "https://api2-16-h2.musical.ly/aweme/v1/play/?video_id=v07025570000brjm6n0src5ub2nt47eg&vr_type=0&is_play_url=1&source=PackSourceEnum_PUBLISH&media_type=4",
  "videoMeta": {
    "width": 540,
    "height": 960,
    "ratio": 13,
    "duration": 13
  },
  "covers": {
    "default": "https://p16-tiktok-sg.ibyteimg.com/obj/tos-alisg-p-0037/c9d6107bf5f74438a8ec9de0020f0b78?x-expires=1593054000&x-signature=cKYzqMLAvG9A%2Fw7DRI%2BuGWpgCuI%3D",
    "origin": "https://p16-tiktok-sg.ibyteimg.com/obj/v0201/2a77d00d32ca4492b7c76e7a99f4373e_1592222568?x-expires=1593054000&x-signature=e%2BRL2SMpxmo2mBoLCL51coPmL24%3D"
  },
  "diggCount": 2226,
  "shareCount": 61,
  "playCount": 37400,
  "commentCount": 91,
  "downloaded": false,
  "mentions": [],
  "hashtags": [
    {
      "id": "18061279",
      "name": "voguechallenge"
    },
    {
      "id": "229207",
      "name": "fyp"
    },
    {
      "id": "1598498371111942",
      "name": "foryourpage"
    }
  ]
}

**Comment by drawrowfly** [comment]
Please use search

**Comment by drawrowfly** [comment]
was already discussed more then ~3 times

**Comment by liuyonggen** [comment]
thank you
