### ISSUE TITLE
Example of working 720x1280 

### ISSUE THREAD

**Issue by remlap** [drawrowfly/tiktok-scraper#225]
Using the new api url and replacing the ratio to default I have been able to grab 720x1280 TikToks again

Here is an example:

`https://api.tiktokv.com/aweme/v1/playwm/?video_id=v09044b20000brls6d9e3ejmgvhtbf3g&line=0&ratio=default&media_type=4&vr_type=0`

Hope this can help this project.

**Comment by tienbm** [comment]
> Using the new api url and replacing the ratio to default I have been able to grab 720x1280 TikToks again
> 
> Here is an example:
> 
> `https://api.tiktokv.com/aweme/v1/playwm/?video_id=v09044b20000brls6d9e3ejmgvhtbf3g&line=0&ratio=default&media_type=4&vr_type=0`
> 
> Hope this can help this project.

it worked but i must request 2 times. so why?

**Comment by Bonbichonkers** [comment]
I got this error using it can you provide some details how to fix it?
`{"status_code": 1, "message": "Url does not match", "log_pb": {"impr_id": "202006241001370101151761480109A558"}, "extra": {"logid": "202006241001370101151761480109A558", "now": 1592992897330, "fatal_item_ids": []}}`

**Comment by qsniyg** [comment]
> I got this error using it can you provide some details how to fix it?
> `{"status_code": 1, "message": "Url does not match", "log_pb": {"impr_id": "202006241001370101151761480109A558"}, "extra": {"logid": "202006241001370101151761480109A558", "now": 1592992897330, "fatal_item_ids": []}}`

Try this instead:

https://api2-16-h2.musical.ly/aweme/v1/play/?video_id=v09044b20000brls6d9e3ejmgvhtbf3g&ratio=default&improve_bitrate=1

**Comment by Bonbichonkers** [comment]
I've found out what was the problem. You have to set user-agent header empty/randomtext.

**Comment by vnnegt** [comment]
has anyone implemented this in a fork yet?

**Comment by wowieem** [comment]
I can't make it work. using command 
tiktok-scraper video https://www.tiktok.com/@pamelakawass/video/6817076054650309894 -w -d
this download an mp4 with 0 byte size.
