### ISSUE TITLE
tiktok-scraper --version returns wrong value

### ISSUE THREAD

**Issue by dlyakin** [drawrowfly/tiktok-scraper#226]
**Describe the bug**
Execute in comand line `tiktok-scraper --version`  get 1.0.17
But in dependencies I have "tiktok-scraper": "^1.2.5"
![image](https://user-images.githubusercontent.com/6614211/85542099-68675580-b621-11ea-8053-5776331f9a93.png)

**Comment by drawrowfly** [comment]
This is not scraper related

**Comment by drawrowfly** [comment]
**tiktok-scraper --version** - this is global

And package.json contains local dependency 

Please use stack-overflow for such problems
