### ISSUE TITLE
Sometimes I get an incomprehensible error "Cannot read property 'statusCode' of undefined"

### ISSUE THREAD

**Issue by dlyakin** [drawrowfly/tiktok-scraper#227]
**Describe the bug**
Try to execute` const newAccauntData = await TikTokScraper.getUserProfileInfo('sibiryachka')`
Get error console.log(error)  `Cannot read property 'statusCode' of undefined`

**To Reproduce**
- Windows 10
- NodeJs v12.16.2
- Scraper Version 1.2.5
- Module
- getUserProfileInfo
- Run in localhost
- Profile is public
- https://www.tiktok.com/@sibiryachka/

**Comment by drawrowfly** [comment]
Use proxy. Works fine from mine side. Also i will work on better error logging later
