### ISSUE TITLE
Short url not working

### ISSUE THREAD

**Issue by tnduc** [drawrowfly/tiktok-scraper#228]
**Describe the bug**
Download single video without the watermark
```
tiktok-scraper video https://vt.tiktok.com/DTFEmo/
Can't extract metadata from the video: https://vt.tiktok.com/DTFEmo/
```

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- Used Windows 10 - 2004
- NodeJs Version (node -v): v12.18.0
- Scraper Version (tiktok-scraper --version): 1.2.5
- CLI or ModuleL all
- Used method: video
- Used options
- Do you run the scraper through Proxy, VPN, VPS? No
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles!
- Preferably provide URL to the profile,hashtag,video and etc page: https://vt.tiktok.com/DTFEmo/

**Screenshots**

**Comment by drawrowfly** [comment]
Working well in the new version of the scraper

**Comment by frozenpandaman** [comment]
@drawrowfly This issue seems to be present again in 1.3.3, notably for videos where the sound has been removed. TikTok sometimes returns the error that the video is "restricted by country." The video in @tnduc's OP is no longer able to be downloaded.
