### ISSUE TITLE
Getting TypeError when scraping more than 50

### ISSUE THREAD

**Issue by VincentVinTin** [drawrowfly/tiktok-scraper#23]
Code app.js:
const TikTokScraper = require('tiktok-scraper');
 
let posts = TikTokScraper.hashtag("singing", { event: true, number: 200});
 
posts.on('data', (json) => {
  console.log(json)
})
 
posts.on('done', () => {
  console.log("done")
})

posts.on('error', (error) => {
  console.log(error)
})

posts.scrape();

Version:
"dependencies": {
    "tiktok-scraper": "^1.0.9"
  }

Error:
TypeError: Cannot read property 'itemListData' of undefined
    at TikTokScraper.mainLoop (*/node_modules/tiktok-scraper/lib/index.js:394:53)
    at async TikTokScraper.scrape (*/node_modules/tiktok-scraper/lib/index.js:297:9)

**Comment by drawrowfly** [comment]
I believe this is new web api limitations. From mine side even in browser i can't scroll down the hashtag page.

**Comment by drawrowfly** [comment]
For now i have pushed new update where we catch this error. Later i will push another update with other way of scraping hashtags

**Comment by VincentVinTin** [comment]
Thank you for the fast reply!
I visited the TikTok website and had the same problem, I hope it is a bug and it will be fixed soon by TikTok. By the way love your TikTok scraper, keep up the good work!

**Comment by VincentVinTin** [comment]
> For now i have pushed new update where we catch this error. Later i will push another update with other way of scraping hashtags

Thanks, I will have a look.

**Comment by youngvo** [comment]
Hi @drawrowfly,

I did close this issue without more information. You did resolve the problem, correct? If yes, please help to add some instructions to explain what is the cause and how to fix the problem. 

Thanks so much,
-Young

**Comment by drawrowfly** [comment]
@youngvo this is now the main issue #24
