### ISSUE TITLE
getUserProfileInfo into command list

### ISSUE THREAD

**Issue by vbaseghyanupwork** [drawrowfly/tiktok-scraper#230]
Hi there,

First of all thanks for the work, that you've done.

It's not exactly a feature request, but something, that probably will be useful for most of people that are using this package.

Can you add getUserProfileInfo  into available command list. I have seen that you have a module, where by calling getUserProfileInfo you're getting general info about the user.

So it will be nice to have command like, which we can run in terminal

`tiktok-scraper userprofile USERNAME -options`

Thanks again

**Comment by drawrowfly** [comment]
Available in new version of the scraper
