### ISSUE TITLE
API  TikTokScraper.hashtag(tagName, options) unstable operation;

### ISSUE THREAD

**Issue by vuducthuan1994** [drawrowfly/tiktok-scraper#231]
Hello
Thank for share this library .^^ 
Can you check again this method : TikTokScraper.hashtag(tagName, options) and this method : .signUrl('URL', options)  .

This method return a signature, but this signature seems unstable operation . If you call about 50-100 times  continuity . It will return undefined . 

You can test it on this url API : https://www.tiktok.com/share/item/list?secUid=&id=1624987877066754&type=3&count=30&minCursor=0&maxCursor=30&shareUid=&recType=&lang=en

**Comment by drawrowfly** [comment]
Hi,

https://github.com/drawrowfly/tiktok-scraper/issues/160#issuecomment-639741662

I have mentioned probably dozen of times that hashtag feed can be unstable.

Later it will push different way of generation signature that will work better with hashtag feed endpoint
