### ISSUE TITLE
Cannot read property 'statusCode' of undefined

### ISSUE THREAD

**Issue by dlyakin** [drawrowfly/tiktok-scraper#233]
**Describe the bug**
Very often I get error "Cannot read property 'statusCode' of undefined". I use one API method - getUserProfileInfo. I use array of 4 working proxy

It's hard to understand what's wrong.

`const newAccauntData = await TikTokScraper.getUserProfileInfo(accaunt.uniqueId, { proxy: config.get('proxy') })`

**To Reproduce**
-Centos 8
- NodeJs Version v14
- Scraper Version 1.2.6
- Module mode
- getUserProfileInfo
- proxy array
- Local and VPS
- Profile is public
- Any profile. For example - https://www.tiktok.com/@therock

**Comment by lu3do** [comment]
I'm also getting this error when retrieving any getUserProfileInfo() since last night.

**Comment by drawrowfly** [comment]
I will push update that will show different error. But the error it self is related to the proxy. Use different proxies

**Comment by ColtraneNadler** [comment]
what proxies work best?

**Comment by lu3do** [comment]
I'm also (still) having this issue, maybe the way the scraper blows up when this happens could be handled in a better way?
