### ISSUE TITLE
Add a bandwidth limiter for downloading

### ISSUE THREAD

**Issue by ledimestari** [drawrowfly/tiktok-scraper#235]
Problem:
A bandwidth limiter of some sort would be nice to have, the other day I accidentally froze up my coworkers video call when I was fiddling around with tiktok-scraper at ~12MB/s and used up most of the bandwidth in house. 

Suggested solution:
Add an option to limit the bandwidth available for tiktok-scraper, something like
--speedlimit <0-1000>, Limit the available bandwidth in MBs. 0 is unlimited and default.

Don't know how this can be applied but would be useful.

**Comment by drawrowfly** [comment]
For the first time someone is telling me that tool eating all the bandwidth :)

Don't have any plans on adding this update as almost no one requires to limit the bandwidth 

You can set --timeout  

As always pull requests are welcomed
