### ISSUE TITLE
Error in pattern matching for batch downloads

### ISSUE THREAD

**Issue by scuttlegun** [drawrowfly/tiktok-scraper#236]
Hey, just a small bug, the regex test found here
`tiktok-scraper\build\entry.js (line 290)`
`if (/^https:\/\/(www|v[a-z]{1})+\.tiktok\.com\/(\w.+|@(.\w.+)\/video\/(\d+))$/.test(item)) {`
doesn't match some valid usernames, making it fail then fall through and treat the entire video url as a username

For example
>@g.tyler
>@j.kaska
>@p.nicee

Changing `@(.\w.+)` to `@([.\w]+)` fixes this

**Comment by drawrowfly** [comment]
Thanks! Update will be pushed soon
