### ISSUE TITLE
Randomly skips downloading some or all videos

### ISSUE THREAD

**Issue by mormonxyz** [drawrowfly/tiktok-scraper#237]
tiktok-scraper keeps randomly skipping some videos resulting in empty (0B) mp4 files. I've noticed that it happens when I keep downloading profiles  without a break in between. For example, if I downloaded 3 profiles (100 videos each), it will start skipping videos in the next profile I try to download. (I'm not sure, though. This is my current conclusion.)

- Used OS: Void Linux & Arch Linux
- NodeJs Version: v13.2.0
- Scraper Version: 1.2.6
- Command used: **tiktok-scraper user** *NAME* **-d -hd -w -a 3** 
- No proxy, VPN, or VPS is used
- All the profiles I tried are public

I've been using this amazing tool for more than month and it works perfectly. However, I started having this issue only recently after a fresh Linux install. So, I might be missing something...

![Screenshot 1](https://i.imgur.com/HSMFuSE.png)

![Screenshot 2](https://i.imgur.com/EvBOmt1.png)

![Screenshot 3](https://i.imgur.com/KtTvzxB.png)

Edit: do you think that it has something to do with my internet connection? I've downloaded on a much slower one. I've also tested my internet and it doesn't seem to be lagging.

**Comment by drawrowfly** [comment]
Use proxy when you download lots of videos from same ip
