### ISSUE TITLE
Scrapping commments

### ISSUE THREAD

**Issue by colymore** [drawrowfly/tiktok-scraper#238]
Hi, i would like to include scrapping comments, I know it's same as https://github.com/drawrowfly/tiktok-scraper/issues/130 but i'm trying to figure out how does the api work and it's not easy as include the cookie, the comments url api is something like `https://www.tiktok.com/api/comment/list/?aweme_id=6840894575092043014&cursor=0&count=20&aid=1988&app_language=en&device_platform=web_pc&current_region=ES&fromWeb=1&channel_id=0&verifyFp=verify_kaqxzh63_jJTHiRrL_rWNi_4CHq_9YTW_gSQ8t7ZKUV52&_signature=_02B4Z6wo00f01Yx2qNQAAIBCVWR5iksNLAGMd6xAAD3kbb`

Do you know where the params signature and verifyFp are obtained from?

**Comment by tandt2402** [comment]
verifyFp can get from cookie,
signature from call sign function

**Comment by drawrowfly** [comment]
to make your task easier verifyFp is not being validated in any request, you can execute request without it
