### ISSUE TITLE
Zero bytes

### ISSUE THREAD

**Issue by pratikwatwani** [drawrowfly/tiktok-scraper#239]
Describe the bug
Downloads of video results in a zero byte sized file 

If fields below will be empty then issue will be Ignored and Closed
To Reproduce

Used OS
Windows 10
NodeJs Version (node -v)
14.0.0
Scraper Version (tiktok-scraper --version)
1.3.0
CLI or Module
CLI
Used method
video
user
Used options
-d -w --hd
Do you run the scraper through Proxy, VPN, VPS?
No
If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles!
Yes, it's public
Preferably provide URL to the profile,hashtag,video and etc page
It happens with any video or profile

**Comment by drawrowfly** [comment]
https://github.com/drawrowfly/tiktok-scraper/issues/237#issue-649628712

**Comment by ankit0183** [comment]
it's not working bro whenever i run , "tiktok-scraper user USERNAME "it only creates the user name folder it's not downloading the user video..! what's wrong

**Comment by vnnegt** [comment]
> it's not working bro whenever i run , "tiktok-scraper user USERNAME "it only creates the user name folder it's not downloading the user video..! what's wrong

your IP was temp blocked because of the amount of videos you've scraped. use a proxy

**Comment by ankit0183** [comment]
Yeah exactly bro, my IP was blocked, I changed my IP by using Proxy now it's working perfectly.! Thank you for your support :)

**Comment by Zachary24** [comment]
> > it's not working bro whenever i run , "tiktok-scraper user USERNAME "it only creates the user name folder it's not downloading the user video..! what's wrong
> 
> your IP was temp blocked because of the amount of videos you've scraped. use a proxy

any other reasoning? i used this script once before (downloaded 25 videos max) back in june-july, and it isn't downloading anything (updated node and tiktok-scraper, as well as have tried on both mac and windows)

i've tried both a vpn and proxies, to no avail.
