### ISSUE TITLE
Scraping is Returning Empty Collector

### ISSUE THREAD

**Issue by tnoetzel** [drawrowfly/tiktok-scraper#24]
Scraping started returning an empty collector. I'm guessing the signature is out of data again.

(Btw, how are you reverse engineering the signature? Happy to help maintain if you point me in the right direction.)

**Comment by TrueCarry** [comment]
I can't speak for repo author, but I've found sign code in webpack module with name duD4.
![image](https://user-images.githubusercontent.com/5431520/75959878-25497100-5ed0-11ea-9d07-a6d4d3517e10.png)
It's not regular js, but some kind of obfuscated/light vm code. So there's no real point in reversing it. We just execute it and grab signature.
It doesn't look like tiktok changed signature method today, but instead added some verification steps. This is response I'm getting:
```
 {
  statusCode: 10110,
  verifyConfig: {
    code: 10000,
    type: 'verify',
    version: '1',
    subtype: 'slide',
    fp: 'verify_6eb670abb446358b11908113359f694e',
    region: 'va',
    detail: 'feuj0d8h10WajdICXEyg4r00'
  }
}
```
Tiktok has captcha that MAYBE needs to be solved to proceed, but i'm not sure. Captcha example: 
![image](https://user-images.githubusercontent.com/5431520/75960106-88d39e80-5ed0-11ea-932f-7d9e52f13d81.png)

**Comment by drawrowfly** [comment]
Yeah it is always same function duD4

I've noticed "statusCode: 10110" few days ago when you scroll down to load more items , but i never saw actual captcha.

Regarding signature last time i've randomized TAC a little and it started working fine. This time not sure what changed again

**Comment by drawrowfly** [comment]
I've updated Tac and it works well for now. Later will find a better way to randomize Tac.

Currently no solution regarding captcha

**Comment by youngvo** [comment]
Hi @drawrowfly Look like the issue happens again. Could you please help to check?
The result is now:
```
{ mediaList: [], mediaSize: 0 }
```

**Comment by TrueCarry** [comment]
> Hi @drawrowfly Look like the issue happens again. Could you please help to check?
> The result is now:
> 
> ```
> { statusCode: 200, contentType: 'application/json', content: '' }
> ```

If you getting this response, you just need to change tac and user-agent.

**Comment by youngvo** [comment]
Thanks @TrueCarry. Could you advise the right way to generate a new tac?

**Comment by drawrowfly** [comment]
There is no need to change user agent. But we can randomize it. Anyway i will try to add today correct Tac randomization

**Comment by youngvo** [comment]
> There is no need to change user agent. But we can randomize it. Anyway i will try to add today correct Tac randomization

Very cool. Thanks @drawrowfly. I will be your tester ;)

Best,
-Young

**Comment by drawrowfly** [comment]
Done,

Tac value is extracted from the tiktok page and being used in generating token. I believe this way it is more stable then it was before

**Comment by trantat** [comment]
> Yeah it is always same function duD4
> 
> I've noticed "statusCode: 10110" few days ago when you scroll down to load more items , but i never saw actual captcha.
> 
> Regarding signature last time i've randomized TAC a little and it started working fine. This time not sure what changed again

The "statusCode: 10110" happen when you scrape user's posts with maxCursor != 0
For example:
`const posts = await TikTokScraper.user("infernumasylum", { number: 100 });`
With count = 48, the scraper will send request more than one time.

**Comment by drawrowfly** [comment]
With count 48 , scraper will do exactly 2 request to collect data from the user video feed
First request will collect 27 videos
Second will respond with "statusCode: 10110" 

Thats how it is right now from the browser side.  Maybe later i will upload a bit different approach to download more then 27 videos from the user feed

**Comment by trantat** [comment]
`if (result.statusCode !== 0) {break;}`
This condition in index.js file makes the scraper stop with "statusCode: 10110".
Besides, the second request for scrape user's post always responds without body key.
`{
  statusCode: 10110,
  verifyConfig: {
    code: 10000,
    type: 'verify',
    version: '1',
    subtype: 'slide',
    fp: 'verify_d85403d7de79d2dbe750d10eab37be3a',
    region: 'va',
    detail: 'GtpqNUNIehK2gwsZgFkd1cla'
  }
}`

**Comment by drawrowfly** [comment]
Thats right. Because after that response you won't get anything

**Comment by exolyt** [comment]
> With count 48 , scraper will do exactly 2 request to collect data from the user video feed
> First request will collect 27 videos
> Second will respond with "statusCode: 10110"
> 
> Thats how it is right now from the browser side. If nothing will change in browser version of the app, then maybe later i will upload a bit different approach to download more then 27 videos from the user feed

@drawrowfly what is that another way? I can do a PR if you know the way to get over 20 videos.

**Comment by drawrowfly** [comment]
Well , mobile api

Currently, I have stucked with the signature generation. There is a header **x-gorgon** that is sent with the mobile api request and it is being generated by using this method in Java

`String a2 = C19822a.m61741a(C49426a.leviathan(i, currentTimeMillis, C19822a.m61742a(sb.toString())));`

**leviathan** - is a public static native method that is located somewhere in C library. So we need to find this method and how it creates the signature, but i don't have much time this days

**Comment by youngvo** [comment]
Hi @drawrowfly 

In addition to the header x-gorgon, do you know that way to search recent data using hashtag? Look like the list is not ordered by timestamp or something like that.

**Comment by exolyt** [comment]
@drawrowfly so this one is fixed now or did we just give up?

**Comment by drawrowfly** [comment]
Current limits
User 30 posts
Trends unlimited
Hashtag unlimited

**Comment by paulwongx** [comment]
@drawrowfly I'm getting `{ collector: [], zip: '' }` trying to download trend videos today. Is there a new limit, did tiktok change something, or am I missing something?

**Comment by ii64** [comment]
@drawrowfly The function that generate x-gorgon is inside native library called `libcms.so` and it is 'obfuscated'.

**Comment by drawrowfly** [comment]
i do aware about this and i do know how it is implemented
