### ISSUE TITLE
Not downloding user vedio, its only ceate user name folder

### ISSUE THREAD

**Issue by ankit0183** [drawrowfly/tiktok-scraper#240]
it's not working bro whenever i run , "tiktok-scraper user USERNAME "it only creates the user name folder it's not downloading the user video..! what's wrong

**Comment by drawrowfly** [comment]
Works fine for me bro

tiktok-scraper user tiktok -n 10 -d

**Comment by ankit0183** [comment]
can you please help me where I'm making mistake? :( 
im using this cmd 
"tiktok-scraper user USERNAME"  should I mention output path cuz video not downloading \
"cli.js user USERNAME"   I also try by using CLI but both end up with an error
not working both in Kali & Windows both 
and when I try to download use single video it's showing this error 

tiktok-scraper video {Vedio urs}
Can't extract metadata from the video: https://vt.tiktok.com/DTFEmo/

**Comment by ankit0183** [comment]
can you please help me where I'm making mistake? :(
im using this cmd
"tiktok-scraper user USERNAME" should I mention output path cuz video not downloading
"cli.js user USERNAME" I also try by using CLI but both end up with an error
not working both in Kali & Windows both
and when I try to download use single video it's showing this error

tiktok-scraper video {Vedio urs}
Can't extract metadata from the video: https://vt.tiktok.com/123243546477473/

**Comment by drawrowfly** [comment]
https://vt.tiktok.com/123243546477473/ it does not exist when visiting from the browser

**Comment by drawrowfly** [comment]
Also always please use search before creating issues

https://github.com/drawrowfly/tiktok-scraper/issues/239#issuecomment-653384221

**Comment by ankit0183** [comment]
apps sorry, yeah but user all file not downloading bro it only creates user folders 

tiktok-scraper video https://vt.tiktok.com/DTFEmo/
![Screenshot_4](https://user-images.githubusercontent.com/29034134/86452788-74969580-bd3a-11ea-9ff1-16b28aa1b224.jpg)

Can't extract metadata from the video: https://vt.tiktok.com/DTFEmo/
