### ISSUE TITLE
getVideoMeta video with no water mark, link not working

### ISSUE THREAD

**Issue by gabidabet** [drawrowfly/tiktok-scraper#242]
**Describe the bug**
The json result give me the link for the video with no water mark, when i copy the link and paste it in my browser, i get no result just blank page.

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- windows 10
- NodeJs last
- Scraper Version last
- CLI or Module
- Used method
- Used options
- Do you run the scraper through Proxy, VPN, VPS? nop

**Screenshots**
![Screenshot_5](https://user-images.githubusercontent.com/42586945/86518197-dc7ad800-be2f-11ea-8317-e4e926077dcc.png)

**Comment by drawrowfly** [comment]
Please use search before opening issues that was discussed few times already
