### ISSUE TITLE
How to use proxy?

### ISSUE THREAD

**Issue by pratikwatwani** [drawrowfly/tiktok-scraper#245]
I am not sure how to use a proxy file and more importantly where to get a list of proxies. I tried free online proxies from open websites and list each one in a file with and without extension, but the CLI method doesn't seem to work for me. 

I am not sure where I went wrong. Some suggestions would help.

**Comment by drawrowfly** [comment]
You can find example on how to use it here https://github.com/drawrowfly/tiktok-scraper/blob/master/examples/CLI/BatchDownload.md

**Comment by drawrowfly** [comment]
If proxies are public then there is 85% chance that the are down or blacklisted. Best proxies will be paid proxies
