### ISSUE TITLE
Option to replace the numerical filename with the user's caption?

### ISSUE THREAD

**Issue by c5001481cepheus** [drawrowfly/tiktok-scraper#247]
Is there an option to replace the numerical filename (ID) with the user's caption/description? Is there another way this can be done? Thank you!

**Comment by drawrowfly** [comment]
#197 #232

**Comment by Gorrrg** [comment]
It would also be helpful to have the nowatermark or raw video attributes in the file name. For easier sorting or for storing the three different video versions in the same directory.

**Comment by SnowDragon997** [comment]
any news on this?
