### ISSUE TITLE
Some problems found during use.

### ISSUE THREAD

**Issue by design365** [drawrowfly/tiktok-scraper#25]
Thank you for providing such a useful tool, but when I used it, I found that the videos are watermarked. There are two suggestions to see if it can be achieved:
1. Can you put the video link without watermark in it?
2. Can you provide a query to get the video information based on the video id (including the video download link without watermark)

**Comment by drawrowfly** [comment]
There is no way to provide the video link to the video without a watermark. Watermark is being added from tiktok side after uploading the video.

**Comment by pokurivijay** [comment]
we can download without watermark.

some websites are implemented.

**Comment by drawrowfly** [comment]
TikTok does not provide url without watermark. You can remove only after downloading

**Comment by design365** [comment]
> we can download without watermark.
> 
> some websites are implemented.

which site？

**Comment by mrlphoenix** [comment]
I think there is a way to request video without watermark.
https://musicallydown.com/ for example
