### ISSUE TITLE
Scraping text and tags, such as "Sponsored"

### ISSUE THREAD

**Issue by alex-rsk** [drawrowfly/tiktok-scraper#251]
Firsly, thank you a lot for your perfect tool and great job.
But I have one question, probably, not as "feature request", but more a "question about feature"
**Is your feature request related to a problem? Please describe.**
I can't find the way, how I can scrape the textual information, which comes along  with media: text, hashtags, marks like "Sponsored" etc.

**Describe the solution you'd like**
I'd like to have the feature, which could download abovementioned textual information.
Like
"tiktok-scraper --with-text-info"

**Comment by xiaolin-TL** [comment]
I can't find the output from running tiktok-scraper in terminal, but I'm able to get the text and hashtags using the module methods.

**Comment by drawrowfly** [comment]
`tiktok-scraper user tiktok -n 2 -t csv`

Command above will download metadata about 2 latest videos post and Video Description will be in the CSV file
