### ISSUE TITLE
Can't find tiktoks by hashtag

### ISSUE THREAD

**Issue by xiaolin-TL** [drawrowfly/tiktok-scraper#252]
**Describe the bug**
**Unable to find tiktoks by hashtag using the module method `hashtag.` An empty list is returned even though the terminal and a python API can find tiktoks with the hashtag.** 

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- Used OS
- NodeJs Version (node -v) **v12.18.1**
- Scraper Version (tiktok-scraper --version) **1.3.0**
- CLI or Module **Module**
- Used method **hashtag**
- Used options **`TikTokScraper.hashtag('funny', { number: 4 })`**
- Do you run the scraper through Proxy, VPN, VPS? **NA**
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles! **NA**
- Preferably provide URL to the profile,hashtag,video and etc page 
https://tiktokhashtags.com/hashtag/funny/

**Screenshots**

Thank you in advance!

**Comment by drawrowfly** [comment]
#231
