### ISSUE TITLE
Error with without warermark video

### ISSUE THREAD

**Issue by hatienl0i261299** [drawrowfly/tiktok-scraper#253]
**Describe the bug**

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- Used OS
- NodeJs Version (node -v)
- Scraper Version (tiktok-scraper --version)
- CLI or Module
- Used method
- Used options
- Do you run the scraper through Proxy, VPN, VPS?
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles!
- Preferably provide URL to the profile,hashtag,video and etc page

**Screenshots**
i used this func to create url without watermark, but it have error
![image](https://user-images.githubusercontent.com/36532499/87115209-cc824e80-c29c-11ea-8aaf-dd33e82cf69f.png)

in this video https://www.tiktok.com/@lolomatolo19/video/6835057376001805574, i found video id is v09044500000brdg0u7vccnonge0r6ig

and use api in your func, it will have url without watermark is https://api2-16-h2.musical.ly/aweme/v1/play/?video_id=v09044500000brdg0u7vccnonge0r6ig&vr_type=0&is_play_url=1&source=PackSourceEnum_PUBLISH&media_type=4

but i have error, pls fix it, ths you so much

**Comment by tnduc** [comment]
Video streaming from videoUrlNoWaterMark is not currently available, but you can download it.
see more: https://github.com/drawrowfly/tiktok-scraper/issues/209

**Comment by drawrowfly** [comment]
https://github.com/drawrowfly/tiktok-scraper/issues?q=is%3Aissue+is%3Aclosed+watermark
