### ISSUE TITLE
Sampling time

### ISSUE THREAD

**Issue by Rodrigo-ip** [drawrowfly/tiktok-scraper#255]
Hi, first congratz on the scraper! It seems to be working very well. 
I think the current trend command may be useful to track engagement in the platform. However, to do this, it would be nice to have a sampling time variable/column in order to compare to previous periods. How can we add this?

**Comment by drawrowfly** [comment]
Scraper is only providing data and you can build any apps around it and analyze it in any way you like

**Comment by Rodrigo-ip** [comment]
Sure. Just think it would be a nice add to the scraper

**Comment by drawrowfly** [comment]
I can add scraping timestamp to the output file/data

**Comment by Rodrigo-ip** [comment]
@drawrowfly thanks!
