### ISSUE TITLE
Hashtags download doesn't work

### ISSUE THREAD

**Issue by igormorozov** [drawrowfly/tiktok-scraper#256]
For some reason scraping of hashtags doesn't work.

It launched and said that scraped done, but results are equal = 0.

I used terminal with the command:

` tiktok-scraper hashtag ad -n 100 -t csv `

**Comment by drawrowfly** [comment]
Won't close this issue as to many people are opening same issues over and over again, without even using Github Issue Search that works better then Hashtag method in this tiktok scraper :)

https://github.com/drawrowfly/tiktok-scraper/issues/231#issuecomment-650780164

I will improve it soon

**Comment by geco** [comment]
> Won't close this issue as to many people are opening same issues over and over again, without even using Github Issue Search that works better then Hashtag method in this tiktok scraper :)
> 
> [#231 (comment)](https://github.com/drawrowfly/tiktok-scraper/issues/231#issuecomment-650780164)
> 
> I will improve it soon

Please! Now it returns always zero results for any hashtag, i can't have anymore the 1/3 medium success rate 😢

**Comment by zipzipip** [comment]
Has this issue been resolved yet

**Comment by drawrowfly** [comment]
Not yet, i was busy

**Comment by MichaelElkan** [comment]
I am having a similar issue when trying to get a large number of clips using hashtag. The workaround I've used is to just keep running the command until it works. It takes hundreds of attempts but eventually works. Is there a better workaround I can use? 

I'd love to help fix this issue as well but I gotta get more familiar with the code. Let me know if you think there is a good place to start :)

**Comment by zipzipip** [comment]
> Not yet, i was busy 
Gotcha @igormorozov  👍

**Comment by socialmediaguy** [comment]
Just wondering, is this fixed now?

**Comment by drawrowfly** [comment]
downloading hashtag feed is working as expected in the latest version

**Comment by slatie** [comment]
On the latest version in github - master it does not work, but other functions do.
In the latest version on npm it does work indeed but other functions don't.
