### ISSUE TITLE
Can't extract metadata from the video

### ISSUE THREAD

**Issue by asportnoy** [drawrowfly/tiktok-scraper#257]
**Describe the bug**
the `getVideoMeta` option is always returning "Can't extract metadata from the video"
## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- Used OS Ubuntu 18.04
- NodeJs Version (node -v) 12.18.0
- Scraper Version (tiktok-scraper --version) 1.3.0
- CLI or Module Module
- Used method `getVideoMeta`
- Used options none, just the video URL
- Do you run the scraper through Proxy, VPN, VPS? no
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles! N/A
- Preferably provide URL to the profile,hashtag,video and etc page https://vm.tiktok.com/JL8UsQ2/ but it occurs with all videos

**Screenshots**
N/A

**Comment by drawrowfly** [comment]
Use proxy works fine from mine side!
