### ISSUE TITLE
fs.promises API is experimental

### ISSUE THREAD

**Issue by chandrasg** [drawrowfly/tiktok-scraper#26]
I see the following message when I try to run the scraper and it exits without downloading any data.
```⠋ TikTok Scraper Started(node:19861) ExperimentalWarning: The fs.promises API is experimental```

Have you bumped into this?

**Comment by drawrowfly** [comment]
No. What version is it ?

**Comment by chandrasg** [comment]
Updated to 1.0.12.
now see
``` ⠋ TikTok Scraper Started(node:66992) ExperimentalWarning: The fs.promises API is experimental
⠼ TikTok Scraper StartedError: Error: Can't extract Tac value
    at TikTokScraper.extractTac (/usr/local/lib/node_modules/tiktok-scraper/lib/index.js:311:19)```

**Comment by drawrowfly** [comment]
Just checked, works well from mine side.
