### ISSUE TITLE
Help get final link download

### ISSUE THREAD

**Issue by tonyquang** [drawrowfly/tiktok-scraper#262]
Hello Drawrowfly, Could you tell me Get final link download video from this link below: 
https://api2-16-h2.musical.ly/aweme/v1/play/?video_id=v07025250000bsaodo9fngv5kr9ts4a0&vr_type=0&is_play_url=1&source=PackSourceEnum_PUBLISH&media_type=4
I have requested it but I responded blank page, In old version Tiktok final link download in Location Key of Header Response, but now Location was disappeared.
Thank you Drawrowfly!

**Comment by drawrowfly** [comment]
Please use search it is such great and amazing feature in github

This URL is valid and you can download the video with simple http request library in any language of your choice, just do not set the User-Agent , leave it blank
Thank You

**Comment by tonyquang** [comment]
@drawrowfly  Thank you so much ^^
