### ISSUE TITLE
Download without watermark does not work anymore

### ISSUE THREAD

**Issue by AidasK** [drawrowfly/tiktok-scraper#263]
**Describe the bug**
Everything works as expected, but links to video without watermark does not work anymore. All of them return response of 0 bytes and 200 status.

Though regular video link still works

**To Reproduce**
- osx and centos 7
- 14.1.0
- Scraper Version 1.3.0 from npm
- Module
- no watermark
- https://www.tiktok.com/@addisonre/video/6796362596044901638
- No proxy, same on two different servers
- Public videos
- https://www.tiktok.com/@addisonre/video/6796362596044901638

Reproduce:
```js
import TikTokScraper from 'tiktok-scraper'

(async () => {
    const videoMeta = await TikTokScraper.getVideoMeta(process.argv[2], {});
    process.stdout.write(JSON.stringify(videoMeta));
})();
```
{"id":"6796362596044901638","text":"","createTime":"1582401479","authorMeta":{"id":"6703550784929793030","name":"addisonre"},"musicMeta":{"musicId":"6795505198061112070","musicName":"Sunday Best x Dont Start Now","musicAuthor":"goalsounds"},"imageUrl":"https://p16-tiktok-va.ibyteimg.com/obj/tos-maliva-p-0068/8937227b3d2a462cad62b5a23001bf17_1582401482?x-expires=1595512800&x-signature=GNjmetKe7dnOMLMZ91P8pOgmAF8%3D","videoUrl":"https://v16m.tiktokcdn.com/059dfc237d254c76b38a4393c6871e6f/5f174f19/video/tos/useast2a/tos-useast2a-ve-0068c002/ee80ddb993a049b88a8f5ade7478a248/?a=1233&br=4882&bt=2441&cr=0&cs=0&dr=0&ds=3&er=&l=20200721142442010190192131331AF47A&lr=tiktok_m&mime_type=video_mp4&qs=0&rc=M2k4a293NWhyczMzOjczM0ApZTtnZjRmOztoNzU1NWU7Omc2bHFfa2VkYzVfLS0tMTZzc2MwXzVgLS1iMzYzYTJhLzQ6Yw%3D%3D&vl=&vr=","videoUrlNoWaterMark":"https://api2-16-h2.musical.ly/aweme/v1/play/?video_id=v09044070000bp8ofeg2htnlbht5of90&vr_type=0&is_play_url=1&source=PackSourceEnum_PUBLISH&media_type=4","videoMeta":{"width":720,"height":1280,"ratio":15,"duration":15},"covers":{"default":"https://p16-tiktok-va.ibyteimg.com/obj/tos-maliva-p-0068/1f41d19cf816879d011b98b0c4cd7f5e?x-expires=1595512800&x-signature=sYtgsHQv4oPNvbz%2F92oJBhtTsuc%3D","origin":"https://p16-tiktok-va.ibyteimg.com/obj/tos-maliva-p-0068/8937227b3d2a462cad62b5a23001bf17_1582401482?x-expires=1595512800&x-signature=GNjmetKe7dnOMLMZ91P8pOgmAF8%3D"},"diggCount":4800000,"shareCount":68200,"playCount":34600000,"commentCount":24900,"downloaded":false,"mentions":[],"hashtags":[]}

**Comment by drawrowfly** [comment]
Please use search before creating issue that was discussed few times already!!!
