### ISSUE TITLE
Is there a way to get the username from the ID?

### ISSUE THREAD

**Issue by vnnegt** [drawrowfly/tiktok-scraper#264]
**Is your feature request related to a problem? Please describe.**
Sometimes people change their username and it's difficult to find the new username. 

**Describe the solution you'd like**
Because the ID never changes, I was wondering if there was a way to retrieve the username, given the ID?

**Comment by llacb47** [comment]
Yes. tiktok.com/share/user/ and put the id after, it will redirect to the username page.

**Comment by vnnegt** [comment]
@llacb47 thanks!

**Comment by drawrowfly** [comment]
Save sec_uid and use it instead of the username in **getUserProfileInfo** method
