### ISSUE TITLE
Can't extract metadata from the video

### ISSUE THREAD

**Issue by jackshi007** [drawrowfly/tiktok-scraper#265]
Describe the bug
  tiktok-scraper video https://www.tiktok.com/@tiktok/video/6807491984882765062
  tiktok-scraper video https://vt.tiktok/ydJeAa/
  is always returning "Can't extract metadata from the video"

If fields below will be empty then issue will be Ignored and Closed
To Reproduce

Used OS Windows 7
NodeJs Version (node -v) 12.18.3
Scraper Version (tiktok-scraper --version) 1.3.0
CLI or Module Module and CLI
Used method getVideoMeta
Used options none, just the video URL
Do you run the scraper through Proxy, VPN, VPS? yes (us and jp IP)
If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles! N/A
Preferably provide URL to the profile,hashtag,video and etc page https://vt.tiktok/ydJeAa/ but it occurs with all videos
Screenshots
N/A

**Comment by drawrowfly** [comment]
tiktok-scraper video https://www.tiktok.com/@tiktok/video/6807491984882765062 - works fine from mine side, use proxy
tiktok-scraper video https://vt.tiktok/ydJeAa/ <- bad url

**Comment by jackshi007** [comment]
tiktok-scraper video https://vt.tiktok.com/ydN48X -p 127.0.0.1:1080
Can't extract metadata from the video: https://vt.tiktok.com/ydN48X

**Comment by jackshi007** [comment]
> tiktok-scraper video https://www.tiktok.com/@tiktok/video/6807491984882765062 - works fine from mine side, use proxy
> tiktok-scraper video https://vt.tiktok/ydJeAa/ <- bad url

can you try this url https://vt.tiktok.com/ydN48X ,Thanks
tiktok-scraper video https://vt.tiktok.com/ydN48X -p 127.0.0.1:1080
Can't extract metadata from the video: https://vt.tiktok.com/ydN48X

**Comment by jackshi007** [comment]
> tiktok-scraper video https://www.tiktok.com/@tiktok/video/6807491984882765062 - works fine from mine side, use proxy
> tiktok-scraper video https://vt.tiktok/ydJeAa/ <- bad url

Thanks for your confirm.
How many times can be requested for each IP, is there a limit for tiktok?
Looking forward to your reply，Thanks！

**Comment by BrunoQuaresma** [comment]
I'm having the same issue
```
Error: Can't extract video metadata: https://www.tiktok.com/@tiktok/video/6807491984882765062
```

**Comment by thelou1s** [comment]
the same here

**Comment by FerrariMarketing** [comment]
Same error here

**Comment by TuskarMA** [comment]
Same error. Tested on couple of vds
