### ISSUE TITLE
Watermark-less and HD downloading broken 

### ISSUE THREAD

**Issue by Fukitsu** [drawrowfly/tiktok-scraper#266]
**Describe the bug**
Downloading videos without the watermark and in HD doesn't work anymore, but I've noticed that it only seems to happen with videos that were uploaded today 2020-July-27.
## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- Used OS
Windows 10
- NodeJs Version (node -v)
12.18.3
- Scraper Version (tiktok-scraper --version)
1.3.0
- CLI or Module
CLI
- Used method
-d -w --hd
- Used options
-d -w --hd
- Do you run the scraper through Proxy, VPN, VPS?
No
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles!
Public profile
- Preferably provide URL to the profile,hashtag,video and etc page
If I try to scrape this video for example: https://www.tiktok.com/@meikasama/video/6854248971682974981 with -d -w --hd flags I get this: Error: options.uri is a required argument
But if I use: tiktok-scraper user meikasama -d -w --hd -n 1 it will download the watermarked video
**Screenshots**

**Comment by drawrowfly** [comment]
Well i have checked videos that were uploaded recently and video id value is missing, and that id is required to download video without the watermark

**Comment by drawrowfly** [comment]
Old videos "dataisomiso2avc1mp41<4data**vid:v09044b00000bs7o7tgp8rs6d937drk**0%dataLavf58.20.10free"
New videos "dataisomiso2avc1mp41%dataLavf58.20.10free"

**Comment by areltiyan** [comment]
v09044b60000bsfiu7frscu75cjatncg

 id for this that video
just checked by sniff TikTok App but idk how to get new id with old method

**Comment by kamronbek29** [comment]
Fukitsu I have the same problem. Can not download videos without watermark, that were uploaded recently

**Comment by drawrowfly** [comment]
Solution that you have used requires implementing signature method
X-Gorgon: 
X-Khronos:

**Comment by areltiyan** [comment]
> "Solution" that you have used requires implementing signature method, so it is not a solution
> X-Gorgon:
> X-Khronos:

agree

**Comment by kamronbek29** [comment]
@drawrowfly Yes, but there is no script to generate these signatures (X-Gorgon and X-Hronos)

**Comment by drawrowfly** [comment]
@kamronbek29 Off-course there won't be any public "script" that's why i have said "so it is not a solution"

Also there are ways to generate signature, the easiest way is through [Frida](https://frida.re/), but this will require bunch of work

**Comment by kamronbek29** [comment]
@drawrowfly Yes, agree with u. Waiting for updates. Thanks

**Comment by harimambura** [comment]
> v09044b60000bsfiu7frscu75cjatncg
> 
> id for that video
> just checked by sniff TikTok App but idk how to get new id with old method

But how you got id for new video?

**Comment by vnnegt** [comment]
i've noticed that it appears to be only videos that have the "Save" option disabled

can anyone else confirm?

**Comment by Fukitsu** [comment]
@vnnegt Can confirm though I got "Error: options.uri is a required argument" with one of the three I tried with but it worked with the other two

**Comment by kamronbek29** [comment]
@drawrowfly When r u going to fix the function to download videos without watermark? Thank u in advance!

**Comment by kandayo** [comment]
> i've noticed that it appears to be only videos that have the "Save" option disabled that exhibit this behavior
> 
> can anyone else confirm?

It seems video id is missing from all new uploads regardless of privacy settings.

**Comment by dlyakin** [comment]
Hello everyone! Have the same problem. Sorry for question, but I don't understand is it possible to make scrapper download nowatermark new videos? And will be scrapper updated soon?

**Comment by drawrowfly** [comment]
I was about to release new update with patching some active issues and now this ....

I will try to find a way or maybe someone else will be able

**Comment by drdexter1989** [comment]
> v09044b60000bsfiu7frscu75cjatncg
> 
> id for that video
> just checked by sniff TikTok App but idk how to get new id with old method

Same question here . How did you get that id?

**Comment by areltiyan** [comment]
> > v09044b60000bsfiu7frscu75cjatncg
> > id for that video
> > just checked by sniff TikTok App but idk how to get new id with old method
> 
> Same question here . How did you get that id?

just sniff with app tiktok, like a fiddler 
btw to get this vidid need to x-gorgon and X-Khronos (timestamp)

**Comment by harimambura** [comment]
I found that this https://api-m.tiktok.com/aweme/v1/aweme/detail/ api endpoint seems to be exist, but don't know how to get something with it..

**Comment by kamronbek29** [comment]
Is there anyone who found a way to download tiktok videos without watermark?

**Comment by Zipdox** [comment]
Can confirm. Newer videos don't have the secret ID anymore.

**Comment by Zipdox** [comment]
Has anyone tried searching for the ID in the video file with a hex editor?

**Comment by Zipdox** [comment]
Uhm yeah I tried searching for "v0" since all IDs start with that. It ain't there chief... Try it for yourself.
I guess we'll have to find a new method. Dammit.

**Comment by ssovit** [comment]
Seems the vid: comment is no longer added metadata to the video on upload. but, you can still get the vid with `aweme/v1/aweme/detail/` endpoint and for that you will still need `device_id`, `iid` and `openuid` 

![image](https://user-images.githubusercontent.com/3162122/89857785-aeba4900-dbbc-11ea-9c9d-b3520631434c.png)

**Comment by areltiyan** [comment]
> Seems the vid: comment is no longer added metadata to the video on upload. but, you can still get the vid with `aweme/v1/aweme/detail/` endpoint and for that you will still need `device_id`, `iid` and `openuid`
> 
> ![image](https://user-images.githubusercontent.com/3162122/89857785-aeba4900-dbbc-11ea-9c9d-b3520631434c.png)

need x-gorgon/x-khronos ?

**Comment by ssovit** [comment]
> > Seems the vid: comment is no longer added metadata to the video on upload. but, you can still get the vid with `aweme/v1/aweme/detail/` endpoint and for that you will still need `device_id`, `iid` and `openuid`
> > ![image](https://user-images.githubusercontent.com/3162122/89857785-aeba4900-dbbc-11ea-9c9d-b3520631434c.png)
> 
> need x-gorgon/x-khronos ?

Nope

**Comment by areltiyan** [comment]
> > > Seems the vid: comment is no longer added metadata to the video on upload. but, you can still get the vid with `aweme/v1/aweme/detail/` endpoint and for that you will still need `device_id`, `iid` and `openuid`
> > > ![image](https://user-images.githubusercontent.com/3162122/89857785-aeba4900-dbbc-11ea-9c9d-b3520631434c.png)
> > 
> > 
> > need x-gorgon/x-khronos ?
> 
> Nope

device_id and other this is from sniffing tiktok app?

**Comment by ssovit** [comment]
> > > > Seems the vid: comment is no longer added metadata to the video on upload. but, you can still get the vid with `aweme/v1/aweme/detail/` endpoint and for that you will still need `device_id`, `iid` and `openuid`
> > > > ![image](https://user-images.githubusercontent.com/3162122/89857785-aeba4900-dbbc-11ea-9c9d-b3520631434c.png)
> > > 
> > > 
> > > need x-gorgon/x-khronos ?
> > 
> > 
> > Nope
> 
> device_id and other this is from sniffing tiktok app?

ya..

**Comment by areltiyan** [comment]
@ssovit  check email thanks.

**Comment by drdexter1989** [comment]
Maybe I would help in that too?

**Comment by areltiyan** [comment]
> > > > > Seems the vid: comment is no longer added metadata to the video on upload. but, you can still get the vid with `aweme/v1/aweme/detail/` endpoint and for that you will still need `device_id`, `iid` and `openuid`
> > > > > ![image](https://user-images.githubusercontent.com/3162122/89857785-aeba4900-dbbc-11ea-9c9d-b3520631434c.png)
> > > > 
> > > > 
> > > > need x-gorgon/x-khronos ?
> > > 
> > > 
> > > Nope
> > 
> > 
> > device_id and other this is from sniffing tiktok app?
> 
> ya..

can you share the example

**Comment by ssovit** [comment]
```
const res = await axios({
            url: 'https://api2.musical.ly/aweme/v1/aweme/detail/',
            params: {
                "carrier": "spusu",
                "mcc_mnc": "23205",
                "ad_area": "1080x1848",
                "sdk_version": "19800",
                "os_api": "26",
                "display_density": "1080x1920",
                "dpi": "480",
                "bh": "368",
                "display_dpi": "480",
                "density": "3.0",
                "ac": "wifi",
                "channel": "googleplay",
                "version_code": "-1",
                "user_period": "0",
                "user_mode": "-1",
                "refresh_num": "5",
                "user_id": "0",
                "gaid": gaid,
                "android_id": android_id,
                "ad_user_agent": useragent,
                "manifest_version_code": "2019091703",
                "current_region": "AT",
                "app_language": "en",
                "app_type": "normal",
                "device_type": "MI+5",
                "language": "en",
                "locale": "en",
                "resolution": "1080*1920",
                "update_version_code": "-1",
                "ac2": "wifi",
                "sys_region": "GB",
                "uoo": "0",
                "is_my_cn": "0",
                "timezone_name": "Europe%2FVienna",
                "residence": "AT",
                "carrier_region": "AT",
                "pass-route": "1",
                "os_version": "8.0.0",
                "timezone_offset": "3600",
                "carrier_region_v2": "232",
                "app_name": "musical_ly",
                "ab_version": "13.1.2",
                "version_name": "13.1.2",
                "device_brand": "Xiaomi",
                "ssmix": "a",
                "pass-region": "1",
                "device_platform": "android",
                "build_number": "13.1.2",
                "region": "AT",
                "aid": "1233",
                "ts": Math.floor(Date.now() / 1000),
                "_rticket": Date.now(),
                "device_id": device_id,
                'iid': iid,
                'openudid': openuid,
                aweme_id: video_id,
            },
            method: 'GET',
            headers: {
                "Host": "api2.musical.ly",
                "X-SS-TC": "0",
                "User-Agent": 'com.zhiliaoapp.musically/2018090613 (Linux; U; Android 8.0.0; tr_TR; TA-1020; Build/O00623; Cronet/58.0.2991.0)',
                "Accept-Encoding": "gzip",
                "Connection": "keep-alive"
            },
            transformResponse: axios.defaults.transformResponse.concat(function (data, headers) {
                if (typeof data.aweme_detail != "undefined") {
                    if (typeof data.aweme_detail.video.download_addr.uri != "undefined") {
                        const vid = data.aweme_detail.video.download_addr.uri;
                        return 'https://api2-16-h2.musical.ly/aweme/v1/play/?video_id='+vid+'&vr_type=0&is_play_url=1&source=PackSourceEnum_PUBLISH&media_type=4&ratio=default&improve_bitrate=1';
                    }
                }
                return false;
            })
```

This works for me

**Comment by areltiyan** [comment]
wow thanks
btw where you get that api? tiktok app?

**Comment by ssovit** [comment]
> wow thanks
> btw where you get that api? tiktok app?

did some research.. had never used worked with device_id and other things before.. I tried, failed and then it worked..

**Comment by Zipdox** [comment]
So there's no way incorporate this into the scraper unless we figure out a way to generate device_id, iid and openuid?

**Comment by drawrowfly** [comment]
Everything is possible, but i don't see point in it , i knew about this way but it is unstable and requires extra hassle

**Comment by drdexter1989** [comment]
This is the code posted previously.

`const res = await axios({
            url: 'https://api2.musical.ly/aweme/v1/aweme/detail/',
            params: {
                "carrier": "spusu",
                "mcc_mnc": "23205",
                "ad_area": "1080x1848",
                "sdk_version": "19800",
                "os_api": "26",
                "display_density": "1080x1920",
                "dpi": "480",
                "bh": "368",
                "display_dpi": "480",
                "density": "3.0",
                "ac": "wifi",
                "channel": "googleplay",
                "version_code": "-1",
                "user_period": "0",
                "user_mode": "-1",
                "refresh_num": "5",
                "user_id": "0",
                "gaid": gaid,
                "android_id": android_id,
                "ad_user_agent": useragent,
                "manifest_version_code": "2019091703",
                "current_region": "AT",
                "app_language": "en",
                "app_type": "normal",
                "device_type": "MI+5",
                "language": "en",
                "locale": "en",
                "resolution": "1080*1920",
                "update_version_code": "-1",
                "ac2": "wifi",
                "sys_region": "GB",
                "uoo": "0",
                "is_my_cn": "0",
                "timezone_name": "Europe%2FVienna",
                "residence": "AT",
                "carrier_region": "AT",
                "pass-route": "1",
                "os_version": "8.0.0",
                "timezone_offset": "3600",
                "carrier_region_v2": "232",
                "app_name": "musical_ly",
                "ab_version": "13.1.2",
                "version_name": "13.1.2",
                "device_brand": "Xiaomi",
                "ssmix": "a",
                "pass-region": "1",
                "device_platform": "android",
                "build_number": "13.1.2",
                "region": "AT",
                "aid": "1233",
                "ts": Math.floor(Date.now() / 1000),
                "_rticket": Date.now(),
                "device_id": device_id,
                'iid': iid,
                'openudid': openuid,
                aweme_id: video_id,
            },
            method: 'GET',
            headers: {
                "Host": "api2.musical.ly",
                "X-SS-TC": "0",
                "User-Agent": 'com.zhiliaoapp.musically/2018090613 (Linux; U; Android 8.0.0; tr_TR; TA-1020; Build/O00623; Cronet/58.0.2991.0)',
                "Accept-Encoding": "gzip",
                "Connection": "keep-alive"
            },
            transformResponse: axios.defaults.transformResponse.concat(function (data, headers) {
                if (typeof data.aweme_detail != "undefined") {
                    if (typeof data.aweme_detail.video.download_addr.uri != "undefined") {
                        const vid = data.aweme_detail.video.download_addr.uri;
                        return 'https://api2-16-h2.musical.ly/aweme/v1/play/?video_id='+vid+'&vr_type=0&is_play_url=1&source=PackSourceEnum_PUBLISH&media_type=4&ratio=default&improve_bitrate=1';
                    }
                }
                return false;
            })`

**Comment by drawrowfly** [comment]
@drdexter1989 ok and ?)

**Comment by Zipdox** [comment]
> const res = await axios({ url: 'https://api2.musical.ly/aweme/v1/aweme/detail/', params: { "carrier": "spusu", "mcc_mnc": "23205", "ad_area": "1080x1848", "sdk_version": "19800", "os_api": "26", "display_density": "1080x1920", "dpi": "480", "bh": "368", "display_dpi": "480", "density": "3.0", "ac": "wifi", "channel": "googleplay", "version_code": "-1", "user_period": "0", "user_mode": "-1", "refresh_num": "5", "user_id": "0", "gaid": gaid, "android_id": android_id, "ad_user_agent": useragent, "manifest_version_code": "2019091703", "current_region": "AT", "app_language": "en", "app_type": "normal", "device_type": "MI+5", "language": "en", "locale": "en", "resolution": "1080*1920", "update_version_code": "-1", "ac2": "wifi", "sys_region": "GB", "uoo": "0", "is_my_cn": "0", "timezone_name": "Europe%2FVienna", "residence": "AT", "carrier_region": "AT", "pass-route": "1", "os_version": "8.0.0", "timezone_offset": "3600", "carrier_region_v2": "232", "app_name": "musical_ly", "ab_version": "13.1.2", "version_name": "13.1.2", "device_brand": "Xiaomi", "ssmix": "a", "pass-region": "1", "device_platform": "android", "build_number": "13.1.2", "region": "AT", "aid": "1233", "ts": Math.floor(Date.now() / 1000), "_rticket": Date.now(), "device_id": device_id, 'iid': iid, 'openudid': openuid, aweme_id: video_id, }, method: 'GET', headers: { "Host": "api2.musical.ly", "X-SS-TC": "0", "User-Agent": 'com.zhiliaoapp.musically/2018090613 (Linux; U; Android 8.0.0; tr_TR; TA-1020; Build/O00623; Cronet/58.0.2991.0)', "Accept-Encoding": "gzip", "Connection": "keep-alive" }, transformResponse: axios.defaults.transformResponse.concat(function (data, headers) { if (typeof data.aweme_detail != "undefined") { if (typeof data.aweme_detail.video.download_addr.uri != "undefined") { const vid = data.aweme_detail.video.download_addr.uri; return 'https://api2-16-h2.musical.ly/aweme/v1/play/?video_id='+vid+'&vr_type=0&is_play_url=1&source=PackSourceEnum_PUBLISH&media_type=4&ratio=default&improve_bitrate=1'; } } return false; })

Doesn't that include all your device info? I imagine that would get invalidated at some point.

**Comment by ssovit** [comment]
> This is the code posted previously.
> 
> `const res = await axios({ url: 'https://api2.musical.ly/aweme/v1/aweme/detail/', params: { "carrier": "spusu", "mcc_mnc": "23205", "ad_area": "1080x1848", "sdk_version": "19800", "os_api": "26", "display_density": "1080x1920", "dpi": "480", "bh": "368", "display_dpi": "480", "density": "3.0", "ac": "wifi", "channel": "googleplay", "version_code": "-1", "user_period": "0", "user_mode": "-1", "refresh_num": "5", "user_id": "0", "gaid": gaid, "android_id": android_id, "ad_user_agent": useragent, "manifest_version_code": "2019091703", "current_region": "AT", "app_language": "en", "app_type": "normal", "device_type": "MI+5", "language": "en", "locale": "en", "resolution": "1080*1920", "update_version_code": "-1", "ac2": "wifi", "sys_region": "GB", "uoo": "0", "is_my_cn": "0", "timezone_name": "Europe%2FVienna", "residence": "AT", "carrier_region": "AT", "pass-route": "1", "os_version": "8.0.0", "timezone_offset": "3600", "carrier_region_v2": "232", "app_name": "musical_ly", "ab_version": "13.1.2", "version_name": "13.1.2", "device_brand": "Xiaomi", "ssmix": "a", "pass-region": "1", "device_platform": "android", "build_number": "13.1.2", "region": "AT", "aid": "1233", "ts": Math.floor(Date.now() / 1000), "_rticket": Date.now(), "device_id": device_id, 'iid': iid, 'openudid': openuid, aweme_id: video_id, }, method: 'GET', headers: { "Host": "api2.musical.ly", "X-SS-TC": "0", "User-Agent": 'com.zhiliaoapp.musically/2018090613 (Linux; U; Android 8.0.0; tr_TR; TA-1020; Build/O00623; Cronet/58.0.2991.0)', "Accept-Encoding": "gzip", "Connection": "keep-alive" }, transformResponse: axios.defaults.transformResponse.concat(function (data, headers) { if (typeof data.aweme_detail != "undefined") { if (typeof data.aweme_detail.video.download_addr.uri != "undefined") { const vid = data.aweme_detail.video.download_addr.uri; return 'https://api2-16-h2.musical.ly/aweme/v1/play/?video_id='+vid+'&vr_type=0&is_play_url=1&source=PackSourceEnum_PUBLISH&media_type=4&ratio=default&improve_bitrate=1'; } } return false; })`

I posted the code.. it doesn't work all the time.

For this to work you still need lots of parameters right.. probably there's better way

**Comment by Zipdox** [comment]
> 
> I posted the code.. it doesn't work all the time.
> 
> For this to work you still need lots of parameters right.. probably there's better way

You're basically using the mobile API at that point. You'll need all the credentials and device ID and stuff. Unless anyone is willing to share theirs and see what happens, this isn't an option.

**Comment by Zipdox** [comment]
Also here's properly formatted code:
    const res = await axios({
        url: 'https://api2.musical.ly/aweme/v1/aweme/detail/',
        params: {
            "carrier": "spusu", "mcc_mnc": "23205", "ad_area": "1080x1848", "sdk_version": "19800", "os_api": "26", "display_density": "1080x1920", "dpi": "480", "bh": "368", "display_dpi": "480", "density": "3.0", "ac": "wifi", "channel": "googleplay", "version_code": "-1", "user_period": "0", "user_mode": "-1", "refresh_num": "5", "user_id": "0", "gaid": gaid, "android_id": android_id, "ad_user_agent": useragent, "manifest_version_code": "2019091703", "current_region": "AT", "app_language": "en", "app_type": "normal", "device_type": "MI+5", "language": "en", "locale": "en", "resolution": "1080*1920", "update_version_code": "-1", "ac2": "wifi", "sys_region": "GB", "uoo": "0", "is_my_cn": "0", "timezone_name": "Europe%2FVienna", "residence": "AT", "carrier_region": "AT", "pass-route": "1", "os_version": "8.0.0", "timezone_offset": "3600", "carrier_region_v2": "232", "app_name": "musical_ly", "ab_version": "13.1.2", "version_name": "13.1.2", "device_brand": "Xiaomi", "ssmix": "a", "pass-region": "1", "device_platform": "android", "build_number": "13.1.2", "region": "AT", "aid": "1233", "ts": Math.floor(Date.now() / 1000), "_rticket": Date.now(), "device_id": device_id, 'iid': iid, 'openudid': openuid, aweme_id: video_id, }, method: 'GET', headers: { "Host": "api2.musical.ly", "X-SS-TC": "0", "User-Agent": 'com.zhiliaoapp.musically/2018090613 (Linux; U; Android 8.0.0; tr_TR; TA-1020; Build/O00623; Cronet/58.0.2991.0)', "Accept-Encoding": "gzip", "Connection": "keep-alive" 
        },
        transformResponse: axios.defaults.transformResponse.concat(function (data, headers) {
            if (typeof data.aweme_detail != "undefined") {
                if (typeof data.aweme_detail.video.download_addr.uri != "undefined") {
                    const vid = data.aweme_detail.video.download_addr.uri;
                    return 'https://api2-16-h2.musical.ly/aweme/v1/play/?video_id=' + vid + '&vr_type=0&is_play_url=1&source=PackSourceEnum_PUBLISH&media_type=4&ratio=default&improve_bitrate=1';
                }
            }
            return false;
        })
    });

**Comment by Zipdox** [comment]
If anyone is desperate for a workaround, you can use ssstiktok.io and wrap it. Here's my implementation: https://github.com/Zipdox/tiktok-download-userscript/commit/ae60cd5d931a52e981ba29c2eeb7b8b9691acd2a

**Comment by Marky** [comment]
what about using some API from https://rapidapi.com/search/tiktok as option?

**Comment by ssovit** [comment]
> what about using some API from https://rapidapi.com/search/tiktok as option?

https://rapidapi.com/ssovit/api/tiktok-no-watermark1 may not always give result you want.. but you may find it useful

**Comment by Zipdox** [comment]
I think we should focus on trying to decompile the TikTok Android app to see how device ID is generated and stuff.

**Comment by drawrowfly** [comment]
This is already getting ridiculous please post here message only about solutions related to the WebAPI!

1. If you disclose something related to the mobile API in public, TikTok will take note of it, i already mentioned before few times that i spotted traffic from bytedance(tiktok owner) to this repo
2. Decompiling an android app is an easy peasy task but getting something from complied and obfuscated C/C++ library that is responsible to generate ID's and etc is another thing and i already mentioned a way how it can be done!

**Comment by Zipdox** [comment]
Yeah TikTok is chinese spyware so obviously they obfuscated their APK. It won't decompile with apktool.

**Comment by drawrowfly** [comment]
lol)

**Comment by harimambura** [comment]
> 1. If you disclose something related to the mobile API in public, ...

Ok, maybe it make sense to create telegram or whatsapp chat to discuss it? I didn't learn java, but can help with something after decompiling apk

**Comment by Zipdox** [comment]
@harimambura Perhaps that's not a bad idea. But how will we know nobody's infiltrating? Also I suggest we use https://element.io/ instead because I don't feel like disclosing my personal telegram or whatsapp.

**Comment by harimambura** [comment]
@Zipdox we can just create it right now and add people from this topic in next 24 hours, then remove invite link and next invite only known people

**Comment by Zipdox** [comment]
I'm making it rn

**Comment by harimambura** [comment]
https://matrix.to/#/!CopCdmwfVxhWSbpwmd:matrix.org?via=matrix.org
this is private chat

**Comment by harimambura** [comment]
@Zipdox  lol)

**Comment by Zipdox** [comment]
Nvm you already made it

**Comment by Zipdox** [comment]
@harimambura https://matrix.to/#/!HrzrwmWaLvIwMtHLre:matrix.org?via=matrix.org

**Comment by harimambura** [comment]
![image](https://user-images.githubusercontent.com/3999607/90192731-34601380-ddcc-11ea-8582-09255902861d.png)

**Comment by Zipdox** [comment]
What's your matrix username?

**Comment by harimambura** [comment]
@harimambura:matrix.org

**Comment by Zipdox** [comment]
We've established a matrix group chat. If you want to be added to the group leave your matrix username below.

**Comment by robertdo** [comment]
@valhallarecords:matrix.org Thanks!

**Comment by Zipdox** [comment]
@robertdo Where did you come from

**Comment by llacb47** [comment]
This is off-topic and I'm sure the repo owner doesn't appreciate it. Go coordinate this on your own repo

**Comment by Zipdox** [comment]
@drawrowfly dex2jar can't seem to be able to decompile the smali.

**Comment by mingch-wei** [comment]
I help with code unencryption, matrix: mingchwei:matrix.org

**Comment by Zipdox** [comment]
It is apparent that there's a lot of TikTok and Bytedance employees lurking here. I will not be adding anyone with dead github accounts that haven't left any comments here.

**Comment by robertdo** [comment]
> @robertdo Where did you come from?

I've been following the issue. Haven't had anything significant that still works to add. 

I'm aware of these endpoints, but they either don't seem to work anymore or require X-Gorgon.

Web API that USED to work.
https://m.tiktok.com/api/item/detail?item_id=aweme_id

This actually used to work as long as you can grab and pass in the cookie. But now all the vidId results it returns have been replaced by the string "awesome".

https://api2.musical.ly/aweme/v1/aweme/detail?aweme_id=6826129413923507462
https://api19-normal-c-useast1a.tiktokv.com/aweme/v1/aweme/detail/?aweme_id=6833414546351197445

Same thing, different domains. Both require X-Gorgon.

The Chinese endpoint. Not sure how to navigate it, but probably require X-Gorgon as well based on the similar url format
https://aweme-hl.snssdk.com/aweme/v1/aweme/detail?aweme_id=6826129413923507462

Hopefully I can help you guys investigate this more in the chat!

**Comment by Zipdox** [comment]
@robertdo Ok sure I added you

**Comment by mingch-wei** [comment]
> @robertdo Ok sure I added you

I'm new to programming I want to help you guys I just joined github.

**Comment by drdexter1989** [comment]
Please add me drdexter1989:matrix.org

**Comment by kandayo** [comment]
kdyy:matrix.org

**Comment by Zipdox** [comment]
@kandayo I added you

**Comment by drdexter1989** [comment]
Does somebody will add me to the private chat ?

**Comment by tonyquang** [comment]
Please add me @Zipdox : tonyquang1999:matrix.org, thank you so much ^^

**Comment by tienbm** [comment]
Add Me @Zipdox : tienbm:matrix.org . Thanks

**Comment by drawrowfly** [comment]
sorry guys , but i don't appreciate off-topic
