### ISSUE TITLE
The videoUrlNoWaterMark link is empty

### ISSUE THREAD

**Issue by yangchong1214** [drawrowfly/tiktok-scraper#268]
tiktok-scraper --version 
1.3.0
Most videos can be downloaded,but a few can not 
eg
tiktok-scraper video https://www.tiktok.com/@tiktok/video/6854710373115776258 -t json
[
    {
        "id":"6854710373115776258",
        "text":"曾經等過祢的那段時間 是我最痛苦最難熬的時候 現在的祢沒有病痛了 謝謝祢半年給我 現在的我只能用著照片裡的回憶來想祢",
        "createTime":"1595986640",
        "authorMeta":{
            "id":"82518013056",
            "name":"lele20200106"
        },
        "musicMeta":{
            "musicId":"6849452521371568898",
            "musicName":"原聲 - 新竹小周迅 🦋♀️",
            "musicAuthor":"新竹小周迅 🦋♀️"
        },
        "imageUrl":"https://p16-tiktok-sg.ibyteimg.com/obj/v0201/4133d57bf83f4a408cc1447b29c0f3d8_1595986642?x-expires=1596218400&amp;x-signature=RdtbYjQtiqcN1cmA55FGicHYs9Q%3D",
        "videoUrl":"https://v16m.tiktokcdn.com/b1ff763ab8cf52655e1c3bcaec104321/5f22141f/video/tos/alisg/tos-alisg-pve-0037/99cbe8b0e3cf4c8292de02c4e52238cf/?a=1180&amp;br=3370&amp;bt=1685&amp;cr=0&amp;cs=0&amp;dr=3&amp;ds=3&amp;er=&amp;l=20200729182801010115228074043C1B63&amp;lr=tiktok&amp;mime_type=video_mp4&amp;qs=0&amp;rc=am48amVlbzhndjMzOjgzM0ApO2c8Z2loM2Q1NzZlNzxmNGdmYGpkXjRzMWRfLS0tLzRzcy1jMzA0XzJhNWE2NGFeYjU6Yw%3D%3D&amp;vl=&amp;vr=",
        "videoUrlNoWaterMark":"",
        "videoMeta":{
            "width":540,
            "height":960,
            "ratio":13,
            "duration":13
        },
        "covers":{
            "default":"https://p16-tiktok-sg.ibyteimg.com/obj/v0201/ddd8d1c180d281ef1cb66d3075356a6d?x-expires=1596218400&amp;x-signature=clsXiYQ6az%2BifsOxn24kMo4QfJE%3D",
            "origin":"https://p16-tiktok-sg.ibyteimg.com/obj/v0201/4133d57bf83f4a408cc1447b29c0f3d8_1595986642?x-expires=1596218400&amp;x-signature=RdtbYjQtiqcN1cmA55FGicHYs9Q%3D"
        },
        "diggCount":839,
        "shareCount":5,
        "playCount":22300,
        "commentCount":32,
        "downloaded":false,
        "mentions":[

        ],
        "hashtags":[

        ]
    }
]

**Comment by drdexter1989** [comment]
Please use search. Uploaded videos recently are not working without watermark less feature.

**Comment by yangchong1214** [comment]
> Please use search. Uploaded videos recently are not working without watermark less feature.
but this web site can download the above video without watermark
https://ssstiktok.io/
