### ISSUE TITLE
Check if a user is Live on TikTok

### ISSUE THREAD

**Issue by asportnoy** [drawrowfly/tiktok-scraper#269]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
It would be great if you added a feature to check if a user is live on TikTok. I'm not sure if this is possible with the web api, so let me know!

**Comment by llacb47** [comment]
It's not possible.

**Comment by bpo5r5** [comment]
#258

**Comment by drawrowfly** [comment]
Lets keep it clean and discuss same thing in already existing issue
