### ISSUE TITLE
unrecognized arguments

### ISSUE THREAD

**Issue by TheRouletteBoi** [drawrowfly/tiktok-scraper#27]
can someone explain to me how to fix this? 

unrecognized arguments: fyp -n 100 -d -t all

![screenshot](https://user-images.githubusercontent.com/9206290/76033065-8a18c180-5ef8-11ea-944a-dcda4bcd19cf.png)

**Comment by drawrowfly** [comment]
This is completely different package. I guess python one

**Comment by TheRouletteBoi** [comment]
I'm bamboozled, any idea why?

**Comment by drawrowfly** [comment]
No idea. In order for you to install our plugin remove old one and install this one by using Yarn or NPM
