### ISSUE TITLE
Scrape the comments?

### ISSUE THREAD

**Issue by mplobanov** [drawrowfly/tiktok-scraper#284]
**Is your feature request related to a problem? Please describe.**
Sometimes I need to extract comments from videos, how likely is this feature to be implemented?

**Describe the solution you'd like**
Something like this will be suitable:
`tiktok-scraper video 6854096000000000000 --comments`
Or something like this:
`tiktok-scraper user tiktok -t csv --comments`

**Comment by drawrowfly** [comment]
No planing to add any auth related task for now

**Comment by kgaspard** [comment]
@drawrowfly thanks for the reply. How difficult do you think it would be to run the scraper as an authed user? Even if the auth has to happen manually and we pass the auth token in somewhere
