### ISSUE TITLE
0 byte file issue

### ISSUE THREAD

**Issue by m77-droid** [drawrowfly/tiktok-scraper#286]
I'm having issues with doing multiple account scrapes. I can only do about five account scrapes before a majority or all of the files come out as 0 byte empty files. 

   Is anyone else having this issue? It's been going on for a couple months now, and I was wondering when a fix/update would be coming?

**Comment by vnnegt** [comment]
Your IP is being limited. You need to use different IP addresses when scraping a lot of data.
