### ISSUE TITLE
Error: options.uri is a required argument

### ISSUE THREAD

**Issue by cleveriornvz** [drawrowfly/tiktok-scraper#288]
`tiktok-scraper video https://www.tiktok.com/@itsandani/video/6864883463120588034 `-d``
`Error: options.uri is a required argument`

this only happens to the latest videos, old videos can still be downloaded. I hope anyone can fix this problem :D

**To Reproduce**
- Used OS: Ubuntu
- NodeJs Version: v10.19.0
- Scraper Version: 1.3.0
- CLI or Module: CLI
- Used method: Terminal Command
- Used options
- Do you run the scraper through Proxy, VPN, VPS? No
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles! : sure my target is public account
- Preferably provide URL to the profile,hashtag,video and etc page
https://www.tiktok.com/@itsandani/video/6864883463120588034
https://www.tiktok.com/@riaricis/video/6865243788588174593

Screenshot:
![image](https://user-images.githubusercontent.com/25992527/91301537-ab87a580-e7d7-11ea-890d-d4be12f01bf8.png)

**Comment by Beastskyler** [comment]
I am getting this as well but it is when I put in a url like "https://vm.tiktok.com/EXAMPLE" in, but if I but in the example command, it works fine

**Comment by reallyuniquename** [comment]
That would be #266 and it affects only newish videos.

**Comment by MoxxiFX** [comment]
Running into the same error. Tiktok recently made a change that now forces watermarks on videos, not sure if it just "renders" it on the video within the app or some other method but,  your no longer able to remove watermarks with "-w". Your still able to remove watermarks from all videos before this change, but i think this error could have something to do with it, because i;m able to grab any old video with no errors.

**Comment by drawrowfly** [comment]
New update is coming

**Comment by davispuh** [comment]
This is in  #294

**Comment by HafizZiq** [comment]
well, same goes here
![Screenshot_20200909-225440807~01](https://user-images.githubusercontent.com/46204743/92615342-881b2b00-f2ac-11ea-960e-b98ead177799.jpg)
hope @drawrowfly merge #294 fast :)

**Comment by drawrowfly** [comment]
Merged

**Comment by Beastskyler** [comment]
When I run this exact command, "tiktok-scraper video https://vm.tiktok.com/ZMJBEMPq6/ -d" I get, "Couldn't get video without watermark", along with A LOT of other stuff.  Is there something I am doing wrong to download it. I am sorry if it is just me being dumb.
[Output.txt](https://github.com/drawrowfly/tiktok-scraper/files/5241170/Output.txt)
