### ISSUE TITLE
Docker Single Video Meta saving doesn't work correct.

### ISSUE THREAD

**Issue by noil** [drawrowfly/tiktok-scraper#289]
**Describe the bug**
When I try to run `docker run -v $(pwd)/:/usr/app/files tiktok-scraper video https://www.tiktok.com/@tiktok/video/6807491984882765062 -t json`. The file doesn't save in the local system folder.
Also in the console I see response `- TikTok Scraper Started JSON path: 6807491984882765062.json`
Other commands work perfectly and save all files in the local system folder. 
Example(`docker run -v $(pwd):/usr/app/files tiktok-scraper user willsmith -t json -n 1` returns `- TikTok Scraper Started
JSON path: /usr/app/files/willsmith_1598459205688.json`)

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- MacOS
- Dockerfile
- Scraper Version 1.2.6
- CLI
- video
- -t json
- Do you run the scraper through Proxy, VPN, VPS? No
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles! Public profile
- Preferably provide URL to the profile,hashtag,video and etc page.

**Comment by drawrowfly** [comment]
Related to same problem #288
