### ISSUE TITLE
Can't download all user videos

### ISSUE THREAD

**Issue by CCTT9696** [drawrowfly/tiktok-scraper#29]
_Even when setting -n 0, i can only scrape 20-30 videos depending on each users. Redownloading the same user would get the same number of videos.
_I did scraped different users during 24h window, here's just an example:
Username: _chiyuu_
Total videos: 446.
Downloaded: 28. 
In older version i've got 415.
Current version 1.0.12

**Comment by drawrowfly** [comment]
Thats the current limit in browser API

**Comment by CCTT9696** [comment]
Is it gonna stay permanent this way?

**Comment by drawrowfly** [comment]
if the web api will be changed from the TikTok side then now

**Comment by drawrowfly** [comment]
#24
