### ISSUE TITLE
Problem installing with Node.js

### ISSUE THREAD

**Issue by AplhaSlayer1964** [drawrowfly/tiktok-scraper#290]
**Describe the bug**
when I run npm i -g tiktok-scraper i get the error:
npm ERR! Unexpected end of JSON input while parsing near '...","nyc":"^8.1.0","rim'

**To Reproduce**
- Used OS: Windows 10
- NodeJs Version (node -v): v12.18.3

I'm on a fresh install of windows 10 and I tried on a vm with a fresh install of windows 10 and it worked fine on there thats why I'm confused as to why it's not working on my main machine.

**Screenshots**

![Capture](https://user-images.githubusercontent.com/62714929/91459546-bfbdb800-e854-11ea-8aac-f35093d79895.PNG)

**Comment by AplhaSlayer1964** [comment]
following this guide: 
https://stackoverflow.com/questions/50189096/installing-create-react-app-gives-npm-err-shasum-check-failed-and-npm-err-unex/50191315#50191315 
and disabling my vpn fixed it.

**Comment by drawrowfly** [comment]
Thats why you have do research first! and only after create an issue !
