### ISSUE TITLE
Video No Watermark Link not working showing blank

### ISSUE THREAD

**Issue by pranjallyad** [drawrowfly/tiktok-scraper#291]
Sir your script is so good but Video no watermark link is not working means when I click on this link is showing blank and when I use curl for redirection check it show real link but the link got from Video meta is not working sir please help me and don't reply use search this is already solved but I checked it, this issue is not solved yet sir please help me I need urgently and you are only my hope 🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏 please please please please please please please please please please please please

**Comment by drawrowfly** [comment]
If you are getting an actual  URL to the video without the watermark then i've already mentioned somewhere that you can still open it in browser just play with the user-agent

**Comment by Dwite** [comment]
@drawrowfly by **play** what do you mean exactly?)
