### ISSUE TITLE
Save history even for single video download

### ISSUE THREAD

**Issue by davispuh** [drawrowfly/tiktok-scraper#292]
I was downloading single video with `tiktok-scraper video URL -s --historypath hist` and it didn't update/create `tiktok_history.json` which I was expecting.

**Comment by drawrowfly** [comment]
The history function was build only to save history of the downloaded feed(user,hashtag,trends) and there is no reason to make it for the single video

**Comment by drawrowfly** [comment]
i will update the doc's shortly to clarify everything that can be expected or not expected

**Comment by davispuh** [comment]
I think it can be useful even for single video. Let's say I download few videos and then later I want to download all for user but no need to redownload already downloaded.
