### ISSUE TITLE
Post id to video id common collection database

### ISSUE THREAD

**Issue by ssovit** [drawrowfly/tiktok-scraper#295]
Just an idea. Looking for guys, who have figured out ways to get non watermarked video id even after 27th update.

I currently have a small database which stores the data in MongoDB with schema below to do some caching.

```javascript
{
    i: {
        type: String // video post id
    },
    v: {
        type: String // video id
    }
}
```

Probably we could create a common db, where I can also push the video ids. Others can re-use if record exists in db without having to query to tt server.

**Comment by khazidhea** [comment]
Does anyone know how to get video_id after the update without looking for "vid:"?

**Comment by ssovit** [comment]
It's possible to be able to extract video id without looking for `vid:` but requires extra step.

X-Gorgon and X-Khronos seems to be only better way atm. You can find some guys who have those as service for rent. 

It's more complicated than web api with `_signature` and it tends to change on every update.
