### ISSUE TITLE
Anybody still using it?

### ISSUE THREAD

**Issue by mormonxyz** [drawrowfly/tiktok-scraper#299]
It has been almost 3 months since last update. Has it been abandoned? Is there any good alternative? Thanks for your time and effort, but it's no longer useable. Watermarks, daily limitation, and now it downloads corrupted videos (as shown in the image below). 
![image](https://i.imgur.com/2BOSBX8.png)

**Comment by drawrowfly** [comment]
Nothing is abandoned

**Comment by drawrowfly** [comment]
Use proxy to avoid "daily limitations"
