### ISSUE TITLE
Scrape videos without watermark

### ISSUE THREAD

**Issue by AidasK** [drawrowfly/tiktok-scraper#30]
I saw that online tiktok downloaders allows to download videos without a watermark. Is it possible with this lib?

**Comment by drawrowfly** [comment]
After downloading the video , it needs to be video edited , it is a bit heavy task and not a purpose of this library However PR is welcome :)

**Comment by AidasK** [comment]
My point is, that tiktok itself supports returning videos without a watermark. So we don't need to edit them locally. We only need to figure our how those links are created. Check this: https://musicallydown [dot] com/

**Comment by drawrowfly** [comment]
#31

**Comment by bhargavsonagara** [comment]
anybody found the solution for how to get vid from the tiktok video to get a link for no watermark.
