### ISSUE TITLE
[FR] Ability to scrape comments of a post

### ISSUE THREAD

**Issue by kgaspard** [drawrowfly/tiktok-scraper#300]
First of all, loving this repo, thank you for it. It was very easy to get started with it, unlike the tiktok-api npmjs.

However, that other package has the ability to scrape comments of a post. Is this something you plan on adding?

**Comment by mormonxyz** [comment]
A simliar question has been answered [url=https://github.com/drawrowfly/tiktok-scraper/issues/284]here[/url].

**Comment by kgaspard** [comment]
Thanks @mormonxyz , I didn't know comments were only scrapable with auth - interesting!

Will close
