### ISSUE TITLE
Getting videometa videourl no longer sends openable url

### ISSUE THREAD

**Issue by Oli-idk** [drawrowfly/tiktok-scraper#302]
**Describe the bug**
the videometa videourl no longer works and say i have no access to the link
## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- Used OS windows 10
- NodeJs Version (node -v) v14.7.0
- Scraper Version (tiktok-scraper --version) 1.3.0
- CLI or Module
- Used method       const videoMeta = await TikTokScraper.getVideoMeta(link);
- Used options videoMeta.videoUrl
- Do you run the scraper through Proxy, VPN, VPS? no 
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles! yes
- Preferably provide URL to the profile,hashtag,video and etc page doesnt work on any url

**Screenshots**
![image](https://user-images.githubusercontent.com/67001116/93407979-5411ae00-f848-11ea-9750-1ffa8b187259.png)

**Comment by Oli-idk** [comment]
updated to 1.3.1 and still have the same problem

**Comment by wisdomware** [comment]
I had the same problem like Oli-idk with version 1.3.0. However, after updating to 1.3.1, Tiktok-scraper is working again.
Thanks to all the contributors who are working on this project.

Cheers!

**Comment by Oli-idk** [comment]
guess it didnt update to 1.3.1 idk why

**Comment by Oli-idk** [comment]
ok so even on 1.3.1 it still does the same thing

**Comment by drawrowfly** [comment]
https://github.com/drawrowfly/tiktok-scraper/issues/301#issuecomment-693537645

**Comment by paulwongx** [comment]
@drawrowfly Thank you for creating this functionality for all of us to use. I've been clicking around at all the references to the same issues, but still unable to find the answer or any explanation if it's being worked on, or if this is just how it will be for the time being. 

Again, thank you for all your hard work and for creating this repo. At this time, closing all the issues and conversations about urls not working without a source to explain what's going on is confusing us at the least. Could you kindly clarify, please and thank you.
