### ISSUE TITLE
Error: Couldn't get video without watermark

### ISSUE THREAD

**Issue by ry-ga** [drawrowfly/tiktok-scraper#304]
**Describe the bug**
The no-watermark flag does not work when downloading profiles, individual videos or in bulk. 

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- Mac OS Cataline
- v12.18.3
- 1.3.1
- CLI or Module
- tiktok-scraper user USERNAME -d --hd -w all -n
- Used options
- Do you run the scraper through Proxy, VPN, VPS?  I tried with and without.
- If scraping from a profile. Did you checked if profile is Public? Yes
- Preferably provide URL to the profile,hashtag,video and etc page  You can pick any public profile.
<img width="904" alt="Screen Shot 2020-09-17 at 5 16 40 PM" src="https://user-images.githubusercontent.com/14020151/93529222-8e8f4f80-f909-11ea-8ca2-503068e94567.png">

**Screenshots**

**Comment by drawrowfly** [comment]
I have pushed new version that won't show this huge message

Update the app
