### ISSUE TITLE
Video downloads returning 403 response

### ISSUE THREAD

**Issue by Ayesh** [drawrowfly/tiktok-scraper#305]
**Describe the bug**
I suppose due to TikTok checking the referrer header, but I cannot seem to download watermark or non-watermark videos with current version 1.3.2. I get an error saying the response code was 403. 

**To Reproduce**
- Used OS: Windows
- NodeJs Version (node -v): 14.5
- Scraper Version (tiktok-scraper --version): 1.3.2
- CLI or Module: CLI
- Used method: `sh node_modules/.bin/tiktok-scraper video https://www.tiktok.com/@truyenhinhvov/video/6873
689249472974081 -hd`
- Used options: `-d` and `-hd`. The CSV file is generated, but that both video URLs return a 403 response.
- Do you run the scraper through Proxy, VPN, VPS? Not using anything. But it's unlikely that I'm rate limited, because I can watch and browser tiktok on a normal browser.
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles!: Public profile.
- Preferably provide URL to the profile,hashtag,video and etc page: `https://www.tiktok.com/@truyenhinhvov/video/6873689249472974081`

**Screenshots**

![image](https://user-images.githubusercontent.com/811553/93594643-6fafbc80-f9e0-11ea-8d15-c1cc5368cd53.png)

**Comment by ssovit** [comment]
```js
const goodVideoURL=badVideoURL.replace('-web.tiktokcdn','.tiktokcdn');
```

considering `badVideoURL` is the video URL that can't be played without `tiktok.com` as http referer. `goodVideoURL` is the video URL that can be downloaded or is playable in browser.

**Comment by drawrowfly** [comment]
Fixed in the latest update
