### ISSUE TITLE
Video url 403 response-Access to v16-web.tiktokcdn.com was denied

### ISSUE THREAD

**Issue by Crypto75** [drawrowfly/tiktok-scraper#308]
**Describe the bug**
i was copy url from json file and paste on browser that time i received access denied.
i used your latest update 1.3.2.

video download is fine but not play with URL, please watch below video what is issue.

https://www.screencast.com/t/LRYZAaoA 

 
 
**Screenshots**
Watch Video:  https://www.screencast.com/t/LRYZAaoA

**Comment by drawrowfly** [comment]
https://github.com/drawrowfly/tiktok-scraper/issues/303#issuecomment-694280504

**Comment by paulwongx** [comment]
@Crypto75 I'm having the same issue, but video download doesn't work for me. Can you clarify in what way video download works for you?
