### ISSUE TITLE
Custom file/paths names.

### ISSUE THREAD

**Issue by jpramirez87** [drawrowfly/tiktok-scraper#309]
Hello! First of all I want to thank you for this tool, it's G-R-E-A-T! I'm mainly using it for hashtag scraping, everything works perfect so far, however, I would like to know if there's any way to add custom names for files and folders paths, for example:

`<DownloadFolder>\#hashtag\{authorName}\{id}_{date}.mp4`

**Comment by drawrowfly** [comment]
#232
