### ISSUE TITLE
VideoUrl Access to v19-web.tiktokcdn.com was denied

### ISSUE THREAD

**Issue by tienbm** [drawrowfly/tiktok-scraper#310]
![Screen Shot 2020-09-20 at 02 00 04](https://user-images.githubusercontent.com/12368662/93687064-05347480-fae5-11ea-9687-4a22713463e7.png)
Can't open video.

**Comment by drawrowfly** [comment]
https://github.com/drawrowfly/tiktok-scraper/issues/308#issuecomment-695174931
