### ISSUE TITLE
Script doesn't download all videos of particular user

### ISSUE THREAD

**Issue by rabea98** [drawrowfly/tiktok-scraper#311]
**Describe the bug**
The script scrapes only 9 videos of user with the name "okcallie"   , i tried different machines with different ips and would get the same result , it would only download just 9 videos.
It appears that only 9 videos show on Tiktok Webpage on Chrome, while on IOS more that 40 video appear.

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- Used OS
Windows server 2019
- NodeJs Version (node -v)
v14.9.0
- Scraper Version (tiktok-scraper --version)
1.3.3
- CLI or Module
CLI
- Used method
tiktok-scraper user okcallie -d -a 1 --hd -t all --noWaterMark --filepath  D:\tiktok
via CMD
- Used options
-d -a 1 --hd -t all --noWaterMark --filepath  D:\tiktok
- Do you run the scraper through Proxy, VPN, VPS?
I tried with a VPN, and got the same result
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles!
Yes
- Preferably provide URL to the profile,hashtag,video and etc page
https://www.tiktok.com/@okcallie
**Screenshots**

**Comment by drawrowfly** [comment]
If you see only 9 videos on the computer that you are running the scraper from then it means your IP is temporarily "blacklisted" by the tiktok. Use proxy

**Comment by drawrowfly** [comment]
+ i have tried from mine side and no problems at all with that profile

**Comment by Crypto75** [comment]
@rabea98 
Read below link , this is very useful for you.
https://wpfbinstatiktok.blogspot.com/2020/08/how-to-search-tiktok-videos-by-username.html
