### ISSUE TITLE
videoUrl was denied

### ISSUE THREAD

**Issue by haichay88** [drawrowfly/tiktok-scraper#312]
videoUrl can not access

ex: https://v16-web.tiktokcdn.com/7a63a621fce7fcc369a8cc266203b8f0/5f6780c8/video/tos/alisg/tos-alisg-pve-0037c001/e6fdeb637cff4034b06b7c4159f81ba7/?a=1988&br=2896&bt=1448&cr=0&cs=0&cv=1&dr=3&ds=3&er=&l=2020092010180701023409915809003275&lr=tiktok&mime_type=video_mp4&qs=0&rc=amtueDQzdTZqdzMzZDgzM0ApNmRlNTxoZztlNzM5Ozc2aWc2ZWNjMDJoc19fLS02LzRzc2IyYTNfMWA0YTBeNS4tMC86Yw%3D%3D&vl=&vr=

may be tiktok change ?

**Comment by drawrowfly** [comment]
https://github.com/drawrowfly/tiktok-scraper/issues/310#issuecomment-695352457

**Comment by haichay88** [comment]
the same videoId but avaiable with url

https://v19.tiktokcdn.com/cb8a09605cd4818cfa250fe7202506d7/5f6779e1/video/tos/alisg/tos-alisg-pve-0037c001/e6fdeb637cff4034b06b7c4159f81ba7/?a=1988&br=2896&bt=1448&cr=0&cs=0&cv=1&dr=3&ds=3&er=&l=202009200948400101901911630200FE0E&lr=tiktok&mime_type=video_mp4&qs=0&rc=amtueDQzdTZqdzMzZDgzM0ApNmRlNTxoZztlNzM5Ozc2aWc2ZWNjMDJoc19fLS02LzRzc2IyYTNfMWA0YTBeNS4tMC86Yw%3D%3D&vl=&vr=

when get videoUrl from tiktok-scraper, video was denied
