### ISSUE TITLE
videoUrl not working

### ISSUE THREAD

**Issue by paulwongx** [drawrowfly/tiktok-scraper#313]
In the json file that comes back with information for each video, the videoUrl links aren't working. 

When going to the website manually it says 

"Access to v19-web.tiktokcdn.com was denied.
You don't have authorization to view this page.
HTTP ERROR 403"

Is this due to banning of Tiktok by USA? I'm in Canada so surprised it's still blocked.

Example url that doesn't work for me:
https://v19-web.tiktokcdn.com/b365e8b73c1ed72d49ff947be80de4e5/5f69ae94/video/tos/alisg/tos-alisg-pve-0037c001/2c1fe9d443824518be5935a84c01d5aa/

**Comment by Crypto75** [comment]
i think tiktok changed network security so you can only download video from that URL.

**Comment by paulwongx** [comment]
@Crypto75 Hm.. not sure if I might be missing something, but that's what I tried to do. I tried downloading via the "videoUrl" parameter but it doesn't work. So I tried clicking the url link and it gives 403 error.

Are you able to still download videos from tiktok? 
I'm not sure if there's some small issue on my end (my location?) or if everyone can't download now.

**Comment by youngvo** [comment]
I'm having the same issue. I set src of an html video tag to the url. It says: 304 error

**Comment by drawrowfly** [comment]
https://github.com/drawrowfly/tiktok-scraper/issues/310#issuecomment-695352457

**Comment by Crypto75** [comment]
@paulwongx  @youngvo , download is working fine in latest version of tiktok scraper.

i suggested for you , if you want to download any tiktok videos by user so please install below app.
i was used this app for download tiktok users.
https://play.google.com/store/apps/details?id=com.videosearchfortoks&hl=en_IN

**Comment by paulwongx** [comment]
@Crypto75 That app is manually downloading though right...? I think we're looking more for programmatic downloads... but you can confirm that downloading works in the latest version? I tried yesterday to no avail personally.

When you say 'download, can you clarify:
1) Do you mean downloading via tiktok-scraper's preset download options works? OR
2) Using the link provided in the "videoUrl" parameter from the json file works?

I tend to use #2 and it doesn't work for me since yesterday.
