### ISSUE TITLE
videoUrlNoWaterMark always null

### ISSUE THREAD

**Issue by mehulvadodariya2012** [drawrowfly/tiktok-scraper#314]
**Describe the bug**
`videoUrlNoWaterMark` response param always comes with a null value

**To Reproduce**
```
let user = await TikTokScraper.getUserProfileInfo('tiktok', options); 
let video = await TikTokScraper.user(user.uniqueId, options);
```
- Used OS
Ubuntu
- NodeJs Version (node -v)
v12.18.3
- Scraper Version (tiktok-scraper --version)
^1.3.3
- Used method
TikTokScraper.user

- Do you run the scraper through Proxy, VPN, VPS?
Yes with Proxy

- Preferably provide URL to the profile,hashtag,video and etc page
With all profiles

**Comment by mehulvadodariya2012** [comment]
@drawrowfly is this issue already answered?

**Comment by drawrowfly** [comment]
https://github.com/drawrowfly/tiktok-scraper/issues?q=is%3Aissue+watermark+is%3Aclosed

**Comment by mehulvadodariya2012** [comment]
@drawrowfly Thanks, You can delete this issue permanently
