### ISSUE TITLE
Discord Server

### ISSUE THREAD

**Issue by drawrowfly** [drawrowfly/tiktok-scraper#315]
I've been asked few times already to create the discord server

Server is up and running and everyone can join it to discuss important stuff :)

<a href="https://discord.gg/7SZaUs4" target="_blank"><img src="https://i.imgur.com/dUwek7T.jpg" alt="Discord Server" width="435" height="190" ></a>

**Comment by digvijay1331** [comment]
tiktok.com/node/share/user not working.
