### ISSUE TITLE
Some videos still have a watermark after downloading.

### ISSUE THREAD

**Issue by Nefrace** [drawrowfly/tiktok-scraper#316]
**Describe the bug**
When i tested CLI interface on "@NotMarkiplier" page, all videos were downloaded without watermarks [(example)](https://www.tiktok.com/@notmarkiplier/video/6801847571582045445)
But some other videos from trends are still have watermark with any arguments combination. [(example)](https://www.tiktok.com/@neletto0/video/6873729703031639297?lang=ru)
## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- Used OS: Debian 10 x86-64
- NodeJs Version (node -v) 10.21.0
- Scraper Version (tiktok-scraper --version) 1.3.3
- CLI
- Used method: tiktok-scraper video
- Used options: -d -w [url]
- Do you run the scraper through Proxy, VPN, VPS? - No
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles!
- Preferably provide URL to the profile,hashtag,video and etc page
Working video - https://www.tiktok.com/@notmarkiplier/video/6801847571582045445
Not working - https://www.tiktok.com/@neletto0/video/6873729703031639297?lang=ru

**Comment by drawrowfly** [comment]
https://github.com/drawrowfly/tiktok-scraper/issues/314#issuecomment-696559299
