### ISSUE TITLE
videoUrlNoWaterMark is showing empty and null from getVideoMeta method

### ISSUE THREAD

**Issue by GhazanfarKhan** [drawrowfly/tiktok-scraper#318]
Hi,

I just updated the version to 1.33 and without water mark link showing empty and null.

![image](https://user-images.githubusercontent.com/16287368/94343648-fee94f80-0032-11eb-9e95-6482fc74f9eb.png)

It was working previously but now 1.30 also showing the same behaviour.
Can you help me what I am doing wrong.

**Comment by drawrowfly** [comment]
https://github.com/drawrowfly/tiktok-scraper/issues/316#issuecomment-697290156

**Comment by GhazanfarKhan** [comment]
Its not clear I see that. Can you please tell its from your end or tiktok end that newer videos dont't have this feature?

**Comment by GhazanfarKhan** [comment]
Or I have to play with userAgent ?

**Comment by drawrowfly** [comment]
All videos uploaded since ~july 20, 2020 + do not have unique video id that is usually was stored the raw video data

**Comment by GhazanfarKhan** [comment]
So there is no way not to get without watermark video?

**Comment by habibmy** [comment]
I am also having the same issue, videoUrlNoWaterMark is showing empty by using getVideoMeta. but i am able to download without watermark by using terminal method.
I tried these links.
```
https://www.tiktok.com/@avneetkaur_13/video/199950426157596672
https://www.tiktok.com/@avneetkaur_13/video/199864122463703040
https://www.tiktok.com/@avneetkaur_13/video/198580990355619840
https://www.tiktok.com/@avneetkaur_13/video/198579158338371584
```

**Comment by fulminaire** [comment]
Will this be fixed?

**Comment by rosnaib11** [comment]
Is there an alternative to (-w)? to download multiple videos without watermark?

**Comment by Shmi911** [comment]
I know that the "720x1280" nowatermark versions still do exist on tiktok servers. I found an online website that can still find the versions via link.
So this issue shouldn't be closed, or is there no interest in keeping this feature alive?

**Comment by Shmi911** [comment]
So here is an example for a new uploaded video on the 18th of Oct. 2020

**Reproduction**

use "tiktok-scraper video https://www.tiktok.com/@charlidamelio/video/6885087969259080965 -d --hd -w"

It downloads the **tagged non hq version** (576x1024, 2,93 mb)

**Example for existing & accessible hd nowatermark**

**no watermark**, 576x1024, 2,86 mb
found here "https://v19.tiktokcdn.com/26d8dea5468def53081f0e2f3ce9180e/5f8e3b6e/video/tos/useast2a/tos-useast2a-pve-0068/d3ac8cc9ab3b4d038b696d7fae7f5b6c/?a=1180&br=3920&bt=1960&cr=0&cs=0&cv=1&dr=0&ds=6&er=&l=202010191920350102341090814407CE46&lr=&mime_type=video_mp4&qs=0&rc=amR3ZXdqajtleDMzOzczM0ApaTQ7ZjYzaDs3N2Q7aGllO2duX3AxLTNjcjNfLS0tMTZzcy1iLjEzNGAxX2IzMzI0MzY6Yw%3D%3D&vl=&vr="

**no watermark & hd**, 720x1280, 7,49 mb
found here "https://v19.tiktokcdn.com/3a20a4b338a74585634781008c6e2a25/5f8e3be6/video/tos/useast2a/tos-useast2a-v-0068/c8bc1670065f491986dd2baa7eb16a2b/?a=1180&br=10344&bt=5172&cr=0&cs=0&cv=1&dr=0&ds=3&er=&l=202010191922350101151510581407BBE1&lr=&mime_type=video_mp4&qs=13&rc=amR3ZXdqajtleDMzOzczM0ApdGV2NzM5aXg5ZTMzMzc8eWduX3AxLTNjcjNfLS0tMTZzc2RecV9xZGQ1X3ItLTUxLS06Yw%3D%3D&vl=&vr="


but don't ask me how to find these with coding.

**Comment by youngvo** [comment]
> **no watermark & hd**, 720x1280, 7,49 mb
> found here "https://v19.tiktokcdn.com/3a20a4b338a74585634781008c6e2a25/5f8e3be6/video/tos/useast2a/tos-useast2a-v-0068/c8bc1670065f491986dd2baa7eb16a2b/?a=1180&br=10344&bt=5172&cr=0&cs=0&cv=1&dr=0&ds=3&er=&l=202010191922350101151510581407BBE1&lr=&mime_type=video_mp4&qs=13&rc=amR3ZXdqajtleDMzOzczM0ApdGV2NzM5aXg5ZTMzMzc8eWduX3AxLTNjcjNfLS0tMTZzc2RecV9xZGQ1X3ItLTUxLS06Yw%3D%3D&vl=&vr="
> 
> but don't ask me how to find these with coding.

@Shmi911 I'm really curious. Could you please advise about how you can generate these links? Thanks a lot.

**Comment by Shmi911** [comment]
> @Shmi911 I'm really curious. Could you please advise about how you can generate these links? Thanks a lot.

@youngvo I used the webpage "https://downloaderi.com/". It would only provide the 720x1280 versions.. As I said I don't know how to get it myself.
The webpages tiktok function worked until yesterday. For the moment the only output is "https://api-h2.tiktokv.com/aweme/v1/play/?video_id=v09044b60000bu7kfpj8sihgu4f37ph0&vr_type=0&is_play_url=1&source=PackSourceEnum_FEED&media_type=4&ratio=default&improve_bitrate=1" which doesn't download anything.

Hopefuly someone will make the scraper's --hd function work again.
