### ISSUE TITLE
Error when using proxy

### ISSUE THREAD

**Issue by hd531ab** [drawrowfly/tiktok-scraper#32]
Hello,

my setup : 
Ubuntu 18.04
NodeJS : I tried version 12 and 13
tiktok scraper : 1.0.12

I keep getting an error message when I'm trying to use a proxy-server . Tried different proxy-servers.
Only appears when I'm trying to use a proxy.

tiktok-scraper trend -d -n 5 -p https://115.23.28.168:8080
Error: Error: [object Object]
    at TikTokScraper.extractTac (/usr/local/lib/node_modules/tiktok-scraper/lib/index.js:311:19)

**Comment by drawrowfly** [comment]
Pass the proxy as 115.23.28.168:8080

I need to add proxy format validation

**Comment by hd531ab** [comment]
Thanks for the quick response .

The solution was to type it like this 

-p115.23.28.168:8080   

No https and no space after the -p

Great software by the way.

**Comment by drawrowfly** [comment]
With the next update proxy support will be improved

**Comment by drawrowfly** [comment]
Proxy support was improved with the latest update
