### ISSUE TITLE
Cannot read property 'statusCode' of undefined

### ISSUE THREAD

**Issue by lu3do** [drawrowfly/tiktok-scraper#320]
When calling `TikTokScraper.getUserProfileInfo()` it sometimes throws a `Cannot read property 'statusCode' of undefined` error

It seems to happen randomly since the user does exist and when re-trying the same request it doesn't throw the error.
The last few days it seems to be happening more frequently, about 1 out of every 10 requests is throwing this error now.

unfortunately, I'm unable to reproduce it locally.

**Comment by drawrowfly** [comment]
Fill out bug template
