### ISSUE TITLE
Scraping TiktTok doesn't work when userprofile property openFavorite is set to false

### ISSUE THREAD

**Issue by Ikonta68** [drawrowfly/tiktok-scraper#322]
Scraping TiktTok doesn't work when userprofile property openFavorite is set to false:

is their a possibilty to overcome this?
below an example of an tiktok-account which is not "scrapable"

tiktok-scraper userprofile anna_strigl
{
  secUid: 'MS4wLjABAAAARgZwWDrvZrGRGqTDEXrN9SUYT722rV7b6gTRQ7yVRo3FmIjsCuHlC6WrSscDOI2w',
  userId: '88809051228110848',
  isSecret: false,
  uniqueId: 'anna_strigl',
  nickName: '(っ◔◡◔)っ ♥ Anna Lena Strigl ♥',
  signature: 'Griaß di 🇦🇹\n' +
    '🦋Folgt mir auf Insta: anna_strigl⬆️⬆️\n' +
    'Zweitkanal = annastrigl',
  covers: [
    'https://p77-sign-sg.tiktokcdn.com/musically-maliva-obj/a056f2d1277ce7b14b9163ed38aca563~c5_100x100.jpeg?x-expires=1601625600&x-signature=zHpQvzeAl5kcstbRfpwmI7uWD8M%3D'
  ],
  coversMedium: [
    'https://p77-sign-sg.tiktokcdn.com/musically-maliva-obj/a056f2d1277ce7b14b9163ed38aca563~c5_720x720.jpeg?x-expires=1601625600&x-signature=jTj19U1GiAq4r0CUHtsfWeRonr8%3D'
  ],
  following: 340,
  fans: 1400000,
  heart: '55100000',
  video: 1054,
  verified: true,
  digg: 0,
  ftc: false,
  relation: -1,
  **openFavorite: false**
}

**Comment by drawrowfly** [comment]
There is no such option userprofile

**Comment by Ikonta68** [comment]
with tiktok-scraper@1.3.4
scraping works now also with accounts where the property **openFavorite** is set to **false** 
Thank you
