### ISSUE TITLE
[BUG] tiktok-scraper music [id] Not Working at All

### ISSUE THREAD

**Issue by devbiansor** [drawrowfly/tiktok-scraper#324]
I tried everything and wait up to 5 hours. This command does not starting. It stucked or nothing happens. Can you just remove it, or tell what exactly happens this is false hope. I saw this issue #19 I already updated from 1.3.4 to 1.3.5 still unlucky.

tiktok-scraper music Wrap-Me-In-Plastic-Marcus-Layton-Radio-Edit-6539273168605942799 -d -n 10 (Stuck at "Tiktok Scraper Started")
tiktok-scraper music 6539273168605942799 -d -n 10 (Stuck at "Tiktok Scraper Started")
tiktok-scraper music 6539273168605942799 -n 10 (Nothing happens)

I also tried on different music id
I tried on different machines, my other computer and MacOS

No error its just stuck and nothing happens

Other commands works fine. Only this one getting me on trouble

**To Reproduce**
- Used OS: Windows & Mac
- NodeJs Version (node -v) : 10.16.v all my machines
- Scraper Version (tiktok-scraper --version):  1.3.4 and 1.3.5
- CLI or Module: CLI
- Used method: tiktok-scraper music [id]
- Used options:  (-d) , (-d, -n). Everything that can used, I tried too. Also reversing order etc.
- Do you run the scraper through Proxy, VPN, VPS? No
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles! I don't its music ID 
- Preferably provide URL to the profile,hashtag,video and etc page
    * Wrap-Me-In-Plastic-Marcus-Layton-Radio-Edit-6539273168605942799
    * original-sound-6666453854525098758
    * Da-Ni-Darling-Ohayo-6808793653947943681
    * etc.. I guess its all music url ids not working

**Screenshots**
![image](https://user-images.githubusercontent.com/73074563/96375444-9d3c8100-11ab-11eb-8d9f-22f0a5b8529d.png)
![image](https://user-images.githubusercontent.com/73074563/96375471-c0ffc700-11ab-11eb-8069-da30aa1e3781.png)

**Comment by drawrowfly** [comment]
Use only music id (numbers)

**Comment by devbiansor** [comment]
> Use only music id (numbers)

I did, I just woke up and still at "started" nothing happens

![image](https://user-images.githubusercontent.com/73074563/96389886-75b5da80-11e4-11eb-804d-969848ff4ea2.png)

**Comment by devbiansor** [comment]
When I removed this part, its starts to download

![image](https://user-images.githubusercontent.com/73074563/96391014-c5e36b80-11e9-11eb-8cd8-42b4eb939dea.png)

![image](https://user-images.githubusercontent.com/73074563/96391021-cda31000-11e9-11eb-8faa-2443948a704f.png)
