### ISSUE TITLE
User's videos only show up on mobile

### ISSUE THREAD

**Issue by MoosMas** [drawrowfly/tiktok-scraper#326]
**Describe the bug**
When going to tiktok.com on desktop, it says the user hasn't uploaded any video's, But in the TikTok app, there are tons. Is there a way to download them?

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- Windows 10
- NodeJS v12.18.3
- TikTok-scraper v1.3.5
- PowerShell/CMD
- `tiktok-scraper user hiimsoph`
- `-d -w --hd`
- VPN
- Even when signed in with an account that is following this user, they don't show up
- [https://www.tiktok.com/@hiimsoph](https://www.tiktok.com/@hiimsoph)

**Screenshots**
[Screenshots](https://imgur.com/a/4dyx5sx)

**Comment by drawrowfly** [comment]
If there is no videos from browser side, then nothing can be done and this is not a bug related to the scraper

**Comment by MoosMas** [comment]
> If there is no videos from browser side, then nothing can be done and this is not a bug related to the scraper

I know but the videos do show up in the app, so is there any way to scrape them? Maybe changing user agent? Didn't know where else to post it
