### ISSUE TITLE
Returning the bioLink In The getUserProfileInfo Response

### ISSUE THREAD

**Issue by thenotic** [drawrowfly/tiktok-scraper#327]
Is it possible to return the `bioLink` in the `getUserProfileInfo` response?  I think it's a relatively new addition to the user profile on the web version and it seems to be in the same response as the rest of the user data.

![image](https://user-images.githubusercontent.com/4081562/96926672-db73c200-1483-11eb-8cf6-a29974f3156f.png)

**Comment by drawrowfly** [comment]
This data is available in the latest version of the app
