### ISSUE TITLE
getUserProfileInfo is not working

### ISSUE THREAD

**Issue by iwantooxxoox** [drawrowfly/tiktok-scraper#328]
**Describe the bug**
It looks like the end point https://www.tiktok.com/node/share/user/ is no longer available to get user profile info.
You can test with https://www.tiktok.com/node/share/user/@tiktok

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- Used OS: Mac OSX
- NodeJs Version (node -v): v14.13/1
- Scraper Version (tiktok-scraper --version): 1.3.5
- Used method: getUserProfileInfo
- Used options: no
- Do you run the scraper through Proxy, VPN, VPS? yes
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles!
- Preferably provide URL to the profile,hashtag,video and etc page

**Comment by lu3do** [comment]
I'm having the same issue, the response from TikTok for that request is now:
`{ statusCode: 10201, statusMsg: null, userInfo: {} }` 
So it throws the "Can't find user: " error.

**Comment by xiaomingtan** [comment]
me too

**Comment by Tankruslan** [comment]
same problem since today

**Comment by d521bb85** [comment]
It looks like the `.user` method is also affected by the issue. It returns an empty `collector` array.

**Comment by lu3do** [comment]
TikTok made some big changes to their API,
I found that at least these methods are affected, maybe even more.
```
TikTokScraper.user()
TikTokScraper.getVideoMeta() 
TikTokScraper.getUserProfileInfo()
```

**Comment by llacb47** [comment]
`https://www.tiktok.com/node/share/user/` needs some additional parameters now. 

`https://www.tiktok.com/node/share/user/@madi` doesn't work.

`https://www.tiktok.com/node/share/user/@c?uniqueId=madi` works.

**Comment by asportnoy** [comment]
Having same issue, hopefully @drawrowfly can fix soon.

**Comment by euphorbial** [comment]
Signed up to let you know I'm having trouble with scraping posts by Hashtag as well. So a command like 

tiktok-scraper hashtag HELLO -n 20 -d

...Momentarily returns 'Tiktok-Scraper Started' but then nothing. Attached a couple of pics to explain.

![1](https://user-images.githubusercontent.com/73353623/97022520-20fbc200-154c-11eb-916a-51d43a8ec7c3.png)
![2](https://user-images.githubusercontent.com/73353623/97022523-20fbc200-154c-11eb-906f-7af2ddb782e2.png)

**Comment by vnnegt** [comment]
if TikTok made big changes to their API i doubt anything works. other TikTok APIs are broken as well. i'm sure @drawrowfly will fix it eventually.

**Comment by asportnoy** [comment]
It looks like drawrowfly is working on a fix. We'll probably see an update to the package soon.

**Comment by fanoftiktok** [comment]
> `https://www.tiktok.com/node/share/user/` needs a parameter added.
> 
> `https://www.tiktok.com/node/share/user/@madi` doesn't work.
> 
> `https://www.tiktok.com/node/share/user/@c?uniqueId=madi` works.

`https://www.tiktok.com/node/share/user/@madi` works on my machine.
`https://www.tiktok.com/node/share/user/@c?uniqueId=madi` does not return data for user `madi`. It returns data for user `c`

**Comment by llacb47** [comment]
@fanoftiktok lol, tiktok changed it back.

**Comment by fanoftiktok** [comment]
@llacb47 maybe the Friday fix didn't work in production and they had to do a rollback 🚮

**Comment by asportnoy** [comment]
To be safe, you could do https://www.tiktok.com/node/share/user/@madi?uniqueId=madi. That should work regardless.

**Comment by tnoetzel** [comment]
@drawrowfly - getVideoMeta and getMusicInfo are also broken due to the same issue.

**Comment by drawrowfly** [comment]
You can update scraper to the latest version @1.3.6 and it will work as expected. We are strong as a team :) Thank You

**Comment by lu3do** [comment]
You're a boss! 💪
I'm gonna buy you some coffee now. 
I hope that everyone else here that's using this scaper do too.

**Comment by digvijay1331** [comment]
Me too how to solve?

**Comment by dcts** [comment]
If someone is looking if this endpoint still works, it's not. The profile data is now extracted solely through HTML. 

Herees a snippet in case someone wants to only use this method without the whole repo. Or see the code yourself here:
```js
const axios = require("axios");
const config = {
  headers: {
    // or use any other user Agend string => https://deviceatlas.com/blog/list-of-user-agent-strings
    "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36", 
  }
}
const response = await axios.get(
const breakResponse = response.split(/<script id="__NEXT_DATA__" type="application\/json" nonce="[\w-]+" crossorigin="anonymous">/)[1].split(`</script>`)[0];
if (breakResponse) {
  const userMetadata: WebHtmlUserMetadata = JSON.parse(breakResponse);
  return userMetadata.props.pageProps.userInfo;

```

**Comment by codertapsu** [comment]
> `https://www.tiktok.com/node/share/user/` needs a parameter added.
> 
> `https://www.tiktok.com/node/share/user/@madi` doesn't work.
> 
> `https://www.tiktok.com/node/share/user/@c?uniqueId=madi` works.

I am facing 403 error, is there any solution?
