### ISSUE TITLE
Collector is empty when using module. Fine with cli

### ISSUE THREAD

**Issue by andycloke** [drawrowfly/tiktok-scraper#33]
When using the module example, the collector returns an empty array.
Module not working:
```
(async () => {
    try {
        const posts = await TikTokScraper.user({ USER_ID: SOME_USER_ID_STRING }, { number: 20, by_user_id: true });
        console.log(posts); // { collector: [] }
    } catch (error) {
        console.log(error);
    }
})();
```

CLI works:
```
tiktok-scraper user lebeats_211
```

Any idea what could be causing the difference?

**Comment by drawrowfly** [comment]
My bad

Bad example in the readme

(async () => {
    try {
        const posts = await TikTokScraper.user(USER_ID, { number: 100, by_user_id: true });
        console.log(posts);
    } catch (error) {
        console.log(error);
    }
})();

USER_ID - just a string

**Comment by andycloke** [comment]
thanks @drawrowfly
