### ISSUE TITLE
Direct Video URL is invalid

### ISSUE THREAD

**Issue by asportnoy** [drawrowfly/tiktok-scraper#333]
**Describe the bug**
The direct video URL is not giving a valid response

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**

1. use the `getVideoMeta` method to get the direct video URL
2. GET the url with header: `Referer: https://www.tiktok.com/`
3. 403 response

- Used OS: `Ubuntu 18.04 LTS`
- NodeJs Version (node -v) `v12.18.0`
- Scraper Version (tiktok-scraper --version): `package.json` says `^1.3.6` but `tiktok-scraper --version` says `1.3.0`
- CLI or Module: Module
- Used method: `getVideoMeta`
- Used options: proxy
- Do you run the scraper through Proxy, VPN, VPS? Proxy
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles! Yes, public.
- Preferably provide URL to the profile,hashtag,video and etc page: [](https://www.tiktok.com/@charlidamelio/video/6887599575587212550)

**Screenshots**

**Comment by drawrowfly** [comment]
Please use search

**Comment by asportnoy** [comment]
> Please use search

What do you mean?

**Comment by Shmi911** [comment]
> > Please use search
> 
> What do you mean?

https://github.com/drawrowfly/tiktok-scraper/issues/334

**Comment by asportnoy** [comment]
@shmi911 how does that answer my question? #334 was open after my issue.
