### ISSUE TITLE
Video download is not working

### ISSUE THREAD

**Issue by smithd-roses** [drawrowfly/tiktok-scraper#334]
**Describe the bug**

Video download is not working. With and without proxy.

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**

`tiktok-scraper video -d https://www.tiktok.com/@dcepeda21/video/6880575482237078790`

Link to video: 
`https://vm.tiktok.com/ZSQGjgQt/`
`https://www.tiktok.com/@dcepeda21/video/6880575482237078790`

Postman
`/GET `
`https://v16-web.tiktok.com/video/tos/useast2a/tos-useast2a-ve-0068c003/80515f5ed7994300b901ece1d61dfa89/?a=1988&br=2706&bt=1353&cr=0&cs=0&cv=1&dr=0&ds=3&er=&expire=1603674670&l=202010251910210101880612270907E4ED&lr=tiktok_m&mime_type=video_mp4&policy=2&qs=0&rc=ajtncnlzOzlldzMzNTczM0ApZTw1ZTxlZzs3N2g6aDYzZGdrc3JzM2ZyYnJfLS01MTZzc2IyXzNgLzYwNV9fNDUzLTM6Yw%3D%3D&signature=959246b6fa1da8f0c504132737eb36ed&tk=tt_webid_v2&vl=&vr=`
Referer set to:
`Referer: https://www.tiktok.com/ `

Response Headers:
```
Server: AkamaiGHost
Mime-Version: 1.0
Content-Length: 385
Expires: Sun, 25 Oct 2020 19:11:06 GMT
Date: Sun, 25 Oct 2020 19:11:06 GMT
X-Cache: TCP_DENIED from a178-18-231-132.deploy.akamaitechnologies.com (AkamaiGHost/10.1.4-30693377) (-)
Connection: keep-alive
x-tt-trace-tag: id=16;cdn-cache=miss;type=static
server-timing: cdn-cache; desc=MISS, edge; dur=1, origin; dur=0
Content-Type: video/mp4
Access-Control-Allow-Origin: *
```

**Screenshots**
_none_

**Comment by drawrowfly** [comment]
fixed in the latest version

**Comment by Shmi911** [comment]
The nowatermark & --hd function are now both gone also for videos before 21st of July.

I don't know whether it is worth to open an "issue" for that, because it was already discussed several times.
Maybe it's worth mentioning it in the readme that there is no working -w function at the moment.
