### ISSUE TITLE
Throw different errors based on response from TikTok API

### ISSUE THREAD

**Issue by lu3do** [drawrowfly/tiktok-scraper#336]
When retrieving a userProfileInfo() or videoMeta() I want to be able to distinguish if the TikTok servers did respond but the statusCode was not zero, or if the TikTok API didn't respond at all or threw an error.

Because when the statusCode is not zero, the API call was successful so the user or video is either private, hidden or removed.

When the TikTok call returns no response at all or a 404 or 500 error this means the API call failed for some reason and I need to retry the call at a later time because this doesn't mean that the user or video doesn't exist.

**Comment by drawrowfly** [comment]
The reason it was closed #120
