### ISSUE TITLE
commentCount and playCount are swapped in videoItem

### ISSUE THREAD

**Issue by ArjanPronk** [drawrowfly/tiktok-scraper#338]
**Describe the bug**
commentCount and playCount are swapped in videoItem

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- Used OS:  MacOSX
- NodeJs Version (node -v) : v14.5.0
- Scraper Version 1.3.7
- CLI or Module : Module
- Used method : getVideoMeta
- Used options : not relevant
- Do you run the scraper through Proxy, VPN, VPS? Yes
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles! Yes
- Preferably provide URL to the profile,hashtag,video and etc page : any

**Screenshots**

See https://github.com/drawrowfly/tiktok-scraper/pull/337

**Comment by drawrowfly** [comment]
Thanks!)
