### ISSUE TITLE
full list of the followers

### ISSUE THREAD

**Issue by Rawand-f** [drawrowfly/tiktok-scraper#339]
your work is so amazing and it gets the most needed details
but I just wondering is it possible to have a function that gets the full list of followers of the user? if so, it would be so awesome.

**Comment by SethuSenthil** [comment]
That would be pretty hard, especially on TikTok (at least that's what I think). On a hyper-social media platform like TikTok where it's normal for users to have hundreds of thousands of followers, it will take hella requests to TikToks servers, you will probably IP banned before you can even scrape a fraction of your followers.

**Comment by Rawand-f** [comment]
> That would be pretty hard, especially on TikTok (at least that's what I think). On a hyper-social media platform like TikTok where it's normal for users to have hundreds of thousands of followers, it will take hella requests to TikToks servers, you will probably IP banned before you can even scrape a fraction of your followers.

yeah, I totally understand, thank you

**Comment by drawrowfly** [comment]
Not possible with the web api(the one that is used by this app)
