### ISSUE TITLE
Skip downloads when file exists

### ISSUE THREAD

**Issue by tarkov2213** [drawrowfly/tiktok-scraper#341]
Please add the option to skip downloads if file is already present.

The history files are sometimes unreliable and note down videos as downloaded which were never downloaded.
It would be better to just not use them at all and **have the script not re-download already downloaded files**...

**Comment by drawrowfly** [comment]
#120 this functionality will be improved in the future  updates

**Comment by kryztoval** [comment]
I added this to the binary, as soon as I find out how to work the code and get it to compile I will make a pull request.

**Comment by nvmnghia** [comment]
thiss one please.
