### ISSUE TITLE
tiktok videos downloading with the watermark after using -w command

### ISSUE THREAD

**Issue by morningstar-69** [drawrowfly/tiktok-scraper#342]
**Describe the bug**
i have used the scraper before and it worked fine but now the watermark is not being removed 

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- windows 10 professional
- NodeJs Version  v14.4.0
- Scraper Version  1.4.0
- CLI or Module
- Used method  -w
- Used options  -w
- Do you run the scraper through VPN? i use VPN
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles!  YES I DID CHECK
- Preferably provide URL to the profile,hashtag,video and etc page    almost all the pages i tried same result

![Screenshot (48)](https://user-images.githubusercontent.com/58930759/97785731-d7a31680-1bcc-11eb-91bb-d791e07fa27d.png)

**Screenshots**

**Comment by drawrowfly** [comment]
https://github.com/drawrowfly/tiktok-scraper#important-notes
