### ISSUE TITLE
Video downloading not working

### ISSUE THREAD

**Issue by MoosMas** [drawrowfly/tiktok-scraper#343]
**Describe the bug**
Downloading video's is not working. When entering the command and hitting Enter, it displays the animation but quickly disappears.

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- Windows 10
- NodeJs v12.18.3
- Scraper Version 1.3.5
- CMD, PowerShell, Terminus
- tiktok-scraper user {username}
- -d
- Through a VPN, but disabling the VPN or changing countries does not help.
- Tried on multiple profiles, doesn't work. It used to work a while back.

**Comment by drawrowfly** [comment]
Latest version is @1.4.0
