### ISSUE TITLE
Watermark still showing even though using -w

### ISSUE THREAD

**Issue by hasainc** [drawrowfly/tiktok-scraper#346]
I am trying to download a tik tok video without the watermark as described in the documentation using "-w" but still seeing the tik tok watermark. I know its possible to get the video without a watermark as I have seen other online sites that work just would really preffer to use this api instead. 

Is this working for you... what could I be doing wrong?
C:\Users\Admin\AppData\Roaming\npm>tiktok-scraper video https://vm.tiktok.com/ZMJuXNfY5 -w --hd -d

**Comment by drawrowfly** [comment]
https://github.com/drawrowfly/tiktok-scraper#important-notes
