### ISSUE TITLE
.user() function returning empty collector: [] 

### ISSUE THREAD

**Issue by Davey111** [drawrowfly/tiktok-scraper#347]
**Describe the bug**
First of all, I want to thank you for all your work on this project. It's been a huge blessing to me and has been working flawlessly for me up until just recently. I've read through all other bug reports pertaining to this issue but I have a feeling this might be some kind of new verification check or a new query parameter in the request URL.

Empty array response 'collector: []' occurring 95% of the time now from .user().

What's odd to me is that even when using proxies this still occurs from the very beginning. I've also attempted adding more User-Agents to the list but that hasn't helped either. I've tried using the option "by_user_id: true" and searching with the user ID but that hasn't made any difference. I'm also not flooding requests to the server. (maybe 10 .user() requests per hour) 

**To Reproduce**
- Used OS: Ubuntu 18.04.5 LTS
- NodeJs Version (node -v): v12.19.0
- Scraper Version (tiktok-scraper --version): v1.4.0
- CLI or Module: Module
- Used method: TikTokScraper.user("username or user_id", options)
- Used options: {number:30, by_user_id: true} or {number:30}
- Do you run the scraper through Proxy, VPN, VPS?: Problem occurs with & without proxy
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles!: Yes profiles are public
- Preferably provide URL to the profile,hashtag,video and etc page: https://www.tiktok.com/@charlidamelio (or any user profile)

**Response from scraper**
console.log(response); inside the scrapeData(qs, challenge = false) function (from /core/TikTok.js)
`{
  code: '10000',
  from: '',
  type: 'verify',
  version: '',
  region: 'va',
  subtype: 'slide',
  detail: 'RPCD0y*i5i2XVLfHVXL9sB3Gk-yjnFKQwnBjyVp5dkhEsdtQeL3Vw4GKtQjQ-W5aFRG3OYauWvvlSjbbSqgKehbzVgG451HQETgncfYSwuE8v28AS7IgJxD91yBxlfHFWFPOIRDWRCdbSE4P8ULykGz7Xq400Oa*PJWunQOxi-mCPEWwJ9Bhd*J9HFHi9VW-1fDUckgI1gmSSIM3z2t-8fiPyTNhSrswtNAi7f09vO67qgM-nImp3fNU0ik4KIqfP*vt3U83KWI0YY3zdbguZ5qHJ-NkVw7BnQ..',
  verify_event: '',
  fp: 'verify_6ec6eafc2229bf9ad08f5985cfc10d43',
  scene: ''
}`

**Comment by jonas-meng** [comment]
Same here, I use _TikTokScraper.user()_ function, but today found out the returned 'collector:[]'.
IP is irrelevant after I tested on different IPs.

**Comment by weavewillG** [comment]
Looks like it's the same for .music() method.

**Comment by drawrowfly** [comment]
will be updated within few hours

**Comment by drawrowfly** [comment]
Update to the version @1.4.1 

NOTE: i have added list of user-agents that are valid for the TikTok!

I haven't used any 3rd party module that are generating random user-agents as some of them are invalid for tiktok

**Comment by jonas-meng** [comment]
> Update to the version @1.4.1
> 
> NOTE: i have added list of user-agents that are valid for the TikTok!
> 
> I haven't used any 3rd party module that are generating random user-agents as some of them are invalid for tiktok

Sorry to reply here, but after I tested with 1.4.1, indeed posts are coming back.
But getVideoMeta now is not working somehow

**Comment by Davey111** [comment]
> > Update to the version @1.4.1
> > NOTE: i have added list of user-agents that are valid for the TikTok!
> > I haven't used any 3rd party module that are generating random user-agents as some of them are invalid for tiktok
> 
> Sorry to reply here, but after I tested with 1.4.1, indeed posts are coming back.
> But getVideoMeta now is not working somehow

You will probably need to open a new ticket as this one has been closed.
