### ISSUE TITLE
How resume

### ISSUE THREAD

**Issue by mrtbb10** [drawrowfly/tiktok-scraper#348]
**Describe the bug**
Sorry I'm confuse using tiktok-scraper, I don't understand coding.
Sometime download stop randomly, not download all user video, what I read in issue section it is because rate limit, but I not found how resume download, by mean skip already downloaded video then download the rest. I try re-run code/process, but it download same video. 

Is there a way to resume download?

Btw, I dont know why, I cannot use much option (like filepath). It make tiktok-scraper not download anything, or download a video but cannot save to device (undefined).
Just for a simple command like "user USERNAME", I must repeat it several time so tiktok-scraper download the video. 

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- Used OS = Android
- NodeJs Version (node -v) = v14.14.0
- Scraper Version (tiktok-scraper --version) = 1.4.0
- CLI or Module = CLI
- Used method = user
- Used options = -d -n 0 -a 1
- Do you run the scraper through Proxy, VPN, VPS? = no
- Preferably provide URL to the profile,hashtag,video and etc page = happen to all profile I try

**Comment by drawrowfly** [comment]
Currently there is no way. 

With the latest version  @1.4.2 you shouldn't have any issues
