### ISSUE TITLE
How to Download when using Modules

### ISSUE THREAD

**Issue by merqwury** [drawrowfly/tiktok-scraper#349]
I was wondering if there's a way I can download a video based on either the metadata, or video url, via a function provided as a module?

I thought the video(input, options) found in Entry.js (https://github.com/drawrowfly/tiktok-scraper/blob/master/src/entry.ts#L190) would do the trick, but I get "Can't extract metadata from the video"

**Comment by asportnoy** [comment]
https://github.com/drawrowfly/tiktok-scraper#download-video

**Comment by drawrowfly** [comment]
Should work well in the latest version @1.4.2
