### ISSUE TITLE
Download latest videos from music ID 

### ISSUE THREAD

**Issue by PQCrypto** [drawrowfly/tiktok-scraper#351]
**Is your feature request related to a problem? Please describe.**
It would be convenient if we can download latest 'n' videos(sorted by date). Currently we can only download most popular 'n' videos(sorted by likes)

**Describe the solution you'd like**
Introduce a new command line argument which along with -n would download latest posted videos from music ID. Alternatively allow specifying negative numbers in -n argument which would download

**Comment by drawrowfly** [comment]
If you know a way to extract latest posted videos through the API, then please mention this information here. As of now  we can extract data from the api as it is
