### ISSUE TITLE
Creates directory but no videos download

### ISSUE THREAD

**Issue by gj622** [drawrowfly/tiktok-scraper#352]
Used the following command:

tiktok-scraper user @gordonramsayofficial -d -n100

Created the directory '@gordonramsayofficial'.

Briefly see TikTok Scraper Started, but that's all.

**To Reproduce**
- Used OS - Win 10
- NodeJs Version (node -v), 14.15.0
- Scraper Version (tiktok-scraper --version)   1.4.1
- CLI or Module   CLI
- Used method
- Used options
- Do you run the scraper through Proxy, VPN, VPS?  None
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles!  It is public
- Preferably provide URL to the profile,hashtag,video and etc page - @gordonramsayofficial

**Comment by drawrowfly** [comment]
Should work well in the latest version @1.4.2
