### ISSUE TITLE
All requests stop working randomly

### ISSUE THREAD

**Issue by asportnoy** [drawrowfly/tiktok-scraper#353]
**Describe the bug**
All methods through TikTok Scraper will randomly start failing. This often happens when I start my node.js process, but sometimes just happens randomly without any noticeable pattern.

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- Ubuntu 20.04.1
- NodeJS v12.18.0
- Scraper Version 1.4.1
- Module
- All Methods
- No options 
- Proxy is used, its dashboard  isn't reporting errors.
- Profile is public
- Happens to all users

**Screenshots**
N/A

**Comment by petertenhoor** [comment]
Same story here. The same request works locally but not on my live server.

TikTok seems to be able to recognise and block requests (through a proxy) fired by tiktok-scraper.

Perhaps we could learn from the Python community to make the scraper more stable: https://github.com/davidteather/TikTok-Api/blob/347e60a81055f620fa8245c5197b75c5ae0e8318/TikTokApi/tiktok.py#L81

They use a lot of headers and query parameters and sign the request with a finger print (verifyFp).

**Comment by drawrowfly** [comment]
verifyFp is not important value

The issue is that some user-agents are invalid. I will push update shortly

**Comment by petertenhoor** [comment]
Awesome 😄 

May I suggest using something like this for random user agents?

```
import UserAgent from "user-agents"

const randomUserAgent = new UserAgent()
```

**Comment by drawrowfly** [comment]
I need to start writing release notes :)
https://github.com/drawrowfly/tiktok-scraper/issues/347#issuecomment-723319382

3rd party plugins do provide invalid user-agents some times

**Comment by razzy777** [comment]
It seems to be important to change the user-agents with every request (e.g. when looping through an array). This way there won't be the problem when using a blocked user-agent. My quick-fix was to just randomly pick the user-agent inside the method and not defining it globally.

**Comment by drawrowfly** [comment]
Should work well in the latest version @1.4.2
