### ISSUE TITLE
Cannot download videos

### ISSUE THREAD

**Issue by zyadomer999** [drawrowfly/tiktok-scraper#355]
Hello

When I try to download a video from TikTok through the direct link returned by getVideoMeta function, I always get this error and it is same for all other videos.
<img width="861" alt="Screen Shot 2020-11-10 at 8 19 54 PM" src="https://user-images.githubusercontent.com/66646536/98708809-a1b31e80-2392-11eb-93e7-629048c22fc0.png">

**Comment by drawrowfly** [comment]
Documentation is a perfect place to find answers

**Comment by zyadomer999** [comment]
Please help me, I tried my best and went through the documentation but could not get it solved and that is why  I asked.

Please

**Comment by drawrowfly** [comment]
```javascript        
        const videoMeta = await getVideoMeta('https://www.tiktok.com/@tiktok/video/6889096755028233478');

        const magic = await ANY_HTTP_REQUEST_LIBRARY({
            uri: videoMeta.collector[0].videoUrl,
            headers: videoMeta.headers,
        });
        console.log(magic); // <--------------- RAW VIDEO
```

**Comment by mukkaramwaheed** [comment]
I also got the same issue @zyadomer999

**Comment by Glutch** [comment]
@drawrowfly  i got quite confused by this, why do you set filepath, filename & download: true in options if i handle the downloading manually with for example node-fetch?

great package btw, big thank you

**Comment by drawrowfly** [comment]
@Glutch  no idea what are you talking about

If you are using it as a package then download by default is false and other related params
