### ISSUE TITLE
[Feature Request] Cookie usage in terminal

### ISSUE THREAD

**Issue by normanlol** [drawrowfly/tiktok-scraper#357]
**Is your feature request related to a problem? Please describe.**
I wanna be able to download private accounts in the terminal, to back up people's accounts. Is there a way to use cookies from the browser in the terminal, along with the UA.

**Describe the solution you'd like**
Maybe something like a ``--user-agent`` & ``--cookies`` option in the CLI?

I'm not sure if there is an option already and I'm just dumb.

**Comment by normanlol** [comment]
Got added recent with session IDs.

**Comment by MrJmpl3** [comment]
> Got added recent with session IDs.

I tried to download private profile but I had 0 videos.

**Comment by normanlol** [comment]
> 
> 
> > Got added recent with session IDs.
> 
> I tried to download private profile but I had 0 videos.

yeah just realized this too, reopening

**Comment by drawrowfly** [comment]
You can download them if you will use a session from a profile that has access to view the content of a private profile!

**Comment by normanlol** [comment]
> You can download them if you will use a session from a profile that has access to view the content of a private profile!

I have done this with an account that has content I have access to, still does nothing :/
