### ISSUE TITLE
Download timeout

### ISSUE THREAD

**Issue by azbotboyz** [drawrowfly/tiktok-scraper#359]
**Is your feature request related to a problem? Please describe.**
When using rolate proxy to scrape and download it usually get stuck because of IP change from the proxy side.
**Describe the solution you'd like**
Add time out for each download thread

Sorry for my bad English :)

**Comment by azbotboyz** [comment]
maybe the problem comes from by machine. tested on a different machine and the problem didn't happen

**Comment by azbotboyz** [comment]
problems still happen

**Comment by drawrowfly** [comment]
There is already options that is used to set timeout between requests. Please read documentation
