### ISSUE TITLE
getMusicInfo documentation is outdated

### ISSUE THREAD

**Issue by tnoetzel** [drawrowfly/tiktok-scraper#360]
**Describe the bug**
The getMusicInfo documentation is outdated. The data object returned is different.

FWIW, it would be extremely helpful if future updates didn't always change the data objects in question; best practice for scraper tools is to add data while keeping any existing fields the same, that way everybody who uses your library as a dependency doesn't have to change their code for every minor update.

## If fields below will be empty then issue will be Ignored and Closed
**To Reproduce**
- Used OS: OSX 10.15.7
- NodeJs Version (node -v): 15.0.1
- Scraper Version (tiktok-scraper --version) 1.4.2
- CLI or Module: Node
- Used method: getMusicInfo
- Used options: N/A
- Do you run the scraper through Proxy, VPN, VPS?: N/A

**Comment by drawrowfly** [comment]
Can't disagree!

Everything else should be the same, at least i have tried to keep it the same.

Will update the docs a bit later

**Comment by tnoetzel** [comment]
Appreciate the response! I will not, however, that the objects returned are pretty different... field names have changed, most of the data is now nested in an accumulator, etc.

**Comment by drawrowfly** [comment]
You will not what?) 

The current output will stay as it is

**Comment by tnoetzel** [comment]
*note

If it's stable from now forward, that's awesome!

**Comment by drawrowfly** [comment]
oh)

Yup i will be stable
