### ISSUE TITLE
getVideoMeta does not workNot

### ISSUE THREAD

**Issue by bumsun** [drawrowfly/tiktok-scraper#361]
Code like this

```
const options =  {
    headers : {
        'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.80 Safari/537.36',
        Referer: 'https://www.tiktok.com/',
        Cookie: 'tt_webid_v2=689854141086886123'
    }
}
var videoMeta = await TikTokScraper.getVideoMeta(photo_url, options);
```
Always such a error with proxy and without
`error = Can't extract metadata from the video: https://www.tiktok.com/@mountainheads/video/6814153907695062278`

Ubuntu 18
tiktok-scraper 1.4.2
NodeJs v12.16.1

**Comment by drawrowfly** [comment]
Can't reproduce, works fine from mine side

My guess is that it is IP related

**Comment by bumsun** [comment]
Thank you, yes it was a bad ip and proxy
