### ISSUE TITLE
Custom history path for batch command

### ISSUE THREAD

**Issue by bodyhopper** [drawrowfly/tiktok-scraper#362]
Is a custom history path available when using batch command or is it only for single user downloads?

I am using the following command but the history is still being saved in /tmp (which is deleted on shutdown)
> tiktok-scraper from-file users 10 -d -f -s -hd all --historypath history

**Comment by ItsABlackScreen** [comment]
It is available for batch downloads. Absolute path in quotes should do it.

**Comment by bodyhopper** [comment]
> tiktok-scraper from-file users 10 -d -f -s -hd all --historypath "/home/{user}/history"

Still didn't save. I tried without the quotes as well

**Comment by ItsABlackScreen** [comment]
Does the path exist on the system, cause i have had problems where it doesn't create the folder but just fails silently.

**Comment by drawrowfly** [comment]
You should mention more details(OS, version and etc) before creating issue

**Comment by drawrowfly** [comment]
if you store path value in **user** param then pass is as **$user** instead **{user}**
tiktok-scraper from-file users 10 -d -f -s -hd all --historypath "/home/$user/history"
