### ISSUE TITLE
getUserProfileInfo endpoint not working

### ISSUE THREAD

**Issue by dlyakin** [drawrowfly/tiktok-scraper#363]
**Describe the bug**
(async () => {
  try {
    const accaunt = await TikTokScraper.getUserProfileInfo("tiktok", {
      proxy: [
            ... your proxy list
      ],
    });
    console.log(accaunt);
  } catch (error) {
    console.log(error);
  }
})();

After execute get error "Can't find user: karinakross"

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- Centos 8
- NodeJs Version v14.7.0
- Scraper Version 1.4.2
- Module use
- getUserProfileInfo
- Proxy
- I use scraper with proxy
- Profile is public
- https://www.tiktok.com/@karinakross

**Comment by PrasannaBrabourame** [comment]
same issue with `const videoData = await TikTokScraper.user` endpoint too. It is returning 0 in videos list.

**Comment by dlyakin** [comment]
> same issue with `const videoData = await TikTokScraper.user` endpoint too. It is returning 0 in videos list.

For me TikTokScraper.userEvent works well

**Comment by drawrowfly** [comment]
Captcha related issue. Currently i will implement ONLY temp fix
