### ISSUE TITLE
Proxy Recommendations

### ISSUE THREAD

**Issue by tnoetzel** [drawrowfly/tiktok-scraper#364]
Can anyone recommend a proxy service they like?

I've been using Luminati's static residential proxies; they work, but they're pretty expensive.

**Comment by art2cool** [comment]
You can try this like alternative Luminati's https://www.scraperapi.com/ but they are a little bit slow

**Comment by drawrowfly** [comment]
A lot of people being asking me about what proxy services do i use.

This is one of the services that i use https://proxy-store.com/uMaA3kOx
I will appreciate, If you will signup by using my referral link :slight_smile: 

All proxies are with unlimited bandwidth, the price for 10 private IPv4 proxies is ranging between 5$-8$ per month. 

When order select Personal Proxies -> FOR SOCIAL NETWORKS -> Other Social Network(has more GEO) or TikTok

Also always order few to test them out before order more

**Comment by pratikwatwani** [comment]
Does anyone have a free proxy service recommendation?

**Comment by quangtuyendev** [comment]
Hi @tnoetzel!
Can you give me an example about use proxy?

**Comment by quangtuyendev** [comment]
Hi @tnoetzel!
Can you give me an example about use proxy?
This is my approach, now not working.
Did I have a wrong configuration at syntax or proxy?
```
const posts = await TikTokScraper.trend('', {
            number: 10,
            sessionList: ['sid_tt=xxxxxxxxxxx;'],
            proxy: 'socks5://xxx.xxx.xxx.xxx'
        });
```

**Comment by Andrew214-dot** [comment]
Hi,
I created the file for batchdownload and name is tklinks.txt then Where should i place Batch file for that pick links from that batch file by following command ( tiktok-scraper from-file tklinks 5 -d --filepath Desktop)
