### ISSUE TITLE
Custom history path not working with batch 

### ISSUE THREAD

**Issue by bodyhopper** [drawrowfly/tiktok-scraper#365]
**OS:** Ubuntu 20.04
**tiktok-scraper version:** 1.4.2

I am trying to use a custom history path when using batch command since the default saves to /tmp, which is deleted on shutdown

I'm trying the following command:  
> tiktok-scraper from-file users 10 -d -f -s -hd all --historypath "/home/myusername/history"

where "/home/myusername/history" already exists as a blank file

**Comment by drawrowfly** [comment]
Can't replicate the issue 

Works fine from mine side 

Also always include example code and etc
