### ISSUE TITLE
.user(id, options) seems not work now

### ISSUE THREAD

**Issue by arceus-jia** [drawrowfly/tiktok-scraper#366]
I have tried other functions and they all work fine.  Only this function returns an empty array

`
let result = await TikTokScraper.user('qpark',{number:1, proxy: config.luminati.unblocker_proxy  });
console.log(result)
`

`
{
  headers: {
    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.80 Safari/537.36',
    Referer: 'https://www.tiktok.com/',
    Cookie: 'tt_webid_v2=689898921745007481'
  },
  collector: []
}
`

**Comment by aldrin431** [comment]
I updated the latest version of package but still persist the problem.
now is working for you?

**Comment by arceus-jia** [comment]
> I updated the latest version of package but still persist the problem.
> now is working for you?

Thanks for your reply.  
I've already upgraded to the latest version yesterday.

And today I found that it doesn't work without proxy either.
`
tiktok-scraper user qpark -n 1 -t csv
`
while 
`
tiktok-scraper hashtag qpark -n 1 -t csv
`
works fine

**Comment by arceus-jia** [comment]
@aldrin431 
I found this verifyFp works  for me "verify_khpndkhf_ERut2lgl_kAb1_4TM1_9Zp3_4bG4cYoT86xY".
Can you add this parameter that we can pass by ourselves? To prevent tiktok change the verification code
