### ISSUE TITLE
output is nothing when I use tiktok-scraper trend -n 50 -d -z -t csv

### ISSUE THREAD

**Issue by daixiangzi** [drawrowfly/tiktok-scraper#369]
but it have files when I use 'tiktok-scraper video https://www.tiktok.com/@tiktok/video/6807491984882765062 --hd -t json'

**Comment by daixiangzi** [comment]
I doubt I can use  tiktok-scraper trend -n 50 -d -z -t csv at 1.2.5 version

**Comment by tnoetzel** [comment]
You should update... you're dozens of versions behind.

**Comment by daixiangzi** [comment]
> You should update... you're dozens of versions behind.

I have updated, but still not work
