### ISSUE TITLE
Search by keyword

### ISSUE THREAD

**Issue by youngvo** [drawrowfly/tiktok-scraper#37]
Hi @drawrowfly 

Currently, your node module supports for searching by hashtag, user, trend, music. Do you know a way to search by keyword? Are you planing to add "search by keyword" to this module?

Best,
-Young

**Comment by drawrowfly** [comment]
Hi,

"search by keyword" what exactly, and where can i see this input field in the web version of the tiktok ?

If you are referring to the mobile version then this is a different story for now

**Comment by youngvo** [comment]
@drawrowfly Yeah, "search by keyword", something like the mobile app is doing? Do you have any clues about how it is working on mobile app?

**Comment by drawrowfly** [comment]
i do know how it works from the mobile side. The only problem right now is to generate correct signature that is required to send valid request

**Comment by drawrowfly** [comment]
#21
