### ISSUE TITLE
.user always returning empty list

### ISSUE THREAD

**Issue by ciccio-87** [drawrowfly/tiktok-scraper#370]
**Describe the bug**
.user() seems to be always returning an empty list (regardless of proxy settings, verifyFp etc.),
have there been some changes in the data format? 

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- Used OS
Linux

- NodeJs Version (node -v)
v12.19.0

- Scraper Version (tiktok-scraper --version)
1.4.3

- CLI or Module
module, cli

- Used method
.user

- Used options
None

- Do you run the scraper through Proxy, VPN, VPS?
Both proxy and direct connect

- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles!
Yes, all tested profiles were public

- Preferably provide URL to the profile,hashtag,video and etc page
https://www.tiktok.com/@tiktok

**Screenshots**
Not applicable

**Comment by drawrowfly** [comment]
I have removed hardcoded verifyFp values,  if you will run the scraper with good proxy or home IP it should work fine

Later i will push another updated related to the captcha solving

Latest version @1.4.4

**Comment by PrasannaBrabourame** [comment]
@drawrowfly Latest version @1.4.4 is published?

**Comment by drawrowfly** [comment]
@PrasannaBrabourame i'm really curious before asking this questions, did thought about checking it yourself or is it that hard?

**Comment by PrasannaBrabourame** [comment]
@drawrowfly i checked it is not published..

**Comment by drawrowfly** [comment]
@PrasannaBrabourame ...
