### ISSUE TITLE
Broken Broken = Captcha

### ISSUE THREAD

**Issue by drawrowfly** [drawrowfly/tiktok-scraper#371]
Hello Everyone,

There are captcha related issues with **user**, **getUserProfileInfo** and i think few more

For now you can update to the version @1.4.4 and if you will be using clean IP/PROXY the app will work fine, otherwise you won't be able to get any data

Soon i will have more time and will implement captcha solver

Do not create any unnecessary issue threads and stay positive

Best,

Andrew

**Comment by jasongrishkoff** [comment]
Here's a temporary workaround (if you have a video ID). You can still get some useful user info as follows:
```
        (async () => {
            try {
                const videoMeta = await TikTokScraper.getVideoMeta('https://www.tiktok.com/@tiktok/video/' + id)
                var userMeta = videoMeta.collector[0].authorMeta // contains fans, hearts, avatar, etc.
            } catch (error) {
                console.log(error)
            }
        })()
```

**Comment by PrasannaBrabourame** [comment]
@drawrowfly with paid proxy also returns "0" on the "user" method.

**Comment by drawrowfly** [comment]
@PrasannaBrabourame then proxy is bad

**Comment by razzy777** [comment]
I also faced the block after a few requests and my solution is to initialize the userAgent and cookie in the header after every request instead of setting it once globally. With changing userAgents and cookie I experienced a lot less blocks. 

`export const getUserProfileInfo = async (input: string, options = {} as Options): Promise<UserMetadata> => {

    if (options && typeof options !== 'object') {
        throw new TypeError('Object is expected');
    }

    if (options?.proxyFile) {
        options.proxy = await proxyFromFile(options?.proxyFile);
    }
    INIT_OPTIONS.headers = {
        'User-Agent': CONST.userAgent(),
        Referer: 'https://www.tiktok.com/',
        Cookie: `tt_webid_v2=68${makeid(16)}`,
    }
    const contructor: TikTokConstructor = { ...INIT_OPTIONS, ...options, ...{ type: 'sinsgle_user' as ScrapeType, input } };
    const scraper = new TikTokScraper(contructor);

    const result = await scraper.getUserProfileInfo();
    return result;
};`

**Comment by PrasannaBrabourame** [comment]
@drawrowfly Facing issue only with "User" method "getUserProfileInfo" is working fine without any issues (Both with or without proxy).
