### ISSUE TITLE
Creates empty directory with --filepath . option

### ISSUE THREAD

**Issue by tbm** [drawrowfly/tiktok-scraper#372]
**Describe the bug**

When I run:

```
tiktok-scraper user USER -s -d --filepath .
```

it downloads the files currently in the current directory, but it creates a directoy `USER` which is empty.

**To Reproduce**

- Used OS: Debian 10
- NodeJs Version (node -v): v13.14.0
- Scraper Version (tiktok-scraper --version): 1.4.4
- CLI or Module: CLI
- Used method: ???
- Used options: -s -d --filepath .nov
- Do you run the scraper through Proxy, VPN, VPS?: no
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles!
- Preferably provide URL to the profile,hashtag,video and etc page

**Screenshots**

**Comment by tbm** [comment]
Strange, now I can't reproduce this anymore.  Now `--filepath .` puts the files into `./USER` (which imho is also wrong but a different issue).

**Comment by drawrowfly** [comment]
As of right now this is the expected behavior. 

And PR's are welcomed :)
