### ISSUE TITLE
History for hashtag not being stored

### ISSUE THREAD

**Issue by njscorpion** [drawrowfly/tiktok-scraper#374]
History for hashtag not being stored / saved. However, the scraper is saving the video files. 

Command used : tiktok-scraper -p socks5://127.0.0.1:1040 --noWaterMark hashtag HASHTAG -s -d -n 5

also tried : with --historypath c:\tmp\tiktok.history But  when checking history it's only showing user history.

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- Used OS : Windows 10
- NodeJs Version (node -v)  : 12.14.0
- Scraper Version (tiktok-scraper --version) : 1.4.4
- CLI or Module : CLI
- Used method
- Used options : -P --noWaterMark hashtag -s -d -n
- Do you run the scraper through Proxy, VPN, VPS? : proxy
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles! : yes
- Preferably provide URL to the profile,hashtag,video and etc page : dance 

**Screenshots**

**Comment by drawrowfly** [comment]
Fixed in the latest version
