### ISSUE TITLE
getHashtagInfo Video Count returns "0"

### ISSUE THREAD

**Issue by PapaSnags** [drawrowfly/tiktok-scraper#375]
**Describe the bug**
Sometimes using the getHashtagInfo method it will return stats: { **videoCount: 0**, viewCount: 3200000000 },

**To Reproduce**
- Used OS: **Windows 10**
- NodeJs Version: **v12.3.1**
- Scraper Version: **1.4.4 **
- CLI or Module: **Module**
- Used method: **const hash = await TikTokScraper.getHashtagInfo("hashtag");**
- Used options: **None**
- Do you run the scraper through Proxy, VPN, VPS?: **No**

**Screenshots**
https://i.imgur.com/zNUE81U.png

**Comment by drawrowfly** [comment]
#371

**Comment by thibaultleouay** [comment]
@drawrowfly  not related to proxy but TikTok does not return the video count anymore

**Comment by drawrowfly** [comment]
@thibaultleouay it is related to the IP and captcha

**Comment by thibaultleouay** [comment]
Because if you look at this page https://www.tiktok.com/tag/fyp they don't return any videoCount anymore

**Comment by drawrowfly** [comment]
Thats what scrapper is returning
stats: { videoCount: 750200000, viewCount: 6040500000000 },
And thats what manual request through browser
stats: { videoCount: 0, viewCount: 6040500000000 }

No idea what causing this, but if it will return 0 in the future then this sort of issues are completely non related to the scraper, i can't fix TikTok Api :)

**Comment by thibaultleouay** [comment]
I know that was I meant it's related to the TikTok API :) 

Since the 20 of October, they didn't return any videoCount but the last couple of days they return some data. It's not reliable at all.
