### ISSUE TITLE
Bandwidth for getVideoMeta()

### ISSUE THREAD

**Issue by tnoetzel** [drawrowfly/tiktok-scraper#381]
**Describe the bug**
It seems like the `getVideoMeta()` function is downloading far more than the required data. When running via node, it seems to download 400KB of data on average for a single video, but requests to `https://m.tiktok.com/api/item/detail/` via Chrome only download about 5KB of data.

While not a big deal on a one-off basis, doing this across a few hundred videos on an ongoing basis ads up to multiple GBs per day, making proxy usage expensive (on the order of $100s or $1000s).

Possible to improve performance here by hitting the api endpoint rather than doing a full request of the page?

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- Used OS: OSX or Unix
- NodeJs Version: v15.0.1
- Scraper Version: 1.4.4
- CLI or Module
- Used method: getVideoMeta()
- Used options: N/A
- Do you run the scraper through Proxy, VPN, VPS: N/A - Happens in both cases

**Screenshots**
![node-kb](https://user-images.githubusercontent.com/1002744/100813909-7316e980-340e-11eb-9523-8306825a3d9b.png)

*VS*

![chrome-kb](https://user-images.githubusercontent.com/1002744/100813914-76aa7080-340e-11eb-80c0-2d9a237c641a.png)
￼

**Comment by drawrowfly** [comment]
This api endpoint won't work with short url. With short url we would need to execute extra request to extract video id instead of one

**Comment by tnoetzel** [comment]
Why is using a shortUrl preferably to saving substantial money on data?
