### ISSUE TITLE
archiving private account you have access to when logged in

### ISSUE THREAD

**Issue by hirezz** [drawrowfly/tiktok-scraper#384]
**Is your feature request related to a problem? Please describe.**
Trying to archive a private account of which I am following and have access to when logged in to my person tiktok account

**Describe the solution you'd like**
When running the command on any user marked as private, the downloader does nothing. Is there a way to authenticate as a logged in user using my browser cookies, etc?

**Comment by drawrowfly** [comment]
Set session
