### ISSUE TITLE
Implement www.scraperapi.com

### ISSUE THREAD

**Issue by kostadindraganov** [drawrowfly/tiktok-scraper#385]
Hello ,
Can you implement www.scraperapi.com.
This will be very useful,
Thank you!

**Comment by DankMemeGuy** [comment]
What is that? Just captcha bypass? Proxy?

**Comment by drawrowfly** [comment]
Hello,

People before asked me to add different proxy related services, if i will add them it will create a mess,confusion and won't be that convenient

For now i do not have any plans to add 3rd party services to the package, but later it will be possible,

Thanks
