### ISSUE TITLE
- TikTok Scraper Started

### ISSUE THREAD

**Issue by andersonrobert1313** [drawrowfly/tiktok-scraper#389]
It was working before...but now when i hit any command it is saying undefined.
Can you tell why this happen?

**Comment by andersonrobert1313** [comment]
Hi..
How can I access now?
What's the solution.

**Comment by drawrowfly** [comment]
You question sound like this " I won't to buy the thing , where can I buy the thing?"

**Comment by andersonrobert1313** [comment]
Hi,
I didn't get you!
I can't understand the meaning of "you authored the thread".
Can you please help me.

**Comment by drawrowfly** [comment]
Same here

i have no idea what are you talking about!

**Comment by andersonrobert1313** [comment]
Today i used your package for get videos via username and it was working today.
but suddenly after few hours it is not giving the result.
it's saying undefined via terminal.
