### ISSUE TITLE
Not getting all of certain public user's posts

### ISSUE THREAD

**Issue by spenciefy** [drawrowfly/tiktok-scraper#392]
**Describe the bug**

Appreciate all your great work! I'm having a problem with scraping certain TikTok user's post feed metadata. For a few users (ex. @thebigbradwolf, @marcelllei), I'm not able to get all their posts - some of them are missing. It's strange because for most users, I'm able to get all posts. 

**Example:**

1. For user @thebigbradwolf, `tiktok-scraper userprofile thebigbradwolf` returns 246 videoCount. 
2. But if I try to get all post metadata: `tiktok-scraper user thebigbradwolf -t json`, the resulting JSON only contains 66 posts. 

```
$ tiktok-scraper userprofile thebigbradwolf
{
  user: {
    id: '6744808547165799429',
    shortId: '0',
    uniqueId: 'thebigbradwolf',
    nickname: 'BRAD WOLF',
    avatarLarger: 'https://p16-sign-va.tiktokcdn.com/tos-maliva-avt-0068/a35c15bb9166c7c6580bf73de9985175~c5_1080x1080.jpeg?x-expires=1607889600&x-signature=QBwXNInaB5PN5J9%2FO4CepWOm%2FIk%3D',
    avatarMedium: 'https://p16-sign-va.tiktokcdn.com/tos-maliva-avt-0068/a35c15bb9166c7c6580bf73de9985175~c5_720x720.jpeg?x-expires=1607889600&x-signature=zstxTv5rRpP3Paww1IJjvy18fmg%3D',
    avatarThumb: 'https://p16-sign-va.tiktokcdn.com/tos-maliva-avt-0068/a35c15bb9166c7c6580bf73de9985175~c5_100x100.jpeg?x-expires=1607889600&x-signature=Xyd0lsxQSUIlhEUV4wD2%2BFXNJro%3D',
    signature: '😻🤚\ncreator of THE hurricane remix\nDM FOR BUSINESS\n6k on insta😭',
    createTime: 1570398347,
    verified: false,
    secUid: 'MS4wLjABAAAAohHBZQ_iaCXFWPqyXwJUF_szJYKoG6N4Y0rW7IIyQqnIPxXDKjstRRAMiA0khil3',
    ftc: false,
    relation: 0,
    openFavorite: false,
    bioLink: {
      link: 'https://open.spotify.com/user/7tutj6x24zenf2abo3xe557s5?si=QB1d62B8SfaiHjSBCggJZw',
      risk: 0
    },
    commentSetting: 0,
    duetSetting: 0,
    stitchSetting: 0,
    privateAccount: false,
    secret: false
  },
  stats: {
    followerCount: 397700,
    followingCount: 399,
    heart: 20200000,
    heartCount: 20200000,
    videoCount: 246,
    diggCount: 0
  },
  itemList: []
}
```

I asked about this on the Discord and David Teather reporting seeing a similar problem, where he was only able to scrape 152/246 videos. 

```
I'm able to query 152 videos which may be as many as he has I'm not sure with the following code:
from TikTokApi import TikTokApi
api = TikTokApi(use_test_endpoints=True)

print(len(api.byUsername('thebigbradwolf',gen_new_verifyFp=True, count=300)))

my guess is maybe the code isn't continuing when hasMore is true because the TikToks returned is empty. Sometimes this happens for a variety of reasons like user deleting TikToks from what i can tell.
```

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- Max OS X Catalina
- NodeJs Version: 12.16.3
- Scraper Version: 1.4.4
- CLI or Module
- Used method: user
- Used options: -t 
- Do you run the scraper through Proxy, VPN, VPS?: No
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles!: Yes
- Preferably provide URL to the profile,hashtag,video and etc page: https://www.tiktok.com/@thebigbradwolf

**Screenshots**

**Comment by spenciefy** [comment]
@drawrowfly bump, any ideas? thanks!

**Comment by drawrowfly** [comment]
Some user profiles do return from the user feed api max ~3-5 items(no idea why) at the time, i will update the app soon for such cases

**Comment by nt-jjrubio** [comment]
+1

**Comment by spenciefy** [comment]
Thanks for the 1.4.7 update! I'm finding that pretty much all users with more than 10 videos are only returning 25-40 videos. I'm guessing TikTok changed something so it's harder to get the user feed?

`tiktok-scraper user justmaiko -t json`   --> 46 videos. A previous scrape of him had 1k videos
`tiktok-scraper user addisonre -t json`   --> 28 videos. A previous scrape had 1.3k videos.

**Comment by hirezz** [comment]
Also having this issue. Running version 1.4.7
User has 225 videos but can only scrape 50.

**Comment by nikolamajmunovic** [comment]
same here

**Comment by ColtraneNadler** [comment]
When using the .user() method, I'm no longer getting any posts returned for any user. 
v 1.4.9

```
posts {
  headers: {
    'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4159.179 Safari/537.36',
    referer: 'https://www.tiktok.com/',
    cookie: 'tt_webid_v2=685542347652849299'
  },
  collector: []
}
```

**Comment by drawrowfly** [comment]
Unfortunately this is the way data is being outputted by the tiktok. For now nothing can be done
