### ISSUE TITLE
Getting TikTok Cover Signature

### ISSUE THREAD

**Issue by henry-1987** [drawrowfly/tiktok-scraper#393]
I am a frequent user of this library and I wanted to ask about getting a way to generate the signatures to access TikTok covers images directly.

Each TikTok image has two parameters, x-expires & x-signature.

The x-expires is just a timestamp that is 6 hours from now. What I would like to know is how to generate an x-signature token.

Here's an example:
`https://p16-sign-va.tiktokcdn.com/obj/tos-maliva-p-0068/21cce337905b466eb614d7d621c4e8ff_1607888052?x-expires=1607983200&x-signature=Jilkl9NnQnagLBovhwK3dDw0cyA%3D`

**Comment by luispablo** [comment]
Same here. Is there a way to get a "permalink" for the post covers (at least one of them)?

**Comment by drawrowfly** [comment]
Unfortunately the signature key's are being generated by the tiktok back end side
