### ISSUE TITLE
videotos.mp4

### ISSUE THREAD

**Issue by Tromick** [drawrowfly/tiktok-scraper#395]
Hello,

Please forgive me that i am newbie. 

![image](https://user-images.githubusercontent.com/13919269/102326329-572a5080-3f95-11eb-9b2a-953696fe788e.png)
![image](https://user-images.githubusercontent.com/13919269/102326351-5c879b00-3f95-11eb-98b5-3d265aa7ed1e.png)

Then i am checking the file on NotePad, it says:

![image](https://user-images.githubusercontent.com/13919269/102326485-7de88700-3f95-11eb-9c20-7056472aee4c.png)

What is the error? What should i do? Thank you!

**Comment by drawrowfly** [comment]
https://github.com/drawrowfly/tiktok-scraper#download-video

**Comment by Tromick** [comment]
I have seen it sir but still don't know how to use it. What should i write? How should i start? Where should i look? I am very noob. T_T

**Comment by drawrowfly** [comment]
Read/view coding tutorials
