### ISSUE TITLE
getUserProfileInfo() stopped working

### ISSUE THREAD

**Issue by lu3do** [drawrowfly/tiktok-scraper#396]
**Describe the bug**
Since an hour ago getUserProfileInfo() stopped working, no matter what username you try it always returns "Can't find user"

**To Reproduce**
- Used OS
**Multiple**
- NodeJs Version (node -v)
**v15.0.1**
- Scraper Version
**I tried both 1.4.4 and 1.4.5**
- CLI or Module
**Module**
- Used method
**getUserProfileInfo('addisonre')**
- Used options
- Do you run the scraper through Proxy, VPN, VPS? 
**VPS**

**Comment by kh71** [comment]
yes me too i try with still error

**Comment by drawrowfly** [comment]
Just need to add one extra query to all requests, will update it shortly

**Comment by drawrowfly** [comment]
Update to @1.4.6
