### ISSUE TITLE
signature is invalid after 2020-12-17,can help fix it? thx~!

### ISSUE THREAD

**Issue by iamhujiebin** [drawrowfly/tiktok-scraper#398]
**Describe the bug**

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- Used OS
- NodeJs Version (node -v)
- Scraper Version (tiktok-scraper --version)
- CLI or Module
- Used method
- Used options
- Do you run the scraper through Proxy, VPN, VPS?
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles!
- Preferably provide URL to the profile,hashtag,video and etc page

**Screenshots**

**Comment by xiaomingtan** [comment]
i have same problem

**Comment by drawrowfly** [comment]
**If fields below will be empty then issue will be Ignored and Closed**
