### ISSUE TITLE
getUserProfileInfo is currently not working

### ISSUE THREAD

**Issue by petertenhoor** [drawrowfly/tiktok-scraper#399]
**Describe the bug**

Since a few hours method getUserProfileInfo() stopped working, regardless of which username you use. My proxies are working.

**TikTok gives the following response:**

```
{statusCode: 0,body: {userData: {},statusCode: -1,shareUser: {}}} 
```

**The request is fired using the following options:**

```
{
  uri: 'https://m.tiktok.com/node/share/user/@charlidamelio?uniqueId=charlidamelio&verifyFp=',
  method: 'GET',
  qs: {
    user_agent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4256.143 Safari/537.36'
  },
  headers: {
    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4256.143 Safari/537.36',
    Referer: 'https://www.tiktok.com/',
    Cookie: 'tt_webid_v2=685496898075912582'
  },
  json: true,
  resolveWithFullResponse: true,
  proxy: 'xxxxx',
  timeout: 10000
}
```

**To Reproduce**
- Used OS
   - OSX and Ubuntu 20
- NodeJs Version (node -v)
   - 15.0.1
- Scraper Version (tiktok-scraper --version)
   - 1.4.7
- CLI or Module
   - Module
- Used method
   - getUserProfileInfo
- Used options
   - See option object mentioned above
- Do you run the scraper through Proxy, VPN, VPS?
   - Through proxies
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles!
   - I checked, they are public.
   
Is the verifyFp parameter meant to be empty? I just compared the request with the one TikTok does and they add a lot of headers.

Thanks in advance!

**Comment by lu3do** [comment]
yep same here.

**Comment by avivhazor** [comment]
same

**Comment by fabnoe** [comment]
There seems to be a problem with most of the methods? 
const posts = await TikTokScraper.trend('', { number: 100 });

Also return an empty collection.

**Comment by drawrowfly** [comment]
They keep on checking more and more params every day. I will update it shortly

**Comment by uponatime2019** [comment]
Right now problem happen, it can't crawl any videos

**Comment by luispablo** [comment]
I cannot get neither profile nor posts for any account since yesterday.

Do you need help with this?

**Comment by drawrowfly** [comment]
I have fixed most of the methods already, few to go , but probably i will push it as it is, shortly

**Comment by Nicotroll** [comment]
> 
> 
> I have fixed most of the methods already, few to go , but probably i will push it as it is, shortly

Thanks for your hard work, we appreciate it

**Comment by Androz2091** [comment]
All right, thank you! ❤️

**Comment by alexgarciab** [comment]
Same problem here - Following

**Comment by DanielZhu03** [comment]
Yep same problem

**Comment by alexgarciab** [comment]
If it could be useful, on the mobile app, they use this endpoint to retrieve user data when accessing a profile:

https://apiX-core-c-alisg.tiktokv.com

Where X is a number, like 16, 19, 21 - so for example:

https://api19-core-c-alisg.tiktokv.com

What I am not sure is how do they send the request

**Comment by drawrowfly** [comment]
@alexgarciab Just to be clear i'm aware on how the mobile API is working and signatures generated but i don't have any plans to implement it in this app, as it can get patched faster then web api stuff

**Comment by uponatime2019** [comment]
It seem tiktok change the code again. So sad

**Comment by drawrowfly** [comment]
For now the best solution that i have:
1. Update to version @1.4.8
2. **In order to scraper user/hashtag/music/trending feeds** you need to set your own session cookie value. How to do it you can read here https://github.com/drawrowfly/tiktok-scraper#get-set-session
3. In the **CLI** you can do it by setting the option **--session: BLAH BLAH**
4. In the module you can do it by setting the option value:: **sessionList:["BLAH BLAH"]**
5. **Other methods do not require to set the session**

The next steps will be to clean up/organize the documentation and add more methods

**Comment by 433452523523532** [comment]
@drawrowfly const posts = await TikTokScraper.user('USERNAME', {  ??

**Comment by drawrowfly** [comment]
@433452523523532 https://github.com/drawrowfly/tiktok-scraper#promise

**Comment by alexgarciab** [comment]
@drawrowfly are there any restrictions you have seen on requests made with the logged user cookie?
For example, after 200 requests in a time span of 5 minutes, the user search endpoint does not return anything or 429.

**Comment by drawrowfly** [comment]
@alexgarciab no idea. You can set multiple sessions

**Comment by Nicotroll** [comment]
This works great with the session, thank you so much for the hard work. 
Do you know if the session expires after a number of days/months ?

**Comment by drawrowfly** [comment]
@Nicotroll i guess 1 month +-

**Comment by Androz2091** [comment]
Do you think that it could be possible to make a simple script with Puppeteer to generate a cookie?

**Comment by drawrowfly** [comment]
@Androz2091 required cookies are generated Only when you login in to your account! And, i don't have plans to use any headless browsers in this module

**Comment by burneracct** [comment]
@drawrowfly Andrew, I aprpeciate how quickly you updated the script and also for maintaining this

FYI for everyone experiencing this issue, follow his instruction - you need to use the session token that TikTok provides. May I suggest that you create your account on an actual mobile device, and upload a dummy video. This flags TikTok's system to think that your account is legitimate.

If you create an account via the web and the email/phone is unverified, the session token will not work. TikTok, like Instagram, is locking their paltform down more and more everyday

**Comment by dencorg** [comment]
Hello, first of all I would like to thank you for your efforts on tiktok-scraper.
I updated to version 1.4.8 and used the sid_tt cookie value in sessionList as described. Yesterday it was working as intended. However today both .user function (with sessionList enabled) and .getUserProfileInfo function stopped working again.
Has anyone encountered the same issue?

**Comment by Nicotroll** [comment]
> 
> 
> Hello, first of all I would like to thank you for your efforts on tiktok-scraper.
> I updated to version 1.4.8 and used the sid_tt cookie value in sessionList as described. Yesterday it was working as intended. However today both .user function (with sessionList enabled) and .getUserProfileInfo function stopped working again.
> Has anyone encountered the same issue?

Same issue, the problem has come back

**Comment by vnnegt** [comment]
> Hello, first of all I would like to thank you for your efforts on tiktok-scraper.
> I updated to version 1.4.8 and used the sid_tt cookie value in sessionList as described. Yesterday it was working as intended. However today both .user function (with sessionList enabled) and .getUserProfileInfo function stopped working again.
> Has anyone encountered the same issue?

yea. i scraped 5 videos from 1 profile, and then it stopped working.

**Comment by burneracct** [comment]
I told you niggas man

Make sure the token you're using is from a legit, verified account
registered using the mobile app. Upload a dummy video to further
bulletproof it.

Check your profile and see if a lock is best to your name. If it it, your
account is locked and the token generated won't work with the scraper.

**Comment by Nicotroll** [comment]
> I told you niggas man Make sure the token you're using is from a legit, verified account registered using the mobile app. Upload a dummy video to further bulletproof it. Check your profile and see if a lock is best to your name. If it it, your account is locked and the token generated won't work with the scraper.
> […](#)
First of all.. wtf.
Secondly, even methods not requiring a token are not working anymore.. and for the methods that do, I’m using a verified account that isn’t locked so that’s not the issue

**Comment by lu3do** [comment]
Same as @Nicotroll

**Comment by asportnoy** [comment]
@drawrowfly has acknowledged the issue on the [discord server](https://discord.gg/7SZaUs4). 
![image](https://user-images.githubusercontent.com/14863373/102727344-d055da80-42ea-11eb-93b7-dd1bf5f15074.png

**Comment by luispablo** [comment]
Can we reopen this issue to be notified of its progress... @drawrowfly ?

**Comment by luispablo** [comment]
> For now the best solution that i have:
> 
>     1. Update to version @1.4.8
> 
>     2. **In order to scraper user/hashtag/music/trending feeds** you need to set your own session cookie value. About how to do that, you can read here: https://github.com/drawrowfly/tiktok-scraper#get-set-session
> 
>     3. In the **CLI** you can do it by setting the option **--session: BLAH BLAH**
> 
>     4. In the module you can do it by setting the option value:: **sessionList:["BLAH BLAH"]**
> 
>     5. **Other methods do not require to set the session**
> 
> 
> The next steps will be to clean up/organize the documentation and add more methods

With a logged in session, won't it be easy for TikTok to block / ban us if you request too many items (when we're scraping data) @drawrowfly ?

**Comment by alexgarciab** [comment]
Same issue here - Seems like TikTok is improving its security

**Comment by fabnoe** [comment]
Damn. It worked for a couple for hours.

- TikTokScraper.hashtag still working
- TikTokScraper.user **not** working

**Comment by vnnegt** [comment]
> Same issue here - Seems like TikTok is improving its security

seems like TikTok has an entire team dedicated to stopping `tiktok-scraper` haha

**Comment by asportnoy** [comment]
After uploading to 1.4.9, `getVideoMeta` and `user` are both not working.

**Comment by burneracct** [comment]
Yes he is aware of that fact. This is a cat and mouse game that started
around 1.4.8. TikTok will serve a proprietary captcha that requires mouse
input (drag x -> b). Even after solving this captcha in the browser, using
the token generated still won't work.

I'm doing other software things right now but if the author can ramp me up,
I would be more than willing to help.

I think TikTok is storing the user agent or doing some form of
fingerprinting with the token and browser. I dont know if the script is
already implementing this, but perhaps spoofing as the browser that
generated a token would be the best bet.


I do not know python

**Comment by burneracct** [comment]
In the Taco Bell Drive through right now and will be back at my workstation
in a bit

You guys mind sharing the users/content you're ripping? Personally I'm only
here for @_selams

**Comment by Rydgel** [comment]
Even with a session the pagination fails and can only get the first 3 or 4 media.
I wonder if I got shadowbanned? I have the same behavior when using my account on Chrome.
