### ISSUE TITLE
Getting error 'RequestError: Error: ESOCKETTIMEDOUT'

### ISSUE THREAD

**Issue by VincentVinTin** [drawrowfly/tiktok-scraper#40]
**Code**
const TikTokScraper = require('tiktok-scraper');
 
let posts = TikTokScraper.hashtag("singing", { event: true, number: 10});
 
posts.on('data', (json) => {
  console.log(json)
})
 
posts.on('done', () => {
  console.log("done")
})

posts.on('error', (error) => {
  console.log(error)
})

posts.scrape();

**Version:**
"tiktok-scraper": "^1.0.14

**Error:**
Error: RequestError: Error: ESOCKETTIMEDOUT
    at TikTokScraper.scrapeData (*/node_modules/tiktok-scraper/lib/index.js:616:19)
done

**Comment by drawrowfly** [comment]
"RequestError: Error: ESOCKETTIMEDOUT" - bad proxy

**Comment by VincentVinTin** [comment]
Can you give more details, I don't understand?

**Comment by drawrowfly** [comment]
Can you post here please with what options did you used it. "ESOCKETTIMEDOUT" usually means that you haved used bad proxy (http or socks)

**Comment by VincentVinTin** [comment]
I have edited my post
