### ISSUE TITLE
Cannot use Crawlera proxy

### ISSUE THREAD

**Issue by luispablo** [drawrowfly/tiktok-scraper#400]
**Describe the bug**
I'm trying to make a single call to get a user profile through the Crawlera proxies

```javascript
const TikTokScraper = require("tiktok-scraper");
const profile = await TikTokScraper.getUserProfileInfo("hamster_land1", { 
  proxy: "crawlera_key:@proxy.crawlera.com:8010" 
});
console.log(profile);
```

Seems that there's an issue with the SSL certificates, as I'm getting the following error:

```Error: unable to verify the first certificate```

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- Used OS: Ubuntu 20.10
- NodeJs Version (node -v): v14.15.1
- Scraper Version (tiktok-scraper --version): 1.4.7 (latest)
- CLI or Module: module
- Used method: getUserProfileInfo
- Used options: username and proxy (string)
- Do you run the scraper through Proxy, VPN, VPS?: Yes, Crawlera
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles!: Not scraping from a profile
- Preferably provide URL to the profile,hashtag,video and etc page: Any username used gives the same result

**Screenshots**

**Comment by luispablo** [comment]
Seems to be an issue with Crawlera CA certificate, adding these options on the HTTP request seem to work

```javascript
                    ca: fs.readFileSync("/home/user/certs/crawlera-ca.crt"),
                    requestCert: true,
                    rejectUnauthorized: true
```

Is there a way to set these options to the scraper?
Thanks!

**Comment by luispablo** [comment]
If this is a new feature, maybe I can make a pull request to include it.

**Comment by tnoetzel** [comment]
FWIW, another option is to use `process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";`

It's NOT very secure, but it does work as a hack until this issue is resolved.

**Comment by drawrowfly** [comment]
@luispablo be my guest :)
