### ISSUE TITLE
Undefined when running

### ISSUE THREAD

**Issue by RandomUserDave** [drawrowfly/tiktok-scraper#401]
No matter what I run the only result I get is undefined.  Don't know where log files are going.

- Used OS: Win 10
- NodeJs Version: 14.15.1
- Scraper Version: 1.4.7
- CLI or Module: ?
- Used method: ?
tiktok-scraper user [USERNAME] -d
- Used options: ?
- Do you run the scraper through Proxy, VPN, VPS? No
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles!
Yes, public

**Comment by luispablo** [comment]
Maybe this is related to #399 ?
