### ISSUE TITLE
Script doesn't work? Quickly Exits out immediately, have tried all different flags

### ISSUE THREAD

**Issue by burneracct** [drawrowfly/tiktok-scraper#402]
Hey guys, this script was working the last time I used it like last year or so (or maybe it was another script)

This script isn't working for me on Ubuntu 18. 
![server](https://user-images.githubusercontent.com/76247917/102687394-cafa7200-41bc-11eb-9ca0-92451485608c.png)

Here is a video of the behavior of the script in the terminal. as you can see, it quickly exits out when ran with different parameters. 

Please help

https://imgur.com/a/U6bubOm

**Comment by drawrowfly** [comment]
#399
