### ISSUE TITLE
Not working with File and history

### ISSUE THREAD

**Issue by ProteoNimra** [drawrowfly/tiktok-scraper#403]
Can't get it work with this instruction:
tiktok-scraper from-file Users.txt 3 -n 50 -d -s -w --historypath c:\legna\tiktok\_History

it used to work in that way before the last 2 updates..

Any advice ?

**Comment by drawrowfly** [comment]
Yes this functionality requires an update as well

**Comment by ionapjolive** [comment]
I am unable to get anything to download in CLI for user, e.g. 
tiktok-scraper user willsmith -d -n 1 -w --session sid_tt=fffff 

But similar command for trend works fine: 
tiktok-scraper trend willsmith -d -n 1 -w --session sid_tt=fffff 

Not sure if this is related to the above. I have updated just today.

**Comment by ajervin1** [comment]
Nothing is working for me, the user one has been not working for a minute but now trend/hashtag/music are all not working for me.

**Comment by ry-ga** [comment]
I have tried individual users as well as a batch file. It looks like it is going to scrape, then downloads nothing.

**Comment by ajervin1** [comment]
Everything works for me now

**Comment by ProteoNimra** [comment]
> Everything works for me now, even the user one which wasn't working for me three days straight. Is anyone else having these problems?

Not working for me yet, using "from-file"
tiktok-scraper from-file Users.txt 3 -n 150 -d -s -w --historypath c:\legna\tiktok\_History

**Comment by drawrowfly** [comment]
Works fine in the latest version

**Comment by ProteoNimra** [comment]
> Works fine in the latest version

Thanks for your great work!!!
