### ISSUE TITLE
Can't download (user/trend)

### ISSUE THREAD

**Issue by skylar01** [drawrowfly/tiktok-scraper#406]
**Describe the bug**
Can't download anything be it user/trend i'm using docker if that matters
I use this command:
docker run -v /path/to-download:/usr/app/files tiktok-scraper user [tiktok-user] -d -s --session sid_tt=[cookie]

I've used this command for ages, apart from the --session

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- Linux
- v8.10.0
- 1.4.8
- CLI - Docker
- Used method
- -d -s
- Local computer
- Yes, I've tried it on multiple public profile.

**Screenshots**
I don't think a screenshot would help since it just exits.
It says the scraper started but will exit immediately.
It only outputs this:
- TikTok Scraper Started

**Comment by drawrowfly** [comment]
#399
