### ISSUE TITLE
Get profile information from a link with the following format: https://vm.tiktok.com/<id>

### ISSUE THREAD

**Issue by pierrehabte2017** [drawrowfly/tiktok-scraper#407]
First of all, thanks a lot for the different methods and the great work!
Sometime I encounter profile link under this format:  https://vm.tiktok.com/<id>
(ex: https://vm.tiktok.com/ZSt53N8K/). That would be great to be able to get the user information from this link!

**Comment by drawrowfly** [comment]
For now i do not have plans to implement it, but i do accept PR's )
