### ISSUE TITLE
.user and .getVideoMeta are not working in 1.4.9

### ISSUE THREAD

**Issue by asportnoy** [drawrowfly/tiktok-scraper#408]
**Describe the bug**
`.user` and `.getVideoMeta` are not working in 1.4.9. They worked while 1.4.8 was working. `.getUserProfileInfo` works.

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- Ubuntu 20.04.1
- NodeJS 12.18.1
- Scraper Version 1.4.9
- Module
- `.user` and `.getVideoMeta`
- Options: Proxy, session id (for .user)
- Proxy was used
- Profile was public, videos were public

**Screenshots**

**Comment by drawrowfly** [comment]
Can't reproduce it

Use proxy

**Comment by asportnoy** [comment]
`getVideoMeta` was actually working and `user` started working again after I replaced my session. Thanks
