### ISSUE TITLE
Update command (downloading the same user twice or more)

### ISSUE THREAD

**Issue by DankMemeGuy** [drawrowfly/tiktok-scraper#409]
**Is your feature request related to a problem? Please describe.**
When downloading a user that was previously downloaded it seems the script downloads the user all over again (or appears in the terminal that way)

**Describe the solution you'd like**
To prevent rate-limiting, and other unnecessary connection requests, would be nice to have an 'update' flag that will download all the new videos since the last download. It could work by downloading a video until it detects a video that it already downloaded then stops the operation, thus not downloading the other videos already downloaded.

Or if the script pulls a list then downloads them all, it could check all the filenames and just make a new list of what hasn't been downloaded and just download those.

**Comment by drawrowfly** [comment]
https://github.com/drawrowfly/tiktok-scraper/blob/master/examples/CLI/DownloadHistory.md
