### ISSUE TITLE
after this error can't download any video 

### ISSUE THREAD

**Issue by sunnydev3301** [drawrowfly/tiktok-scraper#410]
using MacBook Air
Mojave 10.14.6
node v14.15.3
npm v 6.14.9

the error manifested with this command : tiktok-scraper user hannsoff -n -d -w --hd 
it started to download and at a certain point it returned me this error:

/usr/local/lib/node_modules/tiktok-scraper/node_modules/progress/lib/node-progress.js:160
  complete = Array(Math.max(0, completeLength + 1)).join(this.chars.complete);
             ^

RangeError: Invalid array length
    at ProgressBar.render (/usr/local/lib/node_modules/tiktok-scraper/node_modules/progress/lib/node-progress.js:160:14)
    at ProgressBar.tick (/usr/local/lib/node_modules/tiktok-scraper/node_modules/progress/lib/node-progress.js:97:8)
    at MultipleBar.tick (/usr/local/lib/node_modules/tiktok-scraper/build/helpers/Bar.js:74:17)
    at ProgressBar.barObj.tick (/usr/local/lib/node_modules/tiktok-scraper/build/helpers/Bar.js:47:18)
    at Request.<anonymous> (/usr/local/lib/node_modules/tiktok-scraper/build/core/Downloader.js:78:30)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/tiktok-scraper/node_modules/request/request.js:1073:12)
    at IncomingMessage.emit (events.js:315:20)
    at IncomingMessage.Readable.read (internal/streams/readable.js:519:10)
    at flow (internal/streams/readable.js:992:34)
    at resume_ (internal/streams/readable.js:973:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

**Comment by sunnydev3301** [comment]
@drawrowfly pls help me out don't know much about coding just followed the steps

**Comment by bebunw** [comment]
i have the same error, it seems we reach a array limit after 160 vids downloaded from a profile

**Comment by sunnydev3301** [comment]
@bebunw No I don't think so because I have downloaded 1.7k videos from a different account before this error

**Comment by bebunw** [comment]
As i understand it the error not coming from tiktok servers, but from our shell rendering each download with progress bar in each line, maybe one of the download do not correspond to the progress in the shell, maybe different size than expected ??? but i'm just a newbie in coding

**Comment by sunnydev3301** [comment]
@bebunw what do you suggest to do

**Comment by src7** [comment]
Hi @sunnydev3301, as a workaround, try option `-a` with a very low value (like `-a 1`), worked for me.

**Comment by bebunw** [comment]
I noticed why it's bugging, at one moment in the scrape it download "older" vids with one less number in url, and always near that moment the bug happened shortly after


Downloading (WITH WM) 6514733547108979727 [==============================] 100%
Downloading (WITH WM) 6514430327446852623 [==============================] 100%
Downloading (WITH WM) 6514104677561275407 [==============================] 100%
Downloading (WITH WM) 6514346432927896591 [==============================] 100%
Downloading (WITH WM) 6514113006501106703 [==============================] 100%
Downloading (WITH WM) 6513957660478411776 [==============================] 100%
Downloading (WITH WM) 319509606924218368 [==============================] 100%
Downloading (WITH WM) 319518296372973568 [==============================] 100%
Downloading (WITH WM) 319508788577832960 [==============================] 100%
Downloading (WITH WM) 319508251736150016 [==============================] 100%
Downloading (WITH WM) 317915342071283712 [==============================] 100%
Downloading (WITH WM) 319369611198541824 [==============================] 100%
Downloading (WITH WM) 317914738229649408 [==============================] 100%
Downloading (WITH WM) 317913983251009536 [==============================] 100%
Downloading (WITH WM) 317913566697648128 [==============================] 100%
Downloading (WITH WM) 317913377291464704 [==============================] 100%
Downloading (WITH WM) 317913216162942977 [==============================] 100%
Downloading (WITH WM) 317911795422244864 [==============================] 100%
Downloading (WITH WM) 317897779672907776 [==============================] 100%
Downloading (WITH WM) 317642096985866240 [==============================] 100%
Downloading (WITH WM) 317639990413619201 [==============================] 100%
Downloading (WITH WM) 317637668073586688 [==============================] 100%
Downloading (WITH WM) 317591703656386560 [==============================] 100%
Downloading (WITH WM) 317536710978977792 [==============================] 100%
Downloading (WITH WM) 317538479293489152 [==============================] 100%
Downloading (WITH WM) 316444468923260928 [==============================] 100%
Downloading (WITH WM) 316107625023078400 [==============================] 100%
Downloading (WITH WM) 317532688276713472 [==============================] 100%
Downloading (WITH WM) 316028489986609152 [==============================] 100%
Downloading (WITH WM) 315890090638290944 [==============================] 100%
Downloading (WITH WM) 315883151665307648 [==============================] 100%
Downloading (WITH WM) 315796580710723584 [==============================] 100%
Downloading (WITH WM) 315756390340435969 [==============================] 100%
Downloading (WITH WM) 315752652896739328 [==============================] 100%
Downloading (WITH WM) 315750435079020544 [==                            ] 7%
Downloading (WITH WM) 315751967992160257 [=                             ] 3%
Downloading (WITH WM) 315749253480476672 [                              ] 0%
C:\Users\Boss\AppData\Roaming\npm\node_modules\tiktok-scraper\node_modules\progress\lib\node-progress.js:160
  complete = Array(Math.max(0, completeLength + 1)).join(this.chars.complete);
             ^

**Comment by khanakhun** [comment]
> @bebunw No I don't think so because I have downloaded 1.7k videos from a different account before this error

Can you Please Guide me how did you download the Video  because I'm getting a problem while downloading using Module method getVideometaData(); 
but when i use CLI command video is downloading
