### ISSUE TITLE
tiktok.com/node/share/user not working

### ISSUE THREAD

**Issue by digvijay1331** [drawrowfly/tiktok-scraper#412]
I use this link in my app, but now not working. 

https://www.tiktok.com/node/share/user/@tiktok?isUniqueId=true

Any new change in this request?

**Comment by digvijay1331** [comment]
???

**Comment by yuralokoss** [comment]
> I use this link in my app, but now not working.
> 
> https://www.tiktok.com/node/share/user/@tiktok?isUniqueId=true
> 
> Any new change in this request?

Have you solved this issue?
