### ISSUE TITLE
I FOUND HOW TO DOWNLOAD WITHOUT WATERMARK AGAIN

### ISSUE THREAD

**Issue by Zipdox** [drawrowfly/tiktok-scraper#414]
Sorry for all caps, but I had to draw your attention.

If you're in a browser you can extract the secret video ID by running this in the console.
```javascript
window.__NEXT_DATA__.props.pageProps.itemInfo.itemStruct.video.id
```
That's the secret ID! You should be able to adapt this into the scraper easily.

**Comment by Zipdox** [comment]
Here's my updated userscript: https://github.com/Zipdox/tiktok-download-userscript

**Comment by Zipdox** [comment]
Created a PR with changes https://github.com/drawrowfly/tiktok-scraper/pull/415

**Comment by Obitech96** [comment]
i tried the program but i download the videos only with watermark

**Comment by merqwury** [comment]
Until your PR gets merged in, any ideas how to use your fork as a Node Module? I've been trying to use npm install --save <your git> but keep getting 'Please verify that the package.json has a valid "main" entry'

Thanks

**Comment by Zipdox** [comment]
> Until your PR gets merged in, any ideas how to use your fork as a Node Module? I've been trying to use npm install --save but keep getting 'Please verify that the package.json has a valid "main" entry'
> 
> Thanks

You need to build it with yarn.
Install yarn:
```bash
sudo npm i -g yarn
```
Install package dependencies and build from inside the project dir
```bash
yarn install
yarn build
```
Move up out of the project dir and install it
```bash
npm i -g ./tiktok-scraper/
```

**Comment by merqwury** [comment]
> 
> 
> > Until your PR gets merged in, any ideas how to use your fork as a Node Module? I've been trying to use npm install --save but keep getting 'Please verify that the package.json has a valid "main" entry'
> > Thanks
> 
> You need to build it with yarn.
> Install yarn:
> 
> ```shell
> sudo npm i -g yarn
> ```
> 
> Install package dependencies and build from inside the project dir
> 
> ```shell
> yarn install
> yarn build
> ```
> 
> Move up out of the project dir and install it
> 
> ```shell
> npm i -g ./tiktok-scraper/
> ```
> 
> **Note:** I'm afraid my patch only works for video downloading mode. Scraping users doesn't work. Someone more knowledgeable needs to fix it.

I believe scraping users was fixed in 1.4.10 by providing a session

**Comment by drawrowfly** [comment]
I will merge it but i think this is temporarily solutions, they had videoId exposed before but fixed it later

**Comment by drawrowfly** [comment]
@1.4.11

**Comment by Zipdox** [comment]
Shit they patched it, now the video ID is the public one.

**Comment by merqwury** [comment]
> 
> 
> Shit they patched it, now the video ID is the public one.

Indeed.. It seems now secretId is now returned with "awesome" for all videos.
