### ISSUE TITLE
Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by lu3do** [drawrowfly/tiktok-scraper#416]
**Describe the bug**
When getting a getUserProfileinfo() I'm now suddenly getting the error: 
"Cannot read property 'split' of undefined"

**To Reproduce**
- Used OS
Linux
- NodeJs Version (node -v)
v15.0.1
- Scraper Version (tiktok-scraper --version)
tiktok-scraper@1.4.10
- CLI or Module
module
- Used method
`getUserProfileInfo()`
- Used options
```
TikTokScraper.getUserProfileInfo("addisonre", {
            sessionList: ['sid_tt=b91d......a9f9;']
        });
```
- Do you run the scraper through Proxy, VPN, VPS?
VPS
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles!
Yes
- Preferably provide URL to the profile,hashtag,video and etc page
www.tiktok.com/@addisonre

**Screenshots**
Unrelated: Not sure how I ended up with version 1.4.10 because I see we're at 1.4.9, but I def have 1.4.10
<img width="416" alt="Schermafbeelding 2021-01-04 om 12 09 42" src="https://user-images.githubusercontent.com/482346/103529332-c228c200-4e85-11eb-9e51-66898158e2e6.png">

**Comment by drawrowfly** [comment]
@1.4.12 this error is properly handled but also use proxies

**Comment by fadytaher** [comment]
this is appearing in latest version
