### ISSUE TITLE
Add Install from source instructions

### ISSUE THREAD

**Issue by AlexBocken** [drawrowfly/tiktok-scraper#417]
As someone who's not very familiar with npm and js I couldn't find a good answer to installing from source.

`npm i -g git:<git-repo>.git`

for some reason doesn't create the `/usr/lib/node_modules/tiktok-scraper/bin/` for some reason. I've looked around the web but couldn't find much. I know there are other ways to install and these work fine for me.

Would it be possible to instructions on how to properly install from source in the README.md?

**Comment by drawrowfly** [comment]
download the source -> then build it from the TS to the JS **npm run build** or **yarn build**
