### ISSUE TITLE
User not exist handling

### ISSUE THREAD

**Issue by hoikin** [drawrowfly/tiktok-scraper#421]
Describe the bug
Can the method return Error if the user not exist by checking the http status code 404 and the html contains "Couldn't find this account". 

To Reproduce

Used OS
Linux
NodeJs Version (node -v)
v10.23.0
Scraper Version (tiktok-scraper --version)
tiktok-scraper@1.4.12
CLI or Module
module
Used method
getUserProfileInfo()
Used options

Do you run the scraper through Proxy, VPN, VPS?
Proxy
If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles!
Yes
Preferably provide URL to the profile,hashtag,video and etc page
www.tiktok.com/@sdfsdsfsdfsdfs

**Comment by fabnoe** [comment]
Same here:
Error: Can't extract user metadata from the html page. Make sure that user does exist and try to use proxy

`            feed = await TikTokScraper.user(username, {number: options.userVideoLimit, sessionList: [TTSessions]});
`

**Comment by fabnoe** [comment]
I just noticed this error occurs only in some internet environment. If I use a different access point, everything works fine.

**Comment by MrJmpl3** [comment]
> I just noticed this error occurs only in some internet environment. If I use a different access point, everything works fine.

I use many proxies, and not work u.u

**Comment by interroliq** [comment]
The same problem for me

**Comment by rizwan-rizu** [comment]
Same problem here, I am facing the same error and not able to get the required data. It was working fine before but suddenly stopped working.

**Comment by Michaelmala** [comment]
Hi guys, try to use the cookie value "sessionId_ss" in the sessionList option

**Comment by drawrowfly** [comment]
@1.4.33
