### ISSUE TITLE
Following batch download tutorial, I keep getting error "You need to set number of task that should be executed at the same time

### ISSUE THREAD

**Issue by paulescobar** [drawrowfly/tiktok-scraper#423]
Please forgive me for posting this support request as a feature request (couldn't find a discussion section here, or I'd post there). I don't think this is a bug...more my own misunderstanding...so I'm hoping someone here can offer me guidance on batch downloading.

I've just installed the scraper. I succeeded in using the program for individual downloads. But now I'm following the "Batch Download" tutorial and it's not working at all:
https://github.com/drawrowfly/tiktok-scraper/blob/master/examples/CLI/BatchDownload.md

- From my understanding of this tutorial, I can create a text file containing download tasks on each line.

- I created a text file named:
`[TikTok-Scraper] [Batch].txt`
- I placed that text file at the path:
`C:\-- TikTok-Scraper --`

I used the sample code from the tutorial, merely adding the path of my text file in quotation marks:
`tiktok-scraper from-file "C:\-- TikTok-Scraper --\[TikTok-Scraper] [Batch].txt" ASYNC_TASKS -d -f all`

But the scraper doesn't download and throws this error message:
`You need to set number of task that should be executed at the same time`

I've tried to modify the commands various ways, but keep getting that error message.

**Can anyone help me understand what's going on? Or what I'm doing wrong? I feel like I've misunderstood something in the tutorial or am formatting the commands incorrectly.**

**Comment by drawrowfly** [comment]
Replace ASYNC_TASKS with number of tasks for example 5
