### ISSUE TITLE
Files downloaded contain 0kb of data

### ISSUE THREAD

**Issue by Seuong** [drawrowfly/tiktok-scraper#425]
- Windows 10 20h2
- Node v14.15.4
- tiktok-scraper v1.4.12

When downloading users, e.g.  tiktok-scraper user aespa_official -d --hd -w, files are downloaded
 but contain 0kb of data. For certain accounts like the one listed, the entire channel is 0kb, some channels are only partially downloaded with 0kb files. It seems this is caused by the -w and maybe --hd flag, when disabled, the files are downloaded properly. I was using these settings prior, and they worked fine. 

![Screenshot 2021-01-15 141301](https://user-images.githubusercontent.com/58326324/104768537-db5e2800-573b-11eb-9dbe-0a1441d80087.png)

**Comment by ProteoNimra** [comment]
yeah, I have the same issue using  from-file command:
tiktok-scraper from-file Users.txt 1 -n 50 -d -s -w --historypath c:\legna\tiktok\_History

**Comment by blasphemite** [comment]
I'm also getting 0 byte files:

Ubuntu 18.04
Node.js v10.23.1
tiktok-scraper 1.4.12

tiktok-scraper from-file users.txt 5 -n 5 -d --hd -w --session sid_tt=_xxx_ -s -p socks5://127.0.0.1:8123

**Comment by Shmi911** [comment]
Downloading without watermark is currently not working.  See https://github.com/drawrowfly/tiktok-scraper/issues/414

**Comment by drawrowfly** [comment]
I will update the repo shortly
