### ISSUE TITLE
AuthorMeta: "Heart" in Billions Return 0

### ISSUE THREAD

**Issue by Dlas1212** [drawrowfly/tiktok-scraper#427]
**Bug:**

I tried **charlidamelio**  who current has **8.4B** likes and the "AuthorMeta" returns "0"

When I tried **justinbieber** who has **62.3M** likes,"AuthorMeta" returned "62300000"

Therefore, 
There is an issue when the **likes** is in **billion**.

**Comment by drawrowfly** [comment]
This is what tiktok web api is giving us , nothing more can be done
