### ISSUE TITLE
[Feature Request] Social Handles

### ISSUE THREAD

**Issue by ColtraneNadler** [drawrowfly/tiktok-scraper#428]
Is it possible to get social media handles that are attached to one's account?
Picture from within the tiktok app-

![image0](https://user-images.githubusercontent.com/8130184/104966881-018bfe00-59b0-11eb-86d0-3f3296234797.png)

**Comment by Oli-idk** [comment]
i believe he has said before that it uses the web app and it isnt possible to get those

**Comment by drawrowfly** [comment]
Not with the web api
