### ISSUE TITLE
HD download not possible

### ISSUE THREAD

**Issue by parnet** [drawrowfly/tiktok-scraper#429]
**Describe the bug**
by calling the app to download a video without watermark the output size of the video is 0 bytes, the same when the --hd option is given.
think the api changed somehow
the downloads of videos with watermark are still possible 

**To Reproduce**
the call 
tiktok-scraper video https://www.tiktok.com/@motioncosplays/video/6916557643771301122-d --hd -w
leads to a 0 bytes video

**Comment by RonnieBlaze** [comment]
if that is the comment you are trying to run, the -d has no space between it and the video link. so its going to fail

**Comment by parnet** [comment]
oh sorry as i have tried it there was a space between the link and the -d else the error Can't extract video metadata.
sorry for confusion. 
the filesize of 0bytes remains with --noWaterMark or -w as a parameter
![fs](https://user-images.githubusercontent.com/33659146/105082370-c105b080-5a93-11eb-860f-e9a1e95bedf0.png)

**Comment by Shmi911** [comment]
No watermark "hd" is currently not working.
You can read here:
https://github.com/drawrowfly/tiktok-scraper/issues/425
and/or here:
https://github.com/drawrowfly/tiktok-scraper/issues/414
etc.

I do feel very sad aswell about the fact that tiktok changes stuff so often.

**Comment by parnet** [comment]
Thank you both for your answers. :)
These Issues are all closed. Is it a problem which can not be fixed?
Should this thread also be closed?

**Comment by Shmi911** [comment]
Yes, it should be closed.

Unless there is no videoid to be found through the WebAPI, there will be no hd and/or ''no watermark'' function working.

And as mentioned before by the creator we do not discuss other possibilities like MobileAPI etc., because it's off-topic for this repo.
