### ISSUE TITLE
Not scraping videos w/ "This sound isn't available." message.

### ISSUE THREAD

**Issue by vnnegt** [drawrowfly/tiktok-scraper#43]
When viewing TikTok videos via the mobile app, sometimes there is a 

> This sound isn't available.

message above the video. I noticed that these videos do not get scraped. Is it possible to include them?

IDK if it helps in figuring out the issue, but I've been able to share them to Instagram via the mobile app and download/hear the sound that way.

Love the scraper, thanks!

**Comment by drawrowfly** [comment]
I guess this is related to the copy rights in some countries

Can you post here please tiktok profile as an example with such videos

Thanks

**Comment by vnnegt** [comment]
What's weird is that I can't see them using my web browser.

I receive:

> Video currently unavailable

but on my iPhone app I can see them. Maybe that's why they don't get scraped?

This account has an example of such videos: https://www.tiktok.com/@naomiwatanabe

The video is here: https://vm.tiktok.com/sy7eW6/

I browsed to the video on my iPhone and then emailed myself the link.

Again, I can see it, but not hear it on my iPhone.

Via the web browser it simply says:

> Video currently unavailable

Thanks

**Comment by drawrowfly** [comment]
If Web Api is not showing the video then currently it is not possible

**Comment by vnnegt** [comment]
Ok thanks
