### ISSUE TITLE
Failed downloads, empty mp4's.

### ISSUE THREAD

**Issue by reinstallgentoo** [drawrowfly/tiktok-scraper#430]
**Describe the bug**
Hi, recently all my downloads are failing. afaik nothing in my env has changed and tiktok-scraper version is the same.
Instead of displaying the usual % bar for downloads there is simply a blank line for each post followed by the typical 'Folder path:' output. mp4's are being written but they empty.

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- Used OS
Ubuntu 20.04 5.4.0-42
- NodeJs Version (node -v)
10.19.0
- Scraper Version (tiktok-scraper --version)
1.4.12
- CLI or Module
cli
- Used method
tiktok-scraper user $i -s --hd -w -d -n 0
- Do you run the scraper through Proxy, VPN, VPS?
N
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles!
Y
- Preferably provide URL to the profile,hashtag,video and etc page
Any

**Comment by Shmi911** [comment]
"--hd" "-w"
functions are currently not working. Try without them.
And if you want to read about it, read here:
https://github.com/drawrowfly/tiktok-scraper/issues/266 https://github.com/drawrowfly/tiktok-scraper/issues/414 https://github.com/drawrowfly/tiktok-scraper/issues/425 https://github.com/drawrowfly/tiktok-scraper/issues/429

**Comment by reallyuniquename** [comment]
Previous versions had a fallback to watermarked videos. This is how it's supposed to work. As far as I know you can still download **old** videos without watermark so dropping `-w` is not a good idea.

**Comment by reinstallgentoo** [comment]
Thanks.
