### ISSUE TITLE
All the files download are of "Zero bytes"

### ISSUE THREAD

**Issue by njscorpion** [drawrowfly/tiktok-scraper#436]
**Describe the bug**

All the files download are of 0 bytes, tested it for "user mode" only, it doesn't matter whether updating or new scrap.

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- Used OS : **Windows 10 20H2 Build 19042.742**
- NodeJs Version (node -v) : **v12.14.0**
- Scraper Version (tiktok-scraper --version) : **Latest (tiktok-scraper@1.4.12)**
- CLI or Module : **CLI**
- Used method : **CLI**
- Used options : **tiktok-scraper -p socks5://0.0.0.0:1234 --filepath c:\test -n 10 --noWaterMark user laceycakes03 -d** (*Removed Real Proxy)
- Do you run the scraper through Proxy, VPN, VPS? : **Socks v5 Proxy**, Opened profile URL on browser via proxy without any issue
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles! : **Yes it's Public Profile**
- Preferably provide URL to the profile,hashtag,video and etc page : **https://www.tiktok.com/@laceycakes03**

**Screenshots**
![image](https://user-images.githubusercontent.com/44571306/105819471-3f0b0f80-5fde-11eb-86ea-7eab5bf7dc7a.png)

**Comment by jewishmoses** [comment]
I had the same error when I removed the -w / --noWaterMark argument it worked fine.

**Comment by njscorpion** [comment]
Yes, this work around does work

**Comment by artem1480** [comment]
Hi! I have the same issue. Mac OS x. Zero bytes after downloading

**Comment by drawrowfly** [comment]
Don't use -w/--noWaterMark it is not working. I will update documentation shortly
