### ISSUE TITLE
.User method failing randomly (due to website change rollout?)

### ISSUE THREAD

**Issue by coder39248583** [drawrowfly/tiktok-scraper#438]
**Describe the bug**
In the last couple of days the .user method has started to fail on my Brazil proxies, as well as some others. When I check a user's page in a browser using the same proxy a redesigned page appears in which a user's posts appear in a twitter-like feed (with a toggle button to change it back to a grid view). When I check the user's page using a proxy from a different region, the page appears in the traditional grid design, and the .user method works.

I can't be 100% certain, but it seems that the success of the .user method is dependent on whether or not a given proxy brings up the old design in a browser. If it brings up the new design in a browser, the .user method fails.

Also, sometimes it will fail but later succeed if I try again. I'm not sure how to explain it unless TikTok is rolling out changes and the chances of getting the redesigned site is sort of random based on user and region?

Brazil seems to have consistent failures (but rarely working). Norway and Netherlands are mixed, working sometimes and failing other times. U.S. proxies seem to be unaffected so far.

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- Windows 7 64-bit
- Node v12.16.3
- Scraper Version 1.4.12
- CLI or Module: Module
- Used method: .user
- Used options: number (6), sessionList (the cookie sid_tt value), proxy
- Do you run the scraper through Proxy, VPN, VPS? Yes, Proxies
- Profile is public
- Preferably provide URL to the profile,hashtag,video and etc page: @gordonramsayofficial

**Screenshots**

Here is a screenshot of the redesigned page, with the left and right panes showing the toggled options:

![redesign](https://user-images.githubusercontent.com/47176092/106337935-cad7a280-624f-11eb-9c76-6777cb07d9a3.jpg)

**Comment by coder39248583** [comment]
Accidentally clicked "close the issue." I reopened it again.

**Comment by coder39248583** [comment]
The random failures have been getting somewhat better for the last couple of hours, so I'm not sure what's going on. I will keep this thread posted.

**Comment by coder39248583** [comment]
Update: My proxies are still experiencing a roughly 20% failure rate on the .user method.

**Comment by lu3do** [comment]
Having this exact same issue, I'm running a status check every hour on the same user, and only some of the times it fails.

**Comment by lu3do** [comment]
I'm using US proxy btw. And looks like it's failing more frequently now. @drawrowfly

**Comment by coder39248583** [comment]
@lu3do I'm using all US Luminati.io proxies now (data center proxies with tiktok.com domain exclusivity). I've noticed these recent random failures effect some proxies more than others, and I've had some success in switching out the bad ones. But if it's some sort of rollout on TikTok's end I wonder if I'm just delaying the inevitable.

**Comment by lu3do** [comment]
@coder39248583 I've tried using a few different proxy services, but they all seem to fail randomly at some point. 

I actually looked at the code of the 2 different layouts and that shouldn't be what's causing this issue. Because the way the profile data is represented is still the same.

**Comment by drawrowfly** [comment]
Latest version works fine
