### ISSUE TITLE
Nothing to be downloaded

### ISSUE THREAD

**Issue by Tekkni** [drawrowfly/tiktok-scraper#44]
As of 9:50am CET, I can't download video's anymore. What worked the day before, doesn't work now, I'm affraid.

command use: tiktop-scraper user thisisanexampleuser -n 9999 -d -store

commands used to download by music association does not work, either.

**Comment by drawrowfly** [comment]
Yes, they definitely changed something

It will take time for me to figure out what exactly

**Comment by drawrowfly** [comment]
I will push update shortly

**Comment by drawrowfly** [comment]
You can update package and it will work

**Comment by arelxcode** [comment]
Thanks you! @drawrowfly i know to get video without watermark.
can you send me a contact?

**Comment by drawrowfly** [comment]
@arelxcode Great, that will save me a lot of time

andrew.nord.flow@gmail.com

**Comment by Tekkni** [comment]
Awesome quick work, many internetpoints to you bro!
