### ISSUE TITLE
Proxy list via module method

### ISSUE THREAD

**Issue by dreamer-cloud** [drawrowfly/tiktok-scraper#448]
**Describe the bug**

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- Used OS Linux
- NodeJs Version (node -v) v12.14.1
- Scraper Version (tiktok-scraper --version) 1.4.12
- CLI or Module Module
- Used method .user() - promise
- Used options - ??
- Do you run the scraper through Proxy, VPN, VPS? Trying to
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles! Yes
- Preferably provide URL to the profile,hashtag,video and etc page

**Screenshots**

Hi, can you please declare, how should I define proxy list (two or more proxies) in options via Module method? 

Like this: 
`proxy: ['000.000.000.000:xx;000.000.000.00:xx;]`

or each per new line: `proxy: ['000.000.000.000:xx\n000.000.000.00:xx;]`

**Comment by asportnoy** [comment]
It's just a normal JS array.

**Comment by drawrowfly** [comment]
["1.1.1.1","2.2.2.2"]
