### ISSUE TITLE
max number of videos that can be downloaded

### ISSUE THREAD

**Issue by DanilKonon** [drawrowfly/tiktok-scraper#450]
I try to download videos by some hashtag. Yet for every hashtag I get max 1000-2000 videos. Is this intended? How can I get more videos? 

I use this command. 
`tiktok-scraper hashtag fun  -n 10000 -s  -d -t all  --session`

I get some amount of new videos (about 10) if I wait for a day or so. I use the same command for this.

**Comment by sigaloid** [comment]
That's likely a server side limit. Not much you can do since that's tiktok servers limiting # responses
