### ISSUE TITLE
What is verifyFP option and how to get verifyFP value

### ISSUE THREAD

**Issue by Zulfiqar-Qureshi** [drawrowfly/tiktok-scraper#451]
Hello,
Firstly, I tried fetching a single video meta and the data comes back in JSON just fine, but the video link, when opened in the browser doesn't work (the video player shows up, but is blank), tried with default values.
secondly, I don't know what is verifyFP and how to get it's value, kindly guide me.
Thank you

**Comment by drawrowfly** [comment]
Visit tiktok, open inspector and you will find it there . It is used to verify request and bypass captcha if there is one
