### ISSUE TITLE
Videos being download as 0 byte files

### ISSUE THREAD

**Issue by throw395583** [drawrowfly/tiktok-scraper#456]
The first 36 (chronological) videos downloaded successfully, 4 more were downloaded as 0 byte files, one more downloaded successfully, then the remaining 19 videos were downloaded as 0 byte files. I've deleted and redownloaded the files several times and it hasn't helped. The program output 19 blank lines before it output the download bars, not sure if that's related.

- Windows 10
- NodeJs Version v14.15.4
- 1.4.12 (tiktok-scraper --version)
- CLI or Module (?)
- tiktok-scraper user satanpanties666 -d --timeout 1000 -a 1 --hd -w --filepath "PLACEHOLDER"
- No proxy/VPN/VPS

**Comment by drawrowfly** [comment]
don't use -w , currently it is not possible to download videos without the wm
