### ISSUE TITLE
Failing to download some or all of the files.

### ISSUE THREAD

**Issue by kilpsz** [drawrowfly/tiktok-scraper#459]
It's constantly failing to download some if not all of the files. 

For example
tiktok-scraper user nellalaakso-d -n 0 --filepath F:\Pics\tiktok --noWaterMark --hd 
Fails to download every single file. It started happening after i tried --timeout 500 at the end of that line but i'm not sure if that actually mattered.

https://i.imgur.com/gVMgT6O.png
https://i.imgur.com/JIAnPcn.png
https://i.imgur.com/FBaSHLE.png

All of the empty lines are files that ended up being "downloaded" but not really.
https://i.imgur.com/vUfs03A.png

**Comment by drawrowfly** [comment]
do not use --noWaterMark
