### ISSUE TITLE
"TikTok Scraper Started" message and then program exits.

### ISSUE THREAD

**Issue by vnnegt** [drawrowfly/tiktok-scraper#46]
This morning I tried to scrape a profile and the program immediately exited with no other message after displaying the "TikTok Scraper Started" message.

I updated the program and repeatedly receive the same message. Could it be that my IP is banned/limited?

Thanks

**Comment by arelxcode** [comment]
me too! i'm running in Windows Server 2012 R2

**Comment by arelxcode** [comment]
nothing result, idk my IP banned or limited.

**Comment by xelarate86** [comment]
Seeing the same on Ubuntu 18.04.
Downgraded to 1.0.14 and the same issue is happening. Assuming something TT-server side.

I don't believe my IP would be banned nor limited.

**Comment by drawrowfly** [comment]
I would be so much better if you all post here **options** and **method** that you are using!

**Comment by drawrowfly** [comment]
There is one big change in the latest version

I have separated Promise and Event methods

**Comment by drawrowfly** [comment]
Im currently running successfully the latest version **1.0.15** of the scraper on Mac and Ubuntu 18

**Comment by arelxcode** [comment]
check my email for wm bypass @drawrowfly

**Comment by vnnegt** [comment]
> I would be so much better if you all posted here **options** and **method** that you have used!

I used `tiktok-scraper -n 0 -d user <USERNAME>`

**Comment by xelarate86** [comment]
> I would be so much better if you all posted here **options** and **method** that you have used!

Similar to @vnnegt my usage of `tiktok-scraper user [USERNAME] -n 20 -d` 
did not work, just the spinning square and "TikTok Scraper Started" then immediate exit.

I spun up a fresh VM with Ubuntu 18.04 and found that `tiktok-scraper user [USERNAME] -n 20 -d` did not work either. I tried `tiktok-scraper hashtag fyp` and that didn't work either.

Out of curiosity, what node version are you running @drawrowfly ? I assume it wouldn't affect it but I'm on v13.11.0, tried v11.15.0 and it didn't work either.

If there's any other info I can provide, just let me know.

**Comment by drawrowfly** [comment]
TikTok's api is glitching, i can access some pages without signature key. My guess we should wait

**Comment by Tekkni** [comment]
Yeah, it stopped working for me too at the moment, will see tomorrow.

**Comment by drawrowfly** [comment]
Well did some "hacking" with the signature and its working better. At least from mine side

With the help of @arelxcode implemented feature to download the video without the watermark

**Comment by vnnegt** [comment]
> Well did some "hacking" with the signature and its working better. At least from mine side
> 
> With the help of @arelxcode implemented feature to download the video without the watermark

Awesome!

Is the quality any better?

**Comment by xelarate86** [comment]
Looks like it's working for me now, no changes. Speedy.

**Comment by drawrowfly** [comment]
@vnnegt no idea, i just know that they are without the watermark :)

**Comment by arelxcode** [comment]
@vnnegt maybe if you need quality better in video you can use the param 

urlnowm + &improve_bitrate=1&ratio=1080p
 (or 720p)

**Comment by drawrowfly** [comment]
We can implement extra options to customize the video quality

**Comment by andreabenedetti** [comment]
I tried every option and method available, but the script is not running for me either since last week. Did you find a workaround to this issue?

**Comment by drawrowfly** [comment]
Please always check the latest version, it is so easy :)
