### ISSUE TITLE
Get Music triggers verification method

### ISSUE THREAD

**Issue by lu3do** [drawrowfly/tiktok-scraper#460]
**Describe the bug**
Get music is failing almost all the time, and I checked the response from the TikTok API and it's triggering the verification method. I'm using 50 different proxy's, and also tried another 50 proxy's from another provider.

Only seems to be happening on the `getMusicInfo()` and not that often on any of the other methods.

Returned response:
```
{
  statusCode: 10000,
  verifyConfig: {
    code: 10000,
    type: 'verify',
    subtype: 'slide',
    fp: 'verify_927e96cb3......51161df74',
    region: 'va',
    detail: 'y4zUJsMEA......wribm5Rp1s.'
  }
}
```

**To Reproduce**
- Used OS
Linux
- NodeJs Version (node -v)
v15.0.1
- Scraper Version (tiktok-scraper --version)
tiktok-scraper@1.4.11
- CLI or Module
Module
- Used method
`getMusicInfo()`
- Used options
`sessionList` and `proxy`
- Do you run the scraper through Proxy, VPN, VPS?
VPS + Proxy
- Preferably provide URL to the profile,hashtag,video and etc page
https://www.tiktok.com/music/Savage-Love-Laxed-Siren-Beat-6834110584288447237

<img width="1167" alt="Schermafbeelding 2021-02-24 om 10 18 36" src="https://user-images.githubusercontent.com/482346/108978272-ba1d1f80-7689-11eb-9909-70f9345f9269.png">

**Comment by drawrowfly** [comment]
#455 almost same problem that is related to the music method. Closing it to keep it clean
