### ISSUE TITLE
Error while scraping:

### ISSUE THREAD

**Issue by shazac** [drawrowfly/tiktok-scraper#461]
I tried downloading a list of tiktok videos but after a while I keep getting this error for all videos.

## If fields below will be empty then issue will be Ignored and Closed

Scraper version: 1.4.12
I ran this command while under a VPN: tiktok-scraper from-file [path] [file] 5 --hd -w -d -s -n 0 -t all --historypath [path]

Example of result: 

Error while scraping: https://www.tiktok.com/.lxxreen/video/6820970295017360641
Error while scraping: https://www.tiktok.com/.shikimo/video/6881894370191232262
Error while scraping: https://www.tiktok.com/.smalltiddyg0thgf/video/6790132273736895749
Error while scraping: https://www.tiktok.com/.mamasel/video/6785628258567277829
Error while scraping: https://www.tiktok.com/.smalltiddyg0thgf/video/6807884793318067462
Error while scraping: https://www.tiktok.com/.smalltiddyg0thgf/video/6869865409617743109
Error while scraping: https://www.tiktok.com/.tyler.mckay/video/6831781528314318085
Error while scraping: https://www.tiktok.com/.yvan/video/6813463045692607749
Error while scraping: https://www.tiktok.com/@00jung/video/6789862290242981122
Error while scraping: https://www.tiktok.com/@0nethe0ne/video/6840214670213762309
Error while scraping: https://www.tiktok.com/@08fjcruiser/video/6856554023567281413
Error while scraping: https://www.tiktok.com/@1111_2222_3333_4444/video/6850073496274455814
Error while scraping: https://www.tiktok.com/@0x41414141/video/6855464516893838597
Error while scraping: https://www.tiktok.com/@1228.7320.0528/video/6793654502370184449
Error while scraping: https://www.tiktok.com/@1228.7320.0528/video/6793700402048027905
Error while scraping: https://www.tiktok.com/@16pawmom/video/6788222884360850694
Error while scraping: https://www.tiktok.com/@178blank/video/6846243908268068102
Error while scraping: https://www.tiktok.com/@1992hondacivic/video/6825759762387356933
Error while scraping: https://www.tiktok.com/@1araquinn/video/6785255913302314246
Error while scraping: https://www.tiktok.com/@201866k/video/6824717412999384326
Error while scraping: https://www.tiktok.com/@208skindoc/video/6826091135245585670
Error while scraping: https://www.tiktok.com/@2_0_6_w_a_v_e/video/6817809104573107462
Error while scraping: https://www.tiktok.com/@222skyy/video/6802030983781616901
Error while scraping: https://www.tiktok.com/@2cantv/video/6797573845470563590
Error while scraping: https://www.tiktok.com/@2d_rice/video/6801710224886566149
Error while scraping: https://www.tiktok.com/@2doorcinemaclub/video/6849890816937200901
Error while scraping: https://www.tiktok.com/@2ubrey/video/6814592866396966150
Error while scraping: https://www.tiktok.com/@2furclouds/video/6800056749702335749
Error while scraping: https://www.tiktok.com/@3.points/video/6796471204602596613
Error while scraping: https://www.tiktok.com/@3dprinter_boi/video/6896856516280831238
Error while scraping: https://www.tiktok.com/@3fortiori/video/6827916109191073030
Error while scraping: https://www.tiktok.com/@3tubas/video/6839129095167626502
Error while scraping: https://www.tiktok.com/@414.jackson/video/6795642572812406021
Error while scraping: https://www.tiktok.com/@429_shun/video/6911640470280064258
Error while scraping: https://www.tiktok.com/@420gurn.it/video/6813529048971562246
Error while scraping: https://www.tiktok.com/@4af123/video/6832663151083900165
Error while scraping: https://www.tiktok.com/@4biddenknowledge/video/6889150350562004230
Error while scraping: https://www.tiktok.com/@5uhdude/video/6860612980749470981
Error while scraping: https://www.tiktok.com/@5thyear/video/6799280017932061957
Error while scraping: https://www.tiktok.com/@60secdocs/video/6860937307269106949
Error while scraping: https://www.tiktok.com/@5usei0/video/6826930969845435649
Error while scraping: https://www.tiktok.com/@666babyspice666/video/6851743716420504838
Error while scraping: https://www.tiktok.com/@6_9koolkid6_9/video/6804613179130268933
Error while scraping: https://www.tiktok.com/@69blade420/video/6786544749345066246
Error while scraping: https://www.tiktok.com/@6spirit9/video/6812409460317883653
Error while scraping: https://www.tiktok.com/@6trevorreese9/video/6787471070736682245
Error while scraping: https://www.tiktok.com/@6foot4honda/video/6835829375573822726

**Comment by drawrowfly** [comment]
don't use -w
