### ISSUE TITLE
getMusicInfo() Failing

### ISSUE THREAD

**Issue by tnoetzel** [drawrowfly/tiktok-scraper#462]
**Describe the bug**
The `getMusicInfo()` method is failing.

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- OS: Mac OS 11.2.1
- NodeJs Version: Node 15.0.1
- Scraper Version: 1.4.12
- CLI or Module: Node
- Used method: `getMusicInfo()`
- Used options: Tried with and without proxy on multiple URLs.

**Comment by lu3do** [comment]
https://github.com/drawrowfly/tiktok-scraper/issues/460
