### ISSUE TITLE
scraper not working

### ISSUE THREAD

**Issue by sunnydev3301** [drawrowfly/tiktok-scraper#464]
I try to run as usual the command 

$ tiktok-scraper user [user] -n -d -w --hd

returns nothing, only creates empty file in directory

**Comment by drawrowfly** [comment]
use without -w

**Comment by sunnydev3301** [comment]
![Screenshot 2021-02-26 at 15 20 36](https://user-images.githubusercontent.com/76663895/109311539-3cead980-7846-11eb-808c-a3b36a6ea399.png)

**Comment by drawrowfly** [comment]
and use without hd then

**Comment by sunnydev3301** [comment]
not working anyway

@drawrowfly
