### ISSUE TITLE
Scraper not working 

### ISSUE THREAD

**Issue by sunnydev3301** [drawrowfly/tiktok-scraper#465]
I'm using the scraper un macOS Mojave 10.14.6

I try to run as usual the command

$ tiktok-scraper user [user] -n -d -w --hd

returns nothing, only creates empty file in directory

1)
used without -w

it won't work 

![Screenshot 2021-02-26 at 15 20 36](https://user-images.githubusercontent.com/76663895/109311539-3cead980-7846-11eb-808c-a3b36a6ea399.png)

2)
used without hd then

but won't return nothing anyway

what should I do?

**Comment by sunnydev3301** [comment]
@drawrowfly could you help me?

**Comment by drawrowfly** [comment]
Use proxy

**Comment by sunnydev3301** [comment]
@drawrowfly 

still not working

**Comment by sunnydev3301** [comment]
hey @drawrowfly could you help me?
