### ISSUE TITLE
Getting user posts is broken, it returns empty collector

### ISSUE THREAD

**Issue by lu3do** [drawrowfly/tiktok-scraper#469]
The `user()` method now returns empty collection. This started a couple of hours ago.

Response:
```
{
  "headers": {
    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4284.156 Safari/537.36",
    "referer": "https://www.tiktok.com/",
    "cookie": "tt_webid_v2=6.............................3"
  },
  "collector": []
}
```

To Reproduce

Used OS
Linux
NodeJs Version (node -v)
v15.0.1
Scraper Version (tiktok-scraper --version)
tiktok-scraper@1.4.11
CLI or Module
Module
Used method
`user()`
Used options
`sessionList` and `proxy`
Do you run the scraper through Proxy, VPN, VPS?
VPS + Proxy
Preferably provide URL to the profile,hashtag,video and etc page
https://www.tiktok.com/@addisonre

**Comment by dencorg** [comment]
I can confirm this issue. It's happening from our side as well.

**Comment by alhuar** [comment]
We are getting the same issue calling the `user()` method, both from command line and module.

**Comment by drawrowfly** [comment]
Ill check it shortly

**Comment by asportnoy** [comment]
same issue here. using proxy

**Comment by llacb47** [comment]
Tiktok changed API endpoints on the site at least 2 weeks ago, so really can't blame them for disabling it now

**Comment by asportnoy** [comment]
Did some digging and found info on the new endpoint (not-required query strings omitted):
https://m.tiktok.com/api/post/item_list?aid=1988&count=COUNT&cursor=CURSOR&secUid=SECUID

CURSOR is an epoch timestamp (ms) for the cursor. You can just use the current timestamp for that. AID was always `1988` for my requests but I'm not sure if it's the same for everyone.

**Comment by drawrowfly** [comment]
Update to @1.4.13

**Comment by ambigos1** [comment]
Hi.
Using version 1.4.14 with proxy.
user method is not working, getting the error from TikTok API 
message:'400 - {"statusCode":10201}'

getUserProfileInfo methos is working properly

**Comment by DankMemeGuy** [comment]
@drawrowfly the videos are blank files (0 bytes)
