### ISSUE TITLE
Getting Trends is Broken

### ISSUE THREAD

**Issue by tnoetzel** [drawrowfly/tiktok-scraper#470]
**Describe the bug**
Calling `trend()` returns an empty collector, both with and without sessions and proxies.

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
OS: Mac OS 11.2.1
NodeJs Version: Node 15.0.1
Scraper Version: 1.4.12
CLI or Module: Node
Used method: trend()
Used options: Tried with and without `sessionList` and `proxy`

**Comment by drawrowfly** [comment]
Fixed in @1.4.14
