### ISSUE TITLE
Suddenly not able to scrape users

### ISSUE THREAD

**Issue by maxiedaniels** [drawrowfly/tiktok-scraper#471]
I'm trying to scrape users today but even though the command finishes, no file shows up. I've tried no proxy and two different proxy gateways, I've tried both post and get, not sure what's going on. Also, why doesn't tiktokscraper show any errors if a scrape attempt doesn't return anything??

**Comment by drawrowfly** [comment]
https://github.com/drawrowfly/tiktok-scraper/issues/469#issuecomment-792894998
