### ISSUE TITLE
Scraping doesn't return anything suddenly

### ISSUE THREAD

**Issue by maxiedaniels** [drawrowfly/tiktok-scraper#472]
I'm trying to scrape users today but even though the command finishes, no file shows up. I've tried no proxy and two different proxy gateways, I've tried both post and get, not sure what's going on. Also, why doesn't tiktokscraper show any errors if a scrape attempt doesn't return anything??

**To Reproduce**
- Used OS - Mac OS 10.15.7
- NodeJs Version (node -v) - v15.6.0
- Scraper Version (tiktok-scraper --version) - 1.4.12
- CLI or Module - command line
- Used method - post and also tried get
- Used options - nothing right now, I had options initially but I've tried using no options including no proxy and it still doesn't work
- Do you run the scraper through Proxy, VPN, VPS? I've tried proxies, a proxy gateway, and direct.
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles! - Yes it's public.
- user profile example: https://www.tiktok.com/@themealprepking

**Comment by maxiedaniels** [comment]
Nevermind, updated tiktokscraper to 1.4.14 and it fixed the issue. Weird!

**Comment by sunnydev3301** [comment]
hey man @maxiedaniels  I'm having the same problem could you help me?

I don't know how to run the scraper through proxy etc.

I'm using the updated version 1.4.17
