### ISSUE TITLE
user method error 

### ISSUE THREAD

**Issue by ambigos1** [drawrowfly/tiktok-scraper#473]
NodeJs Version 14.8.0
Scraper Version ^1.4.14
Used method - user

Hi.
Using version 1.4.14 with proxy.
user method is not working, getting the error from TikTok API
message:'tunneling socket could not be established, statusCode=502'

getUserProfileInfo method is working properly

![image](https://user-images.githubusercontent.com/13655768/110372198-acd33e00-8056-11eb-884e-4ad8e1424766.png)

**Comment by drawrowfly** [comment]
Update to @1.4.15

**Comment by ambigos1** [comment]
version 1.4.15
still getting error

error:{statusCode: 10201}
statusCode:10201
__proto__:Object
message:'400 - {"statusCode":10201}'
name:'StatusCodeError'


![image](https://user-images.githubusercontent.com/13655768/110382645-e0689500-8063-11eb-96a2-387396fa1ea5.png)

**Comment by drawrowfly** [comment]
change proxy
