### ISSUE TITLE
getVideoMeta is not working with latest v1.4.15

### ISSUE THREAD

**Issue by seth100** [drawrowfly/tiktok-scraper#475]
Hi,

I have a code that does the extraction of the video metadata:

```js
(async () => {
    try {
        const videoMeta = await TikTokScraper.getVideoMeta('https://www.tiktok.com/@tiktok/video/[ID]', options);
        console.log(videoMeta);
    } catch (error) {
        console.log(error);
    }
})();
```

and it was working fine with **`v1.4.12`**, but now I get:

```
Error: Can't extract video metadata: https://www.tiktok.com/@tiktok/video/[ID]
```

**To Reproduce**
- Used OS: **Ubuntu 20.10**
- NodeJs Version (node -v): `v14.15.4`
- Scraper Version (tiktok-scraper --version): **`v1.4.15`**
- CLI or Module: **module**
- Used method: **`TikTokScraper.getVideoMeta`**
- Used options: **none (default)**
- Do you run the scraper through Proxy, VPN, VPS? **No**
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles! **Yes, I tried only with public profiles!**
- Preferably provide URL to the profile,hashtag,video and etc page: **I tried many videos, it was used to work with previous v1.4.12 of the scraper.**

Thanks

**Comment by daniel-simplyphp** [comment]
+1

**Comment by drawrowfly** [comment]
Update to @1.4.16

**Comment by seth100** [comment]
I think I'm having the same issue again with latest `1.4.19`!
