### ISSUE TITLE
Redownloading videos.

### ISSUE THREAD

**Issue by reinstallgentoo** [drawrowfly/tiktok-scraper#477]
**Describe the bug**
Hi, all videos are redownloaded, every time.
The history json are present but ignored? (the directory is accessible)
No system changes other than updating tiktok-scraper from 1.4.12 to 1.4.15
Unsure what other info to provide. Thank you.

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- Used OS Ubuntu 
20.04
- NodeJs Version (node -v) 
v10.19.0
- Scraper Version (tiktok-scraper --version) 
1.4.15
- CLI or Module 
CLI 
- Used method
tiktok-scraper user "$i" -d -number 0 --store --historypath "$TTHDIR"
- Do you run the scraper through Proxy, VPN, VPS?
No
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles!
- Preferably provide URL to the profile,hashtag,video and etc page

**Comment by drawrowfly** [comment]
it will be fixed today with the new update

**Comment by reinstallgentoo** [comment]
Thanks, take my potat.

**Comment by drawrowfly** [comment]
@1.4.16
