### ISSUE TITLE
Method .user(id, options) return empty collector array

### ISSUE THREAD

**Issue by interroliq** [drawrowfly/tiktok-scraper#478]
**Describe the bug**
Looks like TikTok updated their policy. 

I added console.log inside scrapeData method and it always return error - { statusCode: 10201 }.
Is it a new update from tiktok? Or do I miss some parameters?

**To Reproduce**
- Used OS: 
macOS Big Sur v11.2.2 (or AWS Lambda with Amazon Linux 2)
- NodeJs Version: 
v14.15.4
- Scraper Version: 
v1.4.15
- CLI or Module:
Module
- Used method: 
.user(id, options) // userId I try to get 295788546777391104
- Used options: 
{ number: 30, by_user_id: true }
- Do you run the scraper through Proxy, VPN, VPS?: 
- Yes, I use Proxy
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles!
The profile is public and exists
- Preferably provide URL to the profile,hashtag,video and etc page
https://www.tiktok.com/@ba.bich_?lang=en

**Comment by drawrowfly** [comment]
use sec_uid instead of userId
