### ISSUE TITLE
Profile history file now uses the secUid as the filename

### ISSUE THREAD

**Issue by kandayo** [drawrowfly/tiktok-scraper#479]
**Describe the bug**
The profile history file now uses the user `secUid` as the filename, e.g. `<secUid>.json`. 

I noticed a weird spike in bandwidth usage on logs. It's kind of a breaking change, as it will trigger a redownload of already collected videos. Did the API stop exposing the user `id`?

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- Used OS: 
  Linux
- NodeJs Version (node -v): 
  v14.16.0
- Scraper Version (tiktok-scraper --version): 
  1.4.16
- CLI or Module: 
  CLI
- Used method: 
  `tiktok-scraper user [id]`
- Used options: 
  `--historypath <path>`
- Do you run the scraper through Proxy, VPN, VPS? 
  Yes
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles! 
  Yes

**Screenshots**

**Comment by Dreamer269** [comment]
He said on Discord that he will make an update regarding that.
