### ISSUE TITLE
Delete stored download history per user?

### ISSUE THREAD

**Issue by vnnegt** [drawrowfly/tiktok-scraper#48]
This isn't really an issue, I'm just not sure where to put questions.

Is it possible to easily delete stored download history per user?

For instance, I want to re-download a user's videos and store the download history.

How do I delete their old download history?

I'm using ubuntu. I can navigate to the tmp folder but I'm not seeing how to identify which history file belongs to which user.

Thanks

**Comment by drawrowfly** [comment]
User: tmp_folder/{USER_ID}.json
Hashtag: tmp_folder/{HASHTAG_ID}.json
Trends: tmp_folder/trend.json
Music: tmp_folder/{MUSIC_ID}.json

I will add an extra option to the CLI to show the location and history of such files

**Comment by drawrowfly** [comment]
New update released. You can now manage all history files by using **history** command right in the CLI
