### ISSUE TITLE
Get user feeds not working?

### ISSUE THREAD

**Issue by danielsGit** [drawrowfly/tiktok-scraper#481]
Actually I am trying to get posts from a specific user and here is my code.
```
const userPosts = await TikTokScraper.user(user, {
  number: 2, 
  sessionList: ['sid_tt=60ff2cfa8a1935821e32809e9bdb9f82;'] 
});
```
I am sure the sid_tt is valid and I just get it from browser cookie.
But the response is as follows.
```
{
        "headers": {
            "user-agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4221.171 Safari/537.36",
            "referer": "https://www.tiktok.com/",
            "cookie": "tt_webid_v2=681311815966110452"
        },
        "collector": []
    }
```
I tried to get hashtag feeds but it was working fine. Is there anything I got missed?
I would appreciate any help. Thanks

**Comment by Nicotroll** [comment]
I have the same issue with the TikTokScraper.user function as well, but it seems like it's intermittent. It works for a few hours then gives an empty collector like you for a few hours then starts working again later.
Very weird !
Anyone know how to solve this ?
I have the latest version 1.4.17

**Comment by drawrowfly** [comment]
use issue template!
