### ISSUE TITLE
"--timeout" does not work

### ISSUE THREAD

**Issue by j19981106** [drawrowfly/tiktok-scraper#482]
**Describe the bug**
"--timeout" does not work, there will always be some download cards that cannot continue at 1%-99%.

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- Use OS
Windows10 19042.844
- NodeJs Version (node -v)
v14.16.0
- Scraper Version (tiktok-scraper --version)
1.4.17
- CLI or Module
default
- Used method
default
- Used options 
I waited three hours for the following command, and the two threads got stuck at different percentages.
`tiktok-scraper.cmd trend -d -s -t all -n 300 --historypath "C:\Users\***\Desktop\TikTok-history"`
- Do you run the scraper through Proxy, VPN, VPS?
VPN
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles!
I'm sure it's public
- Preferably provide URL to the profile,hashtag,video and etc page
This is uncertain, I can use `video` to download
```
tiktok-scraper hashtag [id]
tiktok-scraper trend
tiktok-scraper from-file [file] [async]
```
The problematic video.
I did not test
```
tiktok-scraper user [id]
tiktok-scraper music [id]
```
Will the same problem occur.

**Screenshots**
The command used in the figure is `tiktok-scraper.cmd trend -a 1 -d -s -t all -n 300 --timeout 10000 --historypath "C:\Users\***\Desktop\TikTok-history"`.
It hasn't changed for half an hour.
![Snipaste_2021-03-12_17-52-19](https://user-images.githubusercontent.com/74053663/110923385-d09aca80-835b-11eb-832a-c1fabaee61d8.png)

**Comment by drawrowfly** [comment]
use:  
--asyncDownload, -a  Number of concurrent downloads 

--timeout is being used to on requests related to the API call not the downloading video
