### ISSUE TITLE
Scraping doesn't return anything

### ISSUE THREAD

**Issue by sunnydev3301** [drawrowfly/tiktok-scraper#486]
**Describe the bug**
I'm trying to scrape users but even though the command finishes, no file shows up.
I don't know how to run the scraper through proxy etc.
I'm using the updated version 1.4.17

## Here details

**To Reproduce**
- Used OS : MacOS Mojave 10.14.6
- NodeJs Version (node -v): v 14.16
- Scraper Version (tiktok-scraper --version):  v 1.4.17
- CLI or Module: don't know what it is
- Used method: scrape user
- Used options: tiktok-scraper user [user] -n -d -w --hd

**- Do you run the scraper through Proxy, VPN, VPS?** : Don't know how to do Could you explain me? please!

- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles!: Yes, it's Public!
- Preferably provide URL to the profile,hashtag,video and etc page

**Screenshots**

returns nothing

**Comment by drawrowfly** [comment]
use without -w --hd

**Comment by sunnydev3301** [comment]
@drawrowfly It doesn't work anyway

**Comment by drawrowfly** [comment]
Use proxy

**Comment by sunnydev3301** [comment]
Could you explain me how to use it?? @drawrowfly please! I know it's annoying.

**Comment by drawrowfly** [comment]
https://github.com/drawrowfly/tiktok-scraper/blob/master/examples/CLI/BatchDownload.md

**Comment by sunnydev3301** [comment]
hey @drawrowfly I tried several times but it returns empty files 

![Screenshot 2021-03-15 at 19 47 19](https://user-images.githubusercontent.com/76663895/111205507-99c8ec80-85c7-11eb-87aa-eddb795799e3.png)

what should I do ?

**Comment by sunnydev3301** [comment]
@drawrowfly still not working
