### ISSUE TITLE
Add support for batch users scraping

### ISSUE THREAD

**Issue by rabea98** [drawrowfly/tiktok-scraper#49]
Please add support to scrape multiple users from a text file

**Comment by drawrowfly** [comment]
will add to a to do list

**Comment by Dealsnooz** [comment]
if you can pls add support for proxy list from txt also

**Comment by drawrowfly** [comment]
Sure will be added as well

**Comment by drawrowfly** [comment]
You can now download in batch and set proxys from proxy file https://github.com/drawrowfly/tiktok-scraper#batch-scrape-and-download-example

**Comment by rabea98** [comment]
Thanks !
