### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by sasoriza** [drawrowfly/tiktok-scraper#490]
**Describe the bug**
The TikTok Scraper started message will appear and the spinner will spin for a second but no videos will be downloaded and the scraper will stop without showing any error.

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- Used OS
Windows 10 v20H2
- NodeJs Version (node -v)
v14.16.0
- Scraper Version (tiktok-scraper --version)
v1.4.12
- CLI or Module
CLI
- Used method
POST
- Used options
-d -n 0
- Do you run the scraper through Proxy, VPN, VPS?
No
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles!
Yes
- Preferably provide URL to the profile,hashtag,video and etc page
tootymcnooty

**Comment by drawrowfly** [comment]
1.4.17

**Comment by sasoriza** [comment]
Just updated. Exact same behavior

**Comment by drawrowfly** [comment]
works fine for me, try to use clean proxy

**Comment by sasoriza** [comment]
It's helpful to read the output when updating packages. The first update didn't go through because the resource was locked. It's working now. Thanks!
