### ISSUE TITLE
tiktok-scraper keeps on downloading videos with watermark whenever i told tiktok-scraper an argument without watermark

### ISSUE THREAD

**Issue by BluelyTASer** [drawrowfly/tiktok-scraper#492]
# Installations:
Latest Version of Node.js available to Ubuntu 18.04.5 LTS (installed via `sudo apt install nodejs`)
Installed Ubuntu Version Below:
![image](https://user-images.githubusercontent.com/59511669/111875169-25030300-8977-11eb-86f2-c3201a5a14f2.png)
Installed tiktok-scraper Version Below:
![image](https://user-images.githubusercontent.com/59511669/111875256-9b076a00-8977-11eb-871a-f4574db1506c.png)
# Image of that bug:
![image](https://user-images.githubusercontent.com/59511669/111875117-e66d4880-8976-11eb-89d7-a2b594eaf8cf.png)
It says `(WITH WM)` instead of `(WITHOUT WM)`.

**Comment by blasphemite** [comment]
From README - 

> As of right now it is NOT possible to download video without the watermark
