### ISSUE TITLE
TikTok-Scraper doesn't work from today

### ISSUE THREAD

**Issue by ProgrammingLife** [drawrowfly/tiktok-scraper#495]
**Describe the bug**
Tried to scrap some public acc for posts but collector.lenght is always 0-length.

**To Reproduce**
- Scraper Version: 1.4.16

```tiktok-scraper user bellapoarch -n 30 -t json --session sid_tt=asda3aa3123123123adasda```

No output out of this command.

**Screenshots**
n/a

**Comment by tonydtran** [comment]
Looks like I have a similar problem: `TikTokScraper.getUserProfileInfo` works but when I try `TikTokScraper.user` I got an empty `collector`. Everything worked fine until today. I have tried with several working proxies. I'm running on 1.4.17

**Comment by Tythiras** [comment]
I have the same issue with video collectors.
Seems like TikTok have added some new triggers for their captcha. The response always seems to be a captcha verification response, I have tried to fix it by using my browser headers and verifyFP (that generated the session) but this is not fixing it.

**Comment by bebunw** [comment]
I just tried to scrape something with the latest version and yeah it did not work, probably a  tiktok side change

**Comment by rzv** [comment]
Confirming this also on my side

**Comment by asportnoy** [comment]
![image](https://user-images.githubusercontent.com/14863373/112532781-3a14d300-8d77-11eb-94d0-202b5b592ee1.png)

**Comment by asportnoy** [comment]
Any updates on this?

**Comment by asportnoy** [comment]
Just did some testing. If you just remove the `_signature` query string from the request, it will go through.

**Comment by drawrowfly** [comment]
Latest working version @1.4.18

**Comment by tonydtran** [comment]
@drawrowfly Thanks a lot for your reactivity!
