### ISSUE TITLE
[Bug] hastag method return nothing

### ISSUE THREAD

**Issue by TheEZIC** [drawrowfly/tiktok-scraper#496]
Hastag method return nothing. I also tried to go to the endpoint API but the ItemList key is an empty array

- Windows 10
- Node v14.16.0
- Scraper Version latest (1.4.17)
- NPM module
- hastag
- No used options
- I don't use proxy, VPN etc
- https://m.tiktok.com/node/share/tag/summer

![image](https://user-images.githubusercontent.com/35061249/112625554-25e8d880-8e40-11eb-856c-95795f4f8937.png)

**Comment by Tythiras** [comment]
There has been a fix released 2 hours ago.

**Comment by TheEZIC** [comment]
Okay, thanks, that helped. What was the problem?

**Comment by youngvo** [comment]
@drawrowfly look like this issue happen again. As a favor, could you please check and resolve asap? Thanks much!
