### ISSUE TITLE
Not able to download public videos

### ISSUE THREAD

**Issue by JunkyardCat** [drawrowfly/tiktok-scraper#498]
**Describe the bug**
I tried scraping but its not working

tiktok-scraper user <enter username>

after i press enter it paused then says "tiktok scraping" then nothing. no error no nothing

```
C:\User\User\TiktokFolder> tiktok-scraper user <enter username>
Tiktok Scraper Started
C:\User\User\TiktokFolder>
```

where is the directory located?

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- Win 10
- 12
- 1.4.18
- CLI
- tiktok-scraper user <enter username>
- user
- no
- it is public because i can see its video without logging in
- 

**Screenshots**
```
C:\User\User\TiktokFolder> tiktok-scraper user <enter username>
Tiktok Scraper Started
C:\User\User\TiktokFolder>
```

**Comment by PETYSON** [comment]
Meet this issues twooo...

**Comment by drawrowfly** [comment]
Works fine for me
