### ISSUE TITLE
Download user working from CLI but not from node

### ISSUE THREAD

**Issue by andycloke** [drawrowfly/tiktok-scraper#50]
Firstly, thanks for all your awesome work on this!

I'm using the latest version (0.0.16), so I do not think it's a duplicate of this issue https://github.com/drawrowfly/tiktok-scraper/issues/44

CLI works just fine. e.g. 
```
tiktok-scraper user USERNAME -n 20 -d -store
```

Using the node method returns 0 results (was previously working). Any ideas?
```
const posts = await TikTokScraper.user(USER_ID, {
      by_user_id: true,
      user_data: true,
      number: 10,
    });
```

**Comment by andycloke** [comment]
Update - the node version does seem to work when using usernames, not user ids, e.g.
```
const posts = await TikTokScraper.user(USER_NAME, {
      user_data: true,
      number: 10,
    });
```
So maybe updating that just got missed in the 0.0.16 release?

**Comment by drawrowfly** [comment]
Regarding **by_user_id**
// Some TikTok user id's are larger then MAX_SAFE_INTEGER, you need to pass user id as a string

And it should work

Let me know

**Comment by drawrowfly** [comment]
Also new update is coming soon, with speed improvements and new features

**Comment by andycloke** [comment]
@drawrowfly, unfortunately, I am already passing `user_id` as a string and it is not working

**Comment by drawrowfly** [comment]
I did and it worked well

```
const TikTok = require('tiktok-scraper');

(async () => {
    const posts = await TikTok.user('66654060363731107901', {
        by_user_id: true,
        user_data: true,
        number: 10,
    });
    console.log(posts);
})();
```

**Comment by andycloke** [comment]
That's so strange. I tried that exact code and get `{ collector: [] }`

**Comment by drawrowfly** [comment]
Ouch my bad, this is bad user id, try please '6634543319555588102'

**Comment by andycloke** [comment]
That one works, thanks, I think the issue is I was trying to scrape an account that has no been made private, so it doesn't return anything. I'll close the issue - thanks for your help
