### ISSUE TITLE
`getVideoMeta()` and `user()` not working anymore

### ISSUE THREAD

**Issue by lu3do** [drawrowfly/tiktok-scraper#500]
**Describe the bug**
`getVideoMeta()` stopped working a couple of hours ago. it throws an error.
`user()` returns an empty collection.

## If fields below will be empty then issue will be Ignored and Closed

To Reproduce

Used OS
Linux
NodeJs Version (node -v)
v15.0.1
Scraper Version (tiktok-scraper --version)
tiktok-scraper@1.4.16
CLI or Module
Module
Used method
`getVideoMeta()`
Used options
sessionList and proxy
Do you run the scraper through Proxy, VPN, VPS?
VPS + proxy
If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles!
Yes
Preferably provide URL to the profile,hashtag,video and etc page
just any user or video.

**Screenshots**

**Comment by drawrowfly** [comment]
Check latest version

**Comment by lu3do** [comment]
Correction, i'm actually using the latest (1.4.19) version.
