### ISSUE TITLE
Unicode support for usernames

### ISSUE THREAD

**Issue by Xodarap** [drawrowfly/tiktok-scraper#502]
#28 requested support for Hebrew alphabet, and #42 and #43 implemented this for hashtags by adding `encodeURIComponent` to `getHashTagId`. I think we should do the same for usernames.

I believe this should be done in `getUserProfileInfo` – once we have the secUid we can ignore Unicode.

TikTok handles these usernames in a weird way though. It might be more complicated than just doing this.

**Comment by drawrowfly** [comment]
√

**Comment by drawrowfly** [comment]
update to @1.4.25
