### ISSUE TITLE
TikTokScraper.user returns empty collector when a proxy is used

### ISSUE THREAD

**Issue by samsebree** [drawrowfly/tiktok-scraper#504]
**Describe the bug**
I have been using tiktok-scraper for over 6 months without issues.
As of late, TikTokScraper.user is returning an empty collector when proxies are used.

When I run from my home IP, the scraper works fine.

I know what you're thinking. Your proxies have been blacklisted, try using other proxies.
This does not seem to be the case. The main proxy I use is a rotating proxy that connects to one of several million different IPs on each connection. I've tried running with this proxy endpoint hundreds of times (an endpoint which previously worked), and it always returns an empty collector.

I have also tried running with proxies from an entirely different provider. Same result.

I have tried setting the sessionList and the headers as described in the docs. Nothing changes.

TikTokScraper.user is being run with a username, not a user ID, if that is relevant.

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- Used OS
Mac OS

- NodeJs Version (node -v)
14.14

- Scraper Version (tiktok-scraper --version)
1.4.20

- CLI or Module
module

- Used method
TikTokScraper.user 

- Used options
number, proxy, sessionList, headers

- Do you run the scraper through Proxy, VPN, VPS?
Proxy

- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles!
Yes, it's public

- Preferably provide URL to the profile,hashtag,video and etc page
charlidamelio

**Screenshots**

**Comment by drawrowfly** [comment]
Can't confirm it, works fine for me. Use different proxy + try to set session

**Comment by samsebree** [comment]
Thanks for the quick reply.

As described in my post I've tried proxies from multiple sources. Would you mind letting me know what proxy provider you are using for the sake of testing on my end?

I am setting the session already.

**Comment by youngvo** [comment]
@samsebree @drawrowfly I'm having the same issue. I executed the tiktok-scraper on AWS Lambda. It returns empty result although when I run the same code locally, it works fine.
Could you please take a look @drawrowfly ?

**Comment by claudiorebernig** [comment]
Did you find a solution for the problem?
