### ISSUE TITLE
getUserProfileInfo started failing

### ISSUE THREAD

**Issue by rzv** [drawrowfly/tiktok-scraper#506]
**Describe the bug**
getUserProfileInfo fails

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
Mac OS X / Ubuntu 20
node 15.4.0
Scraper Version 1.4.18
Module
getUserProfileInfo
options: 
1. no options from several fresh ips - fails
2. with socks 5 proxies - fails
- socks 5 proxy
profile is washingtonpost

**Screenshots**
no need

**Comment by drawrowfly** [comment]
fixed in @1.4.21

**Comment by rzv** [comment]
Thank you.
Great reaction time
