### ISSUE TITLE
No longer works as of an hour ago

### ISSUE THREAD

**Issue by staticbuzz** [drawrowfly/tiktok-scraper#509]
Was working fine before about an hour ago.
Now I get Error at `TikTokScraper.getVideoMetadataFromHtml` when running from the CLI:
`tiktok-scraper video https://www.tiktok.com/@tiktok/video/6807491984882765062 -d`

I think tiktok has changed something again.

EDIT: oops updated to latest version and is working again. Sorry!!

**Comment by staticbuzz** [comment]
Updated to latest version 1.4.22 and working fine now.

**Comment by drawrowfly** [comment]
That's why -> first you check if there is and updated version and only after reporting a problem if there is any

**Comment by staticbuzz** [comment]
I did check, and I thought I had updated to latest version but forgot to run npm with the global switch. Honest mistake and I apologise. Your work is very much appreciated!!
