### ISSUE TITLE
[SECURITY] node-uuid: crypto not usable, falling back to insecure Math.random()

### ISSUE THREAD

**Issue by paulwongx** [drawrowfly/tiktok-scraper#51]
I keep getting this error when running the package and it stopped working for some reason. Reading from here that "node-uuid" dependency should be swapped out for "uuid"
https://github.com/jotform/jotform-api-nodejs/issues/20

Also, is the trending function call supposed to be random? I'm just downloading 3 videos and download the same videos 2 weeks ago and today.

**Comment by drawrowfly** [comment]
You cant get this error because this package is not using this dependency!

Also always specify version of the package and options that you are using
