### ISSUE TITLE
Proxy and SessionList values

### ISSUE THREAD

**Issue by ragul2004** [drawrowfly/tiktok-scraper#511]
Hi, Andrew. 

I have the latest ver 1.4.22. 

When I'm using Proxy (user:pass@ip:port) a hashtag feed request returns me an empty result and code (10000) and also "type: 'verify', subtype: 'slide'". As I understand it is a captcha. But sessionList: ['sid_tt=XXXXXX;'], taken from Tiktok cookies does not have any affect. 

Could you clarify what's wrong I did? Any clues

**Comment by drawrowfly** [comment]
Change proxy , the one that you are using requires captcha sovling

**Comment by ragul2004** [comment]
> Change proxy , the one that you are using requires captcha solving

I have a bunch of 200 proxies. No one works.
We refresh it two days ago.

**Comment by youngvo** [comment]
@ragul2004 for the sessionlist, in some cases you have to pass the following format:
```
const options = {
          sessionList: ['sid_tt=434830493804fdfjsd; sessionid=434830493804fdfjsd; sessionid_ss=434830493804fdfjsd;']
}; ```

Hope this helps!

**Comment by devflukeapiwat** [comment]
> @ragul2004 for the sessionlist, in some cases you have to pass the following format:
> 
> ```
> const options = {
>           sessionList: ['sid_tt=434830493804fdfjsd; sessionid=434830493804fdfjsd; sessionid_ss=434830493804fdfjsd;']
> };
> ```
> 
> Hope this helps!

It work, Thank you
