### ISSUE TITLE
Proxy getting data issues

### ISSUE THREAD

**Issue by Parallaps** [drawrowfly/tiktok-scraper#516]
@ragul2004 for the sessionlist, in some cases you have to pass the following format:
```
const options = {
          sessionList: ['sid_tt=434830493804fdfjsd; sessionid=434830493804fdfjsd; sessionid_ss=434830493804fdfjsd;']
};
```

Hope this helps!

_Originally posted by @youngvo in https://github.com/drawrowfly/tiktok-scraper/issues/511#issuecomment-813135651_

Where can I take a sid_tt, sessionid and others? Since yesterday I couldnt find "sid_tt" keys in request cookies. Using Incognito mode it returns nothing, with an TikTok auth I get sid_guard only.

Anyway, it doesn't work with proxy, only local

Which one authenticated session cookie value should I get for scraping data then?

**Comment by drawrowfly** [comment]
used sid_guard

**Comment by Parallaps** [comment]
> use sid_guard

I tried it first. It doesn't work

**Comment by Parallaps** [comment]
@drawrowfly check plz

**Comment by drawrowfly** [comment]
Nothing to check! Change proxy or set active session from your account

**Comment by youngvo** [comment]
> Where can I take a sid_tt, sessionid and others? Since yesterday I couldnt find "sid_tt" keys in request cookies. Using Incognito mode it returns nothing, with an TikTok auth I get sid_guard only.

@Parallaps By logging to Tiktok, open the web inspector, select any XHR request, in cookies section of that request, you will find sid_tt,  sessionid and sessionid_ss. Their value is the same.
