### ISSUE TITLE
getUserProfileInfo fails

### ISSUE THREAD

**Issue by rzv** [drawrowfly/tiktok-scraper#518]
Describe the bug
getUserProfileInfo fails

If fields below will be empty then issue will be Ignored and Closed
To Reproduce
Mac OS X / Ubuntu 20
node 15.4.0
Scraper Version 1.4.18
Module
getUserProfileInfo
options:

no options from several fresh ips - fails
with socks 5 proxies - fails
socks 5 proxy
profile is washingtonpost
Screenshots
no need

**Comment by Michaelmala** [comment]
Hi @rzv , did you added the session list option?

Example:

const info = await getUserProfileInfo('washingtonpost', { sessionList: ['sid_tt=*yourscode*'] });

**Comment by rzv** [comment]
I did not use sessionList for getUserProfileInfo - i thought this method was done by pure scraping.
Anyways, also tried with sessionList and it works - also checked the code and saw sessionList

Thank you very much, you can close it
