### ISSUE TITLE
Short script to download one video

### ISSUE THREAD

**Issue by Zipdox** [drawrowfly/tiktok-scraper#52]
I'm having trouble analyzing your code, would it be to much to ask you to make a script that downloads one video without a watermark? Or perhaps a workflow of how you get the watermark-free video? I'm looking to make it into youtube-dl.

**Comment by drawrowfly** [comment]
this option will be included in the CLI in the next update, that comes out shortly

**Comment by Zipdox** [comment]
That's awesome. But could you maybe make one script that only downloads videos so that I have something easier to work with?

**Comment by drawrowfly** [comment]
When i release an update you will be able to build it your self!
