### ISSUE TITLE
Get user/music posts sometimes returns empty collector

### ISSUE THREAD

**Issue by lu3do** [drawrowfly/tiktok-scraper#520]
**Describe the bug**
I'm running a check on the same sound every hour to see if the scraper is still working correctly, but lately for getting the posts of a user or music it returns an empty `collector[]`, any idea what could cause that?

**To Reproduce**
Used OS
Linux
NodeJs Version (node -v)
v15.0.1
Scraper Version (tiktok-scraper --version)
tiktok-scraper@1.4.22
CLI or Module
Module
Used method
`music()` and `user()`
Used options
sessionList and proxy
Do you run the scraper through Proxy, VPN, VPS?
VPS + proxy
If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles!
Yes
Preferably provide URL to the profile,hashtag,video and etc page
https://www.tiktok.com/music/Savage-Love-Laxed-Siren-Beat-6834110584288447237

**Screenshots**
<img width="836" alt="Schermafbeelding 2021-04-09 om 12 58 51" src="https://user-images.githubusercontent.com/482346/114171321-682c1280-9934-11eb-9a5e-33464e0c6c6c.png">

**Comment by marcelogrsp** [comment]
Same problem here... just curiosity, what service are you using that generated this screenshots? thanks

**Comment by lu3do** [comment]
@marcelogrsp Postman
