### ISSUE TITLE
feature store with avoiding duplicates

### ISSUE THREAD

**Issue by sukrosono** [drawrowfly/tiktok-scraper#521]
Hi thanks for making such a great tools.

by the manual: 
> Scraper will save the progress in the OS TMP or Custom
 folder and in the future usage will only download new
 posts avoiding duplicates      [boolean] [default: false]

I don't see an example to set these options to true.

## Expecting 
no duplicate, kinda resume feature like youtube-dl have.

If that not yet implemented maybe you can describe the current behaviour when i do fecth all video of a user.
     tiktok-scraper user blabla -t json -d -w -d --hd
The scrape seems to take so long before the download begins.
I expect the current does not download any existing video if it already on the destination.

**Comment by sukrosono** [comment]
side note, it's downloading with (with WM).
I think I do it right, CMIIW

**Comment by drawrowfly** [comment]
https://github.com/drawrowfly/tiktok-scraper/blob/master/examples/CLI/DownloadHistory.md

**Comment by drawrowfly** [comment]
https://github.com/drawrowfly/tiktok-scraper#important-notes

**Comment by sukrosono** [comment]
Oh, I see, it depends on their date, some still being downloaded without a watermark. Thanks
