### ISSUE TITLE
Hashtag download does not work

### ISSUE THREAD

**Issue by omatheusmedeiros** [drawrowfly/tiktok-scraper#528]
**Describe the bug**
Hashtag download does not work

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- Windows 10
- NodeJs Version v14.16.1
- Scraper Version 1.4.22
- CLI 
- Used method: hashtag
- Used options: tiktok-scraper hashtag hashtag_business -n 5 -z -t csv --session sid_tt=
- Do you run the scraper through Proxy, VPN, VPS? No

**Comment by drawrowfly** [comment]
#525 almost related
