### ISSUE TITLE
tiktok-scraper hashtag search failing silently

### ISSUE THREAD

**Issue by tuckstone** [drawrowfly/tiktok-scraper#529]
Hello,

Got this package working a few weeks ago, used it as follows:

`tiktok-scraper hashtag HASHTAG_NAME -t json -n 100 --session ssit_tt=randomgarbage`

I tried using it again recently in the exact same way, and it will show "Tiktok Scraper Started" momentarily before bailing back to the command line, no new files created

Same result with the `user` command.

I can get results using the trend command...

is there a way to get debug output?

**Comment by alexrainbowcookies** [comment]
I'm pretty sure that #525 is the same issue
