### ISSUE TITLE
Possible errors updating: deprecated libraries

### ISSUE THREAD

**Issue by DankMemeGuy** [drawrowfly/tiktok-scraper#532]
**Describe the bug**
I updated to 1.4.22 and got this:

```
K:\TikTok>npm i -g tiktok-scraper
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
C:\Users\name\AppData\Roaming\npm\tiktok-scraper -> C:\Users\name\AppData\Roaming\npm\node_modules\tiktok-scraper\bin\cli.js
+ tiktok-scraper@1.4.22
updated 4 packages in 8.498s
```

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- Used OS Windows
- NodeJs Version (node -v) 10
- Scraper Version (tiktok-scraper --version) 1/4/22
- CLI or Module cli
- Used method
- Used options
- Do you run the scraper through Proxy, VPN, VPS?
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles!
- Preferably provide URL to the profile,hashtag,video and etc page

**Screenshots**

**Comment by drawrowfly** [comment]
not relevant/important for the usage

**Comment by dettie** [comment]
I'm having the exact same issue.

> npm WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
> npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
> npm WARN deprecated har-validator@5.1.5: this library is no longer supported

what do you mean "not relevant/important for the usage" ? it's an error upon install... and it's not working :/
