### ISSUE TITLE
This is still working ??

### ISSUE THREAD

**Issue by BuissonArdent** [drawrowfly/tiktok-scraper#533]
**Describe the bug**
I have installed node.js (last 16+) and npm. Run with commands, it's launch perfectlly ....
But when i download a video or a all channel, it's say "tiktok-scraper working" and disepear ...

Anybody know if it works or how it works ? TY

**Comment by matedevs** [comment]
not working currently > #525

**Comment by BuissonArdent** [comment]
Okay ty. Do u know if a patch comes soon?

**Comment by BuissonArdent** [comment]
@drawrowfly Helloooo anybody there? Do think plan to make a patch, or do you abandon the project ??? Yours fans waiting at least one answer... Ty

**Comment by monty-dev** [comment]
There are forks with fixes. Check the network. I am mobile so can't reply.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by drawrowfly** [comment]
Project is not abandoned
