### ISSUE TITLE
scraping hashtag fails silently in teriminal mode, for 1.4.23 release

### ISSUE THREAD

**Issue by cnscorpions** [drawrowfly/tiktok-scraper#537]
Desc:
At tiktok-scraper 1.4.23 release, I execute 
`tiktok-scraper hashtag amazon -n 100 -t all  --session sid_tt=asdasd13123123123adasda`,
but it fails silently. 

Steps to reproduce bug:
1. log into VPS
2. install Node.js 10+
3. `tiktok-scraper hashtag amazon -n 100 -t all  --session sid_tt=asdasd13123123123adasda`
4. fails silently 😂

Env:
- OS: Ubuntu 18.04 x64
- Nodejs: v10.24.1
- Npm: 6.14.12
- Scraper Version: 1.4.23
- CLI or Module: CLI
- command: `tiktok-scraper hashtag amazon -n 100 -t all  --session sid_tt=asdasd13123123123adasda`
- Do you run the scraper through Proxy, VPN, VPS?: Vultr VPS in US

Actually, I am also using another very inefficient way to scraping Tiktok hashtags via some mobile UI automation framework + real device.
But it is slow and error-prone, and wastes my a lot time. 😥

Any help will be highly appreciated. 😆

**Comment by fengyingdian** [comment]
> Desc:
> At tiktok-scraper 1.4.23 release, I execute
> `tiktok-scraper hashtag amazon -n 100 -t all --session sid_tt=asdasd13123123123adasda`,
> but it fails silently.
> 
> Steps to reproduce bug:
> 
> 1. log into VPS
> 2. install Node.js 10+
> 3. `tiktok-scraper hashtag amazon -n 100 -t all  --session sid_tt=asdasd13123123123adasda`
> 4. fails silently 😂
> 
> Env:
> 
> * OS: Ubuntu 18.04 x64
> * Nodejs: v10.24.1
> * Npm: 6.14.12
> * Scraper Version: 1.4.23
> * CLI or Module: CLI
> * command: `tiktok-scraper hashtag amazon -n 100 -t all  --session sid_tt=asdasd13123123123adasda`
> * Do you run the scraper through Proxy, VPN, VPS?: Vultr VPS in US
> 
> Actually, I am also using another very inefficient way to scraping Tiktok hashtags via some mobile UI automation framework + real device.
> But it is slow and error-prone, and wastes my a lot time. 😥
> 
> Any help will be highly appreciated. 😆

That is bueacause the request of getting hashtagId failed!

**Comment by cnscorpions** [comment]
I will use my tk account session to have a try. Hope it works as expected. 😂 @fengyingdian

**Comment by cnscorpions** [comment]
My tk session does not work 😅, and the program still fails silently.

**Comment by drawrowfly** [comment]
Can't confirm, working fine from mine side @1.4.24
