### ISSUE TITLE
Accept proxy self-signed certs, via option "strictSSL"

### ISSUE THREAD

**Issue by bblack** [drawrowfly/tiktok-scraper#538]
**Is your feature request related to a problem? Please describe.**
Our http proxy uses a self-signed certificate. When specifying the location of that proxy in tiktok-scraper's `proxy` option, the requests fail and the `collector` returns an empty array.

**Describe the solution you'd like**
I'd like to be able to pass, along with the `proxy` option, a new option `strictSSL: false`. Since tiktok-scraper uses the `request-promise` package, which is built atop the `request` package and takes the same options, passing `strictSSL: false` would allow the self-signed certificate to be accepted, and the collector will be successfully populated.

**Comment by jcpalacios** [comment]
For this feature, it's need set in line 310 of https://github.com/drawrowfly/tiktok-scraper/blob/master/src/core/TikTok.ts
a new option param `rejectUnauthorized`

**Comment by drawrowfly** [comment]
merged

@1.4.33
