### ISSUE TITLE
tiktok-scraper module doesn't like long urls

### ISSUE THREAD

**Issue by RyonHuedepohl** [drawrowfly/tiktok-scraper#543]
**Bug description:**
Upon entering a normal TikTok URL such as [https://www.tiktok.com/@tiktok/video/6807491984882765062](https://www.tiktok.com/@tiktok/video/6807491984882765062) or [https://www.tiktok.com/@tiktok/video/6807491984882765062?sender_device=pc&sender_web_id=6946314762666001926&is_from_webapp=v1&is_copy_url=0](https://www.tiktok.com/@tiktok/video/6807491984882765062?sender_device=pc&sender_web_id=6946314762666001926&is_from_webapp=v1&is_copy_url=0) you're met with the error "Can't extract video metadata: (insert url here)" however when you use a short link such as [https://vm.tiktok.com/ZMeb45Cv2/](https://vm.tiktok.com/ZMeb45Cv2/) from the TikTok app, everything works fine. I was able to download the video successfully using CLI but it will not work through the method.

**Steps to reproduce the behavior:**
- Used OS: Ubuntu 20.04.2 LTS
- NodeJs Version (node -v): v14.16.0
- Scraper Version (tiktok-scraper --version): 1.4.23
- CLI or Module: Module
- Used method: getVideoMeta
- Used options: None
- Do you run the scraper through Proxy, VPN, VPS? No
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles!: N/A
- Preferably provide URL to the profile,hashtag,video and etc page: [https://vm.tiktok.com/ZMeb45Cv2/](https://vm.tiktok.com/ZMeb45Cv2/), [https://www.tiktok.com/@tiktok/video/6807491984882765062](https://www.tiktok.com/@tiktok/video/6807491984882765062), [https://www.tiktok.com/@tiktok/video/6807491984882765062?sender_device=pc&sender_web_id=6946314762666001926&is_from_webapp=v1&is_copy_url=0](https://www.tiktok.com/@tiktok/video/6807491984882765062?sender_device=pc&sender_web_id=6946314762666001926&is_from_webapp=v1&is_copy_url=0)

**Screenshots**
![image](https://user-images.githubusercontent.com/13386411/117587098-34d2d400-b0ea-11eb-8194-c215850cecbe.png)
![image](https://user-images.githubusercontent.com/13386411/117587114-503ddf00-b0ea-11eb-8ce2-9729afb3c239.png)
![image](https://user-images.githubusercontent.com/13386411/117587160-9c891f00-b0ea-11eb-97c3-f27b51998ed6.png)

**Comment by DiscordCatto** [comment]
All 3 links worked for me: 

Results:
![img](https://i.imgur.com/kf1WJ2J.png)

```js
const t = require("tiktok-scraper");

t.getVideoMeta("https://vm.tiktok.com/ZMeb45Cv2/")
.then(c => console.log(`URL has returned: ${c.collector.length} results.`))
.catch(e => console.log(`URL has returned an error:`, e));
```

> Most likely your IP got blocked, try using a proxy or VPN.

**Comment by Pezhvak** [comment]
@DiscordCatto confirmed, I can load all 3 links too (with proxy)

**Comment by RyonHuedepohl** [comment]
> All 3 links worked for me:
> 
> Results:
> ![img](https://camo.githubusercontent.com/be787c654e94b69c8fb27ce9ff747fd30d776dfd9dafdd694367e326a067d1d3/68747470733a2f2f692e696d6775722e636f6d2f6b6631574a324a2e706e67)
> 
> ```js
> const t = require("tiktok-scraper");
> 
> t.getVideoMeta("https://vm.tiktok.com/ZMeb45Cv2/")
> .then(c => console.log(`URL has returned: ${c.collector.length} results.`))
> .catch(e => console.log(`URL has returned an error:`, e));
> ```
> 
> > Most likely your IP got blocked, try using a proxy or VPN.



> @DiscordCatto confirmed, I can load all 3 links too (with proxy)

Without proxies are you both able to fetch the first link but not the others?

**Comment by DiscordCatto** [comment]
> > All 3 links worked for me:
> > Results:
> > ![img](https://camo.githubusercontent.com/be787c654e94b69c8fb27ce9ff747fd30d776dfd9dafdd694367e326a067d1d3/68747470733a2f2f692e696d6775722e636f6d2f6b6631574a324a2e706e67)
> > ```js
> > const t = require("tiktok-scraper");
> > 
> > t.getVideoMeta("https://vm.tiktok.com/ZMeb45Cv2/")
> > .then(c => console.log(`URL has returned: ${c.collector.length} results.`))
> > .catch(e => console.log(`URL has returned an error:`, e));
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > > Most likely your IP got blocked, try using a proxy or VPN.
> 
> > @DiscordCatto confirmed, I can load all 3 links too (with proxy)
> 
> Without proxies are you both able to fetch the first link but not the others?

all requests was made without a proxy.

**Comment by drawrowfly** [comment]
Working fine from mine side as-well
