### ISSUE TITLE
getMusicInfo not working

### ISSUE THREAD

**Issue by Pezhvak** [drawrowfly/tiktok-scraper#551]
**Describe the bug**

```
await TikTokScraper.getMusicInfo('https://www.tiktok.com/music/doja-x-calabria-6882925279036066566', {
    proxy: proxy,
});
```

returns:
```
Can't find music data: doja-x-calabria-6882925279036066566
```

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- Used OS: Mac, Ubuntu
- NodeJs Version (node -v) 15.8.0
- Scraper Version (tiktok-scraper --version) 1.4.23
- CLI or Module Both
- Used method getMusicInfo
- Used options proxyOnly
- Do you run the scraper through Proxy, VPN, VPS? YES
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles! YES
- Preferably provide URL to the profile,hashtag,video and etc page: https://www.tiktok.com/music/doja-x-calabria-6882925279036066566

**Screenshots**

**Comment by nikolamajmunovic** [comment]
+1

**Comment by Andrew214-dot** [comment]
Hi,
        I created  the file for batchdownload and name is tklinks.txt then Where should i place Batch file for that pick links from that batch file by following command ( tiktok-scraper from-file tklinks 5 -d --filepath Desktop)

**Comment by drawrowfly** [comment]
Can't confirm, working fine from mine side

"https://www.tiktok.com/music/doja-x-calabria-6882925279036066566" not a valid url
