### ISSUE TITLE
run command and disapper

### ISSUE THREAD

**Issue by ztza** [drawrowfly/tiktok-scraper#552]
**Describe the bug**
I have installed node.js (v14.16.1) and tiktok-scraper(1.4.23). Run with commands, it's launch perfectlly ....
But when i download a video or a all channel, it's say "tiktok-scraper working" and disepear ...

Anybody know if it works or how it works ? Thanks

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- Used OS: Mac
- NodeJs Version (node -v):v14.16.1
- Scraper Version (tiktok-scraper --version):1.4.23
- CLI or Module: CLI
- Used method
- Used options
- Do you run the scraper through Proxy, VPN, VPS? Yes
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles! It is public profile.
- Preferably provide URL to the profile,hashtag,video and etc page. https://www.tiktok.com/@gnb.official?
<img width="965" alt="Screen Shot 2021-05-17 at 7 05 40 PM" src="https://user-images.githubusercontent.com/19197552/118479129-3c762680-b743-11eb-9f9e-cc57633aab5a.png">

**Screenshots**

**Comment by videoprice** [comment]
Same problem here. Before 2 months this script works perfect

**Comment by drawrowfly** [comment]
Works fine from mine side. Use high quality proxy
