### ISSUE TITLE
noWaterMark option not working

### ISSUE THREAD

**Issue by iftekhs** [drawrowfly/tiktok-scraper#555]
Hey my nowatermark option dosent work on video :(  
![image](https://user-images.githubusercontent.com/77227045/118964199-0fb35080-b989-11eb-9f7a-e5f02d9531f2.png)

**Comment by sixem** [comment]
This is not an issue that they are unaware of. If you would read the README under **Important notes,** you would see that:

`As of right now it is NOT possible to download video without the watermark`.

**Comment by iftekhs** [comment]
OK, so they are fixing it currently?

**Comment by asportnoy** [comment]
Unless another way to do it is found, it is not fixable.

**Comment by rosnaib11** [comment]
how come some other top tiktok downloading site are still able to download tiktok videos without watermark? Are they using third party tool? Any Idea?

**Comment by iftekhs** [comment]
> how come some other top tiktok downloading site are still able to download tiktok videos without watermark? Are they using third party tool? Any Idea?

Yes i think they are using most probably a paid tool.
