### ISSUE TITLE
Trends scraping

### ISSUE THREAD

**Issue by MilicaCvet** [drawrowfly/tiktok-scraper#556]
Hello, I have an issue with the tiktok-scraper trend command. I used it to return a span from 100 to 10,000 records and it worked good up until a couple of weeks ago. Now when I run it, it executes in a second and stops without printed errors, returning up to about 400 records, regardless of the number entered. Is it an API issue, a change in the max capacity or something else? Thanks!

OS Windows 10

**Comment by drawrowfly** [comment]
TikTok api limitations+ the more hq proxies the lower chances of getting blocked by the tiktok
