### ISSUE TITLE
Trend from a language or country

### ISSUE THREAD

**Issue by Conexur** [drawrowfly/tiktok-scraper#557]
Hi:

This script really rock, thanks!

When I run the command trend, Tiktok uses the server ip to geotag me and get a list of videos from this specific country and language.
I saw in TikTok homepage you can set the language adding the 2 letter ISO code of the language at the end, example: www.tiktok.com/en, www.tiktok.com/es, etc. It is possible to set this as endpoint of this script?

Thanks.

**Comment by drawrowfly** [comment]
The best approach is to set IP, i have tested with RU, US and got my current location trends only
