### ISSUE TITLE
[Question/Bug] Downloading favorited videos using tiktok's GDPR data export

### ISSUE THREAD

**Issue by dvdcd** [drawrowfly/tiktok-scraper#561]
Hey! 
I'm currently trying to use tiktok scraper to download all of my favorited videos from my account, to archive them.
I requested and downloaded a data package from tiktok's GDPR data export function, which contained a list of my favorited videos. I then converted the json file from the export into a text file with the links each on their own line

The links contained in the data export are formatted as follows:
`https://www.tiktokv.com/share/video/6951866814787833094/`

I then tried to download these by piping it in using this command:
`tiktok-scraper from-file favorites.txt 5 -d`
However, upon doing so it appears that tiktok-scraper doesn't correctly identify the links. I received a `Error while scraping` message for each link, and in the table printed at the end, each link's type was labeled as \`user\` 

When this failed, I tried to input the same link through 
`tiktok-scraper video https://www.tiktokv.com/share/video/6951866814787833094/ -d` and it worked flawlessly. 

It's also unclear to me if videos with their download option off in tiktok are still downloaded.

I'm using Node v14.17.0 x64 and tiktok-scraper v1.4.24
Thank you for your help and tool!

**Comment by asportnoy** [comment]
You can use the format `https://m.tiktok.com/v/VIDEO_ID/`, eg [https://m.tiktok.com/v/6951866814787833094/](https://m.tiktok.com/v/6951866814787833094/). You should be able to get them in this format with a simple find & replace.

**Comment by dvdcd** [comment]
I changed the format and ran `tiktok-scraper from-file favorites.txt 5 -d` again, however it's still giving the same errors as before and reporting the link's type as \'user\'

**Comment by asportnoy** [comment]
It's possible that the bulk parsing will only work with the `https://tiktok.com/@user/video/id` format, but I'm not positive. If so, you would be able to get that format by opening the link in your browser, which would redirect you to a URL in that format.

**Comment by dvdcd** [comment]
That does work, however opening each one of the 500 video links i would like to download seems unfeasible.

I did try just putting literally @user in (`https://tiktok.com/@user/video/6951866814787833094`) and that does work, but it would be nice if support for the `https://tiktokv.com/share/video/id/ ` and `https://m.tiktok.com/v/id/` formats were added.

**Comment by dvdcd** [comment]
It also appears that not only do those other forms not work, but `https://tiktok.com/@user/video/6951866814787833094/` doesn't work while `https://tiktok.com/@user/video/6951866814787833094` does

**Comment by drawrowfly** [comment]
Because **from-file** method thinks that this URL https://www.tiktokv.com/share/video/6951866814787833094/ is a **user** method, when i created this method tiktok didn't had this URL format. I will adjust it in the next update

**Comment by drawrowfly** [comment]
update to @1.4.25
