### ISSUE TITLE
User media not working

### ISSUE THREAD

**Issue by noorhackie** [drawrowfly/tiktok-scraper#562]
Always returning empty collector.

**Comment by asportnoy** [comment]
Same issue here, using rotating residential proxies.

**Comment by noorhackie** [comment]
@drawrowfly Please make some sulution for it.

Thanks a lot in advance.

**Comment by asportnoy** [comment]
Found a fix, will work on a PR now.

**Comment by asportnoy** [comment]
@drawrowfly #563 fixes this issue, please merge when you have a chance!

**Comment by noorhackie** [comment]
@asportnoy Thank you so much

**Comment by asportnoy** [comment]
I put instructions to apply this fix for yourself temporarily in the PR.
