### ISSUE TITLE
Empty collector array in the response.

### ISSUE THREAD

**Issue by Fyp89** [drawrowfly/tiktok-scraper#565]
Updated the tiktok-scraper node package to use the latest version. Earlier it worked fine when it didn't needed any sessionList as a parameter.

Passed the sid_tt value in sessionList parameter , got it from my logged in user account just as described in the docs.

No matter what function I call be it either getUserProfileInfo, user or trend. I always get the empty array against the collector array.

Is it working for anyone else, I am just not able to get any videos from the server even when I pass the correct session id.

**Comment by ambigos1** [comment]
Somehow today I am facing a problem with fetching videos...
also after updating to the latest version ^1.4.24
Is this issue closed because it were fixed?

**Comment by Fyp89** [comment]
@drawrowfly was this issue fixed ?

**Comment by hirezz** [comment]
I'm also having this problem. Running version 1.4.23 and v12.22.1. of node.
Encountered the problem using my session ID and VPNs. Still nothing.
