### ISSUE TITLE
CLI usage problem for downloading video according to username

### ISSUE THREAD

**Issue by 369855707** [drawrowfly/tiktok-scraper#567]
**Describe the bug**
my goal is downloading the videos under an username, my command was like :
tiktok-scraper user abram_draws -d -n 100 --session sid_tt=92a12c296cd678c69966cb998c06dfe9
only see tiktok-scraper is starting, then nothing happend after, no files were downloaded in my local
anyone know what's wrong with my command? I fetch the latest sid_tt from console

**To Reproduce**
- Used Mac OS
- NodeJs Version (v12.6)
- Scraper Version (1.4.24)
- CLI

- Do you run the scraper through Proxy, VPN, VPS? 
I used VPN

**Comment by DiscordCatto** [comment]
This has been fixed, it just hasn't been updated on npm yet for people to update their projects with. 

However you could add the temp-fix yourself. 
```bash
npm root -g
```
-> Find your npm global folder. 

Then find the `tiktok-scraper` folder and follow the steps listed [here](https://github.com/drawrowfly/tiktok-scraper/pull/563#issuecomment-852264427)

**Comment by drawrowfly** [comment]
I have checked current version 1.4.24 and it is working fine from mine side!
