### ISSUE TITLE
please make some changes for max usefulness

### ISSUE THREAD

**Issue by raisedhand** [drawrowfly/tiktok-scraper#568]
hi Andrew ,
please manipulate project below to your project & add deploy to heroku button in readme.md file badge.this project is only one file can do auto download all videos of some youtube channel and crop it into parts of 40 s to post them to the tik tok. or just only work with direct links as input .
https://github.com/freQuensy23-coder/TikTok-content-farm
waiting for your response
finest regards

**Comment by drawrowfly** [comment]
Do not have any plans for such feature . PR is welcome
