### ISSUE TITLE
No info returned

### ISSUE THREAD

**Issue by OscarHedeby** [drawrowfly/tiktok-scraper#572]
**Describe the bug**
´No information is retuned when on trend('', options) or hashtag('HASHTAG', options). Event with the bare minimum code required, returns no info from the tiktok servers.

only receiving:
{
  headers: {
    'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4185.160 Safari/537.36',
    referer: 'https://www.tiktok.com/',
    cookie: 'tt_webid_v2=686356946336759721'
  },
  collector: []
}

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- Used OS
Windows 10 and macOS big sur
- NodeJs Version (node -v)
Node js version 16.1.0
- Scraper Version (tiktok-scraper --version)
tiktok-scraper version: 1.4.25
- CLI or Module
Both CLI and Module
- Used method
trend('', options) and hashtag('HASHTAG', options)
- Used options
Both with a proxy, custom sessionList
- Do you run the scraper through Proxy, VPN, VPS?
Tried through a proxy and a VPN

Code to reproduce
const TikTokScraper = require("tiktok-scraper");

async function test() {
  try {
    const value = await TikTokScraper.trend("", {
      number: 10,
      sessionList: ["sid_tt=custom sid_tt;"],
    });
    console.log(value);
  } catch (error) {
    console.log(error);
  }
}

test();

I have tried just about anything, but am i missing something?

**Comment by drawrowfly** [comment]
Can't confirm the issue, everything is working from mine side. Use proxies

**Comment by ambigos1** [comment]
> Can't confirm the issue, everything is working from mine side. Use proxies

Geo-surf residential proxy is good for scraping videos links of user?
