### ISSUE TITLE
Fontconfig error: Cannot load default config file

### ISSUE THREAD

**Issue by fanrenaz** [drawrowfly/tiktok-scraper#574]
**Describe the bug**

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- Used OS: CentOS 8
- NodeJs Version (node -v): 16.3.0
- Scraper Version (tiktok-scraper --version): 1.4.25
- CLI or Module
- Used method: Both from file and from user.
- Used options
- Do you run the scraper through Proxy, VPN, VPS? It does not work either using proxy or not.
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles! Yes, I checked.
- Preferably provide URL to the profile,hashtag,video and etc page

**Screenshots**
![image](https://user-images.githubusercontent.com/51114968/121294392-e3ec1080-c91f-11eb-99ac-60250457ed72.png)

**Comment by drawrowfly** [comment]
https://discord.com/channels/757973862733316127/757978804567277622/846051958406250498
