### ISSUE TITLE
Video files not working

### ISSUE THREAD

**Issue by asportnoy** [drawrowfly/tiktok-scraper#576]
**Describe the bug**
1.4.27 broke video files due to the change in cookies.
Previously the `tt_webid_v2` cookie was set here https://github.com/drawrowfly/tiktok-scraper/blob/7f76e1f5395477cde9297ffdbce1337809b5e914/src/entry.ts#L44-L49 but due to the changes in this update that was removed https://github.com/drawrowfly/tiktok-scraper/blob/944b19b04b7e97e6df05c024958693a1fb344df6/src/entry.ts#L44-L47 This means there is no webid sent with the request nor returned in the headers, therefore resulting in a failed download.

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- Used OS: Ubuntu 20
- NodeJs Version (node -v) v14.16.0
- Scraper Version (tiktok-scraper --version) 1.4.27
- CLI or Module: Module but people on Discord are having the same issue with the CLI
- Used method: `getVideoMeta`
- Used options: proxy
- Do you run the scraper through Proxy, VPN, VPS? proxy
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles! Yes
- Preferably provide URL to the profile,hashtag,video and etc page Any

Again, this worked before updating.

**Comment by drawrowfly** [comment]
Ouch. Forgot to pass cookie jar to Download.ts

**Comment by drawrowfly** [comment]
Update to @1.4.28

**Comment by asportnoy** [comment]
I mentioned this on the Discord but I'm putting it here too so it doesn't get lost. `.getVideoMeta` works after updating but `.user` has the same issue as with the video meta before.

**Comment by asportnoy** [comment]
@drawrowfly if you could reopen this that would be great.

**Comment by asportnoy** [comment]
`.user` fixed with 1.4.31
