### ISSUE TITLE
Everything works except `getMusicInfo()`

### ISSUE THREAD

**Issue by lu3do** [drawrowfly/tiktok-scraper#577]
**Describe the bug**
All methods seem to work except for `getMusicInfo()`, 
I think it has been broken for a while now.

**To Reproduce**
Used OS
**Linux**
NodeJs Version (node -v)
**v15.0.1**
Scraper Version (tiktok-scraper --version)
**tiktok-scraper@1.4.27**
CLI or Module
**Module**
Used method
`getMusicInfo()`
Used options
**sessionList and proxy**
Do you run the scraper through Proxy, VPN, VPS?
**VPS + proxy**
If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles!
**Yes**
Preferably provide URL to the profile,hashtag,video and etc page
https://www.tiktok.com/music/Savage-Love-Laxed-Siren-Beat-6834110584288447237

Tested it like this (removed the actual sessionId and proxy for obvious reasons)
```
TikTokScraper.getMusicInfo('https://www.tiktok.com/music/Savage-Love-Laxed-Siren-Beat-6834110584288447237' , {
          sessionList: 'sid_tt=xxxxxxxxxxx',
          proxy: '123.456.789:000'
});
```
The result:
 ```
 Can't find music data: Savage-Love-Laxed-Siren-Beat-6834110584288447237
 ```

**Comment by drawrowfly** [comment]
Update to @1.4.28

**Comment by AsherHandaly** [comment]
I'm having the same issue with version 1.4.28. Everything works correctly when running locally, but getMusicInfo always fails when called from a Firebase cloud function. I've tried proxies, VPC, session ids, but nothing is working. Any ideas?
