### ISSUE TITLE
Can't load video meta if url part with username contains dot

### ISSUE THREAD

**Issue by dlyakin** [drawrowfly/tiktok-scraper#58]
In terminal:
https://www.tiktok.com/@maevaa.ghennam/video/6805591629471173894
Bad url format. Correct format: https://www.tiktok.com/@USERNAME/video/ID
In code regex:
if (!/^https:\/\/www\.tiktok\.com\/@(\w+)\/video\/(\d+)$/.test(this.input)) {
            throw `Bad url format. Correct format: https://www.tiktok.com/@USERNAME/video/ID`;
        }
Part w+ equals [a-zA-Z0-9]+

**Comment by drawrowfly** [comment]
Oh right forgot about dots and underscores

Will fix it

**Comment by drawrowfly** [comment]
fixed in the last update
