### ISSUE TITLE
--noWaterMark not work

### ISSUE THREAD

**Issue by iBinh** [drawrowfly/tiktok-scraper#581]
**Describe the bug**

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- Mac OS
- NodeJs Version 16.3.0
- Scraper Version 1.4.30
- CLI
- Used method: download video without watermark
- Used options: -w -d
- Do you run the scraper through Proxy, VPN, VPS? No
- Public profile
- https://www.tiktok.com/@tiktok/video/6807491984882765062

**Comment by drawrowfly** [comment]
https://github.com/drawrowfly/tiktok-scraper#important-notes
