### ISSUE TITLE
VideoURL returns 403 even after I set headers

### ISSUE THREAD

**Issue by davut** [drawrowfly/tiktok-scraper#583]
I am trying to download the video from the videoURL but getting 403 respond even after I set headers -> "Failed to load resource: the server responded with a status of 403 (Forbidden)" 

Example:

```js
const videoURL = "https://v16-web.tiktok.com/video/tos/useast2a/tos-useast2a-ve-0068c004/5e5141997513458d943ca08f529d4384/?a=1988&br=5392&bt=2696&cd=0%7C0%7C1&ch=0&cr=0&cs=0&cv=1&dr=0&ds=3&er=&expire=1623385302&l=20210610222042010190219071592BD300&lr=tiktok_m&mime_type=video_mp4&net=0&pl=0&policy=2&qs=0&rc=amdrODZpcTtzNTMzNzczM0ApNDg6NTg7OTw2NzU6OTw8OWc0MHAuYGtnaXFgLS1kMTZzc2MvLS1fMy5jYy9hYS02LWA6Yw%3D%3D&signature=1135ce893be2db97a4ca5efda6f494fd&tk=tt_webid_v2&vl=&vr="
fetch(videoURL, {
 method: "GET",
 headers: {
  'user-agent': 'Mozilla/5.0 ...'
  'referer': 'https://www.tiktok.com/',
  'cookie': 'sid_tt=9f...........; tt_csrf_token=IQ...........'
 }
}
```

Would be happy if you could help.

Thanks

**Comment by dvird** [comment]
Im getting this also without headers

**Comment by davut** [comment]
> Im getting this also without headers

Hey @dvird have you tried with headers?

**Comment by dvird** [comment]
@davut yes.
with different agents and more

**Comment by davut** [comment]
> @davut yes.
> 
> with different agents and more.
> 
> 
> 
> after investigating it, its a global issue because a new change of tiktok, but still some services know to extract it well

@dvird Can you help me? I'm kinda new to web world. While extracting the videoMetaData I also set the headers when I try to download the video but I get 403 error. Would be happy if you could help

**Comment by dvird** [comment]
you need to make sure you download with the same headers you've fetched the data.
read the readme file of this project

**Comment by asportnoy** [comment]
Could you show your full code? Including where you get the header values (you don't have the actual values). Also please provide the version info and other details requested in the [bug report template](https://github.com/drawrowfly/tiktok-scraper/issues/new?template=bug_report.md).

**Comment by drawrowfly** [comment]
Working fine in the latest version @1.4.31 (checked few times all methods)
