### ISSUE TITLE
Where are files downloaded to???

### ISSUE THREAD

**Issue by Berki2021** [drawrowfly/tiktok-scraper#584]
Sorry to ask this question, but I have zero clue where my files ares downloaded to. I just scarped a profile but have zero clue where to find the files...

**Comment by drawrowfly** [comment]
Same folder where you have started the scraper

**Comment by Davey111** [comment]
For example, in my case when returning the hashtags from a video I didn't want to return any of the variations on "#foryou, #4u, #foryou" etc so I created a blacklist to filter them out from my array.

![example](https://i.gyazo.com/1033ba083f2ed2b93a314153dfb0ca48.png)

In your case, the code would be even simpler as you're only checking a single string and not an entire array. You would also run your code **before** tiktok-scraper is even called and if a match is found return the request with an error code.
