### ISSUE TITLE
Empty video files when bulk scraping

### ISSUE THREAD

**Issue by normanlol** [drawrowfly/tiktok-scraper#585]
**Describe the bug**
When bulk downloading profiles with a fresh session ID, only certain videos are actually downloaded.
The video files are produced but the majority of files are never actually completed, with only some actually downloaded.

![image](https://user-images.githubusercontent.com/41760554/121792555-79a7ca00-cbc4-11eb-848d-1f96e0984a0d.png)

**To Reproduce**
- Used OS ``Windows 10``
- NodeJs Version (node -v) ``v15.13.0``
- Scraper Version (tiktok-scraper --version) ``1.4.30``
- CLI or Module ``cli``
- Used method ``bulk scraping``
- Used options ``tiktok-scraper from-file ./tasks.txt 1 -d -f all --session sid_tt=[redacted];``
- Do you run the scraper through Proxy, VPN, VPS? ``yes, tried with and without``
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles! ``yes``
- Preferably provide URL to the profile,hashtag,video and etc page ``it's with any option i try``

**Comment by drawrowfly** [comment]
Try to update to version @1.4.31

I have tested and do not have problems from mine side, if you are scraping a lot of data then try to use proxies as it is shown here https://github.com/drawrowfly/tiktok-scraper/blob/master/examples/CLI/BatchDownload.md

**Comment by drawrowfly** [comment]
Soon i will add debugging option

**Comment by normanlol** [comment]
@drawrowfly now it's downloading some completely, and others be ~350 bytes of data, and the scraper considers the profile complete

![image](https://user-images.githubusercontent.com/41760554/121816876-237e6980-cc4c-11eb-9e74-fab1a75ac4dd.png)

**Comment by normanlol** [comment]
upon opening the file, some files are not downloading properly 

```
<HTML><HEAD>
<TITLE>Access Denied</TITLE>
</HEAD><BODY>
<H1>Access Denied</H1>
 
You don't have permission to access "[url]" on this server.<P>
Reference&#32;&#35;18&#46;bf9233b8&#46;1623605839&#46;12923de
</BODY>
</HTML>
```
