### ISSUE TITLE
381 bytes

### ISSUE THREAD

**Issue by asdfok** [drawrowfly/tiktok-scraper#588]
**Describe the bug**
most of the videos downloaded is only 381 bytes.
## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- Used OS = Windows 10 Pro 64 bit
- NodeJs Version (node -v) = v14.17.0
- Scraper Version (tiktok-scraper --version) = 1.4.31
- CLI or Module = CLI
- Used method = tiktok-scraper user officialtrans7
- Used options = -d
- Do you run the scraper through Proxy, VPN, VPS? = No
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles! = Yes, it's public profile.
- Preferably provide URL to the profile,hashtag,video and etc page = https://www.tiktok.com/@officialtrans7?lang=en

**Screenshots**
If applicable, add screen
![Screenshot - 15_06_2021 , 18_08_53](https://user-images.githubusercontent.com/20973422/122042781-c7127a00-ce04-11eb-8340-76eca9b46638.png)
shots to help explain your problem.

**Comment by AplhaSlayer1964** [comment]
Same problem here. Was going to add a feature request to check if file downloaded file is less then 1KB if so count as failed.

**Comment by asportnoy** [comment]
Follow the instructions on the readme for downloading videos

**Comment by asdfok** [comment]
> Follow the instructions on the readme for downloading videos

Hi, this is not my first time using this. I don't remember maybe 2 months ago, everything is perfect. I redownloaded with commands like on the readme file. 
`tiktok-scraper user officialtrans7 -d -n 100 sid_tt=xxx`
giving the same result.
![Screenshot - 16_06_2021 , 18_12_35](https://user-images.githubusercontent.com/20973422/122209486-c514ed80-cece-11eb-8eaa-7dd83beea21a.png)

**Comment by chowfranco** [comment]
experienced the same thing. was successful downloading a few days ago but it won't succeed this time around.

**Comment by sourmilk01** [comment]
Have the same issue, using latest version.

**Comment by whoamikyo** [comment]
On `C:\Users\<youruser>\AppData\Roaming\npm\node_modules\tiktok-scraper\build\core\` folder, edit the Tiktok.js file

like that:

![img](https://media.discordapp.net/attachments/757978804567277622/854081747918782494/b54bbe9b6b159166d91b9ed66f5af17e.png)

Thanks for Sour, from discord group.

**Comment by asdfok** [comment]
> On `C:\Users\<youruser>\AppData\Roaming\npm\node_modules\tiktok-scraper\build\core\` folder, edit the Tiktok.js file
> 
> like that:
> 
> ![img](https://camo.githubusercontent.com/5209bfbe87aa51c4c5077ba6730520c7ebffda5591ce71dbaeb4903b3a55c62d/68747470733a2f2f6d656469612e646973636f72646170702e6e65742f6174746163686d656e74732f3735373937383830343536373237373632322f3835343038313734373931383738323439342f62353462626539623662313539313636643931623965643636663561663137652e706e67)
> 
> Thanks for Sour, from discord group.

Thanks, it's working now.

**Comment by drawrowfly** [comment]
woops i forgot to push this commit with the latest version https://github.com/drawrowfly/tiktok-scraper/commit/4c4e700be7ef9af33888498c475a351b72fdfc3f

**Comment by asdfok** [comment]
Thanks. It's working now.

> On `C:\Users\<youruser>\AppData\Roaming\npm\node_modules\tiktok-scraper\build\core\` folder, edit the Tiktok.js file
> 
> like that:
> 
> ![img](https://camo.githubusercontent.com/5209bfbe87aa51c4c5077ba6730520c7ebffda5591ce71dbaeb4903b3a55c62d/68747470733a2f2f6d656469612e646973636f72646170702e6e65742f6174746163686d656e74732f3735373937383830343536373237373632322f3835343038313734373931383738323439342f62353462626539623662313539313636643931623965643636663561663137652e706e67)
> 
> Thanks for Sour, from discord group.

**Comment by thienlq** [comment]
Hi, I meet same thing, edited the Tiktok.js file already
If I run cli with -n  <30 it's working fine(video downloaded ok). 
But if run cli without -n(meaning download all) or n>=50 for example, just only 1 video can download, others video file just 377 bytes
Anybody who met the same thing? how can we download all videos now, or can we download like "paging" (30 rec/page)?
