### ISSUE TITLE
Can't get user profile info

### ISSUE THREAD

**Issue by Michaelmala** [drawrowfly/tiktok-scraper#589]
**Describe the bug**

The method ".getUserProfileInfo(username)" always throw the error "Can't extract user metadata from the html page. Make sure that user does exist and try to use proxy".
I logged the response of the ".request()" method in ".getUserProfileInfo(username)" in /build/core/TikTok.js file and i always get this html body:

`<body class="notranslate"><div id="root"></div><div id="iphoneX"></div><noscript>You need to enable JavaScript to run this page.</noscript><script type="text/javascript" src="//sf16-scmcdn-va.ibytedtos.com/goofy/ies/tiktok_webapp_login/common/vendor.cf8aa0c3.js"></script><script type="text/javascript" src="//sf16-scmcdn-va.ibytedtos.com/goofy/ies/tiktok_webapp_login/index.e7f428eb.js"></script></body>`

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- Used OS macOS
- NodeJs Version (node -v) v14.17.0
- Scraper Version (tiktok-scraper --version) 1.4.31
- CLI or Module Module
- Used method .getUserProfileInfo()
- Used options none
- Do you run the scraper through Proxy, VPN, VPS? no
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles! public profile
- Preferably provide URL to the profile,hashtag,video and etc page https://www.tiktok.com/@goshuaaa?

**Screenshots**

<img width="900" alt="Schermata 2021-06-15 alle 21 00 15" src="https://user-images.githubusercontent.com/62499654/122109078-40b66200-ce1d-11eb-90cb-aa38f859d7ea.png">

**Comment by ThaDeveloper** [comment]
I'm also facing the same issue. Hope we get  fix soon

**Comment by asportnoy** [comment]
Works fine for me. Use proxy.

**Comment by bakteribaik** [comment]
how to add the proxy?

**Comment by mishael1-d** [comment]
So please how can someone add proxy?

**Comment by ugurberkecan** [comment]
I added some custom proxies but problem is same

**Comment by crazould** [comment]
I added some custom proxies but problem is same
