### ISSUE TITLE
HTTP Proxy seems not working, only HTTPS or SOCKS4/5 works

### ISSUE THREAD

**Issue by brucedeng** [drawrowfly/tiktok-scraper#59]
Tried a few http proxy and it will always fail. (I suspect it might be related to https over http).

**Comment by drawrowfly** [comment]
Please follow do Bug Template!

How do u set it what version of the scraper ?

**Comment by brucedeng** [comment]
using the latest GitHub version.

Here is a few proxy I tested today:


And a few errors:
tiktok-scraper trend -n 100 -p 206.81.1.199:80  --filepath trend/ -t all
Error: tunneling socket could not be established, statusCode=400



tiktok-scraper trend -n 100 -p 45.55.27.15:8080  --filepath trend/ -t all
Error: tunneling socket could not be established, statusCode=400


tiktok-scraper trend -n 100 -p 206.81.1.199:80  --filepath trend/ -t all
Error: tunneling socket could not be established, statusCode=503

**Comment by drawrowfly** [comment]
To use socks proxy you need to enter: socks5://1.1.1.1:90

Also tiktok web api won't work with IPV6 proxies
