### ISSUE TITLE
nowatermark download does not work

### ISSUE THREAD

**Issue by kingdeking** [drawrowfly/tiktok-scraper#590]
**Describe the bug**
Downloading video without the watermark doesnt work.

**To Reproduce**
run in windows terminal:
tiktok-scraper video https://www.tiktok.com/@_rl9/video/6969985869620972805 -d -w --hd
the video downloaded will have watermark but it should not.

Windows 10
nodeJS Version v14.16.1
scraper version 1.4.31
used method: tiktok-scraper video https://www.tiktok.com/@_rl9/video/6969985869620972805
used options: -d -w --hd

**Comment by sixem** [comment]
[https://github.com/drawrowfly/tiktok-scraper#important-notes](https://github.com/drawrowfly/tiktok-scraper#important-notes)
