### ISSUE TITLE
Scrapped result 0 although using proxies to make requests

### ISSUE THREAD

**Issue by zbtzero7** [drawrowfly/tiktok-scraper#593]
**Command:** tiktok-scraper from-file F:\Tiktoks_using_NodeJS\tt_user_lists\tt_user_short_list.txt 5 --proxy-file F:\Tiktoks_using_NodeJS\Proxies\1.0_Proxies.txt -f -t csv

**Output:**

│(index)  |  type│              input                    │ completed │ scraped │
│    0    │ 'user' │ 'motivational_videos_381' │   true            │    0    │
│    1    │ 'user' │       'mr_aadi__05'             │   true              │    0    │
│    2    │ 'user' │      'motupatlu8575'         │   true              │    0    │
│    3    │ 'user' │   'mr_jerryofficial01'        │   true               │    0    │
│    4    │ 'user' │   'mr_jerryofficial01'        │   true               │    0    │
│    5    │ 'user' │    'mr_hassan_shiekh'      │   true               │    0    │
│    6    │ 'user' │       'mr_battery'              │   true               │    0    │
│    7    │ 'user' │      'motupatlu8575'       │   true                │    0    │

**Note:** I managed to scrape in a same way previously but not anymore.

**Comment by drawrowfly** [comment]
Fill out bug report
