### ISSUE TITLE
Error: tunneling socket could not be established, cause=getaddrinfo EAI_AGAIN http

### ISSUE THREAD

**Issue by rjh336** [drawrowfly/tiktok-scraper#597]
**Describe the bug**
`getUserProfileInfo` method is returning undefined value. I am also seeing the following error emitted each time:
`Error: tunneling socket could not be established, cause=getaddrinfo EAI_AGAIN http`

I am using a proxy and tested it with other sites and scraper methods and seems to be working fine except when trying to get the user meta from this method.

**To Reproduce**
- Used OS:  UBUNTU 18.04 [GCF EXECUTION ENVIRONMENT](https://cloud.google.com/functions/docs/concepts/exec)
- NodeJs Version (node -v):  tested with both v14 and v12 [GCF RUNTIME](https://cloud.google.com/functions/docs/concepts/nodejs-runtime)
- Scraper Version (tiktok-scraper --version):  `1.4.31`
- CLI or Module:  `MODULE`
- Used method: `getUserProfileInfo`
- Used options:  `{"proxy":["http://XXX:XXX@XXX:XXX"],"by_user_id":true,"asyncScraping":3,"useTestEndpoints":false,"sessionList":["sid_tt=XXX; sessionid=XXX; sessionid_ss=XXX;"],"number":5}`
- Do you run the scraper through Proxy, VPN, VPS?  YES
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles! YES, IT IS PUBLIC
- Preferably provide URL to the profile,hashtag,video and etc page -- https://www.tiktok.com/@spotify

**Comment by drawrowfly** [comment]
Proxy related problem
