### ISSUE TITLE
Can't run 'tiktok-scraper' command. Get "not recognized as an internal or external command" error.

### ISSUE THREAD

**Issue by hirezz** [drawrowfly/tiktok-scraper#599]
**Describe the bug**
Been using this command for awhile and today it stopped working.
When running any command after opening a CMD into the folder, I receive the error that the command is not recognized. 
I downloaded newest version and ran npm i -g tiktok-scraper and verified that everything is in \AppData\Roaming\npm and the node_modules folder.

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- Windows 10
- NodeJs Version - v12.22.1
- Scraper Version - Can't get
- CLI or Module - CLI
- Used method
- Used options
- Do you run the scraper through Proxy, VPN, VPS? - No
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles!
- Preferably provide URL to the profile,hashtag,video and etc page

**Screenshots**

**Comment by ProteoNimra** [comment]
I am getting the same error...

**Comment by withoutknowingican** [comment]
the same

**Comment by drawrowfly** [comment]
Can't confirm, works fine from mine side. Try the latest version @1.4.33
