### ISSUE TITLE
Get user info by ID

### ISSUE THREAD

**Issue by yberdnikov** [drawrowfly/tiktok-scraper#6]
Any chance to get user posts by user id ?

**Comment by drawrowfly** [comment]
@yberdnikov yes it is possible, because when you enter plain username the next stage in the scraper is to find the User ID for this username and then rest

**Comment by yberdnikov** [comment]
would be great to have it as an option. Thanks in advance

**Comment by drawrowfly** [comment]
@yberdnikov just pushed an update, but for now you can do it only from the module

**Comment by yberdnikov** [comment]
@drawrowfly maybe I'm doing something wrong - but it returns empty data for me when trying to get user by id

**Comment by drawrowfly** [comment]
Are you sure that this is user id 6740334220058608646 ?

I mean i've tried different user id that is shorter and it worked well

**Comment by yberdnikov** [comment]
@drawrowfly yes, that's userId, btw - your code works perfectly with nickname, but not with user ids

**Comment by drawrowfly** [comment]
@yberdnikov right, some user ids are larger then MAX_SAFE_INTEGER , pass the user id as a string and it will work
