### ISSUE TITLE
Package is not running Online

### ISSUE THREAD

**Issue by shaheryaryousaf** [drawrowfly/tiktok-scraper#600]
I integrated the package with a MERN stack app and I'm trying to get and show the results on the web page. When I try locally, it is working perfectly (but takes a lot of time to get results).

When I try to run the same app after deploying on heroku, it is not working and always returns an empty array of data. 

App link: https://tiktiktest.herokuapp.com/

Code image is attached (https://paste.pics/146d3088da51887f991bba76b385625b). Hashtag is coming from an input field.

Can you please help with this?

**Comment by asportnoy** [comment]
Please use the bug report template and provide all the requested info
