### ISSUE TITLE
Add support for scraping users from tik.fail

### ISSUE THREAD

**Issue by rabea98** [drawrowfly/tiktok-scraper#603]
**Is your feature request related to a problem? Please describe.**
There's this website called https://tik.fail/ which used to mirror tiktok users, they have a big archive of famous tiktokers.
is it possible for you to add support to download tiktoks users from this website?

**Describe the solution you'd like**
Adding an option to scrape users from https://tik.fail/

**Comment by drawrowfly** [comment]
this library supports only official TikTok, no other plans on changing it
