### ISSUE TITLE
Custom filename saving the video upload date. 

### ISSUE THREAD

**Issue by alscaldas** [drawrowfly/tiktok-scraper#604]
**Is your feature request related to a problem? Please describe.**
I'd like to customize the parameter --filename to save the videos in the format "20210401 1232.mp4" instead of, for example, "6807491984882765062.mp4", being that date the time the video was upload. I've read the examples and the other help files but didn't find any solution.

**Describe the solution you'd like**
Something like: tiktok-scraper --filename "tiktokuser/download_date.mp4" would be excellent.

Sorry if I'm asking something that's already implemented, but I really couldn't find and didn't know where else I could ask.

**Comment by drawrowfly** [comment]
Duplicate #232

**Comment by SnowDragon997** [comment]
any news on how to do this?
