### ISSUE TITLE
Fetched Data Issue

### ISSUE THREAD

**Issue by shaheryaryousaf** [drawrowfly/tiktok-scraper#606]
**Describe the bug**
I am creating MERN stack app with tiktok data. I am fetching the data with the package and store it in my database (MongoDB). You can see the attachment for my stored data. Once I store successfully, everything works fine, and I can display images, titles, etc. But after 4-5 hours images links show an Access Denied error in the browser and images are not showing.

This is one demo image link, you can see that it is showing an Access Denied error.
https://p16-sign-va.tiktokcdn.com/obj/tos-maliva-p-0068/ff83f975f9934429979923e70d317276?x-expires=1624910400&x-signature=%2FvyJo1oiVCx7pLcGYopLNebz1I4%3D

**I'm using:**
Windows 10
Node v14.13.0
tiktok-scraper v^1.4.32
Running through promise
No used options, except _session_
I'm not running scrapper through any VPN or proxy

**Screenshots**
![storing data](https://user-images.githubusercontent.com/23572868/123710640-8b59c480-d888-11eb-916b-4ccc6d4f1346.PNG)
![Access denied error](https://user-images.githubusercontent.com/23572868/123710698-a4fb0c00-d888-11eb-8487-4bd266c5b4ca.PNG)

**Comment by drawrowfly** [comment]
Answered in discord
