### ISSUE TITLE
setting filename

### ISSUE THREAD

**Issue by spaceblnkt** [drawrowfly/tiktok-scraper#607]
**Is your feature request related to a problem? Please describe.**
I'm not sure how the filename command is supposed to work. Sorry if I'm going about this the wrong way, I'm not a regular github user. Whenever I use the command '--filename x' , it doesn't change the name of the output file. Am I doing something wrong, or is this feature not usable yet?

**Comment by drawrowfly** [comment]
set --filetype for example to csv

Default value for the --filetype is empty

**Comment by drawrowfly** [comment]
example tiktok-scraper user tiktok -n 5 user tiktok --filetype csv --filename BLABLAH
