### ISSUE TITLE
Set locale when scrape current trends

### ISSUE THREAD

**Issue by dlyakin** [drawrowfly/tiktok-scraper#61]
Hi!
I have vps server in Netherlands.
I want scrape trends from Russia
Is it possible to set locale or language?
For example link fo russian trends is https://www.tiktok.com/trending?lang=ru
I see option "userAgent" but I don't know how to set locale in it.
Also we have request header "Accept-Language". Is it possible to pass it to request?
I use api "TikTokScraper.trendEvent". May you know the way how to fix it directly in source code for me.

**Comment by drawrowfly** [comment]
There is no such options yet. I will add it to a to do list

**Comment by dlyakin** [comment]
May be I can just replace some url in TikTok.ts or headers to get only russian trends?
Or it not easy as I think)

**Comment by tnduc** [comment]
- Can the trending content change after each request is submitted?
- The response time is very long, about 30s -> 50s for data = 20

**Comment by drawrowfly** [comment]
I did some tests and "lang" param is not relevant. You can only get trending from a specific country by setting the proxy of that country

**Comment by dlyakin** [comment]
Yes, I use proxy now. It works well.
