### ISSUE TITLE
What does diggCount attribute mean

### ISSUE THREAD

**Issue by followerstracker** [drawrowfly/tiktok-scraper#611]
> diggCount is the number of people who digged (aka 'liked') the video

Yes, what is the difference between diggCount and hearts?

_Originally posted by @William-Fox-Cantera in https://github.com/drawrowfly/tiktok-scraper/issues/95#issuecomment-822937338_

It's exactly what @drawrowfly said. It's a number of likes given to others. Take a look at this recent data.

![image](https://user-images.githubusercontent.com/86723496/124203992-fe8f5080-daab-11eb-9398-679409174f7c.png)

**Comment by drawrowfly** [comment]
No idea what you mean with that issue

**Comment by skyeagle** [comment]
> No idea what you mean with that issue

This question has not been answered in #95. I just wanted to check on it and provide some clarity on this topic with the data at hand.
