### ISSUE TITLE
download number issue

### ISSUE THREAD

**Issue by securenetworx-shark** [drawrowfly/tiktok-scraper#613]
I try to collect hashtag based info: // tiktok-scraper hashtag "HASHTAG" -n 2000 --session-file ../session-token -t json // but all times the json file have just 1600 around...i dont know why, but i cant download just 1600 record from any hashtag.

**Comment by drawrowfly** [comment]
When you are scraping a lot of data, you are making a lot of requests and you need to use proxies

**Comment by ambigos1** [comment]
Any Recommended proxies for 50K requests a month?
@drawrowfly 

currently using geo surf residential proxies and I am paying $300 a month.. it is expensive..
