### ISSUE TITLE
Why npm and not a prefabricated binary file?

### ISSUE THREAD

**Issue by UnixCro** [drawrowfly/tiktok-scraper#619]
Why do I have to go such a detour and install with yarn or npm via homebrew. Why can't I just go to the releases and download the file and run it?

**Comment by drawrowfly** [comment]
This is how it works, or you can use 3rd party libraries to build your own binary

**Comment by drawrowfly** [comment]
For the most lazy ones https://www.google.com/search?q=nodejs+build+binary
