### ISSUE TITLE
Issue: Not scraping all videos anymore.

### ISSUE THREAD

**Issue by vnnegt** [drawrowfly/tiktok-scraper#62]
Is anyone having an issue with the scraper not scraping all videos?

It will only download up to 30 or so, but sometimes less than that.

It started yesterday. I usually use:
`tiktok-scraper --number 0 --download -w --store user <USER>`

I'm assuming it's a tiktok server side issue?
I'm using version 1.1.1 of the scraper

Same behavior if I omit the `-s` and `-w` flags as well.

Thanks

**Comment by drawrowfly** [comment]
It is not a surprise, sooner or later you can hit "rate limit" with your IP

**Comment by drawrowfly** [comment]
Actually i maybe know where is the issue, i will release new update shortly that can fix that bug

**Comment by vnnegt** [comment]
> Actually i maybe know where is the issue, i will release new update shortly that can fix that bug

Cool. I was just about to say that I havent used it in a few days and I also tried with multiple VPN connections.

Thanks

**Comment by drawrowfly** [comment]
setting 0 will work as expected
