### ISSUE TITLE
scraper no longer working

### ISSUE THREAD

**Issue by ETedward** [drawrowfly/tiktok-scraper#621]
**Describe the bug**
The scraper has previously worked for me before.
Unfortunately when I run the scrape this time, nothing comes out in the output files.
No error messages are thrown. 

**To Reproduce**
- Used Mac OS Big Sur
- Ran command tiktok-scraper hashtag test -d -n 100 --session sid_tt=dae32131231

**Comment by alievk** [comment]
Same problem here. Only scrapes videos from a username.

**Comment by drawrowfly** [comment]
Fill out bug template
