### ISSUE TITLE
History path does not work

### ISSUE THREAD

**Issue by jujaks** [drawrowfly/tiktok-scraper#622]
I'm running this:

`tiktok-scraper from-file /Volumes/SSData/tk/tt 10 --historypath /Volumes/SSData/tk/history --download --filetype all --filepath /Volumes/SSData/tk -s`

Everything works, it scraps all profiles but there is no history file craeted. And everytime I run the command it always re-downlaods everything, taking ages.

Am I using the command correctly?

**Comment by drawrowfly** [comment]
Fill out bug template
