### ISSUE TITLE
nowatermark download does not work 

### ISSUE THREAD

**Issue by hakimfcb** [drawrowfly/tiktok-scraper#623]
**Describe the bug**
 download video without the watermark doesn't work 

**To Reproduce**
- Used Windows 11
- NodeJs Version v16.5.0
- Scraper Version 1.4.33
- use CLI
code : 
tiktok-scraper from-file dz.JSON 2 -d -n 2 -w -f all 
used options: -d -w -n -f
- no proxy
- If scraping from hashtag 
- cars hashtag

**Comment by atmos-o** [comment]
![image](https://user-images.githubusercontent.com/44858581/125809759-84ffa9ab-e9cb-410e-a9d2-088061b2e2ac.png)

**Comment by hakimfcb** [comment]
> https://github.com/drawrowfly/tiktok-scraper#important-notes
> 
> ![image](https://user-images.githubusercontent.com/44858581/125809759-84ffa9ab-e9cb-410e-a9d2-088061b2e2ac.png)

Will it be possible one day or any update to download without a watermark !!!!

**Comment by dvird** [comment]
some websites still work there... how https://snaptik.app/ ?

**Comment by UnixCro** [comment]
Omg Snaptik can really download videos without watermark.

**Comment by alma359** [comment]
This website also works https://godownloader.com/en-us
And there are apps on Google Play that work without watermark !

**Comment by UnixCro** [comment]
@drawrowfly A very nice developer called @rouze-d has several Tiktok scripts. A shell script for downloading a video, the second for the complete page and the third, a video without watermark, which is called [tikwm.sh](https://github.com/rouze-d/tiktok-download/blob/master/tikwm.sh While this script doesn't really work for a reason that isn't really understandable, it's a very good approach. This developer uses very nifty ideas that were built into this source code. If you fix this little error message and what was built into "tikwm.sh" would also be built into `tiktok-scraper` that would be a fantastic result. I would be happy if you take a look

**Comment by alma359** [comment]
@UnixCro I made a python script yesterday that works with godownloader.com without watermark, if you want I can upload it to my Github

**Comment by drawrowfly** [comment]
It is possible to download video without WM but through mobile api, I do not plan to implement it to the public repo
