### ISSUE TITLE
Change Tiktok Region for scraping

### ISSUE THREAD

**Issue by thamquocdung** [drawrowfly/tiktok-scraper#626]
Firstly, I would like to say thank you for your contribution. It's so useful.
After reading the document and executing some samples. I have wondered if it is possible to change the TikTok region for trending scraping (i.e: Japan or Korea,...)? If yes, how can I change the parameters? Thanks

**Comment by a1d4r** [comment]
You have to use proxy from this region. As far as I know no parameters (even `region`) affect the result from API.
