### ISSUE TITLE
Question to quiet mode, npm ...

### ISSUE THREAD

**Issue by UnixCro** [drawrowfly/tiktok-scraper#628]
First thing before I start. Very successful program and thank you for letting us use it. The program saves you a lot of work if you want to download videos from celebrities. There are programs like `youtube-dl` but unfortunately they don't manage to download all videos in one go.

<br>

I have no bugs to report, but if you are okay with this, I have a few questions.

1. The problem I have is that when I want to download videos from people, `tiktok-scraper` always starts over. It does not check whether it has already been downloaded and starts with the newest ... No, unfortunately, it does not download it from scratch instead.
Is there any way to tell `tiktok-scraper` to only download the latest? 

Fixed ✅ Use the Parameters `--store` `--historypath $PWD/tiktokusername`

Example :` i=videozeugs; tiktok-scraper user $i -n 1 -d --store --historypath $PWD/$i`

2. Since tiktok-scraper starts all over again, does it mean that new write cycles are constantly being written to the hard disk and thus the service life is reduced? Since the bar always starts from 0%, I think that all files will be deleted and it will start over.

Fixed ✅ Unfortunately, yes, tiktok-scraper without the required parameters overwrites the files, which reduces the lifespan of the hard disk if it occurs frequently. It should be deactivated by default!

3. Tiktok scraper requires "npm" and that is exactly the problem. I don't want to use npm and don't understand exactly why I need it for the installation. There are so many binaries out there that you would need them without npm. The thing that annoys me the most is that npm, homebrew or other similar third party programs have to install programs for it to work. On the other hand, if it works then it's very awesome ....

Any way to bypass npm or have to compile it yourself. Amateurs who compile themselves will only cause trouble. Somehow to download something where it ends up automatically `/usr/local/bin/tiktok-scraper` and works.

4. Is there a parameter that allows the `tiktok-scraper` to produce no output? Like `tiktok-scraper --quiet`

**Issues**

The parameter `--hd` and the `-w` not working, if I use these parameters and afterwards not, and I can not see any a difference. tiktok-scraper download the videos equal without these parameters or with these parameters.

<br>

Thank you very much for this and look forward to an answer

**Suggestions for Improvments**

PLEASE ENABLE A DOWNLOAD WITHOUT WATERMARK; THAT WOULD BE EXPECIALLY FIT WELL IN THE REPOSITORY

**Comment by drawrowfly** [comment]
Regarding quite mode duplicate #386 . Regarding no wm , when it will be possible to do it through web api then it will be added
