### ISSUE TITLE
The response time is very long.

### ISSUE THREAD

**Issue by tnduc** [drawrowfly/tiktok-scraper#63]
> Node latest
> Expressjs server
> Linux

- The response time is very long, about 30s -> 50s for data = 20

![DeepinScreenshot_select-area_20200404222011](https://user-images.githubusercontent.com/26267956/78454488-76f93d00-76c2-11ea-82c8-5a39cb745dd5.png)

- and Can the trending content change after each request is submitted?

**Comment by drawrowfly** [comment]
This is not a bug there are lot of factors
- How you builded your back end infrastructure  
- Your connection speed
- Your server location
- Current TikTok server response time


And use Redis to cache tiktok response, it will help you a lot

**Comment by tnduc** [comment]
> This is not a bug there are lot of factors
> 
> * How you builded your back end infrastructure
> * Your connection speed
> * Your server location
> * Current TikTok server response time
> 
> And use Redis to cache tiktok response, it will help you a lot

Ok, what about the problem with trending, the video list changes with each request?
> https://www.tiktok.com/share/item/list?secUid=&id=&type=5&count=30&minCursor=0&maxCursor=0&shareUid=&lang=en&_signature=wdRpHAAgEB0pPJQ.HPBGZMHUaAAAJ9m

I tried to include cookies but the video list hasn't changed, do you have a way to resolve it?

**Comment by tnduc** [comment]
@drawrowfly Can you add duration field in video.meta.duration?

**Comment by drawrowfly** [comment]
Video meta was added to the latest version

Regarding trending feed . Later when i will have more free time i will try to find the solution

**Comment by tnduc** [comment]
> Video meta was added to the latest version
> 
> Regarding trending feed . Later when i will have more free time i will try to find the solution

Trending: I am using https://github.com/carcabot/tiktok-signature to get the signature.

**Comment by drawrowfly** [comment]
This is completely non related repo. If you need signature you can use our repo

**Comment by tnduc2** [comment]
@drawrowfly can you add videoMeta to getVideoMeta?
