### ISSUE TITLE
Strange GLib-GIO-WARNING on download

### ISSUE THREAD

**Issue by RonnieBlaze** [drawrowfly/tiktok-scraper#635]
so why is it every time i download a video i get this error

(process:18728): GLib-GIO-WARNING **: 22:11:13.284: Failed to open application manifest `C:\Program Files\WindowsApps\Microsoft.SeaofThieves_2.101.2052.2_x64__8wekyb3d8bbwe\AppxManifest.xml' for package #48 (`Microsoft.SeaofThieves_2.101.2052.2_x64__8wekyb3d8bbwe'): error code 0x3

**Comment by drawrowfly** [comment]
Fill out bug template

**Comment by UnixCro** [comment]
When he must fill out the issue requirements then why you close it? Its not solved?
