### ISSUE TITLE
Can't download videos without watermark!

### ISSUE THREAD

**Issue by S4MS3P101** [drawrowfly/tiktok-scraper#636]
So even after using the parameter -w I can't able to download videos without watermark also tried with --hd

**Comment by UnixCro** [comment]
I already mentioned it. The developer probably doesn't like videos that don't have watermarks. https://github.com/drawrowfly/tiktok-scraper/issues/623#issuecomment-886104211

**Comment by drawrowfly** [comment]
> I already mentioned it. The developer probably doesn't like videos that don't have watermarks. https://github.com/drawrowfly/tiktok-scraper/issues/623#issuecomment-886104211
> 
> Unfortunately, since this program is the best program for downloading tiktok videos, it is a shame that it is not implemented.
> 
> To fix the problem, I duplicated this [repository](https://github.com/UnixCro/tiktok-scraper) In the hope that someone with a pull request will then implement this 

I won't integrate some random 3rd party services, because it isn't right way!!
