### ISSUE TITLE
[Ubuntu 20] -w option does not seem to work

### ISSUE THREAD

**Issue by ics-developer** [drawrowfly/tiktok-scraper#641]
Trying to download video from hashtag
`tiktok-scraper hashtag fun -w --hd -d -n 1 -t json --session <session>`
while option -w specified, video still downloaded with watermark
`Downloading (WITH WM) 6784536387992440070 [==============================] 100%`
tryed directly download video by link, same result.
`tiktok-scraper video "https://www.tiktok.com/@tianna_777555/video/6986846486663367942?is_copy_url=1&is_from_webapp=v1" -w --hd -d -t json --session <session> `

**Comment by drawrowfly** [comment]
https://github.com/drawrowfly/tiktok-scraper#important-notes

**Comment by UnixCro** [comment]
From the README.md

> As of right now it is NOT possible to download video without the watermark

**Comment by ics-developer** [comment]
Yup, thanks.
thou https://ssstik.io/ able to do that somehow

**Comment by UnixCro** [comment]
https://github.com/drawrowfly/tiktok-scraper/issues/513#issuecomment-893554531
