### ISSUE TITLE
Proxy error

### ISSUE THREAD

**Issue by ThaDeveloper** [drawrowfly/tiktok-scraper#644]
**Describe the bug**
Can't get the scrapper to work with proxy, I'm getting `ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames`. It was working before I started to see this error

**To Reproduce**
- Used OS: Ubuntu 18.04
- NodeJs Version (node -v): 10.20.1
- Scraper Version (tiktok-scraper --version): 1.4.35
- CLI or Module: Module
- Used method: getUserProfileInfo()
- Used options: {proxy: 'socks5://0.0.0.0':sessionList: []}

**Comment by amberallergy** [comment]
Hi!
this one seems to work can try it out, they offer free token at the first.
They work on different social media platforms.
Here is the website https://www.influencerhunters.com/docs.html
