### ISSUE TITLE
Canvas dependency prevents install on Alpine

### ISSUE THREAD

**Issue by DavidFrancois** [drawrowfly/tiktok-scraper#649]
**Describe the bug**
The `canvas` dependency prevents project using the library from running on Alpine lts docker image.

When trying to `yarn install` in a project using the lib on Alpine lts, the install will fail.
It is likely due to `canvas` not being handled at all by Alpine.

After a quick search, I didn't find any reference to canvas in the code (except obvioulsy in the package.json).
I solved the issue by forking the lib and just removing the dependency but it is quite a short term solution.

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- OS : Alpine lts
- Scraper Version : latest

**Comment by asportnoy** [comment]
The [signature function](https://github.com/drawrowfly/tiktok-scraper/blob/3faaa049446e209a96c9e69d50cab4136848282a/src/helpers/Signature.ts) requires it, you just can't tell because it's obfuscated. Removing the module will either make the signature invalid or cause it to throw errors, I can't remember which.

**Comment by JackDevAU** [comment]
I had the same issue, to get around it, I manually installed the dependencies needed to get canvas to run!
This works for me!
(Dockerfile) 
```
FROM node:14

COPY . .

RUN apt-get update
RUN apt-get install build-essential
RUN apt-get install libcairo2-dev 
RUN apt-get install -y libpango1.0-dev 
RUN apt-get install -y libjpeg-dev 
RUN apt-get install -y libgif-dev 
RUN apt-get install -y librsvg2-dev

RUN npm i

CMD ["npm", "start"]
```

**Comment by asportnoy** [comment]
^^ fyi you can find commands for your OS at https://github.com/Automattic/node-canvas/wiki#installation-guides

**Comment by DavidFrancois** [comment]
Thanks for the answers.
I personally just removed the dependency to canvas since I didn't need related features, but installing the dependencies in the Dockerfile is obviously a better approach. 

I close the issue!
