### ISSUE TITLE
.trend() returns empty collector every time

### ISSUE THREAD

**Issue by asportnoy** [drawrowfly/tiktok-scraper#650]
**Describe the bug**
.trend() returns empty collector every time

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- Ubuntu v20
- v14.17.5
- 1.4.34 (Also on macOS with 1.4.35)
- Module
- trend
- number, proxy
- Using high quality residential proxies
- No profile
- Link N/A

**Comment by UnixCro** [comment]
It give not a macOS 1.4 Version. Do you mean macOS 10.14 Mojave?

**Comment by asportnoy** [comment]
No, that's the scraper version. @drawrowfly already confirmed this on the Discord.

**Comment by drawrowfly** [comment]
@1.4.36

**Comment by asportnoy** [comment]
Thank you!

**Comment by ncsft** [comment]
@drawrowfly 
Can it throw error message instead empty collection?

**Comment by drawrowfly** [comment]
> @drawrowfly
> Can it throw error message instead empty collection?

try catch
