### ISSUE TITLE
Question: could a tiktok user's secUid ever change?

### ISSUE THREAD

**Issue by ZYinMD** [drawrowfly/tiktok-scraper#651]
In my own workflow, I'd like to know if a user's secUid can possibly change during its lifetime. 

I know a user's id will never change (right?), and a user's @uniqueId can definitely change, but how about the secUid? 

From TikTok's standpoint, the id is already good enough to identify a user, why did they create the secUid? What's the goal?

**Comment by drawrowfly** [comment]
as far as i know , it can't
