### ISSUE TITLE
Scrapper doesn't work at all all of a sudden and it used to just hours ago

### ISSUE THREAD

**Issue by Frank-en-stein** [drawrowfly/tiktok-scraper#652]
**Describe the bug**
I'm using the scraper through CLI command `tiktok-scraper user colinwasson -n 10 -t json --session asd12345654621 `

I successfully used it hours ago for this very user but nothing happens now. No errors whatsoever, scraper just stops. No output files created.

**To Reproduce**
- Windows 10
- NodeJs  v14.17.5
- Scraper Version 1.4.36
- CLI
- Used method: user 
- Used options: -n 10 -t json
- Do you run the scraper through Proxy, VPN, VPS? NO
- If scraping from a profile. Did you checked if profile is Public? Yes
- Preferably provide URL to the profile: https://www.tiktok.com/@colinwasson?

**Comment by CaseyTransylvaniaLabs** [comment]
I got the same problem but I'm using the module method, and I'm using the default '-n'/number at default 20, I even tried 5 

Code:
<pre><code>
  private async getUserVideosById(userId: string) {
    const result: TiktokScraper.Result = await TiktokScraper.user(userId, {});
    const videos = result.collector;
    console.log('getUserVideosById-videos->', videos)
  }
 </code></pre>

Returns:
<code>
getUserVideosById-videos-> []
</code>

**Comment by Frank-en-stein** [comment]
Possibly because of IP blocking? The proxy flag -p didn't work for me either, not even over VPN. If there's a separate issue for that, this one can be closed.

**Comment by CaseyTransylvaniaLabs** [comment]
I just tried it with a proxy and still no luck! Any other suggestions that may help?

**Comment by Frank-en-stein** [comment]
@CaseyTransylvaniaLabs can you try without the proxy flag while having your computer connected to a VPN?

**Comment by CaseyTransylvaniaLabs** [comment]
Okay that might take a minute

**Comment by CaseyTransylvaniaLabs** [comment]
@Frank-en-stein  Okay so I've ran the request while having my vpn up and the request is still loading

**Comment by Frank-en-stein** [comment]
Which query are you running?

**Comment by CaseyTransylvaniaLabs** [comment]
TiktokScraper.user()

**Comment by drawrowfly** [comment]
Can't confirm. Works fine from mine side

**Comment by Frank-en-stein** [comment]
@drawrowfly Can you check if the -p flag works for you from the CLI? If so, could you please post a sample command that worked?

**Comment by drawrowfly** [comment]
Same as in the documentation 

    // Set proxy {string[] | string default: ''}
    // http proxy: 127.0.0.1:8080
    // socks proxy: socks5://127.0.0.1:8080
    // You can pass proxies as an array and scraper will randomly select a proxy from the array to execute the requests
    proxy: '',

`tiktok-scraper user colinwasson -d -n 5 -p "user:pass@ip:port" `

**Comment by CaseyTransylvaniaLabs** [comment]
But I was wanting to use it as a package in a node.js app, as a module and this doesn't work
<code>
TiktokScraper.user({ userId | username }, { proxy: 'proxy-server' })
</code>

**Comment by CaseyTransylvaniaLabs** [comment]
I've tried the cli and I still just get an empty folder, with or without a proxy
