### ISSUE TITLE
user posts

### ISSUE THREAD

**Issue by superjxvv** [drawrowfly/tiktok-scraper#656]
If the user has no post, there is no json file created right? In this case, how do you know if the scraper failed or the user has no post.

**Comment by UnixCro** [comment]
Just try it out yourself, maybe your question will have answered itself :)

**Comment by superjxvv** [comment]
The only way to know if it succeeded is if it printed an output. So I have to return the output to a file to know if the scraper has succeeded or failed? Would it be possible if it just created a file if it succeeded but with no data.

**Comment by drawrowfly** [comment]
if tiktok api response has provided data then you will get data output otherwise nothing
