### ISSUE TITLE
Unrecognized arguments when downloading a user

### ISSUE THREAD

**Issue by MikeTweet** [drawrowfly/tiktok-scraper#661]
Hello

I am trying to use the program but it doesnt appear to be working after following the example. This is what I am typing into the cmd.

"tiktok-scraper user willsmith"

No matter what username I type into the command promt I always get 

"tiktok-scraper: error: unrecognized arguments: willsmith"

I have used the program in the past but doesnt appear to work anymore. I am new to using github programs as well so not the best person for trouble shooting these issues.

Using windows 10.
Latest NodeJs installed.
No VPN used.
Running inside the command prompt
Profiles are all public
No options used.
Using the latest tiktok scraper version

![Capture](https://user-images.githubusercontent.com/47541208/131551720-0e6483e3-ba0e-42a3-8c08-97a7e009c9a0.PNG)

**Describe the bug**

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- Used OS
- NodeJs Version (node -v)
- Scraper Version (tiktok-scraper --version)
- CLI or Module
- Used method
- Used options
- Do you run the scraper through Proxy, VPN, VPS?
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles!
- Preferably provide URL to the profile,hashtag,video and etc page

**Screenshots**

**Comment by drawrowfly** [comment]
You are using different package, probably python one

**Comment by MikeTweet** [comment]
> 
> 
> You are using different package, probably python one

Im kinda new to the whole github thing personally. How exactly do I download a different package, I only see the option to open with github desktop ?
