### ISSUE TITLE
Not scrapping USERNAME post videos

### ISSUE THREAD

**Issue by shadowninja024** [drawrowfly/tiktok-scraper#669]
**Describe the bug**
When i try to run the command 

tiktok-scraper user USERNAME -d

The output im getting 

⠋ TikTok Scraper Started⠙ TikTok Scraper

Not able to download even a single video user

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- linux os
- NodeJs Version (node -v) - v12.22.6
- Scraper Version (tiktok-scraper --version) - 1.4.36
- CLI 
- Used method - installed via yarn 
- Used options - username download
- Do you run the scraper through Proxy, VPN, VPS? No vpn
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles! - public profile
- Preferably provide URL to the profile,hashtag,video and etc page - exact username was added

**Screenshots**
![Screenshot_20210904-014428_Chrome](https://user-images.githubusercontent.com/63149314/132068044-d9a80b8e-caa1-4c65-aa26-15fd46117351.jpg)

**Comment by drawrowfly** [comment]
Duplicate #663
