### ISSUE TITLE
--filepath not working when downloading single video

### ISSUE THREAD

**Issue by Xylot** [drawrowfly/tiktok-scraper#67]
**Describe the bug**
Passing a directory path for downloaded files using --filepath does not take effect.

**To Reproduce**
- OS: Windows 10
- Node.js Version: 12.16.1
- Scraper Verison: 1.1.3
- CLI
- "tiktok-scraper video [id] --filepath [filepath]"
- "tiktok-scraper video https://www.tiktok.com/@oakleythegoldenpuppy/video/6792343534545440005 --filepath "H:\Test\""

**Screenshots**
https://puu.sh/FugpR/a7a15bb21b.png

**Comment by drawrowfly** [comment]
Will be fixed with the next update

Thanks for the nicely done bug report !)

**Comment by drawrowfly** [comment]
Fixed in the latest version

Welcome!
