### ISSUE TITLE
Filtering by date range - (add `until` parameter)

### ISSUE THREAD

**Issue by boscacci** [drawrowfly/tiktok-scraper#672]
**Is your feature request related to a problem? Please describe.**
I want to collect data about TikTok posts from at least one month ago; I am not interested in posts more recent than one month. I noticed there is a `since` parameter in the CLI but not something like `before` or `until` - a way to avoid scraping newer posts and only query the platform for data about older posts.

**Describe the solution you'd like**
A new parameter/arg that takes a datetime string (`--until 2021-08-07`) and scrapes only posts from before that date.

**Comment by oneamanorgy** [comment]
boscacci is right, we'll all be able to sort by hashtag relevance date and not unorganized

**Comment by fracogno** [comment]
[Here](https://www.influencerhunters.com/docs.html)  they have a solution to filter posta even only from a day earlier.

**Comment by boscacci** [comment]
Don't need this anymore
