### ISSUE TITLE
Is there a way to scrape just user data and not videos?

### ISSUE THREAD

**Issue by thkim1234** [drawrowfly/tiktok-scraper#674]
I would like to just scrape a bulk of user data in csv file format for multiple users. 

With my command looking like this - `tiktok-scraper from-file nba 5 -t csv`. When I run that command, it doesn't scrape anything. I also tried attaching session id but that didn't help either. The behavior I was expecting was scraping each of the users' video data.

My nba file just contains usernames such as 

```
nba
miamiheat
warriors
```

**Comment by faunX** [comment]
https://github.com/drawrowfly/tiktok-scraper/issues/663 this is a known issue.

**Comment by thkim1234** [comment]
This issue is being handled by issue #663 - closing this issue
