### ISSUE TITLE
getUserProfileInfo  stopped working while using proxy

### ISSUE THREAD

**Issue by shaital** [drawrowfly/tiktok-scraper#676]
I am using latest version
I changed the proxy , it didn't help.
I replaced the sid_tt, it didn't help
Please advise
(node:15272) UnhandledPromiseRejectionWarning: Error: Can't extract user metadata from the html page. Make sure that user does exist and try to use proxy
    at TikTokScraper.getUserProfileInfo (C:\Users\USER\Desktop\tiktop\node_modules\tiktok-scraper\build\core\TikTok.js:713:15)
    at async Object.exports.getUserProfileInfo (C:\Users\USER\Desktop\tiktop\node_modules\tiktok-scraper\build\entry.js:138:20)

**Comment by Romucmad** [comment]
It does not work at any point #663

**Comment by ambigos1** [comment]
@drawrowfly 
Also TikTokScraper.user returning empty collector

Any help with that?

**Comment by amirdezhkam** [comment]
same for me

**Comment by andrearama** [comment]
It seems to be a common issue, looking at different github repos. 
Some freemium services like [this](https://www.influencerhunters.com/docs.html) works

**Comment by drawrowfly** [comment]
keep it clean and fill out bug template
