### ISSUE TITLE
Can't extract video metadata.

### ISSUE THREAD

**Issue by netherlink117** [drawrowfly/tiktok-scraper#678]
Using the command (example):
```cmd
tiktok-scraper video -d -w --hd -s --historypath "path\to\history" --session "path\to\session" "url"
```
Some videos throws this kind of menssage to the console:
```
Can't extract video metadata. https://www.tiktok.com/@some_user/video/some_video_id
```
NOTE: I also notice that using `video` ignores `-s` and `--historypath` flags, this and the message error from above, happens also using `from-file`.

**Comment by monty-dev** [comment]
i just realized youtube-dl downloads tiktoks. ffs.

**Comment by drawrowfly** [comment]
keep it clean and fill out bug template
