### ISSUE TITLE
Notice! TikTok Block!

### ISSUE THREAD

**Issue by JorjanLLT** [drawrowfly/tiktok-scraper#679]
Today i use personal mac visit tiktok web, its ok, then i test scraper ,as usual it fail.
But i visit web agian, the tiktok web block me, it means my proxy ip was banned !
at last ,i changed other proxy ,it allow me to visit...
u guys should be careful with that, once u use scraper, ur ip will be banned

**Comment by drawrowfly** [comment]
nothing new, usual stuff with the scrapers
