### ISSUE TITLE
How to get the redirected url from "videoUrlNoWaterMark"

### ISSUE THREAD

**Issue by tnduc** [drawrowfly/tiktok-scraper#68]
_The question may not be related to the package, but I hope to find a solution here._

> [
...
videoUrlNoWaterMark: "https://api2.musical.ly/aweme/v1/playwm/?video_id=v07025790000bpagqcvhpliigi473f4g"
...
]

After access **videoUrlNoWaterMark** will move to:

```
http://v16.muscdn.com/bf815f9b3fdde0b5b462b1649c464939/5e8df7f2/video/n/v0102/f1e9f16674df453ebb8051c18175ff92/?a=1233&br=1874&bt=937&cr=0&cs=0&dr=0&ds=6&er=&l=202004081012090101890362000C190F01&lr=musically&qs=0&rc=amk6bGxva2ZqczMzPDgzM0ApaGc6Omk3NWQ1N2YzNTZpNmcxMDFkZm1zbl5fLS00LzRzczExM15fMTEwYy9iMS9hLl46Yw%3D%3D&vl=&vr=
```
Is there a way to use PHP or JS to get the url after redirection?

**Comment by arelxcode** [comment]
const GetDirectAPI = function(url)
{
    return new Promise((resolve, reject) => {
    request({
        headers: {
            "Range": "bytes=0-0",
    "accept-encoding": "gzip",
    "Connection": "Keep-Alive",
    'User-Agent': `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_${Math.floor(
        Math.random() * (15 - 10) + 10,
    )}_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/${Math.floor(Math.random() * (79 - 70) + 70)}.0.3945.117 Safari/537.36`,
        },
        uri: url,
        method: 'GET'
      }, function (err, res, body) {
          resolve(this.uri.href)
      });
    })
}

**Comment by tnduc** [comment]
@drawrowfly I tried but the results were not as expected
https://codesandbox.io/s/charming-mahavira-t2rmu?file=/src/App.js

**Comment by builuc1998** [comment]
> _Câu hỏi có thể không liên quan đến gói, nhưng tôi hy vọng sẽ tìm thấy một giải pháp ở đây._
> 
> > [ 
> > ... 
> > videoUrlNoWaterMark: "https://api2.musical.ly/aweme/v1/playwm/?video_id=v07025790000bpagqcvhpliigi473f4g" 
> > ... 
> > ]
> 
> Sau khi truy cập **videoUrlNoWaterMark** sẽ chuyển đến:
> 
> ```
> http://v16.muscdn.com/bf815f9b3fdde0b5b462b1649c464939/5e8df7f2/video/n/v0102/f1e9f16674df453ebb8051c18175ff92/?a=1233&br=1874&bt=937&cr=0&cs=0&dr=0&ds=6&er=&l=202004081012090101890362000C190F01&lr=musically&qs=0&rc=amk6bGxva2ZqczMzPDgzM0ApaGc6Omk3NWQ1N2YzNTZpNmcxMDFkZm1zbl5fLS00LzRzczExM15fMTEwYy9iMS9hLl46Yw%3D%3D&vl=&vr=
> ```
> 
> Có cách nào để sử dụng PHP hoặc JS để lấy url sau khi chuyển hướng không?

bác có thể cho mình biết hướng nào để get được video_id không ạ?

**Comment by tonyquang** [comment]
@builuc1998 bác biết cách nào lấy được cái video_id=v07025790000bpagqcvhpliigi473f4g ko>?

**Comment by tnduc** [comment]
You can watch at [https://github.com/drawrowfly/tiktok-scraper/blob/master/src/core/TikTok.ts](https://github.com/drawrowfly/tiktok-scraper/blob/master/src/core/TikTok.ts) function `extractVideoId()`

**Comment by drawrowfly** [comment]
I don't see here any issues related to the package! Your answer depends from your knowledge of any request library or just search for example on **https://stackoverflow.com/** 

```javascript
const rp = require('request-promise');

rp({
    uri: 'https://api2.musical.ly/aweme/v1/playwm/?video_id=v07025790000bpagqcvhpliigi473f4g',
    headers: {
        'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36',
    },
    resolveWithFullResponse: true,
    followRedirect: false,
    simple: false,
}).then((url) => {
    console.log(url.headers.location);
});
```

**Comment by tonyquang** [comment]
@tnduc How can I get this url: https://api2.musical.ly/aweme/v1/playwm/?video_id=v07025790000bpagqcvhpliigi473f4g or get video_id?

**Comment by tnduc** [comment]
> @tnduc How can I get this url: https://api2.musical.ly/aweme/v1/playwm/?video_id=v07025790000bpagqcvhpliigi473f4g or get video_id?

This library also supports this, have you tried this function yet?
```
private async extractVideoId(uri): Promise<string> {
        try {
            const result = await rp({ uri });
            const position = Buffer.from(result).indexOf('vid:');
            if (position !== -1) {
                const id = Buffer.from(result)
                    .slice(position + 4, position + 36)
                    .toString();
                return `https://api2.musical.ly/aweme/v1/playwm/?video_id=${id}`;
            }
            throw new Error(`Cant extract video id`);
        } catch (error) {
            return '';
        }
    }
```

**Comment by hamaz562006** [comment]
How can I get extractVideoId(uri) in android app?
