### ISSUE TITLE
Simply not working and no output

### ISSUE THREAD

**Issue by NuLL3rr0r** [drawrowfly/tiktok-scraper#682]
**Describe the bug**
I'm trying the following command, and sadly it won't work. No errors nothing on the screen except TikTok Scraper Started (and then it disappears):

```
$ tiktok-scraper user francescapsychology -t csv --session sid_tt=SOME_SESSION_ID
```

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- Used OS
```
uname -a
Linux mamadou-pc 5.10.65 #62 SMP Thu Sep 16 01:55:11 CEST 2021 x86_64 Intel(R) Core(TM) i7-6820HK CPU @ 2.70GHz GenuineIntel GNU/Linux
```
- NodeJs Version (node -v)
```
$ node -v                     
v16.9.1
```
- Scraper Version (tiktok-scraper --version)
```
$ tiktok-scraper --version
1.4.36
```
- CLI or Module: CLI
- Used method: user
- Used options: -t csv --session sid_tt=SOME_SESSION_ID
- Do you run the scraper through Proxy, VPN, VPS? Nope!
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles!: Yes!
- Preferably provide URL to the profile,hashtag,video and etc page: https://www.tiktok.com/discover/francescapsychology?lang=en

**Screenshots**
If applicable, add screenshots to help explain your problem
![Screenshot_2021-09-21_20_46_47_244104884](https://user-images.githubusercontent.com/2454895/134230089-d4fd9676-20cf-40df-b902-7b1040c68a4c.png)

**Comment by NuLL3rr0r** [comment]
Nothing else works. e.g:

```
$ tiktok-scraper trend -n 50 -d -z -t csv --session sid_tt=SOME_SESSION_ID
```

It would be nice to have a <code>--verbose</codE> flag for such a situation to see what's going wrong.

**Comment by drawrowfly** [comment]
#663

**Comment by asportnoy** [comment]
> It would be nice to have a <code>--verbose</codE> flag for such a situation to see what's going wrong.

https://github.com/drawrowfly/tiktok-scraper/pull/668
