### ISSUE TITLE
Error while using getUserProfileInfo function

### ISSUE THREAD

**Issue by AdiPol1359** [drawrowfly/tiktok-scraper#686]
**Describe the bug**
When I'm using function to get info about user, tiktok-scraper throws me error: UnhandledPromiseRejectionWarning: Error: Can't extract user metadata from the html page. Make sure that user does exist and try to use proxy. The username is correct and issue appears on the second/third requst. TikTok bloked my IP.

**To Reproduce**
- Ubuntu 18.04
- 14.17.4
- 1.4.36
- CLI or Module
- getUserProfileInfo
- Used options
- I tried on my local pc and VPS
- Yee
- Preferably provide URL to the profile,hashtag,video and etc page

**Screenshots**

**Comment by drawrowfly** [comment]
works fine from mine side, use quality proxy
