### ISSUE TITLE
Can't download user videos

### ISSUE THREAD

**Issue by David99990123** [drawrowfly/tiktok-scraper#688]
So i updated everything to 8.1.0, did the "npm audit fix --force". I also can download videos from the trend page, but not from a specific user. It ever worked... I already have downloaded 1500+ videos, but now i can't. I already had this last time, but i thougth probably there will come a new update...

Try for example: tiktok-scraper user mrbeast -n 3 -d --session sid_tt=...

Mine doesn't download anything, but it does with the trend page. Also there aren't coming any error or warning messages. Just a short loading as normal, but then no download... instead i just can put in a new input

**Comment by drawrowfly** [comment]
#663
