### ISSUE TITLE
--noWatermark or -w does not work

### ISSUE THREAD

**Issue by BrunoQuaresma** [drawrowfly/tiktok-scraper#689]
Hi, I'm trying to download a video without a watermark, but looks like the option is not working.

```
npx tiktok-scraper video https://www.tiktok.com/@preta.hi/video/7018625313357729030\?is_copy_url\=1\&is_from_webapp\=v1 -w -d
```

<img width="545" alt="Screen Shot 2021-10-18 at 11 19 41" src="https://user-images.githubusercontent.com/3165839/137749427-f8117ee5-1ef2-48d9-bc31-17468508be41.png">

**Comment by UnixCro** [comment]
#513
