### ISSUE TITLE
Get Audio file from videoMeta.musicId

### ISSUE THREAD

**Issue by dlyakin** [drawrowfly/tiktok-scraper#70]
I want to get url to audio file

**Comment by drawrowfly** [comment]
Will be added to a to do list

**Comment by drawrowfly** [comment]
Music meta contains direct url to the MP3 files

Also in the future versions i will add option to download sound files as well

**Comment by dlyakin** [comment]
I see it in some methods. But I don't understand how to get it for single video. I have video url "https://www.tiktok.com/@tiktok/video/6807491984882765062" and I need to get music url for this video

**Comment by dlyakin** [comment]
Create new issue #91
