### ISSUE TITLE
CLI: No indication of progress/failure, quits after "Tiktok Scraper Started" animation.

### ISSUE THREAD

**Issue by mardab** [drawrowfly/tiktok-scraper#702]
**Describe the bug**
No matter which user I provide, or what options I change, all I get is animated "Tiktok Scraper Started", then that goes away and I get sent back to prompt with no indication of success/progress/failure, confusing as to why nothing has been downloaded

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
Steps to reproduce the behavior: **in shell cd to preferred folder and use tiktok-scraper, eg. "tiktok-scraper user USERNAME -d --hd -w -n 0**
- Used OS **Linux 5.10**
- NodeJs Version (node -v) **v14.17.6**
- Scraper Version (tiktok-scraper --version) **1.4.36**
- CLI or Module **CLI**
- Used method **N/A**
- Used options **various combinations, longest being "-d --hd -w -n 0"**
- Do you run the scraper through Proxy, VPN, VPS? **no**
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles! **yes, it is public**
- Preferably provide URL to the profile,hashtag,video and etc page **this applies to all public profiles tested so far**

**Screenshots**
**N/A**

**Comment by gerickt** [comment]
same problema here.

- Used OS: **Linux Manjaro**
- NodeJs Version (node -v)  **v16.11.0**
- Scraper Version (tiktok-scraper --version) **1.4.36**
- CLI or Module CLI **tiktok-scraper user USERNAME -d -n 100 --session sid_tt=dae3213123**
- Used options various combinations, longest being "-d --hd -w -n 0"
- Do you run the scraper through Proxy, VPN, VPS? **no**
- If scraping from a profile. Did you checked if profile is Public? **Scraper won't work with Private profiles! yes, it is public**
- Preferably provide URL to the profile,hashtag,video and etc page **this applies to all public profiles tested so far**

**Comment by nns33213** [comment]
@mardab @gerickt IMO the scraper is dead for the time being. I've tested on several residential connections as well as VPNs - nothing seems to work if you're not logged in. It's been like that for weeks now.

**Comment by 84281-Martinoli** [comment]
Any other alternative script?

**Comment by freetimeSPB** [comment]
Any other alternative script?

**Comment by Tempest042** [comment]
I've been able to use the The Unofficial TikTok API Wrapper In Python to create a script very similar to what I was using this for. If you know how to program and have a spare hour, it might be worth your time.

The Unofficial TikTok API Wrapper In Python: https://github.com/davidteather/TikTok-Api

Here is the script I made.
It basically takes a username as a command line argument and downloads all tiktoks by that user, it skips any already downloaded tiktoks: [tiktok-scraper-user.py.txt](https://github.com/drawrowfly/tiktok-scraper/files/7834309/tiktok-scraper-user.py.txt)

**Comment by angelopouloschristos** [comment]
> I've been able to use the The Unofficial TikTok API Wrapper In Python to create a script very similar to what I was using this for. If you know how to program and have a spare hour, it might be worth your time.
> 
> The Unofficial TikTok API Wrapper In Python: https://github.com/davidteather/TikTok-Api
> 
> Here is the script I made. It basically takes a username as a command line argument and downloads all tiktoks by that user, it skips any already downloaded tiktoks: [tiktok-scraper-user.py.txt](https://github.com/drawrowfly/tiktok-scraper/files/7834309/tiktok-scraper-user.py.txt)

it works !
I had to try it 4-5 times for it to work but its works !
Thanks a lot !

**Comment by angelopouloschristos** [comment]
> I've been able to use the The Unofficial TikTok API Wrapper In Python to create a script very similar to what I was using this for. If you know how to program and have a spare hour, it might be worth your time.
> 
> The Unofficial TikTok API Wrapper In Python: https://github.com/davidteather/TikTok-Api
> 
> Here is the script I made. It basically takes a username as a command line argument and downloads all tiktoks by that user, it skips any already downloaded tiktoks: [tiktok-scraper-user.py.txt](https://github.com/drawrowfly/tiktok-scraper/files/7834309/tiktok-scraper-user.py.txt)

PS C:\Users\Christos\Desktop\TikTok-Api-4.1.0\examples> python .\download_tiktok.py addisonre

Scraping:  addisonre
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-760' coro=<Route.continue_() done, defined at C:\Users\Christos\AppData\Local\Programs\Python\Python39\lib\site-packages\playwright\_impl\_network.py:189> exception=Error('Target page, context or brows
er has been closed')>

there is an error some times ... with some users for no reason.  It seem to be cause of "playwright" but if you spam 4-5 time as i said, it works

**Comment by drawrowfly** [comment]
#663

**Comment by drawrowfly** [comment]
this repo is not https://github.com/davidteather/TikTok-Api, please move there if you need to discuss something

**Comment by Sav0ia** [comment]
> I've been able to use the The Unofficial TikTok API Wrapper In Python to create a script very similar to what I was using this for. If you know how to program and have a spare hour, it might be worth your time.
> 
> The Unofficial TikTok API Wrapper In Python: https://github.com/davidteather/TikTok-Api
> 
> Here is the script I made. It basically takes a username as a command line argument and downloads all tiktoks by that user, it skips any already downloaded tiktoks: [tiktok-scraper-user.py.txt](https://github.com/drawrowfly/tiktok-scraper/files/7834309/tiktok-scraper-user.py.txt)

Hi everyone, I have tiktokapi and playwright installed, how do I use this script on mac?
Thanks so much :)
