### ISSUE TITLE
Can't get follower, digger and etc if using session

### ISSUE THREAD

**Issue by AthallahDzaki** [drawrowfly/tiktok-scraper#706]
**Describe the bug**
Can't Get Followers of Account if using session

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- Used OS (Windows / Railways)
- NodeJs Version (node -v) (16.x.x)
- Scraper Version (tiktok-scraper --version) (Latest)
- CLI or Module (Module)
- Used method (getUserProfileInfo)
- Used options (sesisonid)
- Do you run the scraper through Proxy, VPN, VPS? (Using Railway)
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles! (Yes)
- Preferably provide URL to the profile,hashtag,video and etc page (profile : google)

**Screenshots**
-

**Comment by drawrowfly** [comment]
related to the #663
