### ISSUE TITLE
music feature not returning anything

### ISSUE THREAD

**Issue by sipka** [drawrowfly/tiktok-scraper#707]
**Describe the bug**

I am using music command via terminal, in order to download post metadata related to the music_id. I am able to run commands for hashtag normally with the same options. I confirmed that music_id exists by scraping through a different API and getting data back. I attempted with and without session_id. I get "Tiktok scraper started", it finishes promptly (within a second), and **no file is created**.

The command I am running is:
tiktok-scraper music 6964104127806720774 -n 50 --filepath "/Users/myuser/Desktop" --filetype "json"

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- Used OS 
        - Mac OS 11.6
- NodeJs Version 
        - v14.15.1
- Scraper Version 
        - 1.4.36
- CLI or Module 
        - CLI
- Used method 
        - tiktok-scraper music
- Used options  
        - -n 50  --filepath "/Users/myuser/Desktop" --filetype "json"
- Do you run the scraper through Proxy, VPN, VPS? 
        - No
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles!
        - N/A
- Preferably provide URL to the profile,hashtag,video and etc page
        - https://www.tiktok.com/music/original-sound-6964104127806720774

**Screenshots**
N/A

**Comment by drawrowfly** [comment]
related to the #663

**Comment by ColtraneNadler** [comment]
> related to the #663

was a fix ever found for this? or is this still an issue
