### ISSUE TITLE
Not getting any results from the scraper after multiple runs

### ISSUE THREAD

**Issue by chen-bill** [drawrowfly/tiktok-scraper#71]
**Describe the bug**
After running this script a few times, I stopped getting results for any of the queries. Perhaps I'm getting rate limited by Tiktok? Could there be an error message added the commands if this is the case?

**To Reproduce**
-Running `tiktok-scraper hashtag HASHTAG_NAME -n 300 -d -t all` like 20 times for different hashtags

**Comment by drawrowfly** [comment]
Use proxy

**Comment by drawrowfly** [comment]
**Could there be an error message added the commands if this is the case?**

Not possible, because result returns as usually http 200 but with empty []
