### ISSUE TITLE
Discord invite link?

### ISSUE THREAD

**Issue by wireman21** [drawrowfly/tiktok-scraper#719]
Can someone provide a link to the discord?

I was a member but lost my password to my old discord account.

Thank you

**Comment by wireman21** [comment]
Hi please, can i get an invite to the discord. I understand the scraper may not be functioning.

**Comment by Jerrk** [comment]
![](https://i.imgur.com/fO7fwEo.png)

**Comment by wireman21** [comment]
> ![](https://camo.githubusercontent.com/2cf426a197215da10c25789c358d3798c0d38b0a7a2db11e86bbb364ee2af874/68747470733a2f2f692e696d6775722e636f6d2f664f376677456f2e706e67)

thank you so much! I am so stupid, i was looking at the link from the issues page. again thank you!
