### ISSUE TITLE
Cyrillic hashtags don't work as is

### ISSUE THREAD

**Issue by dlyakin** [drawrowfly/tiktok-scraper#72]
CODE:
 (async () => {
        try {
            const posts = await TikTokScraper.hashtag('кот', {number: 1});
            console.log(posts);
        } catch (error) {
            console.log(error);
        }
    })();

CONSOLE:
{ collector: [] }

If we use encoder кот -> %D0%BA%D0%BE%D1%82 works fine

**Comment by drawrowfly** [comment]
Thats great! BUT always follow the Bug template please. I'm not asking a lot !

**Comment by drawrowfly** [comment]
Will be fixed with the next update

**Comment by dlyakin** [comment]
I'm sorry. I'm newbe here. Next time I will be follow template

**Comment by drawrowfly** [comment]
Fixed in the latest version

Welcome!
