### ISSUE TITLE
Downloading user videos from CLI always fails

### ISSUE THREAD

**Issue by BetterLifeR** [drawrowfly/tiktok-scraper#720]
**Describe the bug**
While trying to download any number of videos from a user account, the CLI API always fails (It terminates the progress without printing an error message and videos aren't downloaded in --filepath).

I've tried using different valid sid_tt cookies for the --session argument, and also without, yet I always come across the same problem even when using a popular public account such as @charlidamelio

I'm also fairly certain that WiFi isn't an issue (since every other method works), although I would have no actual way of knowing since I don't receive any errors or warnings from the CLI API 

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- Used OS **Windos 10**
- NodeJs Version (node -v) **8.1.2**
- Scraper Version (tiktok-scraper --version) **1.4.36**
- CLI or Module **CLI**
- Used method **user**
- Used options **-d -n --session**
- Do you run the scraper through Proxy, VPN, VPS? **no**
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles! **profile is public**
- Preferably provide URL to the profile,hashtag,video and etc page **www.tiktok.com/@charlidamelio**

**Screenshots**

**Comment by LvLH** [comment]
i have encountered the same problem, have you finished it?

**Comment by drawrowfly** [comment]
#663
