### ISSUE TITLE
Can't scrape by username

### ISSUE THREAD

**Issue by Meliz0** [drawrowfly/tiktok-scraper#722]
Hey there!

I'm actually trying to scrape content by username but I'm getting this:

(process:1728): GLib-GIO-WARNING **: 17:52:54.976: Unexpectedly, UWP app `Evernote.Evernote_10.27.5.0_x86__q4d96b2w5wcc2' (AUMId `Evernote.Evernote_q4d96b2w5wcc2!Evernote') supports 1 extensions but has no verbs

Any solution?

Thanks 😄

**Comment by ambigos1** [comment]
Same Problem here
function: async getUserProfileInfo()
Line: 701
response
                .split(/<script id="__NEXT_DATA__" type="application\/json" nonce="[\w-]+" crossorigin="anonymous">/)[1]

return undefined

then attempt to .split(`</script>`)[0];  Throws error

'Cannot read property 'split' of undefined'
@drawrowfly  Is there a chance for a hot fix?
