### ISSUE TITLE
Unable to scrape by MUSIC_ID

### ISSUE THREAD

**Issue by andreabenedetti** [drawrowfly/tiktok-scraper#723]
Hello! I'm encountering some problems in scraping by music IDs. The scraper starts running without outputting any error, however it returns an empty folder when downloading the videos. When creating a csv file, it doesn't create it at all.

`(base) andrea@Andreas-MacBook-Pro ~ % tiktok-scraper music 7025646747674249985 -d -n 3 --filepath "/Users/andrea/Desktop"
(base) andrea@Andreas-MacBook-Pro ~ %`

**Comment by iosonosempreio** [comment]
I encountered the same issue!
