### ISSUE TITLE
History file disappears when stored on temp folder after system reboot

### ISSUE THREAD

**Issue by marvinhessel** [drawrowfly/tiktok-scraper#74]
**Describe the bug**
As seen below, I am able to scrape and store the files for the user properly.
However, the history path gets stored in a temp folder.  Once the system reboots, the history file disappears.

Possible solution:  Is it possible to provide options for providing the path of the history file to a folder path specified by the user?

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- Used OS: Ubuntu 14.0.4 LTS
- NodeJs Version : 11.3.0
- Scraper Version : 1.1.3
- CLI or Module : CLI
- Used method:  tiktok-scraper user madisonbeer -n 0 -s -d -t all
- Used options: tiktok-scraper user madisonbeer -n 0 -s -d -t all
**Screenshots**
![ubuntu1](https://user-images.githubusercontent.com/48638990/79173272-09859480-7dc5-11ea-8124-1da11b175af2.jpg)
![ubuntu2](https://user-images.githubusercontent.com/48638990/79173275-0a1e2b00-7dc5-11ea-8236-24e9bbb8ee53.jpg)

**Comment by drawrowfly** [comment]
Added support in the latest version

You can set it by using the --historypath

Welcome!
