### ISSUE TITLE
I figured out how to get watermarkless videos

### ISSUE THREAD

**Issue by Zipdox** [drawrowfly/tiktok-scraper#742]
```js
const fetch = require('node-fetch');

function generateDeviceId() {
	var i = 1, a = new Array(19);//Math.floor(Math.random() * 9) + 11
	a[0] = 54;//Math.floor(Math.random() * 9) + 49
	while (i < a.length) {
		a[i++] = Math.floor(Math.random() * 10) + 48;
	}
	return String.fromCharCode.apply(null, a);
}
function generateBase62(length) {
	var i = 0, r = "", base62 = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
	while (i < length) {
		r += base62.charAt(Math.floor(Math.random() * 62));
		i++;
	}
	return r;
}

function requestAweme(path) {
    return new Promise((resolve, reject)=>{
        const date = new Date(); 
        const time = date.getTime() - date.getTimezoneOffset() * 60000;
    
        const requestURL = "https://api-t2.tiktokv.com" + path
        + "&region=US"
        //+ "&version_name=10.0.0"
        + "&ts=" + Math.floor(time / 1000)
        + "&timezone_name=Etc%2FGMT"
        + "&device_type=Pixel%20" + generateBase62(8);
        + "&iid=" + generateDeviceId()
        + "&locale=en"
        + "&app_type=normal"
        //+ "&build_number=10.0.0"
        + "&resolution=1080*1920"
        + "&aid=1180"
        + "&app_name=musical_ly"
        + "&_rticket=" + time
        + "&device_platform=android"
        + "&version_code=100000"
        + "&dpi=441"
        + "&cpu_support64=false"
        + "&sys_region=US"
        + "&timezone_offset=0"
        + "&device_id=" + generateDeviceId()
        + "&pass-route=1"
        + "&device_brand=google"
        + "&os_version=8.0.0"
        //+ "&ab_version=10.0.0"
        + "&op_region=US"
        + "&app_language=en"
        + "&pass-region=1"
        + "&language=en"
        + "&channel=googleplay";
    
        fetch(requestURL, {
            headers: {
                'User-Agent': 'okhttp'
            }
        }).then(async (response)=>{
            response.json().then(resolve);
        }).catch(reject);
    });
}

async function requestVideoDetail(id) {
	return await requestAweme("/aweme/v1/aweme/detail/?aweme_id=" + id);
}
async function requestVideosDetail(ids) {
	return await requestAweme("/aweme/v1/multi/aweme/detail/?aweme_ids=[" + (typeof ids === "string" ? ids : ids.join()) + "]");
}

// example usage of above functions
(async function(){
    const exampleData = await requestVideoDetail('7006347072731401477'); // excuse the cringe, I picked a random video
    const secretID = exampleData.aweme_detail.video.play_addr.uri; // you can use this to manually query for watermarkless videos
    console.log(secretID);
    // or you can just get the URLs from the response
    const watermarklessURLs = exampleData.aweme_detail.video.play_addr.url_list;
    console.log(watermarklessURLs)
})();
```

Thank me later.

**Comment by drawrowfly** [comment]
Well done, the lifetime of your method was shortened by a lot by posting it here in public

**Comment by Zipdox** [comment]
Doubt, this has been public for a while I'm pretty sure.

**Comment by SRoche14** [comment]
This was awesome! How can I download the video once I have the link?

**Comment by Zipdox** [comment]
> This was awesome! How can I download the video once I have the link?

https://www.google.com/search?q=download+file+nodejs

**Comment by hatemqn** [comment]
It used to work, now unfortunately It doesn't.

**Comment by Zipdox** [comment]
Indeed it doesn't work anymore. I'm surprised it worked for this long.

**Comment by nugraizy** [comment]
Any information about this changes? I confused that how some website still be able to scrape/get watermarkless videos, even though the API are somewhat can't be accessed.

**Comment by Zipdox** [comment]
Don't know.

But on a side note, there was a fake TikTok leak recently, with a link to a Chinese Git site (down now) that contained some code relating to TikTok. The leak was fake so it probably isn't actual TikTok internal code, but it might be interesting to look at. I couldn't make out anything myself (some of it is Java and I don't know Java) and frankly I don't know what to look for. I'll cloned the most interesting looking repos. I can't take any responsibility for the code of course, and I haven't run it myself. I'll put them in a zip file. https://files.catbox.moe/sqfibc.zip

**Comment by nugraizy** [comment]
> Don't know.
> 
> But on a side note, there was a fake TikTok leak recently, with a link to a Chinese Git site (down now) that contained some code relating to TikTok. The leak was fake so it probably isn't actual TikTok internal code, but it might be interesting to look at. I couldn't make out anything myself (some of it is Java and I don't know Java) and frankly I don't know what to look for. I'll cloned the most interesting looking repos. I can't take any responsibility for the code of course, and I haven't run it myself. I'll put them in a zip file. https://files.catbox.moe/sqfibc.zip

have you seen this? [https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/tiktok.py](url) 
you can download watermarkless videos but idk how the packages works (idk python 😋)

**Comment by Zipdox** [comment]
> have you seen this? [https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/tiktok.py](url) you can download watermarkless videos but idk how the packages works (idk python yum)

Doesn't work.

**Comment by redraskal** [comment]
> > have you seen this? [https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/tiktok.py](url) you can download watermarkless videos but idk how the packages works (idk python yum)
> 
> Doesn't work.

Link doesn't seem to work but watermarkless video extraction does work in yt-dlp (in 720p). Also, user video listing works on my fork which is not merged.

The apparent exception is soundless videos

**Comment by Zipdox** [comment]
> Link doesn't seem to work but watermarkless video extraction does work in yt-dlp (in 720p). Also, user video listing works on my fork which is not merged.
> 
> The apparent exception is soundless videos

It appears to work on one video but not another. Very weird.
