### ISSUE TITLE
Trend no longer works - can anyone confirm?

### ISSUE THREAD

**Issue by use** [drawrowfly/tiktok-scraper#747]
**Describe the bug**
Trend doesn't do anything

**To Reproduce**

Use the trend option. Nothing happens except a folder gets created. Maybe I'm doing something wrong?

```
~/tmp
❯ tiktok-scraper trend -d -n 1 -t json

~/tmp 11s
❯ find trend
trend

```

**Comment by etepes** [comment]
Indeed, having the same problem too

**Comment by drawrowfly** [comment]
Will be checked shortly
