### ISSUE TITLE
multiple hashtags

### ISSUE THREAD

**Issue by verty411** [drawrowfly/tiktok-scraper#751]
Would be great if we could send multiple hashtags to narrow down video choices a lot more.

**Comment by issuefiler** [comment]
As far as I know, even TikTok does not support that. Correct me if I’m wrong.
Searching by a specific query would be the only available option.

**Comment by etepes** [comment]
> As far as I know, even TikTok does not support that. Correct me if I’m wrong. Searching by a specific query would be the only available option.
> 
> Or you could try separately (and exhaustively) querying items of the specific hashtags and joining the results.

You can make an array with multiple Hashtags, then try Math.random()

const hashtag = ['one', 'two', 'three']
