### ISSUE TITLE
Error while Scraping: Cannot download video from url.

### ISSUE THREAD

**Issue by dannyb648** [drawrowfly/tiktok-scraper#754]
**Describe the bug**
Trying to use the video download feature. Constantly getting "Error while scraping:". This is happening when using the CLI using video or from-file

However, downloading from a hashtag works fine. 

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- Used OS (Windows 11)
- NodeJs Version (node -v) 14.18.3
- Scraper Version 1.4.36
- CLI or Module CLI
- Used method: video, from-file
- Used options: -d 
- Do you run the scraper through Proxy, VPN, VPS? No Proxy, with VPN and without. 
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles! - Public
- Preferably provide URL to the profile,hashtag,video and etc page - I've reproduced bug using the example video files. 
https://www.tiktok.com/@shalisavdlaan/video/6788483055796391173
https://www.tiktok.com/@officialsaarx/video/6785180623263911174
https://www.tiktok.com/@dominos_nl/video/6786669305623842053
https://www.tiktok.com/@jessiejikki/video/6620697278451551493
https://www.tiktok.com/@.one_man_army/video/6798822211307310338
**Screenshots**
![image](https://user-images.githubusercontent.com/6515044/164785767-7ebe0e7a-3fe1-4dc2-a552-b29ce205501d.png)

**Comment by drawrowfly** [comment]
I will take a look at it shortly
