### ISSUE TITLE
Allow custom path for history files in order to save progress over a restart

### ISSUE THREAD

**Issue by anga83** [drawrowfly/tiktok-scraper#76]
Hi there!

I'd suggest that the user should be able to choose a custom path for the history files (which are currently stored in `/var/folders/`), just like you can choose the `--filepath` for the output files.

This has a substantial reason: Files stored in `/var/folders/` don't survive a restart of the device. Meaning, if I download all videos of a user (with `--store`, obviously) and then restart my notebook, all progress is forgotten. The second time I run the command, all files will be downloaded again.

If I want no duplicates I have to manually check if both zip files contain the same videos, or if the user e.g. deleted a video in the meantime, so I cannot safely delete the old zip file. (I hope you get what I mean.)

Alternative suggestion: Rather than allowing the user to choose a path on their own, store the history file in the same directory as the zip file. That way the history file should also survive a system restart.

**Comment by drawrowfly** [comment]
Will be added to a to do list

**Comment by drawrowfly** [comment]
#74 to keep the issues clean

**Comment by drawrowfly** [comment]
Added support in the latest version

You can set it by using the --historypath

Welcome!
