### ISSUE TITLE
Support for vt.tiktok.com URL

### ISSUE THREAD

**Issue by trieuhngl** [drawrowfly/tiktok-scraper#77]
I can't not download with URL copy from my iPhone.
Can add support for URL like vt.tiktok.com or any advise?
Thanks!

**Comment by drawrowfly** [comment]
Will be added to a to do list

**Comment by blackwhite29** [comment]
> I can't not download with URL copy from my iPhone.
> Can add support for URL like vt.tiktok.com or any advise?
> Thanks!

https://github.com/drawrowfly/tiktok-scraper/issues/68#issuecomment-611120265
 url = await GetDirectAPI(url);
                    let url_cv = url_parse.parse(url);
                    url_cv.search = url_cv.query = "";
                    url = url_cv.format(url_cv);

**Comment by drawrowfly** [comment]
Added support in the latest verions
