### ISSUE TITLE
Why tag can only get 1 thousand

### ISSUE THREAD

**Issue by buaichichangfen** [drawrowfly/tiktok-scraper#770]
**Describe the bug**
Why tag can only get 1 thousand

**To Reproduce**
- Used OS
- NodeJs Version (node -v)
- Scraper Version (tiktok-scraper --version)
- CLI or Module
- Used method
- Used options
- Do you run the scraper through Proxy, VPN, VPS?
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles!
- Preferably provide URL to the profile,hashtag,video and etc page

**Screenshots**

**Comment by drawrowfly** [comment]
probably api limits
