### ISSUE TITLE
Can't scrape data with 'user' command

### ISSUE THREAD

**Issue by mattosbruno** [drawrowfly/tiktok-scraper#775]
Hey!

First of all, just wanted to say that the scraper is really great and that it has been helping me a lot to move towards a systematic approach to TikTok research.

While I've been experiencing no problem to scrape metadata from videos associated with specific hashtags, the same cannot be said about user metadata scraping. Whenever I try to run any user related command, I don't even get the default message that tells me that the scraper has started.

Do you know what my issues might be? I'll attach my terminal commands to make myself clear. Thank you!

`Last login: Mon Jul 18 09:22:22 on ttys000

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
(base) Bruno-Mattos:~ teste$ cd Desktop
(base) Bruno-Mattos:Desktop teste$ tiktok-scraper hashtag crentesnotiktok --filename crentesnotiktok --filetype csv --session sid_tt=9d1d0db31287144adba8f0e6e80fb6e6
CSV path: /Users/bruno/Desktop/crentesnotiktok.csv
(base) Bruno-Mattos:Desktop teste$ tiktok-scraper user getwasteed --filename test --filetype csv --session sid_tt=9d1d0db31287144adba8f0e6e80fb6e6
(base) Bruno-Mattos:Desktop teste$ `

**Comment by 08volt** [comment]
Same here, I get the "verify captcha" response just with the user endpoint.

**Comment by LilSherlock** [comment]
Same issue here User and trend command is not working, it doesnt give output

**Comment by SteveSonoa** [comment]
Also same issue. I'm new to this project, and my `collector` only returns an empty array. I've tried multiple usernames (including "tiktok"). I've tried with and without `by_user_id` as well.

**Comment by RazeBerry** [comment]
I believe this empty collector return problem has been with this repo for a year already and no one has gotten it to work

**Comment by drawrowfly** [comment]
duplicate
