### ISSUE TITLE
Use dynamic video ID for non-watermarked videos

### ISSUE THREAD

**Issue by qsniyg** [drawrowfly/tiktok-scraper#78]
The video ID is static here: https://github.com/drawrowfly/tiktok-scraper/blob/09a9307e1df99f7d0231d4358c86e6f4fffb85e7/src/core/__mocks__/request-promise.ts#L28

I haven't tested it, but I'm pretty sure this was just an unintentional mistake? In theory, this will always return the same video.

**Comment by drawrowfly** [comment]
"__mocks__/request-promise.ts" it a tests

**Comment by qsniyg** [comment]
Ah you're right, I had misread the code. My apologies!
