### ISSUE TITLE
I can't download anything

### ISSUE THREAD

**Issue by djmarioka** [drawrowfly/tiktok-scraper#784]
When I execute the script, for example:

**tiktok-scraper user tiktok**

I don't receive anything, even it doesnt' create its folder, could you help me? 

I attach a screenshot:

![image](https://user-images.githubusercontent.com/81478245/185756055-6c425760-dcac-4457-b870-02f6bfd0722a.png)

Thanks.

**Comment by daantee0** [comment]
same problem did u fix it ?
