### ISSUE TITLE
Guidance on not getting IP Blocked

### ISSUE THREAD

**Issue by mandys** [drawrowfly/tiktok-scraper#785]
Hi Everyone,

Does anyone know how often we should hit hashtag search for tiktok to not block our IPs ?

Running one scrape ( 100 records ) every 5 minutes too aggressive ?

And if we run from multiple boxes having multiple IPs, does it block based on domain assigned to the boxes ( reverse ip lookup ) ?

Have been testing all day today and IP hasn't been blocked ( but to set it as a 5 minutely cron, need some guidance ).

Thanks.

**Comment by drawrowfly** [comment]
experiment with proxies
