### ISSUE TITLE
Support link iesdouyin.com

### ISSUE THREAD

**Issue by blackwhite29** [drawrowfly/tiktok-scraper#79]
can you add support get info from other client : https://www.iesdouyin.com/

**Comment by drawrowfly** [comment]
I guess this is a Chinese copy for the TikTok, within 5 minutes i have found a way to collect random users data by just using random user id(int) this way you can scrape all users from that network )

Currently i'm busy with other projects, don't have much time to write another scraper

**Comment by blackwhite29** [comment]
okay thank you <3
