### ISSUE TITLE
Fail to run

### ISSUE THREAD

**Issue by CCTT9696** [drawrowfly/tiktok-scraper#8]
I've got Nodejs and installed from NPM, run the example in terminal but didn't work. Am i missing something?

![image](https://user-images.githubusercontent.com/58856579/74307566-423ec880-4d98-11ea-8c55-17a4af171731.png)

**Comment by drawrowfly** [comment]
Judging by your screen you are running completely different package

**Comment by CCTT9696** [comment]
You've been a great help, after i uninstalled the other package and tried running again, this is what happened.

![image](https://user-images.githubusercontent.com/58856579/74353018-e43bd080-4deb-11ea-913f-c27288761f9a.png)

**Comment by drawrowfly** [comment]
@CCTT9696 message in your CLI is explicitly telling you that there is no such command, it means you have not installed it globally

**Comment by CCTT9696** [comment]
Thank you very much! It works perfectly.
