### ISSUE TITLE
Can't extract Tac value

### ISSUE THREAD

**Issue by xzjh** [drawrowfly/tiktok-scraper#80]
**Describe the bug**
When running command `tiktok-scraper user USERNAME`, it returns `Can't extract Tac value`

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- Used OS: macOS 10.15.4 (19E287)
- NodeJs Version: v13.8.0
- Scraper Version: latest
- CLI or Module: zsh
- Used method: `tiktok-scraper user USERNAME`
- Used options: `-n 10`
- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles!
Yes
- Preferably provide URL to the profile,hashtag,video and etc page
user: ixzjh

**Screenshots**

**Comment by drawrowfly** [comment]
For fine from my side

One thing that comes to my mind in your situation is that your IP is blocked

**Comment by xzjh** [comment]
Tried to open tiktok webpage using browser and it works well. Also tried to use proxy to switch to different IPs and the scraper still seems not working.

**Comment by xzjh** [comment]
Actually I think it works when I use a real VPN instead of ShadowSocks which is not supported in command terminal. Thanks for clarification. Closing the issue now.
