### ISSUE TITLE
Get video url without downloading

### ISSUE THREAD

**Issue by AidasK** [drawrowfly/tiktok-scraper#81]
I would like to get video URL instead of it being downloaded. I could save my load time on the website if I could embed this video url directly to tiktok and not to my server.

**Comment by drawrowfly** [comment]
https://github.com/drawrowfly/tiktok-scraper#getvideometa

**Comment by drawrowfly** [comment]
Even this methods have it https://github.com/drawrowfly/tiktok-scraper#user-hashtag-trend-music

Please always read very carefully the documentation

**Comment by AidasK** [comment]
Sorry. I just looked that it is not possible to do that via console. But it's not a problem for me. Thanks!

**Comment by drawrowfly** [comment]
**"I could save my load time on the website if I could embed this video url "**

You mentioned website so I thought that you use the package as module

From the CLI you can't get single video meta data only
