### ISSUE TITLE
Add support for downloading to a folder without zipping.

### ISSUE THREAD

**Issue by moodiest** [drawrowfly/tiktok-scraper#83]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like the ability to download to a folder instead of the videos being compressed into a zip file. The folder would ideally be customizable and different to the one in --filepath, or a new folder called the username inside --filepath.

Thanks.

**Comment by drawrowfly** [comment]
I will add this to a to do list

**Comment by AplhaSlayer1964** [comment]
Do you know when this will possibly be added?

**Comment by moodiest** [comment]
> Do you know when this will possibly be added? Would it also be possible to now download the csv file?

It's next on the todo list so shouldn't be too long now, just gotta give him some time. Anyway, you can already download a csv file using `--filetype csv` or `--filetype all` for both a json and csv. In fact, csv is the default filetype.

**Comment by AplhaSlayer1964** [comment]
oops I missed typed I meant to ask if there was a way to not download the csv or json file.

**Comment by drawrowfly** [comment]
this will be possible in the next update

**Comment by drawrowfly** [comment]
Done. By default scraper will create Folder and download there videos without ZIPing them

And by default scraper won't download post metadata to the CSV

https://github.com/drawrowfly/tiktok-scraper/blob/master/examples/CLI/Examples.md
