### ISSUE TITLE
Add support for shared urls

### ISSUE THREAD

**Issue by jinyus** [drawrowfly/tiktok-scraper#85]
Could you add support for urls like this one (https://vm.tiktok.com/WH9nkK/). As far as I can tell, it redirects twice before landing on the final page.

It would also be nice if you could add an option to output the post meta for a single video to stdout.

**Comment by drawrowfly** [comment]
Its already supported but not from the CLI, will be added to the CLI with the next update

**Comment by drawrowfly** [comment]
you can update and it will work

**Comment by JayEffTree** [comment]
Re-Opening, not able to retrieve shared linked with the module.


```javascript
try {
  const videoMeta = await tt.getVideoMeta('https://vm.tiktok.com/KYKLmw/')
  console.log(videoMeta)
} catch (err) {
  console.log(err)
}
```

This just returns an error with the following

`Not supported url format`
