### ISSUE TITLE
Add an option to output the postmeta map to stdout

### ISSUE THREAD

**Issue by jinyus** [drawrowfly/tiktok-scraper#86]
When downloading by username, you save the post meta of each post to a json file, could it be possible to print the postmeta json when using the video option also? It would be an option to just extract the postmeta and not download the video.

eg: tiktok-scraper video https://www.tiktok.com/@tiktok/video/6807491984882765062 --print-json --skip-download

**Comment by drawrowfly** [comment]
You can do this with module only

I will consider adding it to the CLI and as always Pull requests are welcome

**Comment by drawrowfly** [comment]
To download video you now need to use -d flag, otherwise scraper will save video metadata to the CSV file

https://github.com/drawrowfly/tiktok-scraper/blob/master/examples/CLI/Examples.md
