### ISSUE TITLE
Scraping get empty array of videos, status_code in body always 200, maybe not more valid signature?

### ISSUE THREAD

**Issue by sebastianobar** [drawrowfly/tiktok-scraper#9]
It seems that the scraper doesn't work anymore, I tried to debug it and I received status code 200 in the body response of video requests (not 0), maybe the signature or something else has changed in tiktok system? hope it help

**Comment by arelxcode** [comment]
me too, maybe need to update.
I hope to be fixed soon

**Comment by drawrowfly** [comment]
i will update the package shortly with the new signature algorithm

**Comment by arelxcode** [comment]
how is the info

**Comment by drawrowfly** [comment]
pushed new update, everything is working again
