### ISSUE TITLE
Get music url for single video

### ISSUE THREAD

**Issue by dlyakin** [drawrowfly/tiktok-scraper#91]
**Is your feature request related to a problem? Please describe.**
I see musicMeta in some methods. But I don't understand how to get it for single video. I have video url "https://www.tiktok.com/@tiktok/video/6807491984882765062" and I need to get music url for this video

**Describe the solution you'd like**
It will be good to get music url in getVideoMeta method.

**Comment by drawrowfly** [comment]
I don't see any urls to the MP3 when scraping single video . If you will find the location of that URL without doing extra requests then reopen this ticket or pull requests are always welcome
