### ISSUE TITLE
What does diggCount in profileInfo mean?

### ISSUE THREAD

**Issue by robben1234** [drawrowfly/tiktok-scraper#95]
This field shows up almost everywhere - in Video Feed, getUserProfileInfo, getVideoMeta. Occasionally named just `digg`, but mostly `diggCount`.

I have yet to find any mention of digg in app or website UI.

There's another issue mentioning `digg` field storing like count for posts, but what does it mean for profiles?

https://github.com/drawrowfly/tiktok-scraper/issues/39

**Comment by drawrowfly** [comment]
Well this filed is provided by the TikTok api )

According to this website https://infohats.com/report/lorengray/tiktokm Digg counter in User meta is likes that are made by the user on other profiles and videos

**Comment by natallg** [comment]
diggCount is the number of people who digged (aka 'liked') the video

**Comment by gcstr** [comment]
@natallg, and what is the difference between Digg to heart counts? Isn't heart the 'like'?

**Comment by William-Fox-Cantera** [comment]
> diggCount is the number of people who digged (aka 'liked') the video

Yes, what is the difference between diggCount and hearts?

**Comment by isaackogan** [comment]
Buuuump ^
