### ISSUE TITLE
Appreciation and a question

### ISSUE THREAD

**Issue by saqib-ahmed** [drawrowfly/tiktok-scraper#96]
This isn't a bug or feature request. I was looking into scraping tiktok before I found this repository. I did narrow down to `/share/item/list` API (that was a no brainer) which is called from the tiktok page to get the metadata info. 

However, I was put off by the `signature` parameter in that request and that's where I gave up. I did see your implementation of  `generateSignature()` and it blew me off. I wouldn't have got it in a thousand years. So my question is: How do you find that? I know it would be somewhere in the page's js, but sifting through that humongous minified and uglified JS is really hard and making sense of it is nigh impossible. I want to know what is the process of reverse engineering and how do you go about it? Please refer to me to some article if there is any. 

Also, I started listening for this API call in my puppeteer implementation of the scraper. Why didn't you go in that direction for scraping.

**Comment by drawrowfly** [comment]
"Why didn't you go in that direction for scraping."
Why i didn't go puppeteer way? Its to heavy and slow. When i write scrapers i prefer to use only http request library without extra heavy libraries as puppeteer and etc.

"How do you find that?"
Just regular web debugging way, follow the code steps and you will always find what you need. 

Web debugging tools as Charles, Mitmproxy, Burp can be helpful plus there are a lot of JS beautifiers online and different plugins for VS Code(example) that will make this task easier.
 
You just need to practice :)

**Comment by saqib-ahmed** [comment]
Thank you for the reply and for the amazing scraper.
