### ISSUE TITLE
Add support for mentioned user

### ISSUE THREAD

**Issue by Dealsnooz** [drawrowfly/tiktok-scraper#97]
if you have time please add other field giving mentioned user just like a hashtag

**Comment by drawrowfly** [comment]
Well it can be achieved by using small regex on video caption

Will add it to a to do list

**Comment by Dealsnooz** [comment]
just found one more thing duet with user.
if you can separate mentioned user and duet please do it

**Comment by drawrowfly** [comment]
Mentioned users are now in result. Regarding duet data, it is only available in newer version of the API i don't have yet plans to change everything, only in the future
