### ISSUE TITLE
Can't download any video

### ISSUE THREAD

**Issue by rabea98** [drawrowfly/tiktok-scraper#99]
**Describe the bug**
When starting the script, at finishes right away without downloading anything

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- Used OS
Windows 10 Pro
- NodeJs Version
node-v12.16.2-x64
- Scraper Version
Latest
- CLI or Module
CLI
- Used method
from cmd
- Used options
tiktok-scraper from-file userss.txt 5 -n 0 -d -y all -w --filepath F:\tiktok\dow

- If scraping from a profile. Did you checked if profile is Public? Scraper won't work with Private profiles!
Yes
- Preferably provide URL to the profile,hashtag,video and etc page
mirleycaballero
**Screenshots**
![image](https://user-images.githubusercontent.com/56865072/79990266-b4511f00-8465-11ea-974c-878048c29998.png)

![image](https://user-images.githubusercontent.com/56865072/79990298-be731d80-8465-11ea-85c2-b32a11306781.png)

**Comment by drawrowfly** [comment]
**1. Use proxies**
2. Not important but decided to note that these commands "-y all -w" do not exist in the scraper

**Comment by rabea98** [comment]
I changed ip and it still wouldn't work

**Comment by drawrowfly** [comment]
Can't advice anything else as it works fine from mine side

If you scrape a lot of profiles then you need to use a lot of Clean proxies not just change single ip you need to use proxy list. 

Create proxy file and point to it with the command --proxy-file

**Comment by Dealsnooz** [comment]
use vpn if proxy does not works

**Comment by drawrowfly** [comment]
Closed due to inactivity
